coveo/plasma

gulpfile.js, package.json, tests/components/PopoverComponent.spec.tsx, tsconfig.json, tsconfig.test.json
* Clean the gulpfile
* Leverage typeRoots for types resolution, make it work with webpack
- Remove the now useless jasmine types reference
=> Types and Gulpfile cleanup!

docs/Index.tsx, package.json, src/Index.ts, src/components/PopoverComponent.tsx, src/utils/ReduxUtils.ts, tests/components/PopoverComponent.spec.tsx
+ Add the mergeProps ReduxUtils method
* Make the PopoverComponent handle it's own state instead of passing a toggle method in props
* Adjust unit test
* Adjust the demo
+ Add the missing underscore peer dependency
=> Make the PopoverComponent handle it's own state instead of passing a toggle method in props

src/ReactVapor.ts, src/components/calendar/Calendar.tsx, src/components/calendar/CalendarConnected.tsx, src/components/calendar/tests/CalendarConnected.spec.tsx, src/components/datePicker/DatePickerDropdown.tsx, src/components/datePicker/DatePickerDropdownConnected.tsx, src/components/datePicker/DatePickerReducers.ts, src/components/datePicker/DatesSelectionConnected.tsx, src/components/datePicker/tests/DatePickerDropdownConnected.spec.tsx, src/components/datePicker/tests/DatesSelectionConnected.spec.tsx, src/components/facets/FacetReducers.ts, src/components/navigation/Navigation.tsx, src/components/navigation/perPage/NavigationPerPage.tsx, src/components/navigation/perPage/NavigationPerPageConnected.tsx, src/components/navigation/perPage/tests/NavigationPerPage.spec.tsx, src/components/navigation/perPage/tests/NavigationPerPageConnected.spec.tsx, src/components/navigation/tests/Navigation.spec.tsx, src/components/navigation/tests/NavigationConnected.spec.tsx, src/components/optionPicker/Option.tsx, src/components/optionPicker/OptionPicker.tsx, src/components/optionPicker/OptionPickerActions.ts, src/components/optionPicker/OptionPickerConnected.tsx, src/components/optionPicker/OptionPickerReducers.ts, src/components/optionPicker/tests/Option.spec.tsx, src/components/optionPicker/tests/OptionPicker.spec.tsx, src/components/optionPicker/tests/OptionPickerActions.spec.ts, src/components/optionPicker/tests/OptionPickerReducers.spec.ts, src/components/optionPicker/tests/OptionsPickerConnected.spec.tsx
What changed: 
1. Value of the option picker is calculated on option click and not re-evaluated each time the state changes. I added the label in the state also to compare the options between them instead of using the value which can sometimes be different because of when it was calculated.
2. The per page navigation gets it's current per page and the page number from the state and not from its parent (currentPerPage was there twice and there were often conflicts were the selected per page number was not the right one).
3. Auto-selections of inputs on the date picker. We select the first one when opening the date picker and the second one when the first one have been selected.
4. Select the end of the day when clicking and selecting the upper limit. Feels more natural this way and fixes …
=> Cleaned up code for the date picker and the per page navigation

gulpfile.js
It simply removes the offending "Partial<>" types from the d.ts which isn't all that useful in the definition file either way.
=> Cleaned up dts for projects using a typescript version below 2.1

src/components/datePicker/DatePickerDropdown.tsx
There was a change in the css for the dropdown class that made the datepicker dropdown unable to open. Since the change in vapor was legitimate, I simply added the class here to make it work again.
=> Added missing class

src/components/datePicker/DatePickerDropdown.tsx, src/components/datePicker/tests/DatePickerDropdown.spec.tsx
if you have many date pickers in a view, it triggers many CLOSE actions which cause the UI to be very very slow, we want to dispatch the action only if the datepicker is open
=> dispatch close only when open

src/components/dropdownSearch/DropdownSearchActions.tsx, src/components/dropdownSearch/DropdownSearchConnected.tsx, src/components/dropdownSearch/DropdownSearchReducers.tsx, src/components/dropdownSearch/MultiSelectDropdownSearch/tests/MultiSelectDropdownSearchConnected.spec.tsx, src/components/dropdownSearch/examples/DropdownSearchExamples.tsx, src/components/dropdownSearch/tests/DropdownSearch.spec.tsx, src/components/dropdownSearch/tests/DropdownSearchConnected.spec.tsx, src/components/dropdownSearch/tests/DropdownSearchReducer.spec.tsx
L'org picker était pété à cause que j'ai joué un peu dans les props du dropdown search. Maintenant ça devrait être beau! On peut entrer une option par défaut à la création du dropdown.
=> fix default selected option in DropdownSearch

package.json, src/components/dropdownSearch/DropdownSearchConnected.tsx, src/components/dropdownSearch/tests/DropdownSearchConnected.spec.tsx, src/utils/TestUtils.ts, webpack.config.test.js
If there is a default selected option since it is currently being overwritten by the reducer, with the update on mount, we are now showing the custom option. This is a quick fix until the dropdown search is being refactored. The reducer should not initialized itself with options that should be customizable.
=> Add update to the dropdown search options on mount 

src/components/filterBox/FilterBox.tsx, src/components/filterBox/tests/FilterBox.spec.tsx
https://drive.google.com/file/d/1wdlVYHWqAJFvMsYnW-O4Xsl2cBwzzbGz/view  
see demo, if you dispatch a `filterThrough` action from outside the filter with a non empty value (like in the video), you still want the clear icon to pop up, this was not the case previously. This does not break the FilterBox unconnected
=> display clear icon on filter through dispatch

src/components/calendar/CalendarConnected.tsx, src/components/calendar/tests/CalendarConnected.spec.tsx, src/components/datePicker/DatePickerBox.tsx, src/components/datePicker/DatePickerReducers.ts, src/components/datePicker/tests/DatePickerReducers.spec.ts
Remove the reset after a click without value for the DateSelected
Use the appliedLowerLimit or the lowerLimit to validate the upperLimit to avoid a undefined value.
Add uts to cover this changes
https://drive.google.com/file/d/1CKAt7T-C56mxw34_8IYR_nyBxmEVAniC/view
=> Fix date picker end date manual input

src/components/headers/HeaderWrapper.tsx
tough to see in the image, but the first one does not have enough padding on top and is different compare to other headers
=> handle padding depending on context and add padding top

.travis.yml, create-live-demo.js, package.json
Since the live demo script is nom in a `after_script` the demo url doesn't show in the build logs. We need to echo it at the `script` level to be able to retrieve it in the logs. I added something to retrieve it in the commits seeable in the gh-pages branch https://github.com/coveo/react-vapor/tree/gh-pages (see besides the `print-live-demo` folder)
=> print the demo url in travis logs

create-live-demo.js
otherwise we sometimes get `Updates were rejected because a pushed branch tip is behind its remote`
see `after_script` logs for details here https://travis-ci.org/coveo/react-vapor/builds/329518230
=> force push to gh-pages for live demos

docs/Index.tsx, src/Index.ts, src/components/labeledValue/LabeledValue.spec.tsx, src/components/labeledValue/LabeledValue.tsx, src/components/labeledValue/examples/LabeledValueExamples.tsx, src/utils/TooltipUtils.ts
the demo at: https://coveo.github.io/react-vapor/labeled-value/ has the wrong style and i don't know why for now, the image above has the right style
=> Labeled Value component

src/Index.ts, src/components/tables/TableConnected.tsx, src/components/tables/TableDataModifier.ts, src/components/tables/examples/TableExamples.tsx, src/components/tables/tests/TableDataModifier.spec.ts
I needed to be able to build the Table composite state from outside of ReactVapor to use the manual version of the Table in more complex ways (fetch from outside for example). We decided to extract the function from `mapStateToProps`.  
I changed the API endpoint for the TableExamples because it was broken.
**POSSIBLE BREAKING CHANGE** the `dispatchPreTableStateModification ` and `dispatchPostTableStateModification` are called with the table ID directly instead of the whole `ownProps`
=> Extract and export a TableCompositeState "builder"

src/components/modal/ModalBackdrop.tsx, src/components/modal/ModalComposite.tsx, src/components/modal/examples/ModalConnectedExamples.tsx, src/components/modal/tests/ModalBackdrop.spec.tsx
An unwanted style was enforced on all `ModalComposite` because of the `displayFor` prop
=> Add isPrompt prop that adds the style in the modalBackdrop

src/components/tables/Table.tsx, src/components/tables/table-children/TableChildBody.tsx, src/components/tables/tests/TableChildBody.spec.tsx
since getActions is always defined and could have returned undefined it could have thrown at `actions.filter...bla bla`
=> add dblclick fix for actions

src/animations/SlideY.spec.tsx, src/components/actions/Action.tsx, src/components/actions/ActionBarConnected.tsx, src/components/actions/LinkAction.tsx, src/components/actions/TriggerAction.tsx, src/components/actions/examples/ActionBarConnectedExamples.tsx, src/components/actions/examples/ActionBarExamples.tsx, src/components/actions/tests/Action.spec.tsx, src/components/actions/tests/ActionBarConnected.spec.tsx, src/components/actions/tests/LinkAction.spec.tsx, src/components/actions/tests/TriggerAction.spec.tsx
we need this for a use case in ML, where offline models won't have access to an action, and we want to give context to the user through a tooltip on the action ("You can not open this model because it is currently inactive") . 
demo: https://coveo.github.io/react-vapor/unhidden-disabled-actions/  
search for `Action bar with actions`
=> implement visible disabled actions

src/components/facets/FacetRow.tsx, src/components/facets/tests/FacetConnected.spec.tsx, src/components/facets/tests/FacetRow.spec.tsx
Reuse one of ReactVapor's own component.
Before, clicking on the checkbox didn't toggle the change in the facets, only clicking the label worked.
Looks like this change will not be breaking behaviour outside of ReactVapor, but I'm still curious.
To test, go checkout connected facets in the demo and click on the checkbox.
DEMO https://coveo.github.io/react-vapor/update-facets-checkboxes/
=> Use ReactVapor's Checkbox in facets instead of input

src/components/dropdownSearch/MultiSelectDropdownSearch/tests/SelectedOption.spec.tsx, src/components/tables/Table.tsx, src/components/tables/TableDataModifier.ts, src/components/tables/tests/TableDataModifier.spec.ts
previously the sort was applied to the raw data value only. It sorted by the raw value when in fact the value was formatted in the UI to another value, so the values were not sorted correctly.  On top of that, if you added a custom sortByMethod to fix this, the sort was made on the id of the data and not on the attribute value, so it was not helping.  
Now, if you have a formatted value in the ui, you can use the sortByMethod to use the formatted value you want for a proper sort.
=> fix sort method

webpack.config.prod.js
I needed to add the plugin to the prod webpack script also because it's the only one that runs when building.
=> FIX: Add feature-export-version to prod script also

package.json, src/components/logoCard/LogoCard.tsx, src/components/svg/Svg.tsx, src/components/svg/tests/Svg.spec.tsx, tsconfig.json, tsconfig.test.json, types/coveo-styleguide/index.d.ts
Before:
`<Svg svgName='source-custom' />` Works :smile_cat:
`<Svg svgName='sourceCustom' />` Doesn't work :crying_cat_face: 
After:
`<Svg svgName='source-custom' />` Works :smile_cat:
`<Svg svgName='sourceCustom' />` Works :smile_cat: 
This allows to use Svg component like so:
`<Svg svgName={VaporSVG.svg.sourceCustom.name} />`
=> Fix svg names

src/components/flippable/Flippable.tsx, src/components/flippable/tests/Flippable.spec.tsx
When multiple flippables are one on top of the other and flipping the one above, the backside is shown under the following flippables which is not what we want. This PR bumps the z-index of the flippable when it is being flipped.
=> Fix flippable z-index on flip

docs/Index.tsx, src/components/sideNavigation/SideNavigationHeader.tsx, src/components/sideNavigation/SideNavigationItem.tsx, src/components/sideNavigation/SideNavigationMenuSection.tsx, src/components/sideNavigation/examples/SideNavigationExample.tsx, src/components/sideNavigation/tests/SideNavigationHeader.spec.tsx, src/components/sideNavigation/tests/SideNavigationItem.spec.tsx, src/components/sideNavigation/tests/SideNavigationMenuSection.spec.tsx
Migrations de nos classes de side navigation du projet Dynamics. Modifiées pour ajouter des icônes et supporter vos truc cool de menu qui collapsent.
Il me reste encore un component qui utilise `react-dom` et `react-router-dom`, comme le `SideNavigationItem` que je viens d'ajouter, mais il render un [NavLink](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/NavLink.md) au lieu d'un anchor.
Vous ne voulez probablement pas de ça dans cette lib, right?
=> Migrate stuff++

src/components/stepProgressBar/StepProgressBar.tsx
Requires an update from vapor that adds `flex: 1` to children:
See here for details: https://github.com/coveo/vapor/pull/490
=> Remove full-content-x on StepProgressBar children

src/components/modal/Modal.tsx, src/components/modal/tests/Modal.spec.tsx
When we called unmount on a modal mounted by not opened, it was calling `closeCallback` prop which was causing some issues further down the road.
=> Fix modal close callback

src/components/modal/Modal.tsx, src/components/modal/tests/Modal.spec.tsx
This will allow to specify a timeout before executing the closeCallback, ensuring a user can wait for the fade animation to be done to perform any cleanup.
=> + Add close timeout prop in modal

src/components/datePicker/DatePickerDropdown.tsx, src/components/datePicker/tests/DatePickerDropdown.spec.tsx
Added condition when the picker is a range to avoid duplicated labels
=> Fix Date Picker Duplicated Labels

src/utils/FalsyValuesUtils.spec.tsx, src/utils/FalsyValuesUtils.ts
Since we often do the following logic, I added a small util to make it a one liner:
```ts
if (someFunctionThatMayBeUndefined) {
someFunctionThatMayBeUndefined(someArg, someOtherArg, ...);
}
```
Becomes this
```ts
callIfDefined(someFunctionThatMayBeUndefined, someArg, someOtherArg, ...);
```
=> Add callIfDefined util

webpack.config.prod.js
We have react-vapor.js and react-vapor.min.js, since the move to webpack 4 both of them are minified
You'll see what I say if you check https://github.com/coveo/react-vapor/blob/master/webpack.config.prod.minify.js and https://github.com/coveo/react-vapor/blob/master/package.json#L28
With my change react-vapor.js is not minified (and can be used it tests to find elements by their name instead of using a string) and react-vapor.min.js is
=> Don't minize the code twice

src/components/tables/TableHeadingRow.tsx, src/components/tables/table-children/TableChildBody.tsx, src/components/tables/tests/Table.spec.tsx, src/components/tables/tests/TableChildBody.spec.tsx, src/components/tables/tests/TableHeadingRow.spec.tsx
Made each table row selectable only when the `getActions` function returns one or more item.
=> Remove table rows selection action when there are no actions to display

docs/Index.tsx, src/components/tables/TableHeadingRow.tsx, src/components/tables/TableHeadingRowConnected.tsx, src/components/tables/TableRowActions.ts, src/components/tables/TableRowReducers.ts, src/components/tables/examples/TableExamples.tsx, src/components/tables/table-children/TableChildBody.tsx, src/components/tables/tests/TableHeadingRow.spec.tsx, src/components/tables/tests/TableHeadingRowConnected.spec.tsx, src/components/tables/tests/TableRowReducers.spec.ts
Improved those following use cases:
* When a table had some collapsible rows mixed with some standard rows, it looked like the screenshot bellow. I added an empty `<td></td>` to the standard rows only when there is one or more collapsible table rows that exists in the table.
* When a table row has no actions, it is not selectable and that is the expected behavior. The problem is that when its a collapsible row, the select action was not triggered, therefore the row wouldn't uncollapse. I separated the select action into 2: selectRow and toggleRow and added a reducer that goes with it.
=> Fix collapsible table behavior

docs/Index.tsx, src/utils/ReduxUtils.ts
Instead of declaring a new interface for each component that exposes a single `id` prop, use the `BasePayload`.
For example:
Would become 
I didn't change all the existing interfaces, because that would cause breaking changes everywhere
=> Add base payload interface

src/components/loading/Loading.tsx, src/components/loading/tests/Loading.spec.tsx
Before: `<Loading className='p2' />` would render `<div class="spinner">.......</div>`
After: `<Loading className='p2' />` will render `<div class="spinner p2">.......</div>`
=> Allow additional classnames on loading component

src/components/tables/TableRowActions.ts, src/components/tables/TableRowReducers.ts, src/components/tables/tests/TableRowReducers.spec.ts
We had a redux action to toggle a table collapsible row collapsed/expanded. I needed a way to set a collapsible row opened no matter what the current state is.
=> Add set collapsible row opened

src/components/tables/Table.tsx, src/components/tables/TableConnected.tsx, src/components/tables/tests/Table.spec.tsx
As shown in the above gif, the initial load is currently not working properly. The blankslate pops up while the initial results are retrieved. The initial loading behavior should be displayed instead. This PR fixes the issue.    
also adressed the following issue:  https://github.com/coveo/react-vapor/issues/621
=> Fix table initial load

karma.conf.js
i was tired of scrolling all the way down the build logs to get the demo link, this should help reduce the logs of the build. It will only print the failed UTs if any to the console, and the warnings.
=> reduce build logs by changing karma reporter in travis

src/components/facets/Facet.tsx, src/components/facets/tests/Facet.spec.tsx
This was previously done in the other repos, but the facets were not added to the state. By doing this here, we remove repetition and make sure everything is cleanly in the state.
=> No render on facets without rows

package.json, src/components/tables/TableConstants.tsx, src/components/tables/TableReducers.ts, src/components/tables/tests/Table.spec.tsx
since we now make a comparison with `JSON.stringify` to toggle  the initial load, an empty table data could be identical to DEFAULT_TABLE_DATA, and we need something to differentiate the two for the initial load to work properly.
=> Fix default to empty table data on table initial load

docs/Index.tsx, src/components/editor/CodeEditor.tsx, src/components/editor/tests/CodeEditor.spec.tsx
=> add border by default for code editors

package.json, src/components/facets/Facet.tsx, src/components/facets/FacetReducers.ts, src/components/facets/FacetRow.tsx, src/components/facets/tests/FacetReducers.spec.ts, src/components/facets/tests/FacetRow.spec.tsx, src/components/select/examples/SingleSelectExamples.tsx
Facets' rows style should respect these criteria:
- Icon like this https://thenounproject.com/search/?q=dont&i=10550.
- Show the icon en grey on hover the facet's row. Became blue on hover the button hit zone.
- Show a tooltip “Exclude [row_name] logs“ on hover the button hit zone.
When you click on exclude facet already exclude it should not be add again in state.
=> Fix exclusion behavior and style on facets

src/components/tables/Table.tsx
this change emerged from a discussion with @pochretien   
The argument is that you do not necessarily need to pass all these arguments to the manual thunk action when you use it from outside the table. You probably don't need all these if you do a simple table refresh, in fact you probably just need to pass the table id.  I added a comment to explain the concept of the manual prop, but it might be overkill, let me know what you think.
=> Make manual more flexible

src/components/collapsible/CollapsibleInfoBox.tsx, src/components/collapsible/styles/CollapsibleInfoBox.scss, src/components/collapsible/styles/CollapsibleInfoBox.scss.d.ts
Made style improvements to the `CollapsibleInfoBox` component following UX review.
- Enlarge the clickable zone by applying padding to the collapsible header instead of the whole container
- Background color is shown only on hover with a transition
=> Collapsible infobox style improvements

src/components/collapsible/CollapsibleInfoBox.tsx, src/components/collapsible/styles/CollapsibleInfoBox.scss
I needed to publish a new patch version to get the new styles from coveo-styleguide, so while at it I updated the collapsible info box styles to use the new rounded border classes.
=> Update collapsible info box style

src/ReactVapor.ts
makes it just easier to fake particular redux state when testing
and all others are optional
=> make autocompletes optional in state

src/components/modal/ModalComposite.tsx, src/components/modal/ModalHeader.tsx, src/components/modal/examples/ModalCompositeConnectedExamples.tsx, src/components/modal/tests/ModalHeader.spec.tsx
add prop to standardize the way doc link is rendered across all modal composite and modal header usage
=> Doc link icon integrated to modal header

src/components/sideNavigation/SideNavigation.tsx, src/components/sideNavigation/tests/SideNavigation.spec.tsx
New class `navigation-opened` was added to vapor, which means that the side-navigation in Dynamics is hidden by default.
- I added a property to control its state (`opened`)
- and used the `withReduxState` to control it and have it opened by default (not sure this is the best idea though)
=> Side-Navigation broken

src/components/tables/Table.tsx, src/components/tables/TableHeader.tsx, src/components/tables/TableHeaderCell.tsx, src/components/tables/table-children/TableChildHeader.tsx, src/components/tables/tests/TableChildHeader.spec.tsx
There was no way to add classes to specify attributes in the **header cells** like it is possible to do with row cells, so here it is.
Plus, added a way to specify a class directly on the **thead** too.
=> Allow to specify table header classes

src/components/sideNavigation/SideNavigationHeader.tsx, src/components/sideNavigation/SideNavigationMenuSection.tsx, src/components/sideNavigation/examples/SideNavigationExample.tsx, src/components/sideNavigation/tests/SideNavigationMenuSection.spec.tsx
A side navigation item with target "_blank" would collapse the menu section.
Fixed it by moving the onclick handler on the section header.
=> Moves onclick handler

src/components/navigation/Navigation.tsx, src/components/navigation/examples/NavigationExamples.tsx, src/components/navigation/perPage/NavigationPerPage.tsx, src/components/navigation/tests/Navigation.spec.tsx
Changes:
- Change to onPerPageClick definition in Navigation and NavigationPerPage interfaces
- Added test for proper arguments being used in onPerPageClick
- Alert the value of onPerPageClick and onPageClick in component examples
=> Fix INavigationChildrenProps's onPerPageClick

src/components/itemBox/ItemBox.tsx, src/components/listBox/ListBox.tsx, src/components/listBox/ListBoxActions.ts, src/components/listBox/ListBoxConnected.tsx, src/components/listBox/ListBoxReducers.ts, src/components/listBox/tests/ListBoxReducers.spec.ts, src/components/select/SelectConnected.tsx, src/components/select/tests/SingleSelectConnected.spec.tsx
I had many `SingleSelectConnected` components rendered by the `attributeFormatter` inside a `TableConnected`. Their `items` prop is changing to reflect the changes occuring in the table's state, but when the prop changes, it isn't actually updating the items of the `SingleSelectConnected`. 
The problem was that the `ListBoxConnected` used by the underlying `SelectConnected` component only updates its items if they change inside the redux store, but not when the `items` prop itself changes. 
To counter that, I dispatched an action to update the `ListBox` items in the store when the `SelectConnected`'s `items` prop changes. With that addition, my table now works flawlessly without any hassle.
=> + Make sure list box items get updated when changing SelectConnected items prop

src/components/select/SingleSelectConnected.tsx, src/components/select/examples/SingleSelectExamples.tsx, src/components/select/tests/SingleSelectConnected.spec.tsx
I needed a way to prepend some text before the selected value of a SingleSelectedComponent, but I did not wanted this prepend to be shown on options in the dropdown.
=> Implement a fixed prepend for the SingleSelectedComponent's toggle button

src/components/select/SelectSelector.ts, src/components/select/tests/SelectSelector.spec.ts
`getListState` selector was missing a check for `selectWithFilter` prop. Since its optional and can be undefined in the ReactVaporState the selector shouldn't throw IMHO. 
@pochretien does not agree with this. Feel free to argue with this here if you want.
=> Fix the getListState select selector

src/components/select/SelectConnected.tsx
We can close the dropdown already open with a single click on the button
=> update selectConnected to close on click again the button

src/components/select/MultiSelectConnected.tsx, src/components/select/SelectConnected.tsx, src/components/select/SelectSelector.ts, src/components/select/SelectWithFilter.tsx, src/components/select/SingleSelectConnected.tsx, src/components/select/examples/MultiSelectExamples.tsx, src/components/tables/examples/TableExamples.tsx
When rendering `SingleSelectConnected` in table rows, the underlying `SelectConnected` was loosing its focus somewhere in the life cycle making it impossible to use the keyboard to select items.
The solution was to fix the boolean check for `SelectConnected.keepFocus` by passing down a new prop called `hasFocusableChild` from the withFilter HOC. This way, the `keepFocus` variable stays to `true` for `SelectConnected` that don't have focusable children and is set to `false` for the ones that render focusable children.
Also did some minor refactoring while at it.
=> Fix SelectConnected component's focus behavior

src/components/table-hoc/TableRowNumberColumn.tsx, src/components/table-hoc/TableRowNumberHeader.tsx, src/components/table-hoc/examples/TableHOCServerExamples.tsx, src/components/table-hoc/styles/TableRowNumber.scss, src/components/table-hoc/styles/TableRowNumber.scss.d.ts, src/components/table-hoc/tests/TableRowNumberColumn.spec.tsx, src/components/table-hoc/tests/TableRowNumberHeader.spec.tsx
https://coveo.github.io/react-vapor/table-with-numbered-rows/#Table%20(server%20+%20hoc)
i don't think it was HOC worthy, especially since renderData is custom to each table, but definitely open for changes here.  
you need to do three things to add numbered rows for now:
- Add <TableRowNumberHeader /> in the header
- Add <TableRowNumberColumn /> as a column in renderData
- add the .table-numbered class on the table  
maybe there would be something simpler, thoughts are welcome  
@otaillon
=> implement table with numbered rows

src/hoc/withEditing/withEditing.tsx
good catch from @tommy-tran , the hoc was returning the wrong prop signature. You can now pass the props interface and state interface to the hoc if needed.
=> add better type for withEditing hoc

src/components/collapsible/Collapsible.tsx, src/components/collapsible/CollapsibleToggle.tsx, src/components/collapsible/tests/CollapsibleToggle.spec.tsx, src/components/modalPrompt/ModalPrompt.tsx, src/components/slider/Slider.tsx, src/components/slider/tests/Slider.spec.tsx, src/components/table-hoc/TableHOC.tsx, src/components/table-hoc/TableRowConnected.tsx, src/components/table-hoc/TableSelectors.ts, src/components/table-hoc/actions/TableRowActions.ts, src/components/table-hoc/examples/TableHOCExamples.tsx, src/components/table-hoc/reducers/TableRowReducers.ts, src/components/table-hoc/styles/TableRowNumber.scss, src/components/table-hoc/tests/TableRowConnected.spec.tsx, src/components/table-hoc/tests/TableRowReducers.spec.ts
Implemented the collapsible row behavior inside the TableRowConnected, so that it can be easily used with the TableHOC
Also, I fixed the orange indicator for selected table rows inside the numbered table. (see commit a3faace)
See before:
=> Collapsible rows for table HOC

src/components/table-hoc/TableRowConnected.tsx, src/components/table-hoc/tests/TableRowConnected.spec.tsx
* `TableRowConnected` renders a collapsible row only if a collapsible content is specified. 
* When setting the `expandOnMount` prop to true, if the row is collapsible (has defined collapsible content), the row gets expanded on mount.
If we do the following:
1. Set `expandOnMount` to true
2. Mount the row with no collapsible content
3. Set collapsible content through props later on
The row will not get expanded because it is already mounted.
If `expandOnMount` is set to true, the row will get toggled opened not just on mount, but also when switching from collapsible content being undefined to being defined. This behavior does more than the prop name says, but typically makes sense for users that want rows to be expanded on mount.
=> Toggle rows open when switching to collapsible rows

package.json, src/components/popover/Popover.tsx, src/components/popover/examples/PopoverConnectedExamples.tsx, src/components/popover/tests/Popover.spec.tsx
=> fix: popover component

src/components/itemBox/ItemBox.tsx, src/components/partial-string-match/PartialStringMatch.spec.tsx, src/components/partial-string-match/PartialStringMatch.tsx, src/components/partial-string-match/PartialStringMatchExamples.tsx, tsconfig.json, tsconfig.test.json
Replace wholeString with a React.ReactNode
Iterate on every children to match string by using a generator
Added example
=> Feature Deep PartialStringMatch

src/components/flippable/Flippable.tsx, src/components/flippable/exemples/FlippableExamples.tsx, src/components/flippable/tests/Flippable.spec.tsx, src/components/modal/examples/ModalExamples.tsx, src/utils/BrowserUtils.ts
- Added `BrowserUtils.isIE()`. It detects if the browser is IE (FYI: returns false in MsEdge);
- Flippables will now have the class `flippable-ie` when the browser is IE;
=> fix: adding class "flippable-ie" to flippables when the browser is IE

src/components/table-hoc/TableRowConnected.tsx, src/components/table-hoc/examples/TableHOCServerExamples.tsx, src/components/table-hoc/tests/TableRowConnected.spec.tsx
- `TableRowConnected` with prop `disabled` set to true will now output a `tr` with the `row-disabled` class. It won't prevent any action from being triggered, if you want such behavior you should handle it in your callback;
- `TableRowConnected` will now trigger all of its actions that have the prop `callOnDoubleClick` set to true;
=> Implement doubleclick behavior on table rows and disabled style

src/components/editor/CodeEditor.tsx, src/components/editor/JSONEditor.tsx, src/components/editor/tests/CodeEditor.spec.tsx, src/components/editor/tests/JSONEditor.spec.tsx
The code editor now uses the `Controlled` version of reac-codemirror-2 which allows to have more control over how it handles its state. I fixed it so that its state changes both when the user inputs something, but also when its value changes programatically.
=> Bind the code editor to its value prop

src/components/itemBox/ItemBox.tsx
passing option to onOptionClick is not always relevant, therefore it should be optional
=> make option optional in on option click

gulpfile.js, package.json, src/utils/ReduxUtils.ts
`tslint` was complaining with our custom `IDispatch` and `IThunkAction` types. I refactored our types so that they use the proper types from redux-thunk.
=> Fix ReduxUtils generic types

src/components/labeledValue/LabeledValue.tsx, src/components/menu/examples/MenuExamples.tsx, src/components/select/SingleSelectConnected.tsx, src/components/select/examples/SingleSelectExamples.tsx, src/components/select/tests/SingleSelectConnected.spec.tsx
Added props on the SingleSelect to add a clear button and a tooltip
Fixed demo for single select and Menu
=> Feature Single Select Clear Button

src/components/calendar/Calendar.tsx, src/components/optionsCycle/OptionsCycle.tsx, src/components/optionsCycle/OptionsCycleConnected.tsx, src/components/optionsCycle/examples/OptionsCycleConnectedExamples.tsx, src/components/optionsCycle/examples/OptionsCycleExamples.tsx, src/components/optionsCycle/tests/OptionsCycle.spec.tsx, src/components/optionsCycle/tests/OptionsCycleConnected.spec.tsx
Added possibility to render any React.ReactNode
Added examples
Removed props from OptionsCycle interface if they are only for the connected
Cleaned up OptionsCycle code
Needs coveo/vapor#642
=> Fixed Options Cycle can Only Display Strings

src/components/modal/ModalComposite.tsx, src/components/modal/ModalCompositeConnected.tsx, src/components/modal/tests/ModalComposite.spec.tsx, src/components/modal/tests/ModalCompositeConnected.spec.tsx
Added the `layer-x` classes to modal overlays so that they all stack properly.
The layer number of a given modal equals its position in the `openModals` array in the store + 1.
=> Handle modal layers

gulpfile.js, package.json, src/utils/ReduxUtils.ts, tsconfig.json
Export the redux-thunk types in the d.ts file because it breaks when using symlinks
=> Export redux thunk types

src/components/stickyFooter/StickyFooter.tsx, src/components/stickyFooter/examples/StickyFooterExamples.tsx, src/components/stickyFooter/tests/StickyFooter.spec.tsx, src/hoc/withEditing/withEditing.tsx
`.stickyFooterOpened` was compiled, so there was no direct way to use this class.
Furthermore, the component was *closed* by default, meaning that the only way we could use the component was by replicating the `stickyFooterOpened` into our project and applying it at all times.
I instead fronted a simple property to add this class when required.
=> Allow to use StickyFooter outside of the project

.travis.yml, src/components/table-hoc/TableRowConnected.tsx, src/components/table-hoc/tests/TableRowConnected.spec.tsx
Action bar was refreshing to much often.
- Stringifying the actions before the check seems to have fixed it.
- Added a check to only refresh the action bar actions when the row was selected.
=> Better check for action changes on table row

src/components/button/Button.tsx, src/components/button/examples/ButtonExamples.tsx, src/components/button/tests/Button.spec.tsx
Don't add the text-medium-grey class if the button is primary
Add unit test
Add example
Before
After
=> Fix primary button disabled color

package.json, src/components/drop/Drop.tsx, src/components/drop/DropPod.tsx, src/components/drop/tests/Drop.spec.tsx, src/components/drop/tests/DropPod.spec.tsx, src/utils/tests/RTestUtils.tsx
Improvement on event handling, no more event when the drop is not open to avoid useless process on the other on the page
Add new props to set the same width for the drop than the button
add little task to create a js file not minified to test in local with link
fix a little miss variable where the number was sent instead of a boolean ( work too because a number is true but fixed now )
Add uts
Fix uts with the old event system
=> Drop improvement

src/components/listBox/ListBox.tsx, src/components/select/SingleSelectConnected.tsx, src/components/select/tests/SingleSelectConnected.spec.tsx
The clear button was shown and was also effective even when the SingleSelect was disabled.
What I did:
- Prevented the clear button from showing when the SingleSelect is disabled
- Prevented the clear single select value action to be dispatched onclick when the SingleSelect is disabled
=> Hide SingleSelect clear button when disabled

src/components/toast/ToastActions.ts, src/components/toast/ToastReducers.ts, src/components/toast/examples/ToastConnectedExamples.tsx
I needed a way to pass down a class to the toast created with addToast action.
=> Expose toast props in add toast action

src/utils/EventUtils.spec.tsx, src/utils/EventUtils.ts
@fblais
`isClickingInsideElementWithClassname` util was throwing "Cannot read property 'classList' of null" errors. It seems to happen when the event target is null. Not sure how this can happen though.
=> Fix "Cannot read property 'classList' of null" error

package.json, src/components/drop/Drop.tsx, src/components/select/MultiSelectConnected.tsx, src/components/select/SelectConnected.tsx, src/components/select/SingleSelectConnected.tsx
- Reduced the dropdowns `z-index` to `100000` instead of `2147483647`
- Fixed multi selects opening when clicking inside the selected values box
=> Reduce dropdown `z-index` & fix disabled multi selects opening

src/components/input/InputSelectors.ts, src/components/input/tests/InputSelectors.spec.ts
We had no selector for the `valid` attribute of the input states.
- Added a `InputSelector` for the `valid` attribute that can be called like so:
```ts
InputSelectors.getIsValid(state, {id: 'the-input-id'});
```
None
=> Add an InputSelector for the `valid ` attribute

packages/react-vapor/gulpfile.js, packages/react-vapor/package.json, packages/react-vapor/tsconfig.build.json, packages/react-vapor/tsconfig.json, packages/react-vapor/tsconfig.test.json, packages/react-vapor/webpack.config.js, packages/react-vapor/webpack.config.prod.js
vscode resolves a given file's typings by finding the nearest parent `tsconfig.json` file. When opening any `.spec` file, typings don't get resolved correctly, because all spec files are excluded in the `tsconfig.json` file. 
- Removed all includes and excludes from `tsconfig.json`
- Added a `tsconfig.build.json` file which is now targeted by webpack and gulp for compilation and d.ts generation.
None
=> Fix unit test typings in vscode

packages/react-vapor/src/components/chart/BarSeries.tsx, packages/react-vapor/src/components/chart/ChartTooltip.tsx, packages/react-vapor/src/components/chart/examples/ChartExamples.tsx, packages/react-vapor/src/components/chart/tests/BarSeries.spec.tsx, packages/react-vapor/src/components/chart/tests/ChartTooltip.spec.tsx, packages/react-vapor/src/components/chart/tests/XYChartContextMock.ts, packages/react-vapor/webpack.config.prod.js
When calculating the bar width of a bar chart, we would end up with a division by 0 when the data series had only one value. Same problem existed in the ChartTooltip component.
- Added a code branch that handles the case when there is only one value in a data series
None
=> Fix bar chart with mono value

packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/DraggableSelectedOption.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/SelectedOption.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/tests/DraggableSelectedOption.spec.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/tests/SelectedOption.spec.tsx, packages/react-vapor/src/components/select/MultiSelectConnected.tsx, packages/react-vapor/src/components/select/examples/MultiSelectExamples.tsx, packages/react-vapor/src/components/tooltip/Tooltip.tsx, packages/vapor/gulpfile.js, packages/vapor/package.json, packages/vapor/scss/components/selected-option.scss
Selected values of multiselect components were not getting truncated:
- Ajusted the style so that selected values get truncated:
I removed the `flex: inline-flex` rule on the `.select-option-value` class. It could potentially have an undesired impact on selected value that render a funky react-node, but I haven't found any way to produce such problem.
=> Fix adui 4499 truncate multiselect values

packages/react-vapor/src/components/breadcrumbs/BreadcrumbLink.tsx, packages/vapor/scss/components/breadcrumbs.scss, packages/vapor/scss/variables.scss
I noticed that when BreadcrumbHeader contained a breadcrumb, the height of the header was 38px instead of the usual 32px and I wanted to fix this.
I noticed the `margin-top: 7px` was the culprit, but then the header was badly aligned, *but only in react-vapor*. 
Once I removed the rule, *vapor* was properly aligned, with the only difference being that `breadcrumb-arrow` was being applied to the `<span>` container instead of directly on the `svg`.
It is kind of hard to see, so here is what it was before. Have a look at the description when I switch back and forth between the two pages:
Here is the proposed change:
- (vapor) Remove the `margin-top: 7px` that was used for alignment 
- (react-vapor) Put "breadcrumb-arrow" on the container instead of the svg, as specified in vapor.
None
=> Remove Breadcrumb's margin-top for height consistency

packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx, packages/react-vapor/src/components/table-hoc/actions/TableHOCRowActions.ts, packages/react-vapor/src/components/table-hoc/examples/TableHOCExamples.tsx, packages/react-vapor/src/components/table-hoc/reducers/TableRowReducers.ts, packages/react-vapor/src/components/table-hoc/tests/TableRowConnected.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableRowReducers.spec.ts
`TableRowActions` is defined in both Table and Table HOC, and this causes great confusion downstream. Or at least I think :)
=> Change name of action symbol to avoid conflicts

packages/vapor/scss/elements/btn.scss
added a styling rule to .btn when also collapsible to remove the all mighty border-radius.
=> fix - removed the border radius in .btn when also collapsible[ADUI-4004]

packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx
Added a function in the root component that grab the true value and switch it to "nocursor". Thus giving us the functionalities that we want.
=> fix added Nocursor function in CodeEditor when in Readonly [ADUI4507]

packages/react-vapor/src/utils/JSXUtils.spec.tsx, packages/react-vapor/src/utils/JSXUtils.tsx
`getReactNodeTextContent` was not stripping consecutive whitespaces on different nodes, because of the order of the functions inside the `_.compose`
None
=> Fix the getReactNodeTextContent util

packages/vapor/gulpfile.js, packages/vapor/svgWrapper.js
- spread syntax is not available with ie 11 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility
- default parameter is not available with ie 11
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility
=> add valid js for ie 11 in svgWrapper file

packages/react-vapor/src/utils/JSXUtils.spec.tsx, packages/react-vapor/src/utils/JSXUtils.tsx
Remove HTML entities generated by renderToStaticMarkup function, because we were getting display issues with `'`: 
```
Expected 'Hello there! Can&#x27;t you see me? I can.' to be 'Hello there! Can't you see me? I can.'
```
None
=> Remove HTML entities in getTextContent util

packages/react-vapor/src/components/headers/BasicHeader.tsx, packages/react-vapor/src/components/title/Title.tsx, packages/vapor/scss/elements/btn.scss, packages/vapor/scss/variables.scss
- Enable to pass down children to `Title` component
- Fix the `Button` mod-small padding when using as link:
Before: 
After: 
None
=> Refactor title component + button style fix

packages/react-vapor/src/components/table-hoc/TableHOC.tsx, packages/react-vapor/src/components/table-hoc/TableWithDatePicker.tsx, packages/react-vapor/src/components/table-hoc/TableWithFilter.tsx, packages/react-vapor/src/components/table-hoc/TableWithPagination.tsx, packages/react-vapor/src/components/table-hoc/TableWithPredicate.tsx, packages/react-vapor/src/components/table-hoc/TableWithSort.tsx, packages/react-vapor/src/components/table-hoc/examples/TableHOCServerExamples.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithDatePicker.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithFilter.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPagination.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPredicate.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithSort.spec.tsx, packages/react-vapor/src/hoc/withServerSideProcessing/withServerSideProcessing.spec.tsx, packages/react-vapor/src/hoc/withServerSideProcessing/withServerSideProcessing.tsx
Implemented the `withServerSideProcessing` HOC. It removes the need to specify `{isServer: true}` in every subsequent HOC configs.
See [TableHOCServerExamples.tsx](https://github.com/coveo/react-vapor/pull/1194/files#diff-63800e89d7e668fdf8d0bcd1e917c234) for an example of what I'm talking about.
None, I made this change fully retro-compatible with the old way of doing things.
=> withServerSideProcessing HOC

packages/vapor/scss/components/modal.scss
this avoid a big space if the description is longer than the title
Remove flex-grow, the bug is caused by this property who set the title text with the same with than the description. Its wrong because we want to have the docs icon next to the title text.
I dont know where the flex-grow property is useful. can break something but I dont understand how...
=> remove flex-grow on the h1 tag in the modal header

packages/react-vapor/karma.conf.js, packages/react-vapor/webpack.config.test.js
In karma's build process, the coverage reporter is doing some processing on the source files behind the scenes before handling them to karma server. This becomes a problem when running unit tests in the browser while placing `debugger;` in the code, because it is barely readable.
The solution I implemented checks if `--browsers Chrome` is an argument to `karma start` command. If so, it does not compute any coverage, allowing us to debug properly. 
None.
=> Show readable source files when debugging UTs in the browser

packages/react-vapor/src/components/select/SelectComponents.tsx, packages/react-vapor/src/components/select/SelectConnected.tsx, packages/react-vapor/src/components/select/SelectWithPredicate.tsx, packages/react-vapor/src/components/select/tests/MultiSelectWithPredicate.spec.tsx
Added support for server side processing of predicate filtering in select components. Followed the same pattern we use in TableHOC withServerSideProcessing.
Basically, the idea is that when processing is done by the server, no filtering is applied on the UI side, so we pass down `ownProps.items` directly to the wrapped component. Also, when the predicate value changes, we trigger the `onUpdate` callback so that a call to the server can be sent.
None.
=> Support withServerSideProcessing in SelectWithPredicate

packages/react-vapor/karma.conf.js, packages/react-vapor/src/components/select/SelectSelector.ts, packages/react-vapor/src/components/select/SelectWithFilter.tsx, packages/react-vapor/src/components/select/tests/SingleSelectWithFilter.spec.tsx, packages/react-vapor/src/hoc/withServerSideProcessing/withServerSideProcessing.tsx, packages/react-vapor/webpack.config.test.js
Added support for server side processing of filtering items of select components. Followed the same pattern we use in TableHOC withServerSideProcessing.
Basically, the idea is that when processing is done by the server, no filtering is applied on the UI side, so we pass down ownProps.items directly to the wrapped component. Also, when the filter input value changes, we trigger the onUpdate callback so that a call to the server can be sent.
None.
=> Support withServerSideProcessing in SelectWithFilter

packages/react-vapor/src/components/listBox/ListBoxActions.ts, packages/react-vapor/src/components/listBox/ListBoxConnected.tsx, packages/react-vapor/src/components/listBox/ListBoxReducers.ts, packages/react-vapor/src/components/select/SelectConnected.tsx, packages/react-vapor/src/components/select/tests/SingleSelectWithFilter.spec.tsx
- Initial value of MultiSelect should be the first element even when using selected props
- Using arrows in Select should behave as expected
none
=> Fix adui 4565 keyboard selection issue in permission filter

packages/react-vapor/src/components/partial-string-match/PartialStringMatch.spec.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.tsx
`PartialStringMatch` was not highlighting matches rendered by functional components.
- Changed the `*deepReplaceStrings` method so that it picks-up children of functional components
- Simplified `*deepReplaceStrings` method my extracting 2 new methods: `lookupChildren` and `hightlightMatches`.
None.
=> Fix PartialStringMatch for function components

packages/react-vapor/src/components/table-hoc/TableWithPagination.tsx, packages/react-vapor/src/components/table-hoc/examples/TableHOCExamples.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPagination.spec.tsx
When specifying perPageNumbers in the tableWithPagination HOC config (say 3, 5, 10), it was getting ignored and the default perPageNumbers were used instead (10, 20, 30). Now it will use the perPageNumbers defined in the config if specified, else it will fallback to the default perPageNumbers as it should.
None.
=> Fix perPageNumbers config in tableWithPagination

create-live-demo.sh
The hash in the demo link should be different than `d41d8cd98f00b204e9800998ecf8427e`
=> Fix the demo link branch name hash

packages/react-vapor/karma.conf.js, packages/react-vapor/src/utils/JSXUtils.spec.tsx, packages/react-vapor/src/utils/JSXUtils.tsx
Implemented a small util that adds className to children (or any react node).
```tsx
// node
<span className="old-class">Hello react-vapor!</span>;
const newNode = addClassNameToChildren(node, 'new-class');
// newNode
<span className="old-class new-class">Hello react-vapor!</span>
```
None
=> Add class name to children util

packages/react-vapor/src/components/itemBox/ItemBox.tsx, packages/react-vapor/src/components/listBox/ListBox.tsx, packages/react-vapor/src/components/listBox/ListBoxActions.ts, packages/react-vapor/src/components/listBox/ListBoxConnected.tsx, packages/react-vapor/src/components/listBox/ListBoxReducers.ts, packages/react-vapor/src/components/listBox/tests/ListBoxReducers.spec.ts, packages/react-vapor/src/components/select/SelectConnected.tsx, packages/react-vapor/src/components/select/hoc/tests/SingleSelectWithFilter.spec.tsx
When playing with the value selection in SingleSelect, we were not previously updating the activate state. It was only updated when using the navigation key.
I now keep track of the item index and change the active cells when selecting an item through a click or key navigation.
=> Fix active state in SingleSelect when clicking or using key navigation

packages/react-vapor/src/components/sideNavigation/SideNavigation.tsx, packages/react-vapor/src/components/sideNavigation/SideNavigationHeader.tsx, packages/react-vapor/src/components/sideNavigation/SideNavigationItem.tsx, packages/react-vapor/src/components/sideNavigation/SideNavigationMenuSection.tsx, packages/react-vapor/src/components/sideNavigation/examples/SideNavigationExample.tsx, packages/react-vapor/src/components/sideNavigation/tests/SideNavigationItem.spec.tsx, packages/react-vapor/src/components/sideNavigation/tests/SideNavigationMenuSection.spec.tsx, packages/vapor/scss/components/navigation.scss
Now the `SideNavigationMenuSection` supports passing down the header props directly on the SideNavigationMenuSection (backwards compatibility has been preserved):
```tsx
// Before
<SideNavigationMenuSection
header={{
title: 'the title',
svgName: 'theIcon',
svgClass: 'theClasses',
onClick: doSomething,
}}
{...otherProps}
/>
// After (you can still use the header prop although it its deprecated)
<SideNavigationMenuSection 
title='the title' 
svgName='theIcon' 
svgClass='theClasses' 
onClick={doSomething}
{...otherProps}
/>
```
Made the `SideNavigationItem` more generic while preserving backwards compatibility.
```tsx
// Before
<SideNavigationItem href="http://coveo.com" title="Link to Coveo" />
// After (you can still use the old way)
<SideNavigationItem>
<a
href="http://coveo.com" …
```
=> Adui 4690/refactor side navigation

packages/react-vapor/package.json, packages/react-vapor/src/components/modal/ModalComposite.tsx, packages/react-vapor/src/components/modal/examples/ModalCompositeConnectedExamples.tsx, packages/react-vapor/src/components/modal/tests/ModalComposite.spec.tsx, packages/react-vapor/src/components/modal/tests/ModalCompositeConnected.spec.tsx
Now that the `afterClose` prop bug has been closed (see https://github.com/reactjs/react-modal/pull/755) we can safely remove the workaround we made in the `ModalComposite` component.
Hopefully none.
=> Remove `react-modal` `afterClose` bug workaround

packages/react-vapor/src/components/input/Label.tsx
I had some error when compiling react-vapor
=> Fix type error in Label

packages/react-vapor/package.json, packages/react-vapor/src/components/actions/ActionConstants.tsx, packages/react-vapor/src/components/actions/ActionDropdownItem.tsx, packages/react-vapor/src/components/actions/ActionsDropdown.tsx, packages/react-vapor/src/components/actions/examples/ActionBarConnectedExamples.tsx, packages/react-vapor/src/components/actions/examples/ActionBarExamples.tsx, packages/react-vapor/src/components/actions/tests/ActionsDropdown.spec.tsx, packages/react-vapor/src/components/actions/tests/SecondaryActions.spec.tsx, packages/react-vapor/src/components/actions/tests/SecondaryActionsConnected.spec.tsx, packages/react-vapor/src/components/tables/examples/TableExamples.tsx
Lots of tests
I was baffled by all the logic required in the sources to make the separator appear where they need to be so I implemented the filtering logic here
The logic should be better then before (and covered by tests)
=> Filter out the separators when they should not be shown

packages/react-vapor/src/utils/FilterUtils.spec.ts, packages/react-vapor/src/utils/FilterUtils.ts
The library that we use throws an error when the value is undefined
None
=> Fix issue with defaultMatchFilter when value is undefined

packages/react-vapor/src/components/input/Input.tsx, packages/react-vapor/src/components/input/examples/InputConnectedExamples.tsx, packages/vapor/scss/controls/input-field.scss
Change value type of labelTitle from 'string' to 'ReactNode' in order to accept any element. Added css for the span that Tooltip creates and added new example.
Removed 'pointer-events: none' on the label. I can't for-see any breaking changes, but might be worth mentioning.
=> Fix adui 4702 input connected have a way

packages/react-vapor/src/utils/FalsyValuesUtils.spec.tsx, packages/react-vapor/src/utils/FalsyValuesUtils.ts
We tried using `callIfDefined` with `strictNullCheck: true` and the method is failing because it does not actually accept `null` and `undefined` values!
Since its purpose is to validate whether it is defined, I think it makes sense to allow passing those values :P
What I have done here is activate `strictNullCheck` temporarily and tested that the unit tests did not return an error. Since `someDeclaredButNotAssignedCallback` was also invalid (assigning `undefined` to a callback type), I instead put `any`.
None, it is more permissive now.
=> Better reflect actual callIfDefined signature

packages/react-vapor/src/components/drop/tests/DropPod.spec.tsx, packages/react-vapor/src/components/listBox/tests/ListBox.spec.tsx, packages/react-vapor/src/components/radio/RadioSelect.tsx
Add classes prop for the RadioSelect button
=> Add Custom Classes for the Radio Select

packages/react-vapor/src/components/blankSlate/BlankSlate.tsx, packages/react-vapor/src/components/blankSlate/examples/BlankSlateExample.tsx, packages/react-vapor/src/components/blankSlate/tests/BlankSlate.spec.tsx
Added a dangerouslySetDescription in the BlankSlate props
none
-   [ x ] The proposed changes are covered by unit tests
-   [ x ] The potential breaking changes are clearly identified
-   [ - ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)
=> Fix add dangerously set description in the blank slate component

packages/react-vapor/docs/src/components/ComponentPage.tsx, packages/react-vapor/docs/src/components/ComponentsInterface.tsx, packages/react-vapor/docs/src/components/index.tsx, packages/vapor/scss/components/markdown-documentation.scss, packages/vapor/scss/guide.scss
Added some logic that generates tab navigation from markdown files name in the "Components" section of the demo.
To enable tab navigation for a component you need to add a markdown file somewhere named according to the following pattern: `<ComponentName>Examples.<order>.<tabName>.md`.
Say I want to add tabs `Salmon` and `Tuna` to section `Fish`, I would need to create the following files:
- `FishExamples.tsx`
- `FishExamples.1.salmon.md`
- `FishExamples.2.tuna.md`
To obtain
PS: the default first tab name is `'Develop'`.
None, it only affects the demo.
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes …
=> Generate tabs from markdown files

packages/vapor/scss/controls/input-field.scss
A [change had some side effect](https://github.com/coveo/react-vapor/pull/1238/files#diff-48a7d6baa8f7bd7c15486dff810ecc17L57) in the UI. I kept the change but added a selector for the rule
@salvarez07 Do you think it can have more unexpected effects?
=> Fix Style When the Element is a Child of the input-field

packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx, packages/react-vapor/src/components/datePicker/examples/DatePickerDropdownConnectedExamples.tsx, packages/react-vapor/src/components/datePicker/tests/DatePickerDropdown.spec.tsx, packages/vapor/scss/components/calendar.scss
The readOnly mode changed the dropdown to an input component.
Now the component stays the same but the `onclick` functionality is disabled and the text is grayed out.
none as far as I know
=> changed the readonly behavior for the datePickerDropdownConnected

packages/vapor/scss/controls/radios.scss
Add _mod-align-with-radio-label_ to align radio description with radio label in _radio-option_
No breaking change.
=> Add padding left class for radio description

packages/react-vapor/src/components/loading/Loading.tsx, packages/react-vapor/src/components/loading/LoadingExamples.tsx
add the prop to set all classes for the full content loading
Add a prop to set all classes for the full content loading
nothing
=> Full Content Loading

packages/react-vapor/src/components/content/Content.tsx, packages/react-vapor/src/components/content/tests/Content.spec.tsx, packages/react-vapor/src/components/headers/examples/BreadcrumbHeaderExample.tsx
add validation to allowed reactNode and number as content for the Content Comonent
add 2 examples
I change the condition to return the ReactNode  or the number instead of throwing an error
=> Add valid Content in Content Component

packages/react-vapor/docs/index.html, packages/react-vapor/docs/src/OneDemoToRuleThemAll.tsx, packages/react-vapor/docs/src/components/ComponentPage.tsx, packages/react-vapor/docs/src/components/ComponentsInterface.tsx, packages/react-vapor/docs/src/components/index.tsx, packages/react-vapor/docs/src/demo-building-blocs/Code.tsx, packages/react-vapor/package.json, packages/react-vapor/src/components/calendar/Calendar.tsx, packages/react-vapor/src/components/datePicker/DatePickerBox.tsx, packages/react-vapor/src/components/table-hoc/examples/TableHOCExamples.tsx, packages/react-vapor/src/components/tables/tests/TableTestCommon.tsx, packages/react-vapor/src/components/tables/tests/TableUtils.spec.ts, packages/react-vapor/tsconfig.build.json, packages/react-vapor/webpack.config.js
Split styles and components in two files
Dynamic imports of examples and markdown
Minify on Travis
Reduce bundle size by only using english in moment and faker
Reduce bundle size by only loading html and tsx in syntax highlighter
It only modify the demo for now, I might do another PR to modify the npm package
=> Enable Split Points in Demo Build

packages/react-vapor/src/components/actions/Action.tsx, packages/react-vapor/src/components/actions/TriggerAction.tsx, packages/react-vapor/src/components/actions/examples/ActionBarConnectedExamples.tsx, packages/react-vapor/src/components/actions/tests/TriggerAction.spec.tsx, packages/react-vapor/src/components/inlinePrompt/InlinePrompt.tsx
…ation objet, added an example in vapor
The inline prompt that is triggered when a requiresConfirmation is set will now take a custom prompt description that will bypass de default 'are you sure ?' string.
Not used anywhere yet.
=> actionTrigger now takes the confirmLabel Props in requiresConfirmation

packages/react-vapor/docs/src/components/ComponentPage.tsx, packages/react-vapor/docs/src/components/index.tsx, packages/react-vapor/src/animations/SlideY.tsx, packages/react-vapor/src/animations/examples/SlideYExamples.tsx, packages/react-vapor/src/components/svg/Svg.tsx
Don't re-calculate the SlideY on unmount
Use a string replace in Svg instead of creating and updating a DOM node
Load all exemples and not just those in the components folder
All the tests are still green and the examples are working so I expect everything to be good
=> Better Performance in the SlideY and Svg Components

packages/react-vapor/src/components/drop/DomPositionCalculator.ts, packages/react-vapor/src/components/drop/DropPod.tsx, packages/react-vapor/src/components/drop/examples/DropExamples.tsx, packages/react-vapor/src/components/drop/tests/DomPositionCalculator.spec.ts
Set the width if we use the sameWidth
Set the position if the drop position bottom-right is rendered
change the drop bottom-right position
=> Fix drop bottom right postion

create-live-demo.js, create-live-demo.sh, packages/react-vapor/docs/src/components/ComponentPage.tsx, packages/react-vapor/docs/src/demo-building-blocs/Code.tsx, packages/react-vapor/webpack.config.js
Examples source code print directives were throwing an error when loading an example for the first time.
- Make the print directives regex work on first load
- Prettify the examples source code based on [the prettier config from tsjs](https://github.com/coveord/tsjs/blob/master/prettier-config.js)
Before: [notice the example source code at the bottom is not rendered](https://static.cloud.coveo.com/react-vapor/index.html#/components/Form).
After: [the source code at the bottom is rendered](https://coveo.github.io/react-vapor/7bd41f9da5ddc65808d21af57b9236a7/index.html#/components/Form)
None, it only affects the demo
-   [ ] …
=> fix: print source directives and prettier config

packages/react-vapor/src/Defaults.ts, packages/react-vapor/src/components/select/SelectConnected.tsx
Every SelectConnect use the default drop root as parent Selector to avoid bad rendering when a single select is used inside a small container "position: relative"
I not sure yet but I dont think its a bad idea to always use the default root as parent selector to have the maximum space to render the dropdown
=> add Defaults DropRoot as default parentSelector for a SelectConnected

packages/react-vapor/src/Defaults.ts, packages/react-vapor/src/components/tooltip/Tooltip.tsx
We start using a lot '_body_' for tooltip.container in the table headers with react. 
no
-   [ x] The proposed changes are covered by unit tests
-   [ x] The potential breaking changes are clearly identified
-   [ x] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)
=> Set default tooltip container as 'body'

packages/react-vapor/package.json, packages/react-vapor/src/components/color-picker/ColorPicker.spec.tsx, packages/react-vapor/src/components/color-picker/ColorPicker.tsx, packages/react-vapor/src/components/color-picker/ColorPickerExamples.tsx
Adds a new component which display a color picker, using `react-color`: https://casesandberg.github.io/react-color/
It's synched with an hidden "InputConnected" so that it's possible to retrieve the currently selected color from the state
- None that I know of ;) 
=> Add ColorPicker component

packages/vapor/scss/typography/headings.scss
add mod for the margin-top for each h
do not use margin on h tag. H tag is used for the font size only
remove breaking change
=> remove margin-top

package.json, packages/react-vapor/src/components/headers/HeaderWrapper.tsx, packages/react-vapor/src/components/headers/tests/HeaderWrapper.spec.tsx
Our headers didn't use the `panel-header` class which was already defined in vapor and specially designed for panel and modal headers. Some other classes like `action` depended on having `panel-header` as parent to be applied.
- Refactored the `HeaderWrapper` component (used by the `BasicHeader` and `BreadcrumbHeader` components) so that it has the `.panel-header` class.
None, I made sure the rendered DOM nodes structured the same way and that all the existing props are still supported.
=> Improve the header styles

packages/react-vapor/src/components/calendar/Calendar.tsx, packages/react-vapor/src/components/calendar/tests/Calendar.spec.tsx, packages/react-vapor/src/components/datePicker/DatePickerBox.tsx
The split-layout is dependent on the window's width and under a certain resolution it wraps.
I replaced the classes with flex to avoid this issue
None
=> Change calendar dropdown layout classes

packages/react-vapor/src/components/table-hoc/reducers/TableRowReducers.ts, packages/react-vapor/src/components/table-hoc/tests/TableRowReducers.spec.ts
`TableHOCRowActions.remove` action was removing all rows with an id that match the id in the action payload no mater what is the tableId specified. This was causing the action to delete rows across tables.
None.
=> fix(tablerow): remove action not checking tableId

packages/react-vapor/src/components/numericInput/NumericInputConnected.tsx, packages/react-vapor/src/components/numericInput/examples/NumericInputExamples.tsx
Added type={'button'} to the increment/decrement button since we don't want them to submit if they are in a Form.
Changed the error message position to fix this issue:
None.
=> fix: error message alignment and buttons should not submit form for NumericInput component

packages/react-vapor/src/components/table-hoc/actions/TableHeaderActions.ts, packages/react-vapor/src/components/table-hoc/reducers/TableWithSortReducers.ts, packages/react-vapor/src/components/table-hoc/tests/TableWithSortReducers.spec.ts
The `sortTable` action was not allowing to specify in which order you want to sort (ascending vs descending). Added the possibility to do so while maintaining the default behavior of toggling between ascending and descending.
None.
=> feat: allow specifing isAsc in sortTable action

packages/react-vapor/src/components/table-hoc/TableHOCUtils.ts, packages/react-vapor/src/components/table-hoc/tests/TableHOCUtils.spec.ts
I needed two more table HOC utils:
- A way to know what are the `id`s of all the predicates associated with a given table
- A way to know what is the date picker id associated with a given table
None, those a new utils
=> Add missing Table HOC utils

packages/react-vapor/package.json, packages/react-vapor/src/utils/UrlUtils.ts
Added a small util to that parses the current url and returns the search params as an object. I added a new lib at the same time that handles query-strings in a graceful way. I will need this lib in some incoming PR.
I didn't do any tests for that one because its simply impossible to mock `window.location` in any way with jasmine :hankey: 
None
=> Add getSearchParams util in UrlUtil

packages/react-vapor/docs/src/components/index.tsx, packages/react-vapor/src/components/table-hoc/TableHOCUtils.ts, packages/react-vapor/src/components/table-hoc/TableWithUrlState.tsx, packages/react-vapor/src/components/table-hoc/examples/TableHOCServerExampleReducer.ts, packages/react-vapor/src/components/table-hoc/examples/TableHOCServerExamples.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithUrlState.spec.tsx, packages/react-vapor/src/utils/UrlUtils.spec.ts, packages/react-vapor/src/utils/UrlUtils.ts
I implemented a `tableWithUrlState` HOC that basically saves any table state in the url query params. 
Usage: 
```tsx
const MyTable = _.compose(
tableWithUrlState,
tableWithPagination()
// whatever other table HOC
)(TableHOC);
<>
<MyTable 
// the usual TableHOC props
onUpdateUrl={(currentQueryString: string) => {
// Update the window href using your favorite way
}}
/>
</>
```
To test it in the demo you can simply navigate to the `TableHOCServer` example and play with the table there.
None expected.
=> Implement tableWithUrlState HOC

packages/react-vapor/Index.ts
React-vapor isn't usable in conjunction with create-react-app in its current state. It seems that underscore needs to be implicitly imported.
You can try it out here
[![Edit vibrant-smoke-g6uef](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-smoke-g6uef?fontsize=14)
=> fix(index.ts): add missing underscore import

packages/react-vapor/src/components/actions/SecondaryActions.tsx
The datePicker dropdown and the actions dropdown of the table hoc generate with their respective ids.
none that I know of
=> Datepicker and actions dropdown do not generate with the same id

packages/react-vapor/src/components/navigation/pagination/NavigationPaginationConnected.tsx, packages/react-vapor/src/components/navigation/pagination/tests/NavigationPaginationConnected.spec.tsx, packages/react-vapor/src/components/navigation/perPage/NavigationPerPageConnected.tsx, packages/react-vapor/src/components/navigation/perPage/tests/NavigationPerPageConnected.spec.tsx
The `turnOnLoading` in the `tableWithPagination` imposes the parent to turn off the loading after changing page, which causes issues for client-side tables. The client-side table does not require a loader while changing page, and for server-side tables, we can handle the loader with the fetch action.   
The loader won't be triggered by the onPageClick and onPerPageClick events.
=> Remove turnOnLoading in the navigation components

packages/react-vapor/package.json, packages/react-vapor/src/components/toast/ToastContainer.tsx, packages/react-vapor/src/components/toast/tests/ToastContainer.spec.tsx
I added in the onClose from the Toast component the step that delete the error from the handledErrors array
=> +onClose from toast that removed the error in handledErrors array

packages/react-vapor/src/components/toast/examples/ToastExamples.tsx, packages/vapor/scss/typography/headings.scss
A max-width has recently been added to headings (`h1`, `h2`, ..., and friends). This makes no sense and is causing issues in some places because it wasn't thought to be used this way.
None, I'm reverting to what we had previously
=> Revert max-width on headings

packages/react-vapor/src/components/navigation/pagination/NavigationPagination.tsx, packages/react-vapor/src/components/table-hoc/TableWithPagination.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPagination.spec.tsx
The `tableWithPagination` was calculating a `totalPages` count of 0 when there are no data, but this is wrong, because there is always at least one page (aka `totalPages === 1`) which will be empty when there are no data (but the page still exist).
=> Fix navigation pagination weird state

packages/vapor/scss/components/markdown-documentation.scss, packages/vapor/scss/typography/elements.scss
Some max-width css rule has been added to `p` and `li` html tags. I guess that was intended to be scoped under the `.markdown-documentation` class and not for any `p` or `li`.
`¯\_(ツ)_/¯`
=> Remove unwanted max-width on `p` and `li`

.travis.yml, create-live-demo.sh, packages/react-vapor/docs/index.html, packages/react-vapor/package.json, packages/react-vapor/webpack.config.js
It seems we were publishing and hosting our demo page along with all its source files:
This is unecessary because the browser doesn't need the .ts files to run properly, only the .js chunks.
From now on we will be publishing a `dist` folder that will look like this:
None expected
=> build: stop uploading demo source files to s3

.travis.yml, invalidate-cloudfront.js, packages/react-vapor/package.json
When pushing new files to AWS S3 (happens each time master builds successfully), the old files were remaining in the AWS CloudFront cache. This behavior resulted in unsuccessful demo page load until the cache was successfully invalidated every 24h. 
What was done here is to trigger a cloudfront cache invalidation right after new files are deployed.
None.
=> Invalidate AWS CloudFront cache

.travis.yml
Currently travis cannot deploy the demo, because I messed up the AWS credentials in my previous PR. Reverting to a working state. The cloudfront invalidation script is expected not to work.
=> Revert travis deploy credentials changes

packages/vapor/scss/forms/block-form.scss
This [PR here](https://github.com/coveo/react-vapor/commit/4cd24c62caebed6daadbc21aeacbd6d62b826621) introduced a rule which broke when I merged the [Scaled Section description PR](https://github.com/coveo/react-vapor/pull/1339)
This will fix the build
None
=> Fix margin-top rule issued from bad merge

packages/react-vapor/src/components/blankSlate/BlankSlateWithTable.tsx, packages/vapor/scss/tables/table-align-header.scss, packages/vapor/scss/variables.scss
=> Add class to remove the 40px for the first row on table align header with a blankslate in error

packages/react-vapor/tsconfig.build.json
It seems like `tsconfig` extends no longer extend the `exlcude` field properly.
=> Fix declaration file

packages/react-vapor/src/components/collapsible/CollapsibleToggle.tsx, packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx, packages/react-vapor/src/components/table-hoc/examples/TableHOCServerExamples.tsx, packages/react-vapor/src/components/table-hoc/reducers/TableRowReducers.ts, packages/react-vapor/src/components/table-hoc/tests/TableRowConnected.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableRowReducers.spec.ts, packages/vapor/scss/tables/table-collapsible-rows.scss
Multiple rows can be opened at the same time (easier to compare)
Clicking on the row selects it but doesn't open it
Clicking on the collapse button doesn't select the row but toggle its collapsed state
Opened rows doesn't have a different background anymore
Different behavior but usage stays the same
=> Change the Style and Behavior of the Table Collapsible Button

packages/react-vapor/src/components/table-hoc/TableSelectors.ts, packages/react-vapor/src/components/table-hoc/TableWithActions.tsx, packages/react-vapor/src/components/table-hoc/examples/TableHOCExamples.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithActions.spec.tsx
Update exemple to remove button since it's not usefull anymore
Add unit tests
Behaviour is different, code isn't
=> Deselect Table Row on Click Outside

packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx, packages/react-vapor/src/components/table-hoc/tests/TableRowConnected.spec.tsx
Added a class `no-hover` if the row has no actions associated
none
=> added no-hover class if no actions associated with that row

packages/react-vapor/src/components/table-hoc/TableHOC.tsx, packages/react-vapor/src/components/table-hoc/examples/TableHOCExamples.tsx, packages/react-vapor/src/components/table-hoc/tests/TableHOC.spec.tsx
Added a prop `hasBorderTop` to the TableHOC, because there was no clean way to add a border top on the actions bar.
None
=> Add hasBorderTop prop to the TableHOC

packages/react-vapor/src/components/tooltip/tests/DateTooltip.spec.tsx
the date of reference was few minutes late from the date in the test since they were not made in the same scope. Fixed it
-   [x ] The proposed changes are covered by unit tests
=> fixed the dateTooltip test where compared date were not the same

packages/react-vapor/package.json, packages/react-vapor/src/components/table-hoc/examples/TableHOCServerExamples.tsx, packages/react-vapor/webpack.config.js, packages/react-vapor/webpack.config.prod.js, packages/react-vapor/webpack.config.prod.minify.js, packages/react-vapor/webpack.config.test.js
I had a look at our build process and did a few optimizations:
- `build` command now produce the `.js`, `.min.js` and `.min.js.map` files in one single webpack execution
- `start` and `docs` command no longer generate the definition files (`transpileOnly: true`), but they still do the necessary type checking.
- better quality source maps are generated during the unit tests and while running `npm start`
I timed each command once with linux `time` command on master and did the same process on this branch and here are the results. The time displayed here is the `real` time on my laptop so it takes into account the multi-threading, which means it could be slower on TravisCI or faster on your machine depending on your CPU specs.
| command | master branch | this branch |
| …
=> Improve build speeds

.travis.yml, create-live-demo.sh, packages/react-vapor/.gitignore
I found out why sometimes our pull request demo links display `Page Not Found`. Its because in our demo build script, we were pulling the `gh-page` branch into our current branch. Occasionally there would be conflicts and therefore force pushing the current pull request branch into gh-page without conserving the old demo folders. :crying_cat_face: 
I edited the script so that we first checkout in `gh-pages`, then create or overwrite the demo folder for the current PR.
Hopefully none.
=> Fix demo page not found occasional problem

packages/react-vapor/src/components/multilineInput/SplitMultilineInput.tsx
This PR should fix following issue: 
- Remove duplicate label title
- Validate onChange
- Add different id to input
This component has not been used in the project AFAIK, so we will not have any negative influence
=> Fix(SplitMultilineInput): Remove duplicate label and validate onChange

lerna.json
This will hopefully prevent Travis from triggering a second useless build when pushing the tags and the changelogs.
None
=> ci(travis): skip travis builds when pushing tags

packages/react-vapor/src/components/form/Form.tsx
Changed the className order on the `Form` component so that we can override the `mt2` style.
=> fix(form): changed the classname order to allow overrides

packages/react-vapor/src/components/multilineInput/MultilineInput.tsx, packages/react-vapor/src/components/multilineInput/tests/MultilineInput.spec.tsx
Add invalid message to the input in MultilineInput component.
nope
=> fix(multilineInput): add invalidmessage prop

packages/react-vapor/src/components/input/examples/InputExamples.tsx
Ux recommendation was to move the multilineBox component in the input examples. But since the multilineBox is more of the generic component /building block type, it can be used to build more complex components that will not only be necessarily used for inputs. 
What I did for now is to add an example of how the component could be used to build a multiline input. I did not remove the multilineBox component example because I feel it still has its place even if it could be modified to show the building block functionnality of the component.
only affect the demo
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed …
=> feat(demo): added a multiline input made with the multilinebox for ADUI-4988

packages/react-vapor/src/components/editor/EditorConstants.ts
To be used for advanced parameters editor in ML model configuration.
This is a temporary solution, since I did not find the mode of _HOCON_ for CodeMirror. https://codemirror.net/mode/index.html
nope
=> feat(editor): add text mode to code mirror modes

packages/react-vapor/src/components/input/Input.tsx, packages/react-vapor/src/components/input/InputConnected.tsx, packages/react-vapor/src/components/input/tests/InputConnected.spec.tsx
Added a isdirty toggle dispatch onChange for inputConnected so that the input gets dirty if not empty and displays error message if empty
=> improvement(inputconnected.tsx): added toggle dispatch on inputconnected

packages/react-vapor/src/components/table-hoc/TableWithFilter.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithFilter.spec.tsx
Add a blankSlate if the filter is defined but the data is empty
Add uts
=> feat(table-hoc): blankslate table with filter

packages/react-vapor/src/components/table-hoc/TableHOC.tsx
Its more easy for react to render and remove the last element instead of the first one.
I change the order because the tbody with the data always stay but the loading is unmount when the loading is false
=> fix(table-loading): table loading improvement

packages/vapor/scss/components/navigation.scss
When setting the css `height` property, the margin is added to this value so it because tricky to set the right parent height.
- Changed `margin-top` for `padding-top`
None
=> fix(navigation): adjust computed height

packages/react-vapor/src/components/table-hoc/TableWithFilter.tsx
dont show the blankslate if not defined as prop
=> fix(table-loading): client-side table

packages/vapor/scss/variables.scss
@oliviertaillon made the remark that the sticky footed did not have the same padding right as it is applied everywhere else. So I adjusted it.
small style change.
=> fix(css): sticky footer css adjusted

packages/react-vapor/src/ReactVapor.ts, packages/react-vapor/src/ReactVaporReducers.ts, packages/react-vapor/src/components/input/examples/InputExamples.tsx, packages/react-vapor/src/components/validation/ValidationActions.ts, packages/react-vapor/src/components/validation/ValidationReducer.ts, packages/react-vapor/src/components/validation/ValidationSelectors.ts, packages/react-vapor/src/components/validation/ValidationState.ts, packages/react-vapor/src/components/validation/ValidationTypes.ts, packages/react-vapor/src/components/validation/components/ValidationMessage.tsx, packages/react-vapor/src/components/validation/components/tests/ValidationMessage.spec.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtyInputHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueInputValidationHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithValidationMessageHOC.tsx, packages/react-vapor/src/components/validation/hoc/connectHOC.d.ts, packages/react-vapor/src/components/validation/hoc/tests/WithDirtyInputHOC.spec.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithNonEmptyValueInputValidationHOC.spec.tsx, packages/react-vapor/src/components/validation/tests/ValidationReducer.spec.ts, packages/react-vapor/src/components/validation/tests/ValidationSelectors.spec.ts
The idea here is to have actions and selectors to easily manage errors, warnings and dirty state for components.
Then, we can add HOCs to wrap existing components with features related to this state. 
Some ground rules for those HOCs, which follow React's doc about it:
* Ensure that you pass all the original props to the child component
* Ensure that you pass down props that might be used in multiple HOCs
* For instance, wrapping a component that does not have an initial value with a new `initialValue` could pretty well be used across multiple validation HOC. Hence it should be propagated
* Do not always reset the state on unmount. The component might be dirty, but unmounted temporarily, for some reason.
Then, there would be Components that read those states and output something. I have …
=> feat(validation): backbone for generic error, warning and dirty components

package.json, packages/react-vapor/src/components/actions/ActionBar.tsx, packages/react-vapor/src/components/actions/tests/ActionBar.spec.tsx, packages/react-vapor/webpack.config.js
```tsx
// source code of the examples in the screenshots below
{
name: 'Link to Coveo (disabled)',
link: 'http://coveo.com',
target: '_blank',
icon: 'edit',
primary: true,
enabled: false, //        <--- Here
hideDisabled: false,
},
{
name: 'Action 3',
trigger: () => alert('You cannot trigger me'),
icon: 'edit',
primary: true,
enabled: false, //        <--- Here
hideDisabled: false,
},
```
Before:
After:
None
=> fix(actionbar): make disabled actions stay that way

packages/react-vapor/package.json, packages/react-vapor/src/components/actionable-item/ActionableItem.tsx, packages/react-vapor/src/components/chart/ChartTooltip.tsx, packages/react-vapor/src/components/drop/Drop.tsx, packages/react-vapor/src/components/drop/DropPod.tsx, packages/react-vapor/src/components/select/SelectConnected.tsx
Make the `DropPod` component fallback on the `Defaults.DROP_ROOT` and `Defaults.DROP_PARENT_ROOT` for `selector` and `parentSelector` props respectively.
None expected.
=> fix(drop): fallback on Defaults for selector and parentSelector props

packages/react-vapor/src/components/button/examples/ButtonExamples.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtySaveButtonHOC.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithDirtySaveButtonHOC.spec.tsx
The idea of this HOC is to use the generic validation to wrap a button that has all the required behavior according to the components it must validate.
The Button is bound to one or multiple "validationIds". Then, for all the ID states:
If there are errors: Button disabled, shows the error tooltip
If there are warnings: Button enabled, shows the warning tooltip
If there is **no** dirty component: Button disabled, shows the dirty tooltip.
So the button is only enabled when a component is dirty and there are no errors.
`skipDirty` allows you to skip the dirty check, so only errors could disable the button.
None
-   [ ] …
=> feat(validation): add withdirtysavebutton hoc

packages/react-vapor/src/components/table-hoc/TableHOC.tsx
In order to implementing cards into `TableHOC`, we would need to apply flexbox or other styles into the parent `tbody`.
nope
=> feat(tablehoc): add tbodyclassname props

packages/react-vapor/src/components/blankSlate/BlankSlateWithTable.tsx, packages/react-vapor/src/components/table-hoc/TableWithFilter.tsx
We would need these two props to apply `flex` and `full-content-x` to the blankslate in a table with cards.
no i swear
=> feat(blankslate): add classname props

.travis.yml
I noticed Travis was invalidating the cloudfront cache when building pull requests.
This is because `$TRAVIS_BRANCH` equals to `master` for pull requests that target master. See Travis docs:
None
=> ci(travis): stop invalidating cloudfront on PR builds

packages/react-vapor/package.json, packages/vapor/package.json
It was only added in the devDependencies of react-vapor package, but we actually import the style in vapor and import the js also in the react-vapor package, so clearly it should be a depedency.
None.
=> fix(dependencies): add rc-slider as dependency

packages/demo/src/components/examples/PartialStringMatchExamples.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.spec.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.tsx
Allow connected components to be rendered as children of the `PartialStringMatch` component.
None.
=> Allow connected components to be rendered as children of the `PartialStringMatch` component.

packages/react-vapor/src/components/input/Input.tsx
the coveo interface editor is using react-vapor v3. bumping the version breaked some props type. fixing them for retro
only added optional properties to an interface.
=> fix(input): added native html prop types for retro compatibility

packages/demo/src/components/examples/PartialStringMatchExamples.tsx, packages/react-vapor/src/components/loading/Loading.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.spec.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.tsx
It seems the `PartialStringMatch` was breaking when trying to render class components that had no children such as the `Loading`.
None.
=> fix(partialstringmatch): allow class components without children

packages/demo/src/components/examples/PartialStringMatchExamples.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.spec.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.tsx, packages/react-vapor/tsconfig.json
The PartialStringMatch is throwing an error when rendering a redux Provider inside it.
None.
=> fix(partialstringmatch): allow rendering redux Provider inside it

packages/demo/src/components/examples/SingleSelectExamples.tsx, packages/react-vapor/src/components/drop/Drop.tsx, packages/react-vapor/src/components/drop/DropPod.tsx, packages/react-vapor/src/components/filterBox/FilterBox.tsx, packages/react-vapor/src/components/filterBox/tests/FilterBox.spec.tsx, packages/react-vapor/src/components/listBox/ListBox.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.spec.tsx, packages/react-vapor/src/components/partial-string-match/PartialStringMatch.tsx, packages/react-vapor/src/components/select/hoc/SelectWithFilter.tsx
- remove highlight for connected components in the PartialStringMatch, because there is no way to compute the state props properly
- make the item selection work in the single select demo page
- refactored a bunch of deprecated componentWillSomething
None
=> Fix partial string match once again

packages/react-vapor/src/components/select/MultiSelectConnected.tsx, packages/react-vapor/src/components/select/SelectConnected.tsx, packages/react-vapor/src/components/select/SingleSelectConnected.tsx, packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx
added the toggleClasses prop as in singleSelect so that we can add classes on multiselect toggle
drop
Sorry, the branch name does not represent the feature, I tried it with spread syntax, didn't work really well, made the fix but forgot to change the branch name
=> feat(multiselectconnected.tsx): +toggleClasses prop

packages/react-vapor/src/components/drop/DropPod.tsx, packages/react-vapor/src/components/drop/tests/DropPod.spec.tsx
The default props in the drop pod are set before the Defaults variables are loaded, thus defaulting
to 'body' all the time.
passing the Defaults.DROP_ROOT and the Defaults.DROP_PARENT_ROOT directly where they are used instead of relying on defaultProps
none
=> fix(drop pod): the Defaults.DROP_ROOT was not properly set

packages/react-vapor/src/components/multilineBox/MultilineBox.tsx, packages/react-vapor/src/components/multilineBox/tests/MultilineBox.spec.tsx
I'm creating a MultiValuesInput and I need the defaultProps to be "" (not an object)
None
=> fix(multilinebox): allow usage of empty string as defaultProps

packages/demo/src/components/examples/TableHOCwithBlankSlateExamples.tsx, packages/react-vapor/src/components/table-hoc/TableWithFilter.tsx
Allow specifying the `tableWithFilter` related options through the props:
```tsx
// before
const Table = _.compose(
tableWithFilter({
matchFilter: (filterText, row) => true,
blankslate: filterBlankslateProps
}),
tableWithActions()
)(TableHOC)
<Table
id='table-id'
className='table'
data={myData}
renderBody={renderMyRows}
/>
// now you also can do:
const Table = _.compose(
tableWithFilter(),
tableWithActions()
)(TableHOC)
<Table
id='table-id'
className='table'
data={myData}
renderBody={renderMyRows}
matchFilter={(filterText, row) => true}
blankslate={filterBlankslateProps}
/>
```
This new way of doing things is more convenient because usually you have the dispatch props in the scope when setting the props on the `Table`.
Deleted some useless interfaces:
- `ITableWithFilterStateProps`
- …
=> feat(tablewithfilter): allow specifying config through props

packages/react-vapor/src/components/filterBox/FilterBox.tsx
Changed the condition in `componentDidUpdate`. Input text value in filter box should be updated to empty string, when resetting filter box by clicking on Clear Filter button in table blank slate.
No
=> fix(filterbox): remove input text when reset filter value

packages/demo/src/components/examples/HeaderExamples.tsx, packages/react-vapor/src/components/breadcrumbs/Breadcrumb.tsx, packages/react-vapor/src/components/headers/BreadcrumbHeader.tsx
`BreadcrumbHeader` will now pass down its children to the `Breadcrumb`, then `Title` component so that they get rendered after the title but before the actions.
Such as the `brain` icon here
=> fix(breadcrumbheader): pass down children prop

packages/demo/src/components/examples/TextAreaExamples.tsx, packages/react-vapor/src/components/textarea/TextArea.tsx, packages/react-vapor/src/components/textarea/tests/TextArea.spec.tsx
Added validation to the textare component
Now when using Labels with htmlFor props you need to give it as a children to the component.
```tsx
<TextAreaConnected
id="super-textarea-8"
validate={(value: string) => value !== ''}
validationMessage={'TextArea should not be empty!'}
>
<Label htmlFor="super-textarea-8">Beautiful Textarea</Label>
</TextAreaConnected>
```
=> feat(textarea): add validation to textarea + refactoring with hooks

packages/react-vapor/src/components/drop/DropPod.tsx
update display to none if ie 11
=> fix(ie-11-drop): ie 11 drop

packages/react-vapor/src/components/table-hoc/TableHOC.tsx
I wanted to make the change in ml blacklist but i forgot to add isCard in TableLoading.Body in tableHOC
=> fix(tablehoc): added isCard in tableLoading.body

packages/demo/src/components/examples/LinkSvgExamples.tsx, packages/demo/src/styles/Menu.tsx
Removed the following navigation entries in the demo:
None
=> docs(demo): remove empty navigation entries

packages/vapor/scss/tables/table.scss
made the mod-card-list display: none when :hidden because the loading cards were not align with the one rendered
=> style(table.scss): remove display when mod-card-list is hidden

packages/react-vapor/src/components/form/Form.tsx, packages/react-vapor/src/components/form/tests/Form.spec.tsx
I needed a Form without those nasty default margin top and bottom.
None
=> feat(form): add noMargin prop

packages/react-vapor/src/components/menu/MenuConnected.tsx, packages/react-vapor/src/components/optionsCycle/OptionsCycle.tsx, packages/react-vapor/src/components/optionsCycle/tests/OptionsCycle.spec.tsx
add a prop to handle something when the option change in the OptionCycle
update uts without a mount in the dom
add uts for this new props
=> feat(optionscycle): add option change callback

packages/vapor/scss/controls/input-field.scss
We want a smaller default padding for the TextArea component, which will make it look like a normal input.
Before:
After:
All the _textarea_ under _.input-field_ will have a smaller padding.
=> Fix the padding of TextArea component

packages/vapor/scss/tables/table.scss
1. When we use the class `.mod-card` in a table row, the background color should not be changed to light grey on hover. This will fix the conflict of background colors in the ML blacklists configuration cards.
2. Add `.no-border-bottom` to allow removing the border bottom in a table row.
Nope. The first one is only used in Blacklists, and the second one is a new class.
=> Minor fixes of table style

packages/vapor/scss/tables/table.scss, packages/vapor/scss/variables.scss
`.mod-card` was created for the feature of blacklists configuration, and it was scoped in `.mod-card-list` which used css grid layout for some specific situations. Currently, for the `StatementGroupCard`, I think we could reuse certain rules of `.mod-card` since they have the same behavior, ex: box-radius, box-shadow, hover effect etc. One thing different from `BlacklistCard` is that we only have one card per row in `StatementGroupsTable`.
Nope. I'll possibly make some tiny adjustments in `BlacklistCard` later when I continue working on this story, but now it's on hold and behind a feature flag.
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) …
=> fix(modcard): update css rules to make it reusable

packages/demo/src/components/examples/CodeEditorExamples.tsx, packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx
The `CodeEditor` component is not exposing all the CodeMirror options such as line wrapping (which I wanted). So I added an optional prop `options` on the `CodeEditor`
None
=> fix(codeeditor): front all codemirror options on code editor

packages/vapor/scss/utility/flex.scss
We already have `align-end` and now we need `align-start` =D
No I swear 
=> Add align-start class to flex.scss

packages/react-vapor/src/components/svg/Svg.tsx, packages/react-vapor/src/components/tooltip/Tooltip.tsx
`import React from 'react'` seems to be incorrectly generating the declaration of components that explicitly use the `React` types.
For example
```tsx
import React from 'react'; // Breaks in admin-ui repo
import * as React from 'react'; // Works in admin-ui repo
export class MyComponent extends React.Component {}
```
Not sure.
=> fix(rollup): correct some imports to make build work for admin-ui

packages/demo/src/components/examples/DatePickerExamples.tsx, packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx, packages/react-vapor/src/components/datePicker/DatePickerDropdownConnected.tsx, packages/react-vapor/src/components/datePicker/tests/DatePickerDropdown.spec.tsx
Add drop as option for the datePicker
Add 2 examples to use the datePicker with drop
add uts for the new drop component
User drop for the Date Picker to be rendered everywhere without parent container problems
none
=> feat(datepicker): use drop

packages/demo/src/components/examples/SliderExamples.tsx, packages/react-vapor/src/components/slider/MiddleSlider.tsx, packages/react-vapor/src/components/slider/SliderHandle.tsx, packages/react-vapor/src/components/slider/tests/MiddleSlider.spec.tsx, packages/vapor/scss/controls/slider.scss
we can now append the slider values to both side of the slider. The to side can be formatted with the `appendedValueFormatter` props
I created an union type for the `appendedValue` props. So if we simply pass the `appendedValue` to `true`, the appended value will normaly appear to the right of the slider. But we can pass it with the `AppendedValueSide` enum that has the `left` `right` `both` keys and the value will appear accordingly.
The Initial implementation of the `appendedValueFormatter` prop still work as intended, but depending of the side it formats, the `left` or `right` will be passed in the params to grant the developer the possibility to customize the format differently if need be. 
no breaking change intended
-   [x] The …
=> feat(middle slider): can append a value on both side

packages/demo/src/components/examples/DatePickerExamples.tsx, packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx, packages/react-vapor/src/components/datePicker/DatePickerDropdownConnected.tsx, packages/react-vapor/src/components/datePicker/tests/DatePickerDropdown.spec.tsx
It was breaking the DatePickerDropdown component.
DatePickers wont be using the drop anymore.
=> revert(datepicker): use drop

packages/demo/src/components/examples/DatePickerExamples.tsx, packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx, packages/react-vapor/src/components/datePicker/DatePickerDropdownConnected.tsx, packages/react-vapor/src/components/datePicker/tests/DatePickerDropdown.spec.tsx
Update the date picker to user drop only when the props is set
=> fix(datepicker): drop

packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx, packages/react-vapor/src/components/datePicker/DatePickerDropdownConnected.tsx, packages/react-vapor/src/components/datePicker/tests/DatePickerDropdownConnected.spec.tsx
Get the drop isOpen in the case of withDrop to handle the cancel
add uts
=> fix(datepicker): fix drop

packages/demo/src/components/examples/SingleSelectExamples.tsx, packages/react-vapor/src/components/select/MultiSelectConnected.tsx, packages/react-vapor/src/components/select/SelectConnected.tsx, packages/react-vapor/src/components/select/SingleSelectConnected.tsx, packages/react-vapor/src/components/select/tests/SingleSelectConnected.spec.tsx, packages/vapor/gulpfile.js, packages/vapor/resources/icons/svg/flag-eu.svg, packages/vapor/resources/icons/svg/flag-us.svg, packages/vapor/scss/common/palette.scss, packages/vapor/scss/components/menu.scss, packages/vapor/scss/components/navigation.scss, packages/vapor/scss/variables.scss
- Added the `customButton` prop on the `SingleSelectConnected` component. It allows to render a custom toggle for the SingleSelectConnected instead of the default white toggle.
- Added 2 new icons: `flagUs` and `flagEu`. SVGs were taken from Wikipedia
- Adjusted the `blue-purple-2` color so that it matches the color we use for active side navigation section and opened dropdowns.
None
=> SingleSelectConnected custom button

packages/demo/src/components/examples/LinkSvgExamples.tsx, packages/react-vapor/src/components/svg/LinkSvg.tsx, packages/react-vapor/src/components/svg/tests/LinkSvg.spec.tsx
Add a prop `text` to the component `LinkSvg` in order to allow displaying customized texts under hyperlink.
nope
=> feat(linksvg): add a prop for text

packages/react-vapor/src/components/select/hoc/SelectWithPredicate.tsx
`matchPredicate` isn't used when `isServer` is set to true, so it is optional.
None
=> fix(selectwithpredicate): make matchPredicate prop optional

packages/react-vapor/rollup.config.js, packages/react-vapor/tsconfig.build.json, packages/react-vapor/webpack.config.js
With `transpileOnly: true` in the webpack.config, the react-vapor.js build was broken because the custom typescript keys transformer was skipped.
With the changes made, here is what is happening:
- `webpack` build: generates the UMD build (`react-vapor.js`) + source maps
- `rollup` build: generates the ES modules build (`react-vapor.esm.js`) + the type declarations
When running `npm run build` it runs the rollup and webpack build concurently so that we have everything at once.
=> fix(commonjs): remove transpileOnly option in webpack build

packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueInputValidationHOC.tsx
[COM-453]
Really quick thing I noticed when using the HOC. This wouldn't clear the right feature, so the error was still showing up.
I tried testing it, but `mount` (or anything else, in fact) doesn't call `React.useEffect`, and apparently the only way to test it is by using `jest.mock()`... 
I validated the other "clearX" and they are fine
No
[COM-453]: https://coveord.atlassian.net/browse/COM-453
=> fix(nonemptyhoc): clearError not clearing the right id

packages/react-vapor/src/components/validation/hoc/WithDirtyMultiSelectHOC.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithDirtyMultiSelectHOC.spec.tsx, packages/react-vapor/src/utils/tests/TestUtils.ts
[COM-453]
I brought back this implementation on Gael's suggestion, so here it is :)
It registers a dirty state if there is a difference between the initial values and the selected values.
none
[COM-453]: https://coveord.atlassian.net/browse/COM-453
=> feat(multiselect): implement dirty hoc

packages/react-vapor/src/components/select/hoc/SelectWithInfiniteScroll.tsx, packages/react-vapor/src/components/select/hoc/tests/SelectWithInfiniteScroll.spec.tsx
The select with infinite scroll was displaying its loading (the one with orange dots) while the skeleton loading was already displayed.
The changes made here remove the loading with orange dots when the skeleton loading is already there.
None
=> fix(select): remove dotted loading from select infinite scroll

packages/react-vapor/src/components/slider/Slider.tsx, packages/vapor/scss/controls/slider.scss
The slider components were spilling out of their container which made them awkward to style in any layout.
- As you can see, the slider handle stretches outside of the slider container to the left.
- The marks spill out on the bottom too.
- Now it is contained in the container.
- Marks are ok too
It might change the slider appearance in some places where workaround were applied to make it fit.
=> fix(slider): make the sliders fit into their parent container

packages/demo/src/components/examples/MultiSelectExamples.tsx, packages/react-vapor/src/components/select/hoc/tests/SingleSelectWithFilter.spec.tsx, packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueMultiSelectValidationHOC.tsx, packages/react-vapor/src/components/validation/hoc/index.ts, packages/react-vapor/src/components/validation/hoc/tests/WithDirtyMultiSelectHOC.spec.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithNonEmptyValueMultiSelectValidationHOC.spec.tsx, packages/react-vapor/src/utils/tests/TestUtils.ts
https://coveord.atlassian.net/browse/COM-435
Created a validation for non empty multi select
=> feat(multiselect): com-435 create non empty validation for multi select

packages/react-vapor/src/components/validation/hoc/WithDirtySaveButtonHOC.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithDirtySaveButtonHOC.spec.tsx
https://coveord.atlassian.net/browse/COM-435
Update error message when there are multiple. This will avoid a long list of errors log and there should be validationMessages near the input to properly identify missing fields
=> improvement(save button hoc): change error message if more than 1

packages/react-vapor/src/components/limit/Limit.tsx, packages/react-vapor/src/components/limit/tests/Limit.spec.tsx, packages/react-vapor/src/components/subNavigation/SubNavigation.tsx, packages/react-vapor/src/components/subNavigation/tests/SubNavigation.spec.tsx, packages/react-vapor/src/components/subNavigation/tests/SubNavigationConnected.spec.tsx
The onclick html property was in conflict with the link property. in order to access the link, the function passed to onlclick must return true. 
I also refactored the component to get rid of the deprecated class component lifeCycle methods.
Fixed the broken uts.
No breaking change intented
=> fix(sub navigation): fixed the link prop and small refactor

lerna.json, packages/demo/src/components/examples/RadioExamples.tsx, packages/react-vapor/src/components/childForm/tests/ToggleForm.spec.tsx, packages/react-vapor/src/components/radio/Radio.tsx, packages/react-vapor/src/components/radio/RadioSelect.tsx, packages/react-vapor/src/components/radio/tests/Radio.spec.tsx, packages/vapor/scss/components/modal.scss
A radio button can now be wrapped inside a div container or a fragment container. Which means that an element could be in the same node level in the DOM as the radio button and a CSS class could affect both components. For instance the following image display a radio button that share the same CSS class with an image, and it's consider inside the same row. 
=> feat(radio-button): add an optional wrapper for radio buttons

packages/react-vapor/src/components/tab/TabSelectors.ts, packages/react-vapor/src/components/tab/tests/TabSelectors.spec.tsx
the selector now returns the selected tab (or false) instead of a boolea isSelected
=> test(tabselectors.spec.tsx): change getTabSelected

packages/react-vapor/src/components/tab/TabSelectors.ts
added the safe operator, that way, it doesn't throw when unmounting
=> fix(tabselectors.ts): added the safe operator

packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/JSONEditor.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx, packages/react-vapor/src/components/editor/tests/JSONEditor.spec.tsx
Exposed line wrapping options for code editor and json editor.
Should not break anything since its a not required exposed prop.
-   The proposed changes are covered by unit tests
-   No breaking changes
=> fix: linewrapping for react-vapor code editor

packages/demo/package.json, packages/react-vapor/package.json, packages/react-vapor/src/components/table-hoc/tests/TableWithUrlState.spec.tsx
Bump Typescript to _latest version_ (To Discuss)
After investigating all the errors, I'm not sure if it's a good idea to bump the latest version/3.9.6. The principal reason is that we cannot use jasmine `spyOn` anymore. For more details https://github.com/jasmine/jasmine/issues/1817
Here are 2 solutions that I see at this moment:
- Use the version `3.8.3` until replacing jasmine with Jest
- There is a workaround https://github.com/jasmine/jasmine/issues/1817#issuecomment-630110087 but personally I think it's a little bit hacky.
See above
=> feat(package): bump typescript version

packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/JSONEditor.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx, packages/react-vapor/src/components/editor/tests/JSONEditor.spec.tsx
Initially the changes for the JSONEditor only exposed linewrapping but after another feature request for place holders for a V2 feature I decided to expose the options param instead of also just exposing the placeholder param. (@gdostie this was a discussion in the other PR: https://github.com/coveo/react-vapor/pull/1632#discussion_r456636800)
There are no potential breaking changes.
=> fix: exposed the options parameter

packages/demo/src/demo-building-blocs/Code.tsx, packages/react-vapor/src/components/radio/Radio.tsx
**Whats Going on**
- Some new props added to manage the Radio container were passed to the HTML element.
- Same think was happening in the `Code.tsx` file.
:man_shrugging:  I dont know what the `lineNumberContainerStyle` Was doing in the `Code.tsx` but removing it doesn't seem to change anything.
=> fix(radioselectconnected): invalid HTML props

packages/react-vapor/src/components/input/LabeledInput.tsx
The tooltip placement was set to `top`, if we want to display information/helper in the label title. Since we use this component mostly in forms, it could be changed to `right` according to current design.
None
=> feat(labeledinput): change default tooltip placement

packages/demo/src/components/examples/SectionExamples.tsx, packages/react-vapor/src/components/input/LabeledInput.tsx, packages/react-vapor/src/components/labeledValue/LabeledValue.tsx, packages/vapor/scss/components/labeled-value.scss, packages/vapor/scss/forms/block-form.scss
Made a bigger tooltip sontainer so icon container and tooltip don't overlap when hovering the svg
info. Still not very experimented with all the class we already have. Fixed it with my knowledge.. I'm opened to alternatives if this doesn't respect react-vapor's rules
Note: Same buggy behavior was found in LabeledValue.tsx
=> fix(labeledvalue-labeledinput): changed the css of the tooltip container

packages/demo/src/components/examples/CollapsibleExamples.tsx, packages/react-vapor/src/components/collapsible/CollapsibleConnected.tsx, packages/react-vapor/src/components/collapsible/CollapsibleContainerConnected.tsx, packages/react-vapor/src/components/collapsible/CollapsibleHeaderIcon.tsx, packages/react-vapor/src/components/collapsible/tests/CollapsibleConnected.spec.tsx, packages/vapor/scss/icons/icons.scss
add disabled state
add new props to set a custom icon
Collapsible
- add disabled state
- add props to override the default collapsible button
none
=> feat(collapsible): disabled

packages/react-vapor/src/components/numericInput/NumericInputSelectors.ts
Add optional chaining to fix type error when using `NumericInputSelectors`.
None
=> fix(numericinput): type error in selectors

packages/demo/src/components/examples/SingleSelectExamples.tsx, packages/react-vapor/src/components/collapsible/CollapsibleConnected.tsx, packages/react-vapor/src/components/editor/JSONEditor.tsx, packages/react-vapor/src/components/flatSelect/FlatSelect.tsx, packages/react-vapor/src/components/select/hoc/SelectWithPredicate.tsx, packages/react-vapor/src/components/slider/Slider.tsx, packages/react-vapor/src/components/textarea/TextArea.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtyInputHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtyMultiSelectHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithInitialValuesMultiSelectHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueInputValidationHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueMultiSelectValidationHOC.tsx
Update every variable to watch on useEffect. we cant watch on a function from mapDispatchToProps redefine every time.
=> fix(infinite-loop): use effect bad watch

packages/demo/src/components/examples/InputExamples.tsx, packages/react-vapor/src/components/input/InputLabelWithTooltip.tsx, packages/react-vapor/src/components/input/index.ts, packages/react-vapor/src/components/input/tests/InputLabelWithTooltip.spec.tsx
This component can be used a lot in forms, especially inside of an input, which needs a tooltip for its label.
https://bitbucket.org/coveord/admin-ui/pull-requests/830/feature-adui-5766-web-source-in-react-part#comment-169911868
Demo -> TextInput -> the second one
None
=> feat(input): add input label with tooltip

packages/demo/src/components/examples/MultiSelectExamples.tsx, packages/react-vapor/src/components/select/MultiSelectConnected.tsx
Adding the support for the selectDisplayValue prop for the multi-select component, similar to the
SingleSelect component
Test for this feature seems to be completed in `MultiSelectConnected.spec.tsx` lines 87-92 with `selectedDisplayValue`
The value to show `selectedDisplayValue` if it is passed in as a prop. This will allow flexibility for users who want to display a different value when an item is selected versus when the item is shown on the dropdown
=> feat(multi-select): supporting the selectDisplayValue prop

packages/demo/src/components/examples/CodeEditorExamples.tsx, packages/demo/src/components/examples/JSONEditorExamples.tsx, packages/react-vapor/src/components/editor/CodeEditor.tsx
To resolve[ ADUI-5838](https://coveord.atlassian.net/browse/ADUI-5838)
It seems that the icon that briefly appears in all instances of the implemented JSONEditorConnected component in the Admin-UI is due to a slight delay between the render of the JSONEditor container and the JSON text. After a troubleshooting with PO, it might be caused by the codemirror's lint addon (same error icon is displayed in this [demo](https://codemirror.net/demo/lint.html) ).
We thought of two possible solutions for this bug: 
1) If we set a default value for the CodeEditor component _value_ prop, we might avoid this kind of issue. 
2) We could set the lint addon option to `false`. For example, I set this option to false in the AssociationJSONEditor component in the Admin-UI repo, in which the appearance of the …
=> Fix adui 5838 code editor with validation quickly shows the invalid icon upon mounting

packages/demo/src/components/examples/ButtonExamples.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtySaveButtonHOC.tsx
[COM-170]
The warning tooltip did not match the behavior of the error tooltip, so here it is!
I have also added two other checkboxes in the examples so that you can test out what happens when multiple components are outputting warnings and errors
No
[COM-170]: https://coveord.atlassian.net/browse/COM-170
=> feat(validation): shorter save button tooltip with mutliple warnings

packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueInputValidationHOC.tsx
`withNonEmptyValueInputValidationHOC` was not showing errors for required fields in their initial state.
Turns out that the validation was occurring onMount, however the useEffect hook runs after that, so it was clearing the error set during validation.
The initial clear is not required, and should only be called on cleanup (unmount)
=> fix(non-empty validation): Do not clear error immediately

packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx, packages/vapor/scss/components/code-editor.scss, packages/vapor/scss/guide.scss
The no cursor option that was implemented a year ago by a wonderfull but newbie developper is preventing the selection of text.
So no ctrl+a, ctrl+c ctrl+v
I changed the implementation to css-ly hide the cursor instead.
none
=> fix(code editor): no cursor option replaced by css

packages/demo/src/components/examples/InputExamples.tsx, packages/react-vapor/src/components/multiValueInputs/MultiValuesInput.tsx, packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx
Subtask of [ADUI-5768](https://coveord.atlassian.net/browse/ADUI-5768)
Add the possibility to add classes specifically for the disabled input in the MultiValuesInput component, which allows a more flexible way to ajust the appearance of this feature.
=> feat(multi-values-input): add disabled input classes props

packages/demo/src/components/examples/JSONEditorExamples.tsx, packages/react-vapor/src/components/editor/JSONEditor.tsx, packages/react-vapor/src/components/editor/tests/JSONEditor.spec.tsx
Second attempt to resolve [ADUI-5838](https://coveord.atlassian.net/browse/ADUI-5838)
It seems that the icon that briefly appears in all instances of the implemented JSONEditorConnected component in the Admin-UI is due to a slight delay between the render of the JSONEditor container and the JSON text. After a troubleshooting with PO, it might be caused by the codemirror's lint addon (same error icon is displayed in this demo ).
This time, I suggest to add a default prop to set the lint addon to false to resolve this issue.
=> fix(json-editor): set the default prop options lint=false

packages/demo/package.json
Exploitable in the Demo from Safari or IE browsers.
Bumbed the `react-syntax-highlighter` package in the `package.json` of the react-vapor package.
Used `npm install react-syntax-highlighter@latest` to make sure the `package-lock` got updated accordingly
~is there any ? gotta look at the code editor demo to make sure.~ 
Did not spot any 
=> fix(demo): vul in the react-syntax-highlighter given by prism-js

Jenkinsfile.groovy
params.SKIP_PUBLISH does not exists, so the step was ignored
=> build: remove validation of unexisting param

packages/react-vapor/src/components/multiValueInputs/MultiValuesInput.tsx, packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx
The placeholder if a limit is reached should be undefined. Otherwise, if a validation is set, it could display two warning messages, and show contradictory instructions for the user. More information on this [ticket](https://coveord.atlassian.net/browse/ADUI-5916).
For instance, this situation shouldn't happened:
=> Fix adui 5768 change the condition to display the reachedlimitplaceholder

packages/react-vapor/src/components/multiValueInputs/MultiValuesInput.tsx, packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx, packages/vapor/scss/controls/input-field.scss
Before a tooltip was shown if the cursor hovered the placeholder (if the number of input is above the limit), like this: 
Now, the tooltip will only be shown if the input has a default-value and if the index of the input is above the limit.
=> fix(multi-values-input): remove tooltip if the placeholder is displayed

packages/react-vapor/src/ReactVapor.ts, packages/react-vapor/src/ReactVaporReducers.ts, packages/react-vapor/src/components/filepicker/Filepicker.tsx, packages/react-vapor/src/components/filepicker/FilepickerActions.ts, packages/react-vapor/src/components/filepicker/FilepickerReducers.ts, packages/react-vapor/src/components/filepicker/FilepickerSelectors.ts, packages/react-vapor/src/components/filepicker/FilepikcerSelectors.ts, packages/react-vapor/src/components/filepicker/index.ts, packages/react-vapor/src/components/filepicker/tests/Filepicker.spec.tsx, packages/react-vapor/src/components/filepicker/tests/FilepickerReducers.spec.ts, packages/react-vapor/src/components/filepicker/tests/FilepickerSelectors.spec.ts, packages/react-vapor/src/components/filepicker/tests/Filepickerelectors.spec.ts, packages/react-vapor/src/utils/FileUtils.spec.ts, packages/react-vapor/src/utils/FileUtils.ts
The filepicker was previously unconnected, meaning there were no information about it in the redux
state. Now it will have information about whether there is a file currently selected or not.
Structure of its state:
```js
{
... // react-vapor state
filepickers: {
'my-file-picker-id': {. // has a file selected
id: 'my-file-picker-id',
isEmpty: false,
selectedFile: {
name: 'whatever.txt',
size: 12,
type: 'text/plain',
lastModified: 1600184137067,
},
},
'my-other-file-picker-id': { // has no file selected
id: 'my-other-file-picker-id',
isEmpty: true,
selectedFile: null,
}
},
}
```
New selectors:
- `FilepickerSelectors.isEmpty()`
- `FilepickerSelectors.getFileMetadata()`
Filepicker is now a connected component so it must be wrapped inside a store
provider
-   [ ] The proposed changes are …
=> improvement(filepicker): add redux state for the filepicker

Jenkinsfile.groovy, lerna.json
Prevent Jenkins from triggering builds when the last commit was a version bump.
None
=> ci(jenkins): prevent builds on version bump

packages/demo/src/components/examples/MultiSelectExamples.tsx, packages/react-vapor/src/components/dropdownSearch/DropdownSearch.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/DraggableSelectedOption.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/MultiSelectInput.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/SelectedOption.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/tests/DraggableSelectedOption.spec.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/tests/SelectedOption.spec.tsx, packages/react-vapor/src/components/select/MultiSelectConnected.tsx, packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx
Modified SelectedOption component by adding selectedTooltips props to accept data type of ITooltipProps and preserve functionality of the ITooltipProps for selected options.
=> improvement(selectedoption): modifying SelectedOption component

packages/demo/src/components/examples/TableHOCExamples.tsx, packages/react-vapor/src/components/table-hoc/TableHOC.tsx, packages/react-vapor/src/components/table-hoc/tests/TableHOC.spec.tsx
The tablehoc component only had showBorderTop but no option for showBorderBottom so I added that
The tablehoc component uses the actionbar component. It never passed mod-border-bottom to it in the first place. I copied the functionality of the top border by adding a showBorderBottom prop that would pass the mod-border-bottom class to ActionBar.
=> improvement(tablehoc): add showBorderBottom prop

packages/vapor/scss/variables.scss
Set default padding of BannerContainer to `40px`.
None
=> fix(banner): set default padding to 40px

packages/react-vapor/src/components/validation/hoc/WithDirtySaveButtonHOC.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithDirtySaveButtonHOC.spec.tsx
[COM-575]
The `skipDirty` prop allows bypassing the dirty check for Save Buttons. 
This is useful if you know the initial values can be valid and thus saveable without requiring the user to change any value.
However, the dirty tooltip was still displayed!
This removes the tooltip if `skipDirty` is set to true
None
[COM-575]: https://coveord.atlassian.net/browse/COM-575
=> fix(validation): should not display tooltip with skipDirty

packages/react-vapor/src/components/sideNavigation/SideNavigationMenuSection.tsx, packages/vapor/scss/components/navigation.scss
`.navigation-menu-section-items` has a margin bottom, however, we don't always need this.
None
=> fix(navigationitems): make margin bottom optional

packages/vapor/gulpfile.js
Added configuration as [listed here](https://www.npmjs.com/package/gulp-svgmin#per-file-options) to make sure all the ids of the definitions are unique
You'll be able to see the effect on the flag icons of the [demo](https://vaporqa.cloud.coveo.com/feature/fix-ADUI-6034-svg-id-collision/index.html#/styles/icons/list) vs [current](https://vapor.cloud.coveo.com/#/styles/icons/list)
=> fix(svg): update svgmin config to avoid collision in svg ids

packages/demo/src/components/examples/FooterExample.tsx, packages/react-vapor/src/hoc/withDirty/withDirty.tsx
update interface
add example
Get props for isDirty HOC with the component instead of the config sent as parameter
=> feat(footer): withDirty

packages/demo/src/components/examples/ButtonExamples.tsx, packages/react-vapor/src/components/listBox/ListBox.tsx, packages/react-vapor/src/components/listBox/tests/ListBox.spec.tsx
Add a prop to remove the state active for the list rendered by the ListBox component
For the MenuConnected, we use the ListBox to show the list of item when the menu open.
Before, we had the first item active but the active state make no sens for a menu because we dont have a item selected like the dropdown.
before:
after: 
On hover, we continue to see the grey background.
=> feat(listbox): remove active

packages/demo/src/components/examples/SingleSelectExamples.tsx, packages/react-vapor/src/components/validation/ValidationActions.ts, packages/react-vapor/src/components/validation/ValidationReducer.ts, packages/react-vapor/src/components/validation/components/ValidationMessage.tsx, packages/react-vapor/src/components/validation/components/tests/ValidationMessage.spec.tsx, packages/react-vapor/src/components/validation/tests/ValidationReducer.spec.ts
add an action to clean all the state for a specific validationMessage
Add example to see when we remove the message from the state
Add uts
Clean ValidationMessage from the state when we unmount the component
How to test: 
1. Open SingleSelect section
2. click on the button to show the error message
3. use the side navigation to change for an other example
4. comeback in SingleSelect and you shouldn't see the message.
=> feat(validation-message): clean state on unmout

packages/demo/src/components/examples/InputExamples.tsx, packages/react-vapor/src/components/input/Input.tsx, packages/react-vapor/src/components/multiValueInputs/MultiValuesInput.tsx, packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx, packages/react-vapor/src/components/multilineBox/MultilineBox.tsx, packages/react-vapor/src/components/multilineBox/hoc/MultilineBoxWithRemoveButton.tsx
update input to handle readOnly to avoid confusion with the disabled from the state
Update multiValueInputs to use disabled as a props
Update MultilineBoxWithRemoveButton to use the disabled as a props
add input and multiValue examples
** Uts next PR
Add "disabled" as a props for the MultiValuesInput.
The first problem was with the Input. we dont have any way to use the ownProps to set the component in disabled. We use the state to do that. I added a new props readOnly to avoid problem with the disabled from the state. I tried to use disabled in both case but it's to dangerous to get weird behaviour in the futur so I created the readOnly to set the component on render ou later in disabled state with his own props.
No breaking changes. The new props are optional and can modify the …
=> feat(multivalue): can disabled

packages/react-vapor/src/components/table-hoc/TableWithPrepend.tsx, packages/react-vapor/src/components/table-hoc/index.ts, packages/react-vapor/src/components/table-hoc/tests/TableWithPrepend.spec.tsx
Sometimes we need something to be displayed above the table only if there is data in the table. For example, if we want to display an info box that gives explanation about the columns. This is what the new `tableWithPrepend` HOC is for.
```tsx
const TableWithPrepend = tableWithPrepend(TableHOC);
const SomePanel = () => (
<TableWithPrepend
// standard table props here (id, data, renderBody, etc.)
prepend={
// Will only be rendered if there is data
<InfoBox>Some information about the current component.</InfoBox>
}
/>
);
```
None
=> tableWithPrepend HOC

packages/react-vapor/src/components/select/SelectSelector.ts, packages/react-vapor/src/components/select/tests/SelectSelector.spec.ts
add a selector to return the first value of a select
=> feat(selector): select

packages/react-vapor/src/components/table-hoc/TableHOC.tsx, packages/react-vapor/src/components/table-hoc/tests/TableHOC.spec.tsx
By doing this, the missing border bottom of the table-actions-container will be fixed
-   [x ] The proposed changes are covered by unit tests
=> fix(tablehoc): set the showBorderBottom to true by default

packages/demo/src/components/examples/MultiSelectExamples.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/DraggableSelectedOption.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/SelectedOption.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/tests/DraggableSelectedOption.spec.tsx, packages/react-vapor/src/components/select/MultiSelectConnected.tsx, packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx, packages/vapor/scss/components/multiselect-input.scss, packages/vapor/scss/components/selected-option.scss
We will let the disabled component as it is, but we made some upgrade on it. We now make a distinction between a multiselect disabled and in readonly. I've added an example to the multiselectexamples file and added UTs for draggable component and selectedoption component
=> Adui 6097 multifacet is so pale that it s looking disabled

packages/react-vapor/src/components/table-hoc/TableWithBlankSlate.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithBlankslate.spec.tsx
The tableWithBlankSlate shouldn't render its blankslate if the table is loading.
Before
https://screencast-o-matic.com/watch/cYXeDvs9B7
After
None
=> fix(table-with-blankslate): check for table is loading

packages/react-vapor/src/components/table-hoc/TableWithDatePicker.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithDatePicker.spec.tsx
The TableWithDatePicker HOC would throw on update when no `initialDateRange` is provided. Since this option is optional in the HOC config it shouldn't.
None
=> fix(tablewithdatepicker): prevent from throwing errors with null dates

packages/demo/src/components/examples/CheckboxExamples.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtyCheckboxHOC.tsx, packages/react-vapor/src/components/validation/hoc/index.ts, packages/react-vapor/src/components/validation/hoc/tests/WithDirtyCheckboxHOC.spec.tsx
[COM-700]
We already have a couple of `withDirty` implementation, but now we needed it for the Checkbox.
Here it is!
None
[COM-700]: https://coveord.atlassian.net/browse/COM-700
=> feat(validation): allow checkbox dirty tracking

packages/vapor/scss/elements/btn.scss
[COM-700]
I put two buttons side-by-side, one with a tooltip, the other without, and there was a difference in margin!
I found out that the `vertical-align: middle` that is *only* on the `btn` class and not on `btn-container`  was responsible for that! See here:
The issue only occurs when the button is included **inline** and another component is in the same block.
It should not cause any issue, if anything, it will repair margins in some places
[COM-700]: https://coveord.atlassian.net/browse/COM-700
=> fix(btn): fix extra margin when using tooltip

packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx, packages/react-vapor/src/components/table-hoc/tests/TableRowConnected.spec.tsx, packages/react-vapor/src/utils/UrlUtils.ts
The row call on double click should not be triggered if the row is disabled.
The American gouvernement administration change. Although probably not.
=> fix(action row): if disabled no double click

packages/react-vapor/src/utils/ReduxUtils.ts
Added a new type in the reduxUtils
This new type can handle de connected component type in a clean way
ex: 
```
enhance = connect(mapStateToProps, mapDispatchToProps)
const MyComponentBase: React.FC<ConnectedProps<typeof enhance>> = (props) => {}
export const MyComponent = enhance(MyComponentBase)
```
none
=> feat(redux utils): added a connected component props type

packages/demo/src/components/examples/InputExamples.tsx, packages/react-vapor/src/components/childForm/ChildForm.tsx, packages/react-vapor/src/components/childForm/ToggleForm.tsx, packages/react-vapor/src/components/childForm/tests/ChildForm.spec.tsx, packages/react-vapor/src/components/childForm/tests/ToggleForm.spec.tsx
Fix ChildForm
1. do not override the disabled prop on each child on mount
2. only set the coveo-child class 
ToggleForm deprecated
Remove Disabled prop set on ChildForm
=> Fix childform disabled issues

packages/demo/src/components/examples/SingleSelectExamples.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtySingleSelectHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithNonEmptySingleSelectHOC.tsx, packages/react-vapor/src/components/validation/hoc/index.ts, packages/react-vapor/src/components/validation/hoc/tests/WithDirtySingleSelectHOC.spec.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithNonEmptySingleSelectHOC.spec.tsx
Add dirty and non empty validation for single select
=> feat(validation): dirty + non empty single select

packages/react-vapor/src/components/calendar/Calendar.tsx
Added a class selector for the FTs. The month arrows in DatePicker have a class named `.mod-month`, now we want the class `.mod-year` for year arrows.
None
=> feat(datepicker): add class for next and previous year

packages/react-vapor/src/components/modal/ModalReducers.ts, packages/react-vapor/src/components/modal/tests/ModalCompositeConnected.spec.tsx, packages/react-vapor/src/components/modal/tests/ModalReducers.spec.ts
The openModals array in the store was emptying only if the modal was explicitaly closed. The modal Id will now be removed from the openModals array if the modal is symply removed.
Also, a condition in the reducer will prevent the same modal from being added in the openModals array many times
none
=> fix(modal composite): openmodals array no duplication and clear

packages/demo/src/components/examples/SingleSelectExamples.tsx, packages/react-vapor/src/components/validation/hoc/WithDirtySingleSelectHOC.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithDirtySingleSelectHOC.spec.tsx
[COM-702]
Small improvement to the `withDirtySingleSelectHOC`, it will automatically select the `initialValue`.
This is mostly for convenience, I think it makes sense to expose an `initialValue` prop and use it that way, even though it is not strictly a "dirty" feature.
No
[COM-702]: https://coveord.atlassian.net/browse/COM-702
=> fix(validation): automatically select initial value in single select

Jenkinsfile.groovy, packages/react-vapor/rollup.config.js, packages/react-vapor/webpack.config.js
I'm trying to assign the bumped react-vapor version on the REACT_VAPOR_VERSION variable.
~~I still have to confirm if the NEW_VERSION variable contains the expected value, and to do so, I have to run to the jenkinfile, which explains why I open this PR to test it out.~~ Like Germain mentioned in his comment, because this command will only be run in master (or a branch named release-.*), I will be able to confirm if it worked or not only after this branch is merged in master.   
=> fix(jenkinsfile.groovy): set the NEW VERSION var after version is bumped

packages/vapor/scss/tables/table.scss
The collapsible row leaves a trail of bottom border as it expands and collapses. This fix will force
the hardware acceleration. Problem only isolated to Windows machines with Chrome and Edge
=> fix(table.scss): ADUI-6283 collapsible row animation fix

packages/vapor/scss/tables/table.scss
This reverts commit 9c81b4c94d679250d351bf8f54bafde156ce57d6.
This fix, efficent for the case of the trailing lines. breaks the z-index of the rows.
revert back to normal behavior so in very specific cases you will see trailling lines from the border of a collablible row.
=> Revert "fix(table.scss): aDUI-6283 collapsible row animation fix"

packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueInputValidationHOC.tsx, packages/react-vapor/src/components/validation/hoc/tests/WithNonEmptyValueInputValidationHOC.spec.tsx
When validating an input field containing only whitespaces, the value should be considered as empty.
One could be impacted if a field is wrapped with `withNonEmptyValueInputValidationHOC` and considers a string composed of whitespaces as valid. I can't think of a real-life scenario where it would be an issue.
=> fix(sfint-3610): consider whitespace string as empty

packages/react-vapor/rollup.config.js, packages/react-vapor/webpack.config.js
**Second attempt to solve this issue:**
Set the react vapor version variable to the current version from the package.json if the NEW_VERSION is empty. 
The reasoning for this change is as follow:
- it would seems that the version contained in the package.json is currently up to date with the release version. So I wonder if the package.json version is actually bumped after a new version is set.
- Because the current result when running the `CoveoJsAdmin.versions` is '0.0.0'. I want to observe what would be the result if we set the to the current version contained in the package.json (which will either confirm my theory explained in the previous statement, or it will display the prior version, just like before).
-   [ ] The potential …
=> fix(react-vapor.version): set react vapor version even if not new

.deployment.config.json
Also change the deployment folder to add a v. E.g., `v9.6.4` instead of `9.6.4`
=> build: add missing acl to make file public

packages/demo/src/components/examples/TabConnectedExample.tsx, packages/react-vapor/src/components/tab/Tab.tsx, packages/react-vapor/src/components/tab/tests/Tab.spec.tsx
I added the possibility to include a Svg icon to an Tab component. You could see an example in the Tab section.
-   [X ] The proposed changes are covered by unit tests
=> feat(tab): add the possibility to include a svg to a tab

packages/vapor/scss/components/application-container.scss
=> fix: remove useless border radius on application-container

package-lock.json, packages/demo/package.json, packages/demo/src/components/examples/DatePickerExamples.tsx, packages/demo/tsconfig.json, packages/demo/webpack.config.js, packages/react-vapor/rollup.config.js
The sourcemaps for the esm build were not produced, making it very hard to debug react-vapor
components from the demo.
None
=> feat(demo): enable esm react-vapor sourcemaps

packages/demo/src/components/examples/TabConnectedExample.tsx, packages/react-vapor/src/components/tab/Tab.tsx, packages/react-vapor/src/components/tab/tests/Tab.spec.tsx
Take 2: this time I also included the children prop: in some instances, I need the children prop to be available, so I could set an icon. For example, if I assign an `ITabProps` array to the tab props of a `BreadcrumbHeader` component, I have to have this prop available. However, even if I included this prop, I also wanted to demonstrate that both ways are valid 
-   [X ] The proposed changes are covered by unit tests
=> feat(tab): include a children prop

packages/demo/src/components/examples/SingleSelectExamples.tsx
When the demo will be up, you will see the new example if you navigate to the SingleSelect section, and check the third example. It should look like this screenshot when you access/refresh the page:
=> feat(single-select-example): add an example with a default selected item

packages/react-vapor/src/components/validation/hoc/WithDirtyInputHOC.tsx, packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueInputValidationHOC.tsx
[COM-703]
While profiling, I noticed that an input that validates both "non-empty" and `dirty" would dispatch 3 actions per keystroke.
Here is a quick and easy optimization that will only dispatch the action when the value actually changes.
You can validate the change in the demo, in the "Input with dirty management" example.
None
[COM-703]: https://coveord.atlassian.net/browse/COM-703
=> fix(validations): only dispatch dirty and error when input changes

packages/demo/src/components/examples/TableHOCExampleUtils.tsx, packages/demo/src/components/examples/TableHOCServerExamples.tsx, packages/react-vapor/src/components/table-hoc/TableSelectors.ts, packages/react-vapor/src/components/table-hoc/TableWithBlankSlate.tsx, packages/react-vapor/src/components/table-hoc/TableWithEmptyState.tsx, packages/react-vapor/src/components/table-hoc/TableWithPrepend.tsx, packages/react-vapor/src/components/table-hoc/index.ts, packages/react-vapor/src/components/table-hoc/tests/TableSelectors.spec.ts, packages/react-vapor/src/components/table-hoc/tests/TableWithBlankslate.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithEmptyState.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPrepend.spec.tsx
Empty state: displayed when no data exist for the resource bound to the table. 
Blankslate: displayed when no data match the current configuration of the table (filter, predicates, date picker, etc)
None
=> feat(table): implement tableWithEmptyState HOC

packages/vapor/scss/redesign/variables.scss
The default text color of buttons should be pure-white.
None
=> fix(button): reset default text color to pure-white

packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx, packages/react-vapor/src/components/table-hoc/tests/TableRowConnected.spec.tsx
when we toggle the collapsible, now we can display or not the borderbottom of the row, which would
give a better feeling of expanding content
-   [ x] The proposed changes are covered by unit tests
=> feat(tablerowconnected): +noBorderBottom props

packages/demo/src/components/examples/LogoCardExamples.tsx, packages/react-vapor/src/components/logoCard/LogoCard.tsx, packages/react-vapor/src/components/logoCard/tests/LogoCard.spec.tsx, packages/vapor/scss/components/logo-card.scss
[For trials improvement ](https://coveord.atlassian.net/browse/ADUI-6382)
When a LogoCard component doesn't have a description or badges, its title is aligned to the top.
When a user does not pass a badge or a description to the Logo Card, align the title to the center vertically to match UI mock-up.
- Conditionally render a class called `logo-card-content-center` with `justify-content: center` to align the text in the `logo-card-content` div element.
- Renamed `DefaultLogo card` to `LogoCard with description` for consistency with other examples. 
- Added a new example to show title only. 
- Title only example will be shown as the first example since it is the most basic Logo Card.
-   [ ] The potential breaking changes are clearly …
=> improvement(logo-card): logo card title will align vertically

packages/react-vapor/src/components/datePicker/DatePickerBox.tsx
[ADUI-6397](https://coveord.atlassian.net/browse/ADUI-6397)
Formatting `calendarId` inside of `componentDidMount` can cause a small delay, it will be `undefined` when `DatesSelection` is rendered.
None
=> fix(datepicker): move calendarId out of lifecycle method

packages/react-vapor/src/components/select/SingleSelectConnected.tsx
stopPropagation was added to the handleDeselect, so the dropdown doesn't open when the selected
option is cleared
=> fix(singleselectconnected): stopPropagation on cler button

packages/demo/src/components/examples/ExamplesUtils.ts, packages/react-vapor/src/components/tab/Tab.tsx, packages/react-vapor/src/components/tab/tests/Tab.spec.tsx
If the url props is set on a tab, It will then redirect upon click.
None
=> feat(tab): redirect to url prop

packages/react-vapor/src/components/drop/DropPod.tsx, packages/react-vapor/src/components/drop/tests/DropPod.spec.tsx
I think there's a way we can remove the created portal after we unmount the `Drop` component (thanks Germain for your support on that one). Here's a screenshot that demonstrate that the element I appended (that includes the created portal) is removed after a component is unmount:
However, if you want to test it out yourself,  the `ActionableItem` component actually includes a ` Drop` component in it. So, before you navigate to another page, you can select with a breakpoint in the devtool the `componentWillUnmount` event in the `DropPod` component, and see that the .removeChild(this.dropElement) function will remove the expected div element. 
-   [ ] …
=> feat(drop-pod): remove the created portal when component is unmount

packages/demo/src/components/examples/BadgeExamples.tsx, packages/react-vapor/src/components/badge/Badge.tsx, packages/react-vapor/src/components/badge/tests/Badge.spec.tsx
adding badge to allow svg icons for trial experience
Prop added to badge component to allow SVG icon
- Add a new lock SVG provided by UI
- Added an optional prop for badges to add SVG icon
=> feat(badge): TRI-26 adding prop to allow svg icons 

packages/vapor/scss/controls/multiline-field.scss
New color for the add-action icon!
None
=> fix: new blue for add-action icon

Jenkinsfile.groovy
This reverts commit 8846283237798aa745471336348c339c4fef8ba0.
The url param passed to the jenkings webhook that is supposed to exclude jenkins commits to rebuild is not working as expected, resulting in jenkins commiting and re-triggering a build over and over again. So I am reverting the removal of the skip stage.
none
=> Revert "feat(jenkins pipeline): remove skip stage"

packages/vapor/scss/variables.scss
changed icon size in admin navigation from 20px to 16px
=> style(variable.scss): reduce navigation icon size 20 -> 16px

packages/demo/src/components/examples/FlatSelectExamples.tsx, packages/react-vapor/src/components/flatSelect/FlatSelect.tsx, packages/react-vapor/src/components/flatSelect/FlatSelectOption.tsx, packages/react-vapor/src/components/flatSelect/tests/FlatSelect.spec.tsx, packages/react-vapor/src/components/flatSelect/tests/FlatSelectOption.spec.tsx, packages/react-vapor/src/components/select/hoc/SelectWithPredicate.tsx
If a option is disabled in an array of `FlatSelectOptions`, it should be disabled. Also, a few unit tests was added to prove when a single option is disabled or all the options are. You can see two examples in the `FlatSelect` section.
Finally, I included an option two disabled all the options in a `SingleSelectWithPredicate` or `MultiSelectWithPredicate` component.
=> fix(flat-select): disabled the flatSelectOption when disabled is true

packages/react-vapor/src/components/modal/ConfirmationModalProvider.tsx, packages/react-vapor/src/components/modal/UnsavedChangesModalProvider.tsx, packages/react-vapor/src/components/modal/index.ts, packages/react-vapor/src/components/modal/tests/ConfirmationModalProvider.spec.tsx
[COM-789]
We will be needing a more generic "Confirmation" provider that exposes the changes that were done, so I was thinking of re-using the `UnsavedChangesProvider` and adapting it to allow a `ReactNode` for its body. It would make it very generic and reusable for many things.
So `UnsavedChangesProvider` now uses the Confirmation provider under the hood!
None
[COM-789]: https://coveord.atlassian.net/browse/COM-789
=> feat(modal): generalize the confirmation modal

packages/react-vapor/src/components/multilineBox/hoc/MultilineBoxWithRemoveButton.tsx, packages/vapor/scss/controls/multiline-field.scss
It was using the --orange variable, so it didn't follow the proper overrides.
=> fix(multiline-field): fix multiline field add action color

packages/react-vapor/src/components/actionable-item/styles/ActionableItem.scss, packages/react-vapor/src/components/button/Button.tsx, packages/vapor/scss/elements/btn.scss, packages/vapor/scss/redesign/variables.scss
update padding for 9px instead of 6 when we use an other tag than button
update padding for actionable item and actionable icon
=> fix(button): text

packages/react-vapor/src/components/optionsCycle/OptionsCycle.tsx
add class to center align text in a tag using class btn without button tag
=> fix(options-cycle): text alignment

Jenkinsfile.groovy
in the `lerna version` command the default id is `alpha`. I switched it to `next` to be coherent with the publish
=> Fix ADUI-6501 next tag

packages/demo/src/components/examples/LogoCardExamples.tsx, packages/demo/src/components/examples/LogoCardExamplesCommon.ts, packages/react-vapor/src/components/logoCard/LogoCard.tsx, packages/react-vapor/src/components/logoCard/tests/LogoCard.spec.tsx, packages/vapor/scss/components/badge.scss, packages/vapor/scss/components/logo-card.scss, packages/vapor/scss/redesign/variables.scss, packages/vapor/scss/variables.scss
Improvements to LogoCard design for trial ux experience and mockup as per design
- Moving the badges to the right side of LogoCard
- Deprecating ribbon from LogoCard
- Stylize Badge and LogoCard component
=> (style): TRI-26 LogoCard and Badge style changes

Jenkinsfile.groovy, lerna.json, packages/demo/package.json, packages/react-vapor/package.json, packages/vapor/package.json
The premajor was "bumping" a major on every merge, which is not what we want. I saw that we can use `--conventional-prerelease` instead and do a breaking change in one of the commits to bump the major (only need to do it once).
I also reverted to version 10.0.0-next.0
=> build(next): avoid bumping a premajor on every commit

packages/vapor/scss/components/tooltip.scss
removed the unused mod-bg-color class
=> Ad UI 6477  utility remove mod bg color for tooltips

packages/demo/src/components/examples/CornerRibbonExamples.tsx, packages/react-vapor/src/components/borderedLine/BorderedLine.tsx, packages/react-vapor/src/components/borderedLine/styles/BorderedLine.scss, packages/vapor/scss/components/corner-ribbon.scss, packages/vapor/scss/utility/colors.scss, packages/vapor/scss/variables.scss
Removed the border color util and fix broken style on borderedLine
PS: --default-border-color is grey-40 and also the same color than the line background so i need to use grey-60 :see_no_evil: 
=> ADUI-6481/remove border color utility

packages/demo/src/components/examples/InputExamples.tsx, packages/vapor/scss/controls/multiline-field.scss
These changes are for an older multiline inputs configuration/classes. However, these changes are based of what seems to be the norm : the 'minus' icon is grey out when the input is disabled, but the 'plus' icon will be hidden instead.
=> fix(multiline-field.scss): when disabled, hide add, change remove icons

packages/vapor/scss/components/calendar.scss
The odd colors noticed in the section mentioned in the Jira's case, is due to color set to the option-picker class (used for the OptionPicker component). The .gif below shows when a cursor hovers an option and when an user select an option. The design when the option is selected is based on my understanding of the coveo library canvas (in Figma). However, I'm not really sure is what is expected (would surely need the approval of UX!).
Edit: the example can be found in the DatePicker section.
=> fix(option-picker): change the hover and active option picked

packages/demo/src/components/examples/ServerSideSelectExampleUtils.tsx, packages/react-vapor/src/components/select/hoc/SelectWithInfiniteScroll.tsx
[ADUI-6482](https://coveord.atlassian.net/browse/ADUI-6482)
By default, the `scrollThreshold` is `1` (100%), so the `next` function (`fetchNextPage`) will be triggered only when scrolling down to the bottom. However, after investigating, the height of the list box item changes randomly when zooming. For instance, the height is 54px when 100%, but 53.631px when 110%, 53.2px when 120%, 53.333px when 150%.
Therefore, this issue was mainly caused by the unfixed height of list box items. So far, I thought about 2 options, give a fixed height, or slightly reduce `scrollThreshold` value to, for example, `10px` to compensate the height lost. Then we will fetch the next page earlier once there is `10px` to the bottom of the scroll bar.
In this PR, I fixed the height for the example, but still, I …
=> fix(single-select): buggy infinite scroll when zoom is 110% in chrome

packages/demo/src/components/examples/CollapsibleExamples.tsx, packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/JSONEditor.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx
This fix add the possibility to refresh the editor when the `isRefreshRequired` prop is true. An example is included in the collapsible section in which the editor is display properly when the collapsible is opened. 
-   [ X] The proposed changes are covered by unit tests
=> fix(code-editor): add the possibility to refresh the editor

packages/vapor/scss/elements/btn.scss, packages/vapor/scss/redesign/variables.scss
I've changed the color of the secondary button on hover to digital-blue-80 + the default color (navy-blue-80, as seen in Figma)
None
=> fix: fix color for icon in button (default + hover)

packages/demo/src/components/examples/BrowserPreviewExamples.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreview.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreviewEmpty.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreviewError.tsx, packages/react-vapor/src/components/browserPreview/index.ts, packages/react-vapor/src/components/browserPreview/tests/BrowserPreview.spec.tsx, packages/react-vapor/src/components/browserPreview/tests/BrowserPreviewEmpty.spec.tsx, packages/react-vapor/src/components/browserPreview/tests/BrowserPreviewError.spec.tsx, packages/react-vapor/src/components/index.ts, packages/vapor/scss/components/browser-preview.scss, packages/vapor/scss/guide.scss
[ADUI-6495](https://coveord.atlassian.net/browse/ADUI-6495)
We need new components of Browser Preview to be added to the SplitLayout. It can be used as a container, or in the empty / error state.
Note: 
- The Gibson is not implemented yet into the master branch of react-vapor, but the font should be good in admin-ui
- UX is working on the new SVG, for now, we put a placeholder of 300 * 300
None
=> feat(browser-preview): add new components

packages/react-vapor/src/components/browserPreview/BrowserPreview.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreviewEmpty.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreviewError.tsx
By following the feedback from @nathanlb, `center-align` should be removed from the container, and be defined in the children if needed. 
None
=> fix(browser-preview): remove center-align from container

packages/react-vapor/src/components/logoCard/LogoCard.tsx
Adding logic to this logo card title to align it perfectly to center without description.
This fix is to capture the same logic as what was shown here:
https://github.com/coveo/react-vapor/pull/1839#issuecomment-768290488
`mb1` will only be applied when there is a description. It currently has a margin bottom with no description which makes it not perfectly centered.
Capturing it in master before the next branch merge so it will appear in admin-ui
=> fix(logo-card title): conditionally render margin bottom with description only

packages/demo/src/components/examples/FlatSelectExamples.tsx, packages/vapor/scss/controls/flat-select.scss, packages/vapor/scss/redesign/variables.scss
removed the UUID generated that cause de store not to catch the changes in selection. Since it's examples, I put hardcoded Ids and I took the time to change the background color with the one recom
mended by Gustavo inside the Figma file
=> Ad UI 6527 flatselect cannot be selected

packages/demo/src/components/examples/BrowserPreviewExamples.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreview.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreviewEmpty.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreviewError.tsx, packages/react-vapor/src/components/browserPreview/tests/BrowserPreviewEmpty.spec.tsx, packages/vapor/resources/icons/svg/arrow-top-slim.svg, packages/vapor/resources/icons/svg/preview-error.svg, packages/vapor/scss/components/browser-preview.scss
- Added official preview error image to browser preview component
- Added prop to be able to insert specific image node for empty state
- Reduced image size
- Added class for preview content and overflow:auto
None
=> feat: update preview images and some styling

packages/react-vapor/rollup.config.js
DiffViewer page throws an error in the demo because of a rollup issue: 
[Error: "[name] is not exported by [module]"](https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module)
For some reason, `commonjs` can't find `diff2html`, but if we replace it with `diff/dist/diff.js`, it looks good.
None
=> fix(rollup): diff2html name export

Jenkinsfile.groovy
Currently the message look like this:  `Build succeeded: https://vaporqa.cloud.coveo.com/feature/PR-1868/index.html` it is hard to know what it is about.
I suggest we change it for  `Build succeeded for PR-1868 (with a link): https://vaporqa.cloud.coveo.com/feature/name-of-the-branch/index.html`
=> build(slack): update slack notification to be more relevant

Jenkinsfile.groovy
The NEW_VERSION variable will be defined as an env variable and accessible in rollup https://github.com/coveo/react-vapor/blob/master/packages/react-vapor/rollup.config.js#L156
This will fix the mismatch between the real package version and the one fronted in the ReactVapor object.
none
=> now open for review.  defining the NEW_VERSION as environment variable to access from the build

packages/react-vapor/src/components/modalWizard/ModalWizard.tsx, packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx
If a ModalWizard component had a FunctionComponent as a child step, it didn't hide this step properly.
None
=> fix(modalwizard): make steps navigation work with function components

packages/vapor/scss/components/badge.scss
Adding a nowrap will prevent the badge to look weird when the surrounding element are squeezing it.
none
=> Fix ad UI 6628 badge text wrap

packages/vapor/scss/components/badge.scss
adding `whitespace: nowrap` will prevent the text to wrap and the badge to look weird if the surrounding elements squeeze the badge.
nope
=> fix(badge): whitespace nowrap

Jenkinsfile.groovy
[ADUI-6576](https://coveord.atlassian.net/browse/ADUI-6576)
In the Jenkinsfile we skip the deploy step if the branch is next, which prevents us from having a demo. It would be nice to update one each time something is merged in the branch 
None
=> build(jenkins): create a permanent demo of the next in vapor

packages/demo/src/styles/utility/Whitespace.tsx
Use single, light background color for the examples in the **Styles > Whitespace** demo, and keep the default text color.
Before:
After:
None
=> fix(next): background color of whitespace examples

packages/demo/src/components/examples/BlankSlateExample.tsx, packages/demo/src/styles/components/Member.tsx, packages/demo/src/styles/filtering/ValuePopup.tsx, packages/demo/src/styles/typography/Utilities.tsx, packages/react-vapor/src/components/breadcrumbs/BreadcrumbLink.tsx, packages/react-vapor/src/components/diffViewer/styles/DiffViewer.scss, packages/vapor/scss/components/header.scss, packages/vapor/scss/components/home-card.scss, packages/vapor/scss/components/limit-box.scss, packages/vapor/scss/components/multi-step-bar.scss, packages/vapor/scss/components/selected-option.scss, packages/vapor/scss/components/sub-navigation.scss, packages/vapor/scss/controls/filtering/filters-values.scss, packages/vapor/scss/redesign/fonts.scss, packages/vapor/scss/redesign/variables.scss, packages/vapor/scss/typography/headings.scss, packages/vapor/scss/typography/utility.scss
This PR includes several fixes for the `next` branch, mostly related to the font. Here is the list of changes:
- Styles > Wizard: header text color 
- Styles > Member: text color
- Components > BlankSlate: update the link of `this website`
- Styles > Cards > Home: color of `Dismiss` link
- Styles > Value Popup: header text color, horizontal space between two checkboxes
- Styles > Typography > Utilities: remove `semibold`, add `bolder`
- Styles > Utility > Text Size: text color of `.h1` - `.h6`, default font-size 14px, small font-size 12px
- Components > DiffViewer: font-weight of the title `Files changed`
- Components > Limit: text color
- Components > MultiSelect: selected label text color
- Components > MultiStepBar: text color
- Components > Header: text color of `not a link`
None
- …
=> fix(next): text colors in demo

packages/demo/src/styles/utility/ColorDot.tsx, packages/vapor/scss/elements/color-dot.scss, packages/vapor/scss/redesign/colors.scss, packages/vapor/scss/redesign/fonts.scss, packages/vapor/scss/redesign/palette-map.scss, packages/vapor/scss/redesign/palette.scss, packages/vapor/scss/redesign/variables.scss, packages/vapor/scss/variables.scss
Before:
After:
`--success-60` has been changed to `#12a344` since UX updated the palette with the new semantic utility colors. More colors will be updated later.
https://www.figma.com/file/JbXRfSOwdEuq3VJGpUyyiJ/Coveo-Library?node-id=0%3A1
=> feat(next): color dots states

packages/vapor/scss/controls/checkboxes.scss
Here's the fixes:
- Not show the checkmark or the horizontal line when the checkbox is disabled.
- Remove the background-color when the checkbox is focused.
- Change the cursor to default when the checkbox is disabled.
Here's a little demo to show case the changes:
If you want to test out yourself: you can go to the "Checkbox" section and enjoy!
=> feat(checkox): fix few styles to improve checkboxes

packages/vapor/scss/controls/filter-box.scss, packages/vapor/scss/elements/btn-append-prepend.scss
Button with append/prepend Svg had a weird contour that I fixed and FilterBox did not have :focus border
before: 
After:
=> Ad UI 6648 fix borders in demo component in vapor

packages/demo/src/components/examples/ToastConnectedExamples.tsx, packages/react-vapor/src/components/toast/Toast.tsx, packages/react-vapor/src/components/toast/tests/Toast.spec.tsx, packages/vapor/scss/components/toast.scss
A new feature in the rebrand will be a "Preparing download" section in the Toast. I went with
modifying the original instead of creating a new one. 
See UI mockup (start by clicking to the left of the red arrow, then *diagnostic log*):
https://9pd08d.axshare.com/#id=2b9uvt&p=activityui_-_option1&g=1
Added a section to the toast that only appears if the download prop is included. User should pass the file that's to be downloaded, ideally through Redux though I'm unsure of the best practice here
None
-   [ x ] The proposed changes are covered by unit tests
=> feat(toast): added a download section to the vapor toast

packages/demo/src/components/examples/modalWindowExamples.tsx, packages/react-vapor/src/components/input/InputLabelWithTooltip.tsx, packages/react-vapor/src/components/svg/LinkSvg.tsx, packages/vapor/scss/components/labeled-value.scss, packages/vapor/scss/components/modal.scss, packages/vapor/scss/controls/input-field.scss, packages/vapor/scss/elements/btn-append-prepend.scss, packages/vapor/scss/forms/block-form.scss, packages/vapor/scss/icons/icons.scss, packages/vapor/scss/redesign/variables.scss
Changed the info/tooltip/link icons that had the wrong color for 
- FilePicker
- LabeledValue (with alignement for the icon itself)
- LinkSvg
- ModalWindow
- TextInput
I've also changed the `X` to close a modal since it was not white anymore. I've tried to create classname that were relevant to the situation, but i'm open to any suggestion
Before: 
After:
=> Ad UI 6642 fix icons color in demo in vapor

packages/react-vapor/src/components/datePicker/DatePicker.tsx, packages/react-vapor/src/components/datePicker/DatePickerBox.tsx, packages/vapor/scss/components/calendar.scss, packages/vapor/scss/controls/multiline-field.scss, packages/vapor/scss/elements/btn.scss, packages/vapor/scss/redesign/fonts.scss, packages/vapor/scss/redesign/variables.scss, packages/vapor/scss/utility/spaced-boxes.scss, packages/vapor/scss/variables.scss
- If we select the start date and the end date, then click on the **Clear** button, the end date background is stuck on blue.
The lifecycle `componentDidUpdate` is executed after the `render` method, and we can no longer use `componentWillReceiveProps` which happened before the `render` since it’s deprecated. Instead, we can directly use the `props.date` to identify if the date input has value and needs the `.date-picked` class.
- Fixed the **Clear** button style and did a cleanup on `--button-secondary` CSS variables.
Before:
After:
None
=> fix(next): clearable date picker dropdown connected

packages/demo/src/components/examples/SectionExamples.tsx, packages/vapor/scss/forms/block-form.scss
[COM-479]
This change is an attempt to simplify the `Section` component while also integrating UX suggestions to have inputs with text closer together.
In short, most of the mock-ups always require the `Section level={3}` around every individual input. This is pretty annoying to do, so this change aims at making it very simple.
So we now enforce the `level 3` spacing between *within* a `LabeledInput` instead of *scaling with the level*. This ensures that the margin is minimal between the label, input, and help text.
The new recommended structure of a Form would be: 
```
<Form> 
<Section title="Something">
<LabeledInput>
<ComponentThatDoesNotHaveItsOwnLabel />
</LabeledInput>
<ComponentThatProvidesItsOwnLabel />
</Section>
<Section title="Another thing">
...
</Section>
</Form>
```
The only …
=> Fix com 479 fixed input spacing

packages/react-vapor/src/components/drop/Drop.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/DraggableSelectedOption.tsx, packages/react-vapor/src/components/dropdownSearch/MultiSelectDropdownSearch/SelectedOption.tsx, packages/react-vapor/src/components/itemBox/ItemBox.tsx, packages/react-vapor/src/components/select/MultiSelectConnected.tsx, packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithPredicate.spec.tsx, packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx, packages/react-vapor/src/components/tooltip/Tooltip.tsx
Right now if I do my fix for the infinite scroll I break a lot of tests, but not the behaviour in the demo.
I've added a few accessibility attributes on different element and swapped enzyme for RTL in some of the tests for the multiselect component. I'll do more PR for the rest of the files and then I'll fix the issue with the infinite scroll.
None
=> test(multi-select): improve tests by swapping Enzyme with RTL

packages/react-vapor/src/components/listBox/ListBox.tsx, packages/react-vapor/src/components/loading/Loading.tsx, packages/react-vapor/src/components/select/hoc/SelectWithInfiniteScroll.tsx, packages/react-vapor/src/components/select/hoc/tests/SelectWithInfiniteScroll.spec.tsx
Use the infinite scroll only when the select is open
Removed all the tests that only get the props. Tested the actual behaviour instead
None that I can think of
=> fix(infinite-scroll): use the infinite scroll only when the select is open

packages/react-vapor/src/components/validation/components/ValidationMessage.tsx, packages/react-vapor/src/components/validation/components/tests/ValidationMessage.spec.tsx, packages/react-vapor/src/components/validation/hoc/WithValidationMessageHOC.tsx
[COM-900]
We needed some use cases where the message should not be shown if the component is not dirty.
So I decided to add a simple prop to make it very easy to support that.
None
[COM-900]: https://coveord.atlassian.net/browse/COM-900
=> fix(validation): prop to show validation message only if dirty

packages/react-vapor/src/components/table-hoc/TableWithPredicate.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPredicate.spec.tsx
https://coveord.atlassian.net/browse/SEARCHAPI-5681
Added a new tableWithPredicateGeneric which wraps a custom parameter.
I need to have a tableWithPredicate with another type of single selected. Instead of copying the whole file, I decided to make a generic one that takes a component as a parameter.
Since I moved some interfaces to the `tableWithPredicateGenerate` file, I exported the interface in `tableWithPredicate` as well.
=> feat(table-hoc-predicate): add generic tableWithPredicate

packages/react-vapor/src/components/select/SelectConnected.tsx, packages/vapor/scss/components/calendar.scss, packages/vapor/scss/components/facet.scss, packages/vapor/scss/controls/checkboxes.scss, packages/vapor/scss/controls/dropdown.scss, packages/vapor/scss/controls/input-field.scss, packages/vapor/scss/controls/radios.scss, packages/vapor/scss/elements/btn.scss, packages/vapor/scss/icons/icons.scss
Fixed facet checkbox button line-height and radio shadow on focus, more adjustments will be done in the admin.
Before:
After:
=> fix(rebranding): radio shadow and facet button line-height

packages/vapor/scss/controls/checkboxes.scss, packages/vapor/scss/controls/radios.scss, packages/vapor/scss/elements/btn.scss, packages/vapor/scss/elements/links.scss, packages/vapor/scss/icons/icons.scss, packages/vapor/scss/utility/layout.scss, packages/vapor/scss/variables.scss
This PR includes several quick fixes:
- Reduce `box-shadow` of the radio button on focus, and remove `font-weight` bolder if the radio is selected (will update this component later in another user story)
- Set the disabled text color to `--grey-20`
- Remove `icon-link` class, use `icon documentation-link` instead
- Fix icon color for `no-link` and `disabled`
- Add utilities for white and light grey background color, there is no example yet since the mods are not completed
None
=> fix(rebranding): radio button box-shadow on focus

packages/demo/src/components/examples/ModalWizardExamples.tsx, packages/react-vapor/src/components/modalWizard/ModalWizard.tsx, packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx
Removing the closing method in the last step of the modal and passing it as a callback for the onFinish function.
The user will be responsible for calling the callback to close the modal.
BREAKING CHANGE: changing the way we close the modal - the user will need to dispatch a closeModal
action at the end of the onFinish method. An example is updated to show the close method being used
after onFinish (after the alert)
This will allow the user to close the modal after an onFinish method is completed.
How to test:
1. Go to ModalWizard and upon finish, the modal will close. (method close() was added after alert which dispatches the closeModal action)
There are no changes to the behaviour. Modal should close as expected when finishing modal.
- ModalWizard will stay open after the onFinish …
=> refactor(modal-wizard): changing the way close ModalWizard on finish

packages/demo/src/components/examples/ModalWizardExamples.tsx, packages/react-vapor/src/components/modalWizard/ModalWizard.tsx, packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx
`title` and `modalFooterChildren` props of the `ModalWizard` component can now be step dependent. Meaning that we can have different titles or additional stuff in the footer depending on what is the current step displayed by the wizard.
BREAKING CHANGE: ModalWizard `validateStep` function now takes in the total number of steps as
second parameter instead of a boolean indicating whether if it is the last step. This change allow
for more flexibility.
=> improvement(modalwizard): allow footer and title to depend on step

packages/react-vapor/src/components/modal/Modal.tsx, packages/react-vapor/src/components/modal/ModalReducers.ts, packages/react-vapor/src/components/modal/tests/ModalReducers.spec.ts
Modals with openOnMount prop set to true were not added to the openModals array in the state which was causing issues with modals not stacking properly.
None.
=> fix(modal): add modal openOnMount to openModals state

packages/react-vapor/src/components/userFeedback/UserFeedback.spec.tsx, packages/react-vapor/src/components/userFeedback/UserFeedback.tsx, packages/react-vapor/src/components/validation/components/ValidationMessage.tsx, packages/react-vapor/src/components/validation/components/tests/ValidationMessage.spec.tsx
Before having different mods for text color, `.validation-error` was used in `ValidationMessage` to set text to red when has errors while removing all text utilities.
But it caused a conflict of style with the same class in admin-ui: https://github.com/coveo/admin-ui/blob/master/packages/v2/stylesheets/_inputs.scss#L215 
We can replace `validation-error` with `text mod-error` to fix this issue.
None
=> fix(validation-message): replace validation-error with text mod-error

Jenkinsfile.groovy
https://coveord.atlassian.net/browse/ADUI-6771
If master or release deployment fail, it will now send a notification to admin-ui-guild and
cloudadmindev. Else, it will have the same previous behavior
master has to fail :| (I will probably add the JOB_NAME of this pr to the groovy file and see when I make it fail, if the notif gets sent on the desired channels)
jenkins
-   [x] The steps to test the changes are clearly identified
-   [x] The scope of the changes is clearly identified
=> ci(jenkinsfile.groovy): +2 more channels on master/release failure

packages/react-vapor/src/components/multiValueInputs/MultiValuesInput.tsx, packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx
If `inputProps.validate` is defined, we need to validate all the inputs instead of only the first one.
None
=> fix(multivaluesinput): validate all the inputs

packages/demo/src/components/examples/DatePickerExamples.tsx, packages/demo/src/components/examples/DatePickerExamplesCommon.ts, packages/react-vapor/src/components/calendar/Calendar.tsx, packages/react-vapor/src/components/calendar/CalendarDay.tsx, packages/react-vapor/src/components/calendar/Countdown.tsx, packages/react-vapor/src/components/calendar/index.ts, packages/react-vapor/src/components/calendar/tests/Calendar.spec.tsx, packages/react-vapor/src/components/calendar/tests/CalendarDay.spec.tsx, packages/react-vapor/src/components/calendar/tests/Countdown.spec.tsx, packages/vapor/scss/components/calendar.scss, packages/vapor/scss/variables.scss
by providing the countdown prop you can switch to a new countdown version of the calendar
[ADUI-6728](https://coveord.atlassian.net/browse/ADUI-6728)
Added a countdown version for the existing calendar component. Changes are only visible by providing the `countdown` props
None
In the Datepicker section of the demo you should see the countdown. The mockups are in the Jira attached above
=> feat(calendar): new countdown feature for calendar

packages/react-vapor/src/components/calendar/Calendar.tsx, packages/react-vapor/src/components/calendar/tests/Calendar.spec.tsx, packages/react-vapor/src/components/calendar/tests/CalendarConnected.spec.tsx
The Datepicker works by providing a list of years and a startingYear / selectedYear index, which is used to select the year from the given list. However, if the given year index falls outside the range provided then it would break. I'm guessing this problem wasn't found before because normally pickiing the year is done in the UI, but when the Datepicker gets its data from the API it can be anything.
This PR adds a check to confirm the selected year (from the api or the user) is present in the years array. If it isn't then it defaults to the current year (UX didn't give me an answer on whether this is the best approach so if its flawed let me know)
[ADUI-6789](https://coveord.atlassian.net/browse/ADUI-6789)
None
This can only really be tested locally as far as I know. I tried changing the …
=> fix(calendar): added condition to default to current year if bad data

packages/demo/src/components/examples/SectionExamples.tsx, packages/demo/src/components/examples/SvgExamples.tsx, packages/react-vapor/src/components/button/Button.tsx, packages/react-vapor/src/components/input/LabeledInput.tsx, packages/react-vapor/src/components/labeledValue/LabeledValue.spec.tsx, packages/react-vapor/src/components/labeledValue/LabeledValue.tsx, packages/vapor/scss/icons/icons.scss
All the icon modifiers with a fixed size (`mod-10` to `mod-30`) had the same vertical aligment and lign-height correction of `-0.2 em` which doesn't make sense since they have difference sizes. Now the size of the corrections follows the size of each modifier.
Tested it in the admin-ui and it improves alignment in a bunch of places.
=> Improve icon alignment

packages/react-vapor/src/components/table-hoc/TableWithFilter.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithFilter.spec.tsx
Bug: https://coveord.atlassian.net/browse/ADUI-6845
A bug was noticed with the changes of the last release. If a tableWithFilter has a custom blankslate and the same TableHOC has a empty state set, the custom blankslate wouldn't appears. For example, the "clear filter" button wouldn't appears on the source blankslate.
To solve this issue, I revert the changes made on the tableWithFilter component.
=> fix(table-with-filter): revert to previous state, ignore empty state

packages/demo/src/components/examples/TableHOCExamples.tsx, packages/vapor/scss/tables/table.scss
https://coveord.atlassian.net/browse/ADUI-6813
I've added a line-height of 25px to help with the badge alignment with the text in <td>. I've also added a badge colum in the demo to help visualise.
Maybe some row in some table in the admin wont be better off with the 25px line-weight :thinking: 
=> fix(table): line-height to help align badges in table

packages/demo/src/components/examples/CodeEditorExamples.tsx, packages/react-vapor/src/ReactVapor.ts, packages/react-vapor/src/ReactVaporReducers.ts, packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/CodeEditorActions.ts, packages/react-vapor/src/components/editor/CodeEditorReducers.ts, packages/react-vapor/src/components/editor/CodeEditorSelectors.ts, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx, packages/react-vapor/src/components/editor/tests/codeEditorReducer.spec.tsx, packages/react-vapor/src/components/editor/tests/codeEditorSelectors.spec.ts
I gave the possibility for the `CodeEditor` to have a value in the redux store.
Basically, if you set the `id` prop. An action will be dispatched on change to set the value of the `CodeEditor` in the store.
You can check the Demo, the first `CodeEditor` displayed there should dispatch the update action on change.
I debounced the redux call not to spam the store with new values on each stroke.
EDIT: upon unmount, the component will remove its ID from the store
We also have a selector to get the value from the codeEditor.
none
=> feat(code editor): value in store

packages/react-vapor/src/components/editor/CodeEditorReducers.ts
code editor reducer is crashing on empty state. modified the condition to avoid that.
none
=> fix(code editor): prevent reducer from crashing on empty state

packages/demo/src/components/examples/RadioExamples.tsx, packages/react-vapor/src/components/radio/RadioCard.tsx, packages/react-vapor/src/components/radio/RadioSelect.tsx, packages/react-vapor/src/components/radio/index.ts, packages/react-vapor/src/components/radio/tests/RadioCard.spec.tsx, packages/react-vapor/src/components/radio/tests/RadioSelect.spec.tsx, packages/vapor/scss/controls/radios.scss, packages/vapor/scss/variables.scss
- Added a RadioCard component to enable usage of the RadioSelect component with cards instead of checkboxes
FYI: This has been developed with members of the UX team. 
https://user-images.githubusercontent.com/16785453/114727369-27554480-9d0c-11eb-8597-13a5a78fd448.mov
This is born from the task to create a ModalSelect component to be used when offering a choice between detailed options.
To avoid confining this type of radio button to this modal component I built it separately. 
I thought, for example, that it might be used in a ModalWizard scenario.
Don't think there are any
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to …
=> feat(radio-card): added radio card variant

packages/react-vapor/src/components/modal/ConfirmationModalProvider.tsx, packages/react-vapor/src/components/modal/UnsavedChangesModalProvider.tsx, packages/react-vapor/src/components/modal/tests/ConfirmationModalProvider.spec.tsx, packages/react-vapor/src/components/modalWizard/ModalWizard.tsx
Added the ConfirmationModalProvider to the store instead of using internal mechanisms which should fix the bug of the confirmation modal not being overlayed over an isDirty modal. I also updated / removed some tests to use RTL and remove enzyme
Might be some issues when the version is updated in the admin, but in theory it should work the same
=> Bugfix/ad UI 6797 isdirty modal prompt not in modal store

packages/demo/src/components/ComponentPage.tsx, packages/demo/src/components/index.tsx, packages/demo/webpack.config.js
Bundling the demo from the `.js` output introduced a regression, compiled `.js` was shown in the examples code sample instead of the actual source code.
None
=> fix(demo): show example source code instead of compiles .js

Jenkinsfile.groovy
Attempt at making publish step pass for next branch. I don't understand why were trying to push on master when releasing `next` branch. Is it to push the tags? Opening this PR for conversation.
it is failing with that error:
```bash
17:15:52  + git push -u origin master
17:15:52  error: src refspec master does not match any.
17:15:52  error: failed to push some refs to **'https://****:****@github.com/coveo/react-vapor.git'**
```
Here is what I found on stackoverflow https://stackoverflow.com/questions/4181861/message-src-refspec-master-does-not-match-any-when-pushing-commits-in-git
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted …
=> ci(jenkins): dont push on master when releasing next

packages/react-vapor/package.json, pnpm-lock.yaml
We need to add the @types packages into our dependencies when we export types that directly reference them, and the package is not specified as a peer dep.
For example here when trying to specify the prop `marks` of the Slider component, we get told that this property doesn't exist.
When looking at the declarations provided by `react-vapor` we can see that `SliderProps` is `unknown` because indeed the types of rc-slider lib are never installed.
```ts
import 'rc-slider/assets/index.css';
import { SliderProps } from 'rc-slider';  //  <---  Here
import { RCTooltip } from 'rc-tooltip';
import * as React from 'react';
export declare enum AppendedValueSide {
left = "LEFT",
right = "RIGHT",
both = "BOTH"
}
export interface SliderOwnProps extends SliderProps {
id: string;
initialValue?: number; …
```
=> fix(types): include types of dependencies we export

packages/react-vapor/package.json, packages/react-vapor/rollup.config.js, pnpm-lock.yaml
The esm build we produce had a weird require of the `indexof` module which doesn't exist. I created an alias that points to the real module called `component-indexof`.
Anyone using our esm build would get 
```bash
./node_modules/react-vapor/dist/bundles/react-vapor.esm.js
Cannot find module: 'indexof'. Make sure this package is installed.
```
Since the [issue](https://github.com/component/classes/issues/31) isn't resolved yet, I added an alias that points to `component-indexof` instead.
Tested it and it works, but the weird thing is that it was working on master without the alias 😕 
None
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is …
=> build(rollup): remove weird dependency on 'indexof'

package.json, pnpm-lock.yaml
There is some confusion around git-cz and commitizen/cz-cli. They are 2 different packages with the same name. We should be using cz-cli, not the other one because emojis break the version bumps.
None
=> ci(commit): switch back git-cz for commitizen/cz-cli

packages/vapor/scss/tables/table.scss
The variable --deprecated-black-rgb didn't exist so changed that
Also changed table card item select color to new blue
nah
=> feat(table): fixed bad variable and changed selected style

packages/demo/src/components/examples/BadgeExamples.tsx, packages/react-vapor/src/components/badge/Badge.tsx, packages/react-vapor/src/components/badge/tests/Badge.spec.tsx, packages/react-vapor/src/components/logoCard/LogoCard.tsx
Badges didn't allow having only an icon and no label. This is a feature that I needed for the IconCard.
None
=> fix(badge): allow badges with only icons

packages/react-vapor/src/components/toast/Toast.tsx, packages/react-vapor/src/components/toast/tests/Toast.spec.tsx
This gives us the option to remove the infoToken when its not needed.
Currently, with the Toast implementation, it always renders the `infoToken` which is a problem for the Login Renewal Prompt in admin-ui. The`TokenRenewalPrompt` uses this `Toast` component. In admin-ui, it renders an empty Svg with a `info-token` class coming from the `infoToken` component.
Adding a `showInfoToken` prop will allow us to use it in the  `Toast` component in `TokenRenewalPrompt`, thus allowing us to remove this class and fix the spacing issue
=> feat(toast): option to move infoToken on toast when its not needed

packages/demo/src/components/examples/InputExamples.tsx, packages/demo/src/components/examples/RadioExamples.tsx, packages/demo/src/components/examples/TableHOCwithBlankSlateExamples.tsx, packages/demo/tsconfig.json, packages/react-vapor/.eslintignore, packages/react-vapor/.eslintrc.js, packages/react-vapor/jest.config.js, packages/react-vapor/src/TestUtils.tsx, packages/react-vapor/src/components/badge/tests/Badge.spec.tsx, packages/react-vapor/src/components/collapsible/tests/CollapsibleContainerConnected.spec.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx, packages/react-vapor/src/components/iconCard/tests/IconCard.spec.tsx, packages/react-vapor/src/components/info-token/tests/InfoToken.spec.tsx, packages/react-vapor/src/components/modal/tests/ConfirmationModalProvider.spec.tsx, packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx, packages/react-vapor/src/components/modalWizard/tests/ModalWizardWithValidations.spec.tsx, packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithPredicate.spec.tsx, packages/react-vapor/src/components/select/hoc/tests/SelectWithInfiniteScroll.spec.tsx, packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithEmptyState.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPredicate.spec.tsx, packages/react-vapor/tsconfig.build.json, packages/react-vapor/tsconfig.eslint.json, packages/react-vapor/tsconfig.json, packages/react-vapor/tsconfig.test.json, packages/tsconfig-base.json
My IDE experienced slownest in its intellisense in this repository, so I spent some time cleaning up the tsconfigs by leveraging config inheritence.
One other thing that seemed to have helped alot with speed issues is to setup your IDE so that it uses the same typescript version than the one specified in the package.json
None expected
=> build(typescript): cleanup tsconfig files

packages/react-vapor/src/components/numericInput/NumericInputConnected.tsx, packages/react-vapor/src/components/numericInput/tests/NumericInputConnected.spec.tsx, packages/vapor/scss/controls/numeric-input.scss
Realigned the `NumericInput` buttons and also improved the overall user experience by adding a proper focus effect and disabled style.
I didn't rewrite the entire test suites, because the component will probably change soon with the new designs.
None
=> fix(numeric input): realign numeric input buttons

packages/react-vapor/src/components/modalWizard/ModalWizard.tsx, packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx
- Adding optional props for onNext and onPrevious
This comes from wanting to use the ModalWizard component in the CreateMLModel component in adui. The latter sends analytics events when these buttons are clicked so I need these props to maintain feature parity. The flexibility could likely also be beneficial to other use cases.
nah
=> feat(modal-wizard): added optional onclick callback props

packages/vapor/scss/components/toast.scss
Looks the same as before but uses the new variable.
=> fix(toast): use high-elevation-on-neutral shadow

packages/react-vapor/src/components/editor/CodeEditor.tsx, packages/react-vapor/src/components/editor/tests/CodeEditor.spec.tsx
using onblur instead of a debounced onChange to trigger the store action in the codeEditor Component.
none
=> fix(code editor): onblur replace debounce

packages/demo/src/components/examples/BadgeExamples.tsx, packages/vapor/scss/components/badge.scss
[COM-958]
While working on a feature in the Catalogs, we needed a new type of badge. We were suggested to add it in react-vapor, and I also got the recommendations from Gustavo to reduce the padding at large.
Before:
After:
You can see the new "tag" which has a white background and no bold text.
It looks cleaner in the context of an inline tag in a table, for instance
It removes capitalization, we'll have to update the places where it assumed that.
It *could* also change the look a bit in pages that use the Badge, but this is what we want with this change :thinking: 
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the …
=> [COM-958] feat(badge): add badge as tag, remove some padding

Jenkinsfile.groovy
Deploy `next` branch demo to `/feature/next` instead of `/feature/null`.
BRANCH_NAME
> For a multibranch project, this will be set to the name of the branch being built, for example in case you wish to deploy to production from master but not from feature branches; if corresponding to some kind of change request, the name is generally arbitrary (refer to CHANGE_ID and CHANGE_TARGET).
CHANGE_BRANCH
> For a multibranch project corresponding to some kind of change request, this will be set to the name of the actual head on the source control system which may or may not be different from BRANCH_NAME. For example in GitHub or Bitbucket this would have the name of the origin branch whereas BRANCH_NAME would be something like PR-24.
[Source](https://ci.eclipse.org/webtools/env-vars.html/)
None
- …
=> ci(demo): deploy next branch to /feature/next

packages/demo/src/components/examples/ToastExamples.tsx, packages/react-vapor/src/components/toast/Toast.tsx, packages/react-vapor/src/components/toast/tests/Toast.spec.tsx, packages/vapor/scss/components/toast.scss
[ADUI-6990](https://coveord.atlassian.net/browse/ADUI-6990)
I updated the Toast component in 2 ways:
1. I replaced instances of `block` and `float` with `flexbox` to make it more aligned with the UX mockups. As a result I had to do a minor refactor to separate functionality between the `isDownload` / `isSmall` versions and the main version, with a small refactor of the `isDownload` version itself
2. While I was at it, I refactored the component to be a Functional Component and. updated the tests accordingly
NOTE: I had to skip one test which I would greatly appreciate help with
None that I can see but I'll say this: this component now has 3 marked deprecated function props (`content`, `onDestroy` & `onRender`). I can find only a couple of places in RV and the Admin where `content` and …
=> Style/ad UI 6990 fix toast styling issues 2

packages/react-vapor/src/components/headers/HeaderWrapper.tsx, packages/vapor/scss/components/panel-header.scss
https://coveord.atlassian.net/browse/ADUI-7096
With the new typekit, the style of the description in headers was too heavy. 
Before:
After:
None :thinking: 
=> Adui-7096/fix: fix description style in headers

packages/demo/src/components/examples/NumericInputExamples.tsx, packages/react-vapor/src/components/numericInput/NumericInputConnected.tsx, packages/react-vapor/src/components/numericInput/tests/NumericInputConnected.spec.tsx, packages/vapor/scss/controls/inputs.scss
Added the possibility to disable the numeric input using the props
your heart
=> feat(numeric input): disabled prop

packages/demo/src/components/examples/BrowserPreviewExamples.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreview.tsx, packages/react-vapor/src/components/browserPreview/tests/BrowserPreview.spec.tsx
https://coveord.atlassian.net/browse/ADUI-7141
Added a prop to the BrowserPreview component so it can receive a Title instead of using a hardcoded value.
=> feat(browserpreview): +title props

packages/demo/src/components/examples/BrowserPreviewExamples.tsx, packages/react-vapor/src/components/browserPreview/BrowserPreview.tsx, packages/react-vapor/src/components/browserPreview/tests/BrowserPreview.spec.tsx
We want to keep the preview string informative and still be able to put a custom title, so I change
the title prop to be rendered in a seperate element instead of replacing Preview string
=> refactor(browserpreview): +seperate title from preview string

packages/demo/src/components/examples/TextInputExamples.tsx, packages/react-vapor/src/components/form/FormProvider.tsx, packages/react-vapor/src/components/form/index.ts, packages/react-vapor/src/components/index.ts, packages/react-vapor/src/components/textInput/TextInput.tsx, packages/react-vapor/src/components/textInput/TextInputReducer.tsx, packages/react-vapor/src/components/textInput/index.ts, packages/react-vapor/src/components/textInput/tests/TextInput.spec.tsx, packages/react-vapor/src/components/textInput/useTextInput.ts, packages/vapor/scss/controls/text-input.scss, packages/vapor/scss/guide.scss
Add a new version of the input component called `TextInput`. 
As you will see, I have tried a new state management pattern that is **free of redux**. The advantage of doing that is that we get rid of unnecessary global redux state updates each time the value of an input changes.
3 things (other than types) related to the `TextInput` are exported:
- `TextInput`: the component. Can only be rendered inside a `FormProvider`
- `FormProvider`: provides the form state. We can have as many of those as we need. Best practice is to have it as low as possible in the DOM tree => less children equals less potential unnecessary rerenders.
- `useTextInput` hook: the only way to query and interact with the text input state. Can only be used within a `FormProvider`.
None, the old input component was …
=> feat(textinput): add new TextInput component

packages/demo/src/components/examples/IconBadgeExamples.tsx, packages/react-vapor/src/components/iconBadge/IconBadge.tsx, packages/react-vapor/src/components/iconBadge/index.ts, packages/react-vapor/src/components/iconBadge/tests/IconBadge.spec.tsx, packages/react-vapor/src/components/index.ts, packages/vapor/scss/components/header.scss, packages/vapor/scss/components/icon-badge.scss, packages/vapor/scss/guide.scss
We will need the IconBadge component for the Notification header section on the Top Bar `.mod-navigation`. More modes will be added later for other sections of the platform.
Mockup: https://www.figma.com/proto/J32OAeoVopRQxvXP1zlojf/Top-bar-simplification?node-id=293%3A299&scaling=min-zoom&page-id=0%3A1
None
=> feat(top-bar): create icon badge component

packages/vapor/scss/components/toast.scss
https://coveord.atlassian.net/browse/ADUI-7173
Something went wrong when merging the toast fix (https://github.com/coveo/react-vapor/pull/2022) into Next branch.
I removed the flex and the infoToken is back where it should be :woman_shrugging: 
Should be none
=> fix(toast): fix info token in toast

packages/demo/src/components/examples/IconCardExamples.tsx, packages/react-vapor/src/components/iconCard/IconCard.tsx, packages/react-vapor/src/components/iconCard/tests/IconCard.spec.tsx, packages/vapor/scss/components/icon-card.scss, packages/vapor/scss/icons/icons.scss
Allowing to display children inside icon cards (here a cloud icon).
none
=> feat(iconcard): allow IconCard to have children

packages/react-vapor/src/components/textInput/TextInput.tsx, packages/vapor/scss/components/labeled-value.scss, packages/vapor/scss/controls/text-input.scss
At the time of implementation, the typekit wasn't available to use for the TextInput so I had to add custom style that did the same thing. Now that the typekit is available, we can remove that style in favor of the official typekit classes.
None
=> refactor(textinput): replace custom style with typekit

packages/demo/src/components/examples/SingleSelectExamples.tsx
Simplest fix was to wrap the Section Children instead of rewriting how the section component scss handles children of levels
=> fix(singleselect): wrapped section children

packages/vapor/resources/icons/svg/associate.svg
Add the `associate` icon to Vapor 
It's coming from: https://www.figma.com/file/bMtrzk73CdW9OKnYlZfjiW/Platform-Library?node-id=32%3A7795
And have been ask by @acverrette 
https://coveord.atlassian.net/browse/SEARCHAPI-6005
=> [SEARCHAPI-6060] feat(svg): add `associate` icon

CODEOWNERS
Add [UI Tooling](https://github.com/orgs/coveo/teams/ui-tooling) as codeowners of react-vapor.
none, not code related
=> ci(codeowners): add ui-tooling team to codeowners

packages/react-vapor/src/components/optionsCycle/OptionsCycle.tsx, packages/vapor/scss/components/calendar.scss
Change the style of the Option Cycle to match the normal buttons
**Before**
**After**
None
=> fix(option-picker): alignement when used as a button

packages/vapor/scss/controls/numeric-input.scss, packages/vapor/scss/elements/btn.scss, packages/vapor/scss/elements/links.scss, packages/vapor/scss/helpers.scss
Firefox has a weird behaviour with outline-style and the auto property. It won't apply the color and the outline appears outside of the element instead of inside like chrome.
In this fix I override the outline-offset and the outline-style in Firefox for the .btn, .numeric-inputs, and .links (Left is Chrome, right is Firefox)
**.btn**
**.numeric-inputs**
**.links**
None
=> fix(focus): override outline for Firefox

packages/react-vapor/src/components/tab/Tab.tsx, packages/react-vapor/src/components/tab/TabActions.ts, packages/react-vapor/src/components/tab/tests/Tab.spec.tsx
Following the tab component refactoring (https://github.com/coveo/react-vapor/pull/2072), we lost the ability to specify a callback when clicking on a TabConnected.
None hopefully this time 🙏 
=> fix(tabs): allow onSelect prop on TabConnected

packages/demo/src/components/examples/ExamplesUtils.ts, packages/demo/src/components/examples/HeaderExamples.tsx, packages/react-vapor/src/components/tab/TabSelectors.ts, packages/react-vapor/src/components/tab/tests/Tab.spec.tsx
The header example had 2 tab navigation rendered at the same time, but they we're not independent from each other. Meaning that when selecting a tab in the first it would also select the tab in the second and vice-versa.
None
=> fix(tabs): allow multiple independent tab navigations at the same time

Jenkinsfile.groovy
Should look something like this, but with `react-vapor/master` instead of just `master`.
None
=> ci(jenkins): add build back to normal notification

packages/vapor/scss/components/tooltip.scss
For tooltips, if we use P tags for the title, the text becomes white again as it was originally
=> fix(typekit,tooltip): set the text color to white

packages/react-vapor/src/components/filterBox/FilterBox.tsx, packages/react-vapor/src/components/itemBox/ItemBox.tsx, packages/react-vapor/src/components/listBox/ListBox.tsx, packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithFilter.spec.tsx, packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithPredicate.spec.tsx, packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithPredicateAndFilter.spec.tsx, packages/react-vapor/src/components/select/hoc/tests/SelectWithInfiniteScroll.spec.tsx, packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx, packages/react-vapor/src/components/select/tests/SingleSelectConnected.spec.tsx, packages/react-vapor/src/components/table-hoc/tests/TableWithPredicate.spec.tsx
https://coveord.atlassian.net/browse/UITOOL-72
Improved the accessibility of select components by adding `listbox` and `option` to ListBox components, and updated the tests
eg BEFORE
```tsx
let lists = screen.getAllByRole('list');
expect(within(lists[1]).queryByText('first')).not.toBeInTheDocument();
```
AFTER
```tsx
expect(
screen.getByRole('option', {
name: /first/i,
})
).toBeInTheDocument();
```
None: functionality is the same, only testing is easier
NOTE: I was unable to update `MultiSelectWithPredicateAndFilter.spec.tsx` to RTL, the input won't change when using RTL and attempts to debug were taking too long. I will open another ticket & PR for documenting debugging Jest tests in React Vapor)
-   [ ] The potential breaking …
=> Chore/ad UI 7296 improve accessibility of select components

packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithFilter.spec.tsx
Remove a `screen.logTestingPlayground` left in by accident
=> test(multiselect): remove log

packages/react-vapor/src/components/table-hoc/TableHOC.tsx, packages/react-vapor/src/components/table-hoc/tests/TableHOC.spec.tsx
In the refactor I missed out on a default option when passing data. I added tests since this was a
corner case previously missed
https://coveord.atlassian.net/browse/UITOOL-112
Adding default `[]`
Added tests to check that `null` and `undefined` are tested against
How to test:
It should be good, but the final confirmation will be with data in the Admin
=> test(tablehoc): tableHOC was missing a ternery

packages/react-vapor/src/animations/SlideY.tsx, packages/react-vapor/src/animations/tests/SlideY.spec.tsx, packages/react-vapor/src/components/iconCard/tests/IconCard.spec.tsx
Add the aria-hidden attribute on the div when closed, which makes the content invisible for the assistive technologies.
Adapt unit tests
None
=> feat: improve accessibility of the SlideY component
