- packages/react-vapor/src/components/modal/ModalComposite.tsx
- packages/react-vapor/src/components/modal/ModalHeader.tsx
- packages/react-vapor/src/components/modal/tests/ModalComposite.spec.tsx
- packages/react-vapor/src/components/title/Title.tsx
Improve the accessibility of the modal by adding a `labelledby` attribute. This allow a developer to get the dialog by it's title:
```typescript
renderModal(<ModalComposite isOpened title={'my title'} />);
expect(screen.getByRole('dialog', {name: 'my title'})).toBeVisible();
```
None
> feat(modal): improve accessibility by adding a labelledby property

- packages/react-vapor/src/components/modal/ModalComposite.tsx
- packages/react-vapor/src/components/modal/tests/ModalComposite.spec.tsx
A simple prop to pass classNames to the modal content.
none
> feat(modal composite): prop for content classes

- packages/demo/src/components/examples/DatePickerExamples.tsx
- packages/react-vapor/src/components/datePicker/DatePicker.tsx
- packages/react-vapor/src/components/datePicker/DatePickerActions.ts
- packages/react-vapor/src/components/datePicker/DatePickerBox.tsx
- packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx
- packages/react-vapor/src/components/datePicker/DatePickerReducers.ts
- packages/react-vapor/src/components/datePicker/DatesSelection.tsx
- packages/react-vapor/src/components/datePicker/DatesSelectionConnected.tsx
- packages/react-vapor/src/components/datePicker/tests/DatePicker.spec.tsx
- packages/react-vapor/src/components/datePicker/tests/DatePickerDropdown.spec.tsx
- packages/react-vapor/src/components/datePicker/tests/DatePickerReducers.spec.ts
- packages/react-vapor/src/utils/DateUtils.spec.tsx
- packages/react-vapor/src/utils/DateUtils.ts
First part to fix this bug: https://coveord.atlassian.net/browse/SEARCHAPI-6055
This PR includes three changes for the date-picker:
1. If the date picker includes a range, and the "end" date is empty when the user apply the changes, the date is set as the end of today, instead of the current time.
Before:
https://user-images.githubusercontent.com/58052881/129240570-5dc0d1e5-ee69-4068-aea4-a8caac439f21.mp4
After:
https://user-images.githubusercontent.com/58052881/129240587-922c6cf1-5547-40a3-bb4a-4de9e8587e95.mp4
2. A new option (optional) is added, which allows a minimal range limit. If this minimum is not reached, the apply button is disabled. That way, it indicates to the user that an minimum range has to be set to save their selection.
Demo: …
> fix(date-picker): allow minimal range limit

- packages/react-vapor/src/components/form/FormProvider.tsx
- packages/react-vapor/src/components/textInput/index.ts
- packages/react-vapor/src/components/textInput/useForm.ts
added a custom hook that, by passing it a specific type of Form, will return the state of all forms. For example, useTextInput need an id so it can return the state of that specific TextInput. In my case, I want to use a hook that returns all of the TextInput of a component (really useful for validation and also when juggling with TextInput with guid() rather than hardcoded ids.
> feat(form): +customhook to get the state of all specific forms

- packages/vapor/resources/icons/svg/ready-to-receive-content-32px.svg
- packages/vapor/resources/icons/svg/success-32px.svg
Add new SGV:
- ready-to-receive-content-32px.svg
- success-32px.svg
> feat(vapor): add new SVG ready-to-receive-content & success in 32px

- packages/react-vapor/src/components/form/index.ts
- packages/react-vapor/src/components/form/useFormComponent.ts
- packages/react-vapor/src/components/textInput/TextInput.tsx
- packages/react-vapor/src/components/textInput/TextInputReducer.tsx
- packages/react-vapor/src/components/textInput/index.ts
- packages/react-vapor/src/components/textInput/tests/TextInput.spec.tsx
- move useFormComponent hook from `textInput` to `form` folder
- reset TextInput state to initial state when unmounting
None
> Clear TextInput state when unmounting

- packages/react-vapor/jest/setup.ts
- packages/react-vapor/src/components/modalWizard/ModalWizard.tsx
- packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx
- packages/react-vapor/src/components/modalWizard/tests/ModalWizardWithValidations.spec.tsx
- packages/react-vapor/src/hoc/withDirty/tests/withDirty.spec.tsx
- packages/react-vapor/src/hoc/withDirty/withDirty.tsx
- packages/react-vapor/src/utils/useMountedState.ts
[Related issue](https://coveord.atlassian.net/browse/ADUI-7405)
`withDirty` HOC had a weird behaviour where it could override the `isDirty` value specified in the config given the right circumstances.
I also fixed some failing tests in the ModalWizard by removing the fake timers.
None
> Fix withDirty HOC

- packages/demo/package.json
- packages/demo/src/components/examples/ChartExamples.tsx
- packages/react-vapor/package.json
- packages/react-vapor/src/components/actions/ActionBarReducers.ts
- packages/react-vapor/src/components/browserPreview/BrowserPreview.tsx
- packages/react-vapor/src/components/datePicker/DatePickerBox.tsx
- packages/react-vapor/src/components/dropdownSearch/DropdownSearch.tsx
- packages/react-vapor/src/components/dropdownSearch/DropdownSearchReducers.tsx
- packages/react-vapor/src/components/facets/FacetMoreRows.tsx
- packages/react-vapor/src/components/lastUpdated/tests/LastUpdated.spec.tsx
- packages/react-vapor/src/components/lastUpdated/tests/LastUpdatedConnected.spec.tsx
- packages/react-vapor/src/components/navigation/pagination/NavigationPaginationReducers.ts
- packages/react-vapor/src/components/tables/tests/TableDataModifier.spec.ts
- packages/react-vapor/src/utils/JSXUtils.tsx
- packages/vapor/svgWrapper.js
- pnpm-lock.yaml
https://coveord.atlassian.net/browse/UITOOL-173
Part 2
I moved Snyk into the devDependecies and i'm importing directly function from underscore.string instead of using `import * as s from` .
Should still be none
> UITOOL-173/cleanup for underscore.string imports

- packages/react-vapor/src/components/table-hoc/TableHOC.tsx
- packages/react-vapor/src/components/table-hoc/tests/TableHOC.spec.tsx
Expose the prefixContent from ActionBar on TableHOC. We need it to migrate the Salesforce Table to TableHOC.
N/A
> feat(table-hoc): added action bar prefix

- packages/vapor/scss/elements/links.scss
After speaking with Gustavo, this is the preferred solution for now as we will remove the `grape-purple-30` colour on link visit since it interferes with the colour on Firefox and not on Chrome.
This should fix the reported bug for ADUI-7509 where the breadcrumb header colour is not consistent between Chrome and Firefox.
We want to keep this visit state as Firefox by default will have their own colour applied if its not overwritten. 
None
> style(links): visiting state to be d-blue

- packages/vapor/scss/components/facet.scss
I changed the padding-bottom from 3px to 2px so the icon is now centered with the label. 
Go in FacetConnected and hover on a row, the exclude icon will appear.
none
> fix: change the padding bottom for the icon

- packages/demo/src/components/examples/ToastExamples.tsx
- packages/vapor/scss/components/toast.scss
Add additional padding, because many toast seen in the admin-ui has only title, no description and can be closed. The result was that the "X" icon was a little bit too close of the title.
Before (in the admin-UI):
After (seen in the current toast examples):
https://user-images.githubusercontent.com/58052881/133671325-f23b8f26-cc88-4581-8b5e-0d85ce73cae1.mp4
I don't it will breaks anything.
> fix(toast): set additional padding for the close part

- packages/react-vapor/src/components/modalWizard/ModalWizard.tsx
- packages/vapor/scss/components/modal-wizard.scss
- packages/vapor/scss/components/step-progress-bar.scss
- packages/vapor/scss/guide.scss
- packages/vapor/scss/utility/flex.scss
**Problem**
The progress bar would scroll with the modal body.
Refactoring the styling to bring the progress bar to the header and allow for it to be sticky at the top.
- Moved the Step Progress Bar to the header
- Added additional CSS classes to align the title and progress bar in the Modal Header component
- Added specific CSS target for the title to add padding (I was not able to do this with the additional CSS classes so I created a custom file called `modal-wizard.scss` to align the title targeting `model-{id}-title` h4 element)
**Before:**
https://user-images.githubusercontent.com/66333175/133631629-0ca1eb49-51c1-4a2d-8d39-9ecb116c4672.mp4
**After:**
https://user-images.githubusercontent.com/66333175/133632102-e5d520fc-c32d-44f0-b5dc-52881d026d85.mp4
None
How to test:
1. Go to the …
> style(modelwizard): making progress bar sticky fix

- packages/react-vapor/src/components/title/Title.tsx
- packages/react-vapor/src/components/title/tests/Title.spec.tsx
Using `useRef` to check if the header in the title is getting truncated
if it is, a tooltip with the whole text will appear on hover
none that I know of 
In the Header section of the Demo, the Breadcrumbs all finish with a Title component. So if you reduce your screen size to make the title truncate you will be able to test the behavior.
> fix(title): tooltip appear if truncated

- packages/vapor/scss/controls/dropdown.scss
Disable the clicks on the save so it goes through to the button
Before
https://user-images.githubusercontent.com/260007/134249572-792ffc86-479d-486a-82b9-bcdcee888341.mov
After
https://user-images.githubusercontent.com/260007/134249579-391a3285-1ea6-41bb-bb56-cd94ddb0d510.mov
I tested all the other components with the same class (SingleSelect, MultiSelect, DropdownSearch) and they still work
> fix(datepicker): datepicker should open when clicking on the svg

- packages/react-vapor/src/components/textarea/TextArea.tsx
The validation message was shown even when no validate function was provided.
- Don't attempt to validate the textarea if no validate function is provided
- Set the id on the textarea tag in order to improve accessibility
None
> fix(textarea): show validation message only when appropriate

- packages/react-vapor/src/components/modalWizard/ModalWizard.tsx
- packages/vapor/scss/components/modal-wizard.scss
I added an extra class `modal-wizard` to the css rule so that other Modals (non wizards) are left unaffected by the title padding.
I introduced a small bug targeting other modal titles when [refactoring the StepProgressBar into the header](https://github.com/coveo/react-vapor/pull/2123) - specifically for the ModalWizard component. This change affected non modal wizards and caused unwanted padding as seen below:
**Before:**
**After**
The **WizardModal** and **Modal** titles should be okay now
None
> fix(modal): adding extra class for specificity modal wizard title

- packages/react-vapor/src/components/slider/SliderHandle.tsx
Change slider handle tooltip position to bottom instead of top. That way the tooltip will never intersect with the marks labels.
Before
After
None
> fix(slider): change sldier handle tooltip position

- packages/react-vapor/src/components/form/index.ts
I need the FormContext in a class component
ADUI-7504-temporaryaccessmodal
Blocking ADUI-7504
A simple export of the FormContext so I can use it in a class component (no hooks allowed in a class component, and refactoring the whole class was way out of scope).
> chore(form): added line to export context

- packages/vapor/scss/components/toast.scss
Bug: https://coveord.atlassian.net/browse/ADUI-7490
Remove the `word-break` attribute as it is preferable to display a full word on a second line than break it.
Before:
After:
Shouldn't be the case.
> fix(toast): remove word-break attribute

- packages/demo/src/components/examples/ExamplesUtils.ts
- packages/react-vapor/src/components/title/Title.tsx
- packages/react-vapor/src/components/title/tests/Title.spec.tsx
The focus border on the SVG was truncated by the breadcrumbs. Now it's not! 
You need to select the focus option in the dev tool on the <a> to get the focus effect in React-Vapor
Before:
After:
None
> fix: add mr1 on documentation link to avoid truncating the focus

- packages/react-vapor/src/components/multilineBox/hoc/MultilineBoxWithRemoveButton.tsx
- packages/react-vapor/src/components/multilineBox/tests/MultilineBoxWithRemoveButton.spec.tsx
remove button is now hidden only when the MultiBox has one child. In any other cases, the remove button will be visible. 
The current behaviour usually expects us to add a method where we call `parentProps.addNewBox()` inside the child component, which can lead to unwanted display like _You just wrote something in the first child (let's say you are rendering inputs). With the expected implementation, a new input will be rendered, but without a remove button_ . I think it would be better to give the option to the user to delete the last child.
it's only a change in visibility/style. No big refactor
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md …
> feat(multiboxwithremovebutton): *remove button

- packages/vapor/resources/icons/svg/arrow-top-slim.svg
https://coveord.atlassian.net/browse/SFINT-4088
Since `arrow-top-slim` had a CSS rule named `st0` containing `fill: none` it conflicted with `logo-white` that defines the same CSS rule but with `fill: #fff`. Including both SVG images in the same page made a part of the Coveo logo disappear.
Since `arrow-top-slim` does not contain any closed shapes, removing the `fill` attribute from the CSS rule does not impact the image rendering. But it avoids conflicts with other images.
None
> fix(svg): css conflict with logo-white

- packages/react-vapor/package.json
- pnpm-lock.yaml
See https://github.com/reactjs/react-modal/pull/883
Bumping react-modal lib to fix memory leak issue in unit tests.
none
> fix(modal): remove memory leak from react-modal

- packages/react-vapor/jest.config.js
- packages/react-vapor/jest/entry.tsx
- packages/react-vapor/jest/setup.ts
- packages/react-vapor/jest/utils.tsx
- packages/react-vapor/src/Defaults.spec.ts
- packages/react-vapor/src/components/chart/tests/ChartTooltip.spec.tsx
- packages/react-vapor/src/components/chart/tests/ChartTooltipContent.spec.tsx
- packages/react-vapor/src/components/modal/tests/ConfirmationModalProvider.spec.tsx
- packages/react-vapor/src/components/modal/tests/Modal.spec.tsx
- packages/react-vapor/src/components/modal/tests/ModalComposite.spec.tsx
- packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx
- packages/react-vapor/src/components/modalWizard/tests/ModalWizardWithValidations.spec.tsx
- packages/react-vapor/src/components/multilineBox/tests/MultilineBoxWithRemoveButton.spec.tsx
- packages/react-vapor/src/components/numericInput/tests/NumericInputConnected.spec.tsx
- packages/react-vapor/src/components/popover/tests/Popover.spec.tsx
- packages/react-vapor/src/components/tooltip/tests/Tooltip.spec.tsx
- packages/react-vapor/tsconfig.build.json
- packages/react-vapor/tsconfig.json
- Removed `renderModal` util
- Cleaned up DOM between each test
- Simplified test config
Before:
After:
none
> test: remove renderModal util

- packages/vapor/resources/icons/svg/arrow-top-slim.svg
https://coveord.atlassian.net/browse/SFINT-4088
Reopened the issue because I found a side-effect (displaying `arrow-top-slim`) in the Admin UI.
The issue is also visible in the BrowserPreview demo page.
It turns out the `fill` attribute is required for some icons (e.g., `arrow-left-return`), while it can break other icons (e.g., `arrow-top-slim`).
The proposed solution is to put back a `style` element with a specific class name into `arrow-top-slim.svg` so it forces `fill: none` without preventing use of the `fill` attribute with other icons.
**Demo page (icon styled with `fill` attribute)**
**Demo page (`arrow-top-slim`)**
**`arrow-top-slim` in icons page**
A page that includes `arrow-top-slim` and relies on a CSS class named `svgArrowTopSlimPaths` could be impacted, but that is very …
> fix(svg): conflict with SVGs that require fill attribute

- packages/react-vapor/src/components/form/Form.tsx
- packages/react-vapor/src/components/form/tests/Form.spec.tsx
when the fieldset is not wrapped in a form, the browser mistakes the input in it for password input and begin to autocomplete them.
none that I know of.
> fix(form component): fieldset without form autocompletes

- packages/react-vapor/src/components/form/Form.tsx
- packages/react-vapor/src/components/form/tests/Form.spec.tsx
The UTs in admin-ui are running forever because the Form of react-vapor submit action is not handled. Since we have no action on the form, the default one is to reload the page with different query parameters.
I added a unit test to make sure we handle the submit
None
> fix(form): prevent the default behaviour of submitting on forms

- packages/demo/src/components/examples/SideNavigationExample.tsx
- packages/demo/src/components/examples/TabConnectedExample.tsx
- packages/vapor/scss/components/navigation.scss
- packages/vapor/scss/components/tab.scss
- packages/vapor/scss/controls/dropdown.scss
- packages/vapor/scss/controls/filter-box.scss
- packages/vapor/scss/controls/inputs.scss
- packages/vapor/scss/controls/numeric-input.scss
- packages/vapor/scss/controls/text-input.scss
- packages/vapor/scss/elements/btn.scss
- packages/vapor/scss/elements/links.scss
- packages/vapor/scss/helpers.scss
https://coveord.atlassian.net/browse/ADUI-7505
[Slack thread](https://coveo.slack.com/archives/GLS6Z9RPD/p1632768959073000)
This was originally done in AdminUI but better to have the changes here. Also took the liberty to clarify the demo for SideNavigation, though this will eventually all be replaced by Plasma
https://user-images.githubusercontent.com/22773767/135301202-6d650ad9-6561-4a5b-8ac7-1785255fc7ae.mov
EDIT: After discussion with UX the focus will not have rounded corners for now, since it looks terrible with the left bar of the nav when its active. The future restyle will fix this issue by removing the left bar and making all the navs more rounded, and the new mixin has the option to provide a border-radius in the future
None
-   [ ] The proposed changes are covered by unit …
> style(sidenavigation): implemented new focus styles

- .github/renovate.json
- Jenkinsfile.groovy
Instead of opening PRs for all the bumps, Renovate can create a branch and 
- if the build is green it can merge that branch into master without any reviews.
- if the build is red, it will open a PR for us to review
I added a comment in the commits to reference a JIRA
I also had to make a small change in the Jenkinsfile for it to work, otherwise we tried to publish a comment on a non-existing PR. E.g., https://jsadminbuilds.dev.cloud.coveo.com/job/react-vapor/job/renovate%252Fjest-26.x/2/console
None, no code is modified
> chore(renovate): use branch instead of PRs to avoid unnecessary reviews

- packages/react-vapor/src/components/headers/HeaderWrapper.tsx
- packages/vapor/scss/variables.scss
- Removing the `header-height` class from `HeaderWrapper` since this limits the height to `100px`
- Adjusting the `header-padding-y` to `16px`, its initial value did not provide enough padding on the top and bottom and will simply help fill the inner div spacing, no major changes will be seen.
**Padding adjustment at 5px:**
**Padding adjustment at 16px:**
**Reason for change:**
There's currently a bug that happens when the Dimensions header is under `1597px` width, the sub text will break causing a push of the title and making it too close to the navbar and not have enough padding underneath
**Bug:**
**After the changes proposed (tested locally using link with admin-ui)**
**No changes will be observed by modal heading (5px vs 16px)** …
> style(header): padding adjustment on header

- .github/renovate.json
add lockfile maintenance config to renovate. It will re-generate the pnpm-lockfile from scratch and automerge if it passes. This is useful to bump dependencies of dependencies
None
> ci: add lockfileMaintenance config to renovate

- Jenkinsfile.groovy
- packages/demo/package.json
- packages/react-vapor/package.json
- pnpm-lock.yaml
- Adding the `--no-git-tag-version` option so that we don't create 2 tags for each release
- Creating the release tag after the commit has been amended
- Added `--follow-tags` to the push command so that it pushes the commit along with its tag all at once
None
> ci: create tag for release after amend

- Jenkinsfile.groovy
- lerna.json
- packages/demo/package.json
- packages/e2eTesting/package.json
- packages/react-vapor/package.json
- packages/tokens/package.json
- packages/vapor/package.json
- pnpm-lock.yaml
27.0.1 is already published to the npm registry and so we cannot publish over it
None
> build(npm): bump to v27.0.1

- Jenkinsfile.groovy
https://coveord.atlassian.net/browse/UITOOL-147
Same change as https://github.com/coveo/admin-ui/pull/3422 but for React-Vapor
When a master build fails, it pushes a notification in the guild saying that master is broken. Its nice because everyone can know immediately that there is a problem, but its doesn't really give any clue about who should be the owner of that failure.
We now list all the commits from the current build so we have at first glance an idea of the potential owner of the failure.
None
> feat: commits + author to failing master build slackbot notifs

- packages/demo/src/components/examples/DatePickerExamples.tsx
- packages/demo/src/components/examples/DatePickerExamplesCommon.ts
- packages/react-vapor/src/components/datePicker/DatePicker.tsx
- packages/react-vapor/src/components/datePicker/DatePickerBox.tsx
- packages/react-vapor/src/components/datePicker/DatesSelection.tsx
- packages/react-vapor/src/components/datePicker/tests/DatePicker.spec.tsx
- packages/vapor/scss/components/calendar.scss
Initial bug: user could enter an invalid date range
Extra bug: While manually typing an invalid date, the `setState` triggered by `componentDidMount` would trigger an infinte loop as parent components tried to validate it and then update the component
How to test:
Datepicker:
- The bug applies to the datepicker dropdown, but worth testing in every example.
- I made a new example in the demo to mimic the bug in Log Browser (see screenshot)
- For any datepicker with `selectionRules`, if you try and manually enter a date that's outside of what's specified in its rules, then it will stay selected, use the last valid date as display (but not set it), and show a red `invalid` border
https://user-images.githubusercontent.com/22773767/139930393-12f55da7-2d0d-499f-b9fb-8f1da5897999.mov
-   [ ] The …
> fix(datepicker): added valid date check

- .deployment.config.json
`disable` key doesn't exist in the deployment config schema, its `disabled`.
none, should fix the master deployment on s3
> ci(deploy): fix typo in deployment config

- CHANGELOG.md
- packages/react-vapor/CHANGELOG.md
- packages/vapor/CHANGELOG.md
- packages/vapor/scss/controls/radios.scss
Radio card makes everything inside it disabled if the option is disabled, but we would still want to show documentation links, or at least have the option to highlight informations even if the radio card is disabled.
> Enable links in disabled radio card

- packages/react-vapor/src/components/actions/Action.tsx
- packages/react-vapor/src/components/actions/tests/Action.spec.tsx
[COM-1330]
I had to apply a specific class to a specific action to work around an issue that we have with a specific icon.
So I found `iconClass` in the props and it pretty much looked like it would fit my use case.
But the prop is completely unused, so here we go...
None, really.
[COM-1330]: https://coveord.atlassian.net/browse/COM-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(action): properly use iconClass

- packages/demo/src/OneDemoToRuleThemAll.tsx
- packages/demo/src/components/NotFound.tsx
- packages/demo/src/components/index.tsx
- packages/demo/src/demo-styling/main.scss
- packages/demo/src/index.html
- packages/demo/src/plasma/Brand.tsx
- packages/demo/src/plasma/Home.tsx
- packages/demo/src/plasma/navigation/SideNavigation.tsx
- packages/demo/src/plasma/navigation/nav-items.ts
- packages/demo/src/styles/index.tsx
- packages/react-vapor/src/components/sideNavigation/SideNavigationItem.tsx
- packages/vapor/scss/components/navigation.scss
- packages/vapor/scss/variables.scss
Added new sidenav, plus a section at the bottom for pages not included in the mockup so we still have access to them until  we can discuss where they go or if they're deprecated.
New items in the side nav have been disabled, since their pages don't exist
Also added placeholder pages for Home, Brand and NotFound. 
Links still have the `/components` or `/styles` link since rerouting is out of scope
All links should work as normal.
> feat(new navigation): added new side nav, style changes

- packages/demo/src/components/examples/TabExamples.tsx
- packages/react-vapor/src/components/tab/Tab.tsx
- packages/vapor/scss/components/tab.scss
https://coveord.atlassian.net/browse/UITOOL-306
After discussion with the tooling team and Gustavo, we agreed to put back the bold text for all tabs, not just the active one.
None
> UITOOL-306/fix active tab drop

- packages/demo/webpack.config.js
- packages/react-vapor/package.json
- packages/react-vapor/tsconfig.build.json
- packages/react-vapor/tsconfig.esm.json
- packages/react-vapor/tsconfig.json
- `main` field of `packages/react-vapor/package.json` will now point to `dist/cjs/Entry.js` 
- `module` field of `packages/react-vapor/package.json` will now point to `dist/esm/Entry.js` 
`dist` will now look like this
> build(react-vapor): distribute the main as common js

- packages/react-vapor/tsconfig.esm.json
Targeting `esnext` is a bit too eager, build tools down the line don't handle all the features well.
> fix: downgrade esm build target to es2015

- package.json
- pnpm-lock.yaml
The publish step  started failing after the aws-sdk packages bump by renovate last night so i'm returning to the previous version.
None
> revert(deps): revert to previous aws-sdk version

- packages/tokens/package.json
Making the package private while the publish issue gets fixed by npm's support.
`@coveord/design-tokens` will not be released on npm anymore
> build(tokens): make package private

- Jenkinsfile.groovy
https://coveord.atlassian.net/browse/UITOOL-351
Stop sending alert in the guild channel for master build failure.
none
> ci: remove guild channel from master build failure list

- packages/react-vapor/src/components/radio/RadioSelect.tsx
- packages/react-vapor/src/components/radio/tests/RadioSelect.spec.tsx
We need to disable certain model creation flows based on missing privileges as well as license. Each scenario needs a specific disabled tooltip string but right now the RadioSelect component forces a single string to be used for all options.
Only set disabledTooltip value on option clones if none is specified already.
> feat(radioselect): allow specific tooltip

- packages/vapor/scss/components/labeled-value.scss
The reason for this change originates from UI updates from [this](https://coveord.atlassian.net/browse/DA-6699) JIRA, but the font issue affects all usages of the `LabeledValue` component.
Use the same font size for `labeled-value` component that is used by `labeled-input` component so visually they look the same.
Currently the `labeled-value` component had a "label" font size of 12px as can be seen [here](https://vapor.coveo.com/#/legacy/LabeledValue)
By using `$form-control-label-font-size` it'll match the `labeled-input` of 13px.
Where is this font size of 13px styling coming from?
It comes from [here](https://github.com/coveo/react-vapor/blob/master/packages/vapor/scss/controls/input-field.scss#L39) which extends `.active` which comes to …
> style: labeled-value font-size to match labeled-input

- packages/demo/src/demo-building-blocs/ExampleLayout.tsx
- packages/demo/src/demo-building-blocs/PropsDoc.tsx
- packages/demo/src/demo-styling/props-doc.scss
- packages/demo/tsconfig.json
- packages/tokens/package.json
- packages/tsconfig-base.json
- pnpm-lock.yaml
Implemented a table that displays the props of a component exported from react-vapor.
Usage:
```tsx
<PropsDoc componentName='Button' />
```
You can view the result here: https://vapor.coveo.com/feature/PR-2362/index.html#/input/Buttonv2
none
> feat(demo): implement PropsDoc component

- Jenkinsfile.groovy
Following [this pr suggestion](https://github.com/lerna/lerna/issues/2788) to fix the fact that Lerna needs to be **removed** from our projects.
... 
Wait :neutral_face: 
I meant that Lerna does not support NPM automation tokens. And we need a NPM automation token beause of the new policiy about 2FA for npm.
This pr will be fine, the publish stage only run in master so  wait for it :sweat_smile: 
Should be none
> ci(jenkinsfile): add no-verify-access to lerna publish

- packages/react/src/components/tile/Tile.tsx
- packages/react/src/components/tile/tests/Tile.spec.tsx
- packages/style/scss/components/tile.scss
- packages/website/src/demo-building-blocs/ExampleLayout.tsx
- packages/website/src/demo-styling/example-layout.scss
- packages/website/src/demo-styling/home.scss
Making the title, description and href props optional on the tile component. We have a use-case in the website where we only want to display the icon in the tile.
None
> feat(tile): make title, description, href optional

- packages/website/src/demo-building-blocs/ExampleLayout.tsx
- packages/website/src/demo-building-blocs/Sandbox.tsx
- packages/website/src/demo-styling/sandbox.scss
- packages/website/src/plasma/routes/input/pages/ButtonV2.tsx
- Fixed an issue with the sandbox throwing errors if the code examples had more than one line of code 😅 
- Each sandbox can now be rendered either in horizontal mode (default) or vertical 
- Made `examples` prop optional
- "Examples" and "Related components" are not rendered anymore if there is nothing to render in those sections
- Added padding to the guidelines tab content
- Added an `icon` prop to be able to specify the thumbnail of the tile
None, it only affects the website
> feat(website): improve example layout + horizontal sandbox

- packages/react/src/components/textInput/TextInput.tsx
- packages/website/src/demo-building-blocs/ExampleLayout.tsx
- packages/website/src/demo-building-blocs/Sandbox.tsx
- packages/website/src/demo-styling/sandbox.scss
- packages/website/src/plasma/routes/input/pages/ButtonV2.tsx
- packages/website/src/plasma/routes/input/pages/TextInputExamples.tsx
Applying the new example layout to the TextInput component examples.
To test, simply navigate to the `Text Input` section in the plasma website.
None, only affects the website
> feat(textinput): apply the new example layout to the textinput examples

- packages/react/src/components/actionable-item/ActionableItem.tsx
- packages/react/src/components/actionable-item/tests/ActionableItem.spec.tsx
The `ActionableItem` component contains the `ListBox` component which has the noActive prop but we cannot access this to remove the highlight on the first item in the ActionableItem.
Setting the the ListBox component to have noActive will fix this problem.
Without this change, the item looks like it's already selected on mount (this is not what we want when using the ActionableItem)
**Before (when action clicked)**
**After (when action clicked)**
The highlighted of the first item will no longer be there
> fix(actionableitem): editing component to hide active on actionableitem component

- packages/website/package.json
- packages/website/src/FeatureFlags.tsx
- packages/website/src/OneDemoToRuleThemAll.tsx
- pnpm-lock.yaml
https://coveord.atlassian.net/browse/UITOOL-397
Using this ---> https://github.com/jamesmfriedman/flagg
This is a simple implementation for feature flags in Plasma, using the sessionStorage for the browser.
The need for Feature flags in Plasma is coming from the Search Bar development. The process is long and we want the possibility of splitting the work in multiple prs without showing the bar during it's development.
None
> UITOOL-397/implement simple feature flags

- packages/react/src/components/itemBox/ItemBox.tsx
- packages/website/src/pages/plasma-search/ResultPage.tsx
- packages/website/src/search/StandaloneSearchBar.tsx
https://coveord.atlassian.net/browse/UITOOL-401
The search is now working from anywhere in Plasma!!
I've also added a focus and blur to hide the listbox when the input is not in focus.
> /*
> * To toggle the feature flag, copy and paste those commands in the dev tool console:
> * sessionStorage.setItem('ff_plasma-search-bar', true) to show the bar
> * sessionStorage.setItem('ff_plasma-search-bar', false) to hide the bar
> * You need to reload the page for it to take effect.
> */
should be none!
> UITOOL-401/make search work from results page

- packages/website/src/building-blocs/ExampleLayout.tsx
- packages/website/src/building-blocs/VaporComponent.tsx
Setup `data-coveo-field` attributes on elements of the page just for the new layout. I figured we could create field mapping that map multiple metadata to the same field, making it easy to have different selectors for the old and the new layout.
The new webscraping configuration will look like this
```json
"metadata": {
"description": {
"type": "CSS",
"path": "[data-coveo-field='description']"
},
"title": {
"type": "CSS",
"path": "[data-coveo-field='title']"
},
"legacy_description": {
"type": "CSS",
"path": "h4.admin-description::text"
},
"legacy_title": {
"type": "CSS",
"path": ".panel-header h4.bolder::text"
}
}
```
None
-   [ ] …
> fix(website): enable crawling of description on the new layout

- packages/website/src/pages/Home.tsx
I noticed while looking into the content browser that the crawler had found some broken routes. Those routes could be returned by the search which is not something we want.
none
> fix(website): remove broken urls from home page

- packages/website/src/building-blocs/Tile.tsx
- packages/website/src/pages/SearchResultPage.tsx
- packages/website/src/search/engine/EngineProvider.tsx
Make sure thumbnails are crawled and that they can be used when rendering search results.
None
> feat(website): crawl thumbnails and display them in search results

- packages/website/src/Index.tsx
Simple js to redirect on `plasma.coveo.com` when loading the `vapor.coveo.com`. It should keep all the rest of the path
None
> fix(website): redirect to plasma when loading vapor

- packages/website/src/building-blocs/Tile.tsx
- packages/website/src/pages/Home.tsx
- packages/website/src/styles/tile.scss
When a tile has no description, it should not have any vertical slide behaviour because there is nothing to show in there anyway.
Before
https://user-images.githubusercontent.com/35579930/152229940-bfe61c8e-b2dd-48d1-b521-6542d8019fe1.mp4
After
https://user-images.githubusercontent.com/35579930/152229953-ea52ef93-c02d-4d16-90c7-1e1d6870c64d.mp4
> refactor(website): remove drawer behaviour on tile without description

- packages/react/src/components/pagination/TablePagination.tsx
- packages/react/src/components/table-hoc/TableWithNewPagination.tsx
Remove the default totalPage value from 1 to undefined, since it was causing a bug in the _i think_ only TableWithUrlState table of the admin. That way, a user can copy-paste an url to a specific date and page in the activity browser table.
If you want to test it, you will have to link plasma/react to the admin repo (please do and verify that the other tables are not broken that way) :) 
will fix https://coveord.atlassian.net/browse/ADUI-7800
> fix(tablepagination): -default value of totalPages

- packages/react/src/components/slider/SliderSelectors.ts
- packages/react/src/components/slider/tests/SliderSelectors.spec.tsx
Fix getSlider selector: prevent it from throwing an error when `sliders` key is undefined in the state (happens in the unit tests of the admin-ui).
None
> fix(slider): prevent slider selectors to throw when sliders is not defined

- packages/react/src/components/toast/Toast.tsx
- packages/website/src/building-blocs/PropsDoc.tsx
- packages/website/src/pages/Home.tsx
- pnpm-lock.yaml
Inside of the props table, 
1. display the default value when it is in the jsdoc
2. display the deprecated props with the associated comment
None
> feat(props): display deprecated and default props

- packages/website/src/building-blocs/PropsDoc.tsx
- packages/website/src/building-blocs/Sandbox.tsx
- packages/website/src/building-blocs/useTypescriptServer.ts
- packages/website/src/index.html
- packages/website/src/styles/loading-screen.css
Instead of loading the plasma and typescript d.ts files each time we load a sandbox I changed the code to load them once and re-use the same promise. It makes the navigation between sandbox a lot smoother. I also added some loading indicators
None, only impacting the demo website
> fix(website): improve UX when switching between sandbox pages

- packages/react/src/components/blankSlate/BlankSlate.tsx
- packages/react/src/components/blankSlate/tests/BlankSlate.spec.tsx
- packages/react/src/components/iconCard/IconCard.tsx
- packages/react/src/components/iconCard/tests/IconCard.spec.tsx
- packages/react/src/components/svg/SvgChild.tsx
We currently have an issue that prevents us from putting some SVG in the plasma repository because it is open source.
By allowing the use of custom `<svg>` tags in the components that previously allowed only svgNames we can keep those icon in a private repository.
I created a generic component that allow us to re-use the same logic in multiple components
None
> feat(blankslate, icon-card): allow usage of custom svgs

- packages/react/src/components/breadcrumbs/Breadcrumb.tsx
- packages/react/src/components/breadcrumbs/tests/Breadcrumb.spec.tsx
- packages/react/src/components/headers/BreadcrumbHeader.tsx
- packages/react/src/components/headers/HeaderWrapper.tsx
- packages/react/src/components/headers/TabsHeader.tsx
- packages/website/src/pages/navigation/BreadcrumbsExamples.tsx
https://coveord.atlassian.net/browse/UITOOL-447
BREAKING CHANGES: `defaultLinkPath` was removed from the Breadcrumb props
> UI tool 447/cleanup breadcrumbs examples

- packages/style/package.json
The `d.ts` files are not exposed to the npm package so there is no types when using the package from outside the plasma mono-repo
None
> fix(plasma-style): expose d.ts files in the npm packages

- packages/website/src/building-blocs/ExampleLayout.tsx
- packages/website/src/styles/example-layout.scss
Applying some UI tweaks to the component layout header suggested by the UX team.
Before
After
none
> feat(website): make small style tweaks to the component page

- .deployment.config.json
> If you configure CloudFront to compress objects and the origin also compresses objects, the origin should include a Content-Encoding header, which indicates to CloudFront that the object is already compressed. When a response from an origin includes the Content-Encoding header, CloudFront does not compress the object, regardless of the header’s value. CloudFront sends the response to the viewer and caches the object in the edge location.
-- [AWS Docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html)
When setting content-encoding to `gzip` ourselves on the s3 files (the origin), it tells CloudFront to send the file to the viewer directly without handling compression. That seems counter productive, and it simplifies our deployment process to …
> fix(deploy): remove gzip content enconding phase

- TokensExtraction.groovy
Added a `LIBRARIES` parameter to the tokens extraction job to target specific figma libraries
When triggering the tokens extraction job, you will be prompted with this interface, which allows to choose only specific figma libraries to extract design tokens from.
None
> feat(tokens): handle jenkins job parameter for libraries

- packages/website/package.json
Since the move to nextjs, we had to manually open that localhost url.
None
> feat(website): automatically open the browser on start

- packages/react-icons/.gitignore
- packages/react-icons/README.md
- packages/react-icons/bin/index.js
- packages/react-icons/package.json
- packages/react-icons/tsconfig.json
- pnpm-lock.yaml
Create a new package called [`@coveord/plasma-react-icons`](https://github.com/coveo/plasma/tree/UITOOL-463/plasma-react-icons/packages/react-icons#readme). This package aims to replace the `Svg` component of `@coveord/plasma-react`.
Example of usage
```ts
import {ZombieSize32Px} from '@coveord/plasma-react-icons';
<ZombieSize32Px className="icon mod-stroke mod-black mod-72" />
```
None for now
> feat(react-icons): create the react-icons package

- packages/react/src/components/svg/index.ts
There was a little oversight when adding the SVGChilds, nothing is exported from Plasma so you can't use the interfaces outside of Plasma
No
> fix(svg): export SvgChild

- packages/website/src/pages/Search.tsx
The plasma.coveo.com was reindex and now to make the search work we need to remove that workaround on the click uri.
none
> fix(website): remove click uri workaround on search results

- packages/website/src/building-blocs/Tile.tsx
- packages/website/src/pages/Search.tsx
- packages/website/src/search/NoSearchResultTemplate.tsx
https://coveord.atlassian.net/browse/UITOOL-402
Adding analytics on No result after using the search bar and on document open in the search results.
More analytics will come in another pr when I change the search bar for the Atomic one :eyes: 
None
> feat(analytics): add analytics on noResult and documentOpen

- packages/react/src/components/collapsible/CollapsibleContainerConnected.tsx
- packages/react/src/components/collapsible/tests/CollapsibleContainerConnected.spec.tsx
Jira: https://coveord.atlassian.net/browse/SPAAS-1164
This update is simply to add the `onClick` property to the `CollapsibleContainerConnected` component, so it can be passed to the `CollapsibleConnected` connected after.
Because it's an optional property, I don't think it can create a breaking change.
> feat(collapsible-container-connected): add optional onClick prop

- packages/website/src/SideNavigation.tsx
- packages/website/src/building-blocs/Tile.tsx
- packages/website/src/building-blocs/useTypescriptServer.ts
- packages/website/src/pages/Search.tsx
- packages/website/src/pages/_app.tsx
By default Next preload all the pages accessible via a `Link` tag. Since we have all the pages in our menu it preloads everything which seem to cause issues for some people.
See https://web.dev/route-prefetching-in-nextjs/ for more details
Website might be a bit slower when navigating between pages
> fix(website): do not preload pages with Nextjs

- packages/react-icons/bin/index.js
- packages/react/package.json
- packages/react/src/components/badge/Badge.tsx
- packages/react/src/components/badge/tests/Badge.spec.tsx
- packages/website/src/pages/feedback/Badge.tsx
- packages/website/src/pages/layout/IconCard.tsx
- pnpm-lock.yaml
- created the `Icon` type in plasma-react-icons
- added `img` ARIA role on all icons with a label
- switch out Svg for plasma-react-icon in badge component
Badge icon prop now expects an Icon from plasma-react-icons
> Remove Svg from Badge

- packages/react-icons/bin/index.js
- packages/react/package.json
- packages/react/src/components/badge/Badge.tsx
- packages/react/src/components/badge/tests/Badge.spec.tsx
- packages/react/src/components/collapsible/CollapsibleConnected.tsx
- packages/react/src/components/collapsible/CollapsibleToggle.tsx
- packages/react/src/components/collapsible/tests/CollapsibleConnected.spec.tsx
- packages/react/src/components/collapsible/tests/CollapsibleInfoBox.spec.tsx
- packages/react/src/components/collapsible/tests/CollapsibleToggle.spec.tsx
- packages/react/src/components/table-hoc/TableRowConnected.tsx
- packages/react/src/components/table-hoc/tests/TableRowConnected.spec.tsx
- packages/react/tsconfig.json
- packages/style/scss/components/navigation.scss
- packages/website/src/pages/feedback/Badge.tsx
- packages/website/src/pages/layout/Collapsible.tsx
- packages/website/src/pages/layout/IconCard.tsx
- packages/website/src/styles/main.scss
- pnpm-lock.yaml
Switch out the Svg component for the icons from plasma-react-icons in the CollapsibleToggle
component
`CollapsibleToggleProps` changed, `svgClassName` is no longer a prop.
Open the demo and look at the collapsible sections of the nav, also navigate to `Collapsible` component.
> feat(react): use react-icons in CollapsibleToggle

- packages/react/package.json
- pnpm-lock.yaml
When trying to import plasma-react in a package that doesn't have `@swc/helpers` as a dependency it breaks.
None
> build(react): @swc/helpers is a dependency not a devDependency

- build/publishNewVersion.mjs
There is this error when publishing from master
```bash
10:56:36  Bumping root, @coveord/plasma-react-icons, @coveord/plasma-website to version 38.13.0
10:56:39  Pushing version v38.13.0
10:56:40  
10:56:41  
10:56:41  Publishing version v38.13.0
10:56:42  No projects matched the filters in "/home/jenkins/slaves/workspace/plasma_master"
[Pipeline] sh
10:56:43  + node -p -e require(`./package.json`).version;
```
None
> ci: fix publish

- packages/react/src/components/filterBox/FilterBox.tsx
[ADUI-7861](https://coveord.atlassian.net/browse/ADUI-7861)
This fixes an issue where dropdowns with filters when opened would not auto focus on the filter.  It is not quite clear how it broke but it appears to be from a change in this [commit](https://github.com/coveo/plasma/commit/4b5a7cc1d67352f4490f53296b6d5bde91c6eb8f).  After some discussion, if this fixes it in the demo link, it should be merged.  Afterwards, I will create a PR to update the release branch.  
I will be creating a JIRA with more details on my findings that will later be used to assess and we can figure out what changes we'll make later.
How to test this:
- On the demo branch go to the "Select - Single" page
- Open up the "A single select with filter" dropdown
- Confirm that the Filter input is focused on
None.  It …
> fix: autofocus for filterbox

- build/publishNewVersion.mjs
Publish to NPM before pushing to git
Remove the force option, it wasn't useful and made things more complex
None
> build(publish): change order of the publish

- packages/react/src/components/browserPreview/BrowserPreview.tsx
- packages/react/src/components/browserPreview/BrowserPreviewEmpty.tsx
- packages/react/src/components/browserPreview/tests/BrowserPreview.spec.tsx
- packages/style/scss/components/browser-preview.scss
- packages/website/src/pages/layout/BrowserPreview.tsx
Switch out the `Svg` for `plasma-react-icons` in `BrowserPreview` component where I could (the `arrowLeftReturn` icon does not exist yet in the new iconography)
Before
After
None
> refactor(react): remove Svg from BrowserPreview

- packages/react/src/components/collapsible/CollapsibleInfoBox.tsx
- packages/react/src/components/collapsible/tests/CollapsibleInfoBox.spec.tsx
Switch out the `Svg` component for the icon from `plasma-react-icons` in `CollapsibleInfoBox`
Before
After
none
> refactor(react): remove Svg from CollapsibleInfoBox

- packages/react/src/components/info-token/InfoToken.tsx
- packages/react/src/components/info-token/tests/InfoToken.spec.tsx
- packages/react/src/components/textInput/tests/TextInput.spec.tsx
- packages/react/src/components/toast/Toast.tsx
- packages/react/src/components/toast/tests/Toast.spec.tsx
- packages/style/scss/components/info-token.scss
- packages/style/scss/components/toast.scss
Switch out the Svg component for plasma-react-icons in the InfoToken component
Before
After
None
> refactor(react): use plasma-react-icons in InfoToken

- packages/react/src/components/chart/ChartTooltip.tsx
The DropPod uses the ref to detect where the tooltip should be positioned. This PR fixes the error it threw since it could not detect the position of the element
To test the fix, open the demo, go in the Chart component and hover data in the 2nd chart. You should see the tooltip
None
> fix(chart): dropPod throws an error when there is no ref

- packages/react/src/components/input/Input.tsx
- packages/react/src/components/multiValueInputs/MultiValuesInput.tsx
- packages/react/src/components/multilineBox/MultilineBoxSelector.ts
- packages/react/src/components/multilineBox/hoc/MultilineBoxWithRemoveButton.tsx
- packages/react/src/components/multilineBox/tests/MultilineBoxWithRemoveButton.spec.tsx
The `MultiValuesInput` had the following problems that needed to be fixed:
- Pressing `Enter` in any of the input lines would remove that line even if it had no remove button displayed.
- The last entry, which is usually an empty new line useful to add a new row could be deleted by clicking on the remove button.
- Copy pasting a value using only the mouse (right click > paste) would not trigger a new line, only the keyboard could.
All of those are fixed by this PR + the `Input` and `InputConnected` are marked as deprecated.
None
> MultiValuesInput fixes

- packages/website/src/building-blocs/PageHeader.tsx
Force choices for section name in the pageLayout 
Before, mistakes were made
Now mistakes are not possible :zap: 
should be none xD
> feat: writing down section names by hand each time is problematic

- packages/website/src/building-blocs/PropsDoc.tsx
The props table will now display jsdocs comments about parameters of a function
None
> feat(website): display jsdocs params in props table

- packages/website/next.config.js
- packages/website/src/building-blocs/Sandbox.tsx
- packages/website/src/building-blocs/useTypescriptServer.ts
- packages/website/src/pages/_app.tsx
- packages/website/tsconfig.json
- packages/website/types/custom/index.d.ts
Allow us to import the examples from another file instead of inlining them.
It comes with a lot of good stuff: automatic imports, syntax validation, code formating, ... 
Add a `.example.tsx` file in the `src/examples/some-folder` folder and add an import like this in your page
`import code from '@examples/some-folder/myExample.example.tsx';` (note the `.example.tsx` extension)
`code` will be a string
None
> feat(website): allow import of examples from files

- packages/react/src/components/syncFeedback/SyncFeedback.tsx
- packages/website/src/examples/SyncFeedback/SyncFeedback.example.tsx
- packages/website/src/examples/SyncFeedback/SyncFeedbackLabel.example.tsx
- packages/website/src/pages/feedback/SyncFeedback.tsx
Added JsDoc on SyncFeedback props
Updated SyncFeedback demo layout
I formatted the example as a table, do you like it?
> refactor(website, sync feedback): update demo layout

- packages/react/src/components/calendar/Calendar.tsx
- packages/react/src/components/calendar/CalendarDay.tsx
- packages/react/src/components/calendar/tests/Calendar.spec.tsx
- packages/react/src/components/calendar/tests/CalendarConnected.spec.tsx
- packages/react/src/components/datePicker/DatePickerActions.ts
- packages/react/src/components/datePicker/DatePickerBox.tsx
- packages/react/src/components/datePicker/DatePickerReducers.ts
- packages/react/src/components/datePicker/DatesSelectionConnected.tsx
- packages/react/src/components/datePicker/tests/DatePickerActions.spec.ts
- packages/react/src/components/datePicker/tests/DatePickerDropdownConnected.spec.tsx
- packages/react/src/components/datePicker/tests/DatePickerReducers.spec.ts
- packages/style/scss/components/calendar.scss
Remove un-used color prop in the calendar component and added CSS class for the selected comparison date for the UA date picker
Removed the `color` prop from calendar.tsx component (not used since rebranding)
> style(prop): remove calendar color prop

- packages/react/src/components/button/Button.tsx
- packages/react/src/components/button/tests/Button.spec.tsx
- packages/react/src/components/editor/tests/CodeEditor.spec.tsx
- packages/website/src/pages/form/Button.tsx
https://coveord.atlassian.net/browse/UITOOL-587
The buttons with an hyperlink + an icon had this weird padding on top cause by the `btn-container` class. I just removed it and added an new example to keep track on the style :+1: 
Before:
After: 
None
> fix(button): fix icon alignment in button with href

- packages/react/src/components/modal/ModalHeader.tsx
The title of the modal was a string but it should be a reactNode
I don't think so? :thinking:  I mean, it was breaking when it was a string so now it's not broken? :woman_shrugging: :laughing: 
> fix(modal): title is now a reactNode

- packages/react/jest/entry.tsx
- packages/react/jest/utils.tsx
- packages/react/src/components/textInput/TextInput.tsx
- packages/react/src/components/textInput/tests/TextInput.spec.tsx
- packages/react/src/components/textInput/useTextInput.ts
Make sure that isDirty is handled well even when setting a defaultValue.
Before
https://user-images.githubusercontent.com/35579930/161303399-b2294c06-9a70-423b-b60e-70729a7533c2.mov
After
https://user-images.githubusercontent.com/35579930/161303423-9684bae5-1b9b-45fe-b085-e4fd98ea1644.mov
None
> fix(plasma-react): better management of isDirty in TextInput

- TokensExtraction.groovy
Fixing this: https://coveord.atlassian.net/browse/UITOOL-612
The library name is actually [`Icons`](https://github.com/coveo/plasma/blob/master/packages/tokens/bin/lib/mappings.ts#L1), not `ICONS`
None
> fix(plasma-tokens): change ICONS for Icons in the jenkins params

- packages/react/src/components/iconCard/IconCard.tsx
- packages/react/src/components/iconCard/tests/IconCard.spec.tsx
- packages/react/src/utils/TypeUtils.ts
- packages/react/src/utils/index.ts
- packages/style/scss/components/card.scss
- packages/style/scss/components/icon-card.scss
- packages/website/src/pages/layout/IconCard.tsx
On the IconCard component:
- Modified the title prop type from `string` to `ReactNode`
- Added props
```typescript
/**
* Whether to place the badges above the title.
*/
placeBadgesAbove?: boolean;
/**
* Classes to apply to the card button element.
*/
cardClasses?: string[];
```
- Added `mod-fixed-size` class in css for use with the cardClasses prop.
| Goal | Result (using the new prop update) |
|---|---|
|<img width="468" alt="Screen Shot 2022-04-01 at 4 38 06 PM" src="https://user-images.githubusercontent.com/16785453/161338018-58b1ce5a-7ce5-4c48-8cb9-9999b77cafc3.png">|<img width="474" alt="Screen Shot 2022-04-01 at 5 29 19 PM" src="https://user-images.githubusercontent.com/16785453/161343889-2565484f-915d-40ae-97ea-792cf9e280ee.png">|
There shouldn't be any if I did it right.
-   [ ] …
> feat(card): added props to iconcard

- .deployment.config.json
Following this [Slack thread](https://coveo.slack.com/archives/CBP3GTFTQ/p1649691790759329), I removed the `public-read` acl on the ressources since it's not needed anymore and it blocks Jenkins from deploying
None
> chore(style, deploy): fix permissions on S3 bucket for CDN files

- packages/react/src/components/loading/components/TableLoading.tsx
- packages/react/src/components/table-hoc/TableHOC.tsx
- packages/react/src/components/table-hoc/tests/TableHOC.spec.tsx
Improve accessibility of tables when they are loading.
You'll be able to do `await waitForElementToBeRemoved(screen.getByRole('status'));` to make sure your table is not loading anymore
None
> fix(react, table): improve accessibility of loading tables

- packages/react-icons/bin/index.js
- packages/react-icons/package.json
- pnpm-lock.yaml
While debugging in another package we saw that loading the icon package could take multiple seconds in Jest (using commonJs). To avoid this we wrap the component in a Loadable component. It should be transparent when using the library.
The d.ts did change a bit, if developer were importing the component from /dist/some/path/sizeXPx it now use a default export
> feat(icons): lazy load react-icons

- packages/style/scss/components/navigation.scss
When a navigation element is locked in the admin (for lack of license access), the user can still click on the element. I've added a quick css trick just so that the click event does not go through (noticed it while working on https://coveord.atlassian.net/browse/UA-6628)
Go in `weirdorgfyxitz4w` and Data Exports should be locked, but you can still click on it (and there is no redirection whatsoever)
> fix(navigation): disable the click event on locked navigation

- package.json
- packages/react/package.json
- packages/style/package.json
- packages/tokens/package.json
- packages/website/package.json
- pnpm-lock.yaml
Instead of manually sorting stuff inside package.json files, I added something ([`sort-package-json`](https://www.npmjs.com/package/sort-package-json)) that will automatically sort package.json files on pre-commit when they are staged. Now all our package.json files will always stay ordered in the same way.
None
> ci(lint): automatically sort package.json files

- packages/website/src/building-blocs/Sandbox.tsx
- packages/website/src/pages/_app.tsx
Use the new jsx transform to render the content of the sandboxes.
None
1. Navigate to the Single Select page
2. The `_react` undefined error should not pop-up
3. The last example should render properly
> fix(website): _react is not defined in sandbox

- packages/style/scss/tables/pagination.scss
https://coveord.atlassian.net/browse/UITOOL-663
The pagination is using the flat-select css classes and when I did the MVP for the flat select, some on the colors for the font were changed. I fixed them 👍 
To test, go in the Table page and scroll down until you get to the example with pagination.
Before:
After:
None
> fix(pagination): fix font color when selected

- packages/website/docs/Button.md
Updated the guidelines related to the order of the buttons that appear in the header.
After much investigation, we came to the decision that that the primary button for this group of button should remain on the left side of the group of buttons.
The principal reason for this change of guidelines is that the we wanted to make sure that the order of actions was consistent with their order importance and the logical reading order.
Since we have a couple of occurrences where the header contains additional secondary actions grouped under the […] (more/actionable items) button, having that button on the right felt wrong.
Read the detailed guidelines here for additional details: https://coveord.atlassian.net/wiki/spaces/UX/pages/3063545872/Header+button+ordering
-   [ ] The proposed changes are …
> Button guidelines order

- packages/react/src/components/checkbox/Checkbox.tsx
- packages/react/src/components/checkbox/tests/Checkbox.spec.tsx
- packages/react/src/components/input/Input.tsx
- packages/react/src/components/input/tests/Input.spec.tsx
- packages/react/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx
- packages/style/scss/controls/checkboxes.scss
Issue we're trying to fix:
- Added prop to Input to set classes on the Tooltip`<span></span>` element as putting it in between the container and the content would break the styling.
- Modified css rule to account for possible tooltip being inserted.
ex:
- checkbox container has a flex display
- span wrapping the content breaks the arrangement and clashes with some css settings which function by specifying a descendant tree.
After change
> fix(checkbox): fix checkbox disabled tooltip

- packages/react/src/components/input/Input.tsx
- packages/react/src/components/textInput/TextInput.tsx
`autoComplete` prop can still be set to something else, but by default it will be turned off on all inputs.
autoComplete behaviour provided by the browser might stop working
> feat(react): set autocomplete off on all input as default

- build/publishNewVersion.mjs
The way PNPM works changed and now it doesn't bump the root package.json version. So in this PR I rely on the tag instead
None
> chore(publish): fix publish script

- packages/react/src/components/editor/CodeEditor.tsx
- packages/react/src/components/editor/JSONEditor.tsx
- packages/react/src/components/editor/JSONEditorConnected.tsx
- packages/react/src/components/editor/tests/JSONEditor.spec.tsx
- packages/react/src/components/editor/tests/JSONEditorConnected.spec.tsx
Fixes [ADUI-7921](https://coveord.atlassian.net/browse/ADUI-7921) and accidentally fixed [UITOOL-646](https://coveord.atlassian.net/browse/UITOOL-646)
- (refactor) JSONEditorConnected converted to Function Component, doing away with `mapDispatch`/`mapState`.  I did this change as part of it as it was a simple component and I find it easier to read.
- ADUI-7921 value prop will not be overridden by Redux - the `mapState` had a `value`, because the initial value was `''` from the selector, it was evaluating on an empty string before updating again from the selector, but whether to show the error was not fired, so it would show it as invalid.
- UITOOL-646 Fixes the Plasma website where the code editor wasn't synced with what was displayed in the JSON editor.
- I moved the default `{}` from …
> fix(plasma-react): value prop will no longer display syntax error

- Jenkinsfile.groovy
- build/getLastTag.mjs
- build/publishNewVersion.mjs
- package.json
Now the bump is using the tag instead of relying on the root package.json and its version
None, only impacts version bump
> fix(publish): deployment package version

- packages/style/scss/components/navigation.scss
reverting this https://github.com/coveo/plasma/pull/2669. instead I used the disabled props from the SideNavigationItem and it works like a charm
> fix(navigation): revert css style for state-locked nav

- packages/react/src/components/badge/Badge.tsx
Removed the extra padding when using an icon-only badge
Before
After
None
> fix(react): remove extra padding for icon only badge

- packages/react/src/components/dropdownSearch/MultiSelectDropdownSearch/DraggableSelectedOption.tsx
- packages/react/src/components/select/tests/MultiSelectConnected.spec.tsx
https://coveord.atlassian.net/browse/UITOOL-696
RemoveOnClick prop was not sent for MultiSelectConnected with sortable prop (rendering DraggableSelectedOption)
Use the select-multi component in plasma and copy paste this in the sandbox
```
import {MultiSelectConnected} from '@coveord/plasma-react';
export default () => (
<MultiSelectConnected
id="mutli-select-1"
items={[
{value: 'one', displayValue: 'Option 1', selected: true},
{value: 'two', displayValue: 'Option 2'},
{value: 'three', displayValue: 'Option 3'},
]}
sortable
/>
);
```
The clear button on selected item in the multi select should not work right now (but is fixed in this pr)
-   [ ] …
> fix(draggableselectedoption): removeOnClick prop was not defined

- packages/react/src/components/subNavigation/SubNavigation.tsx
- packages/react/src/components/subNavigation/tests/SubNavigation.spec.tsx
- packages/style/scss/components/sub-navigation.scss
- packages/style/scss/variables.scss
- packages/website/src/examples/SubNavigation/custom.example.tsx
- packages/website/src/examples/SubNavigation/customWithDesc.example.tsx
- packages/website/src/examples/SubNavigation/defaultSelected.example.tsx
- packages/website/src/examples/SubNavigation/main.example.tsx
- packages/website/src/pages/navigation/SubNavigation.tsx
- Adjust the default padding of the existing sub nav `7px` -> `16px` as per Gustavo's request
- Add an option to add `description` in the SubNavigation component using a slider to appear when selected
- When a user utilizes the `description` in the navItems, the component will style the labels if it is a `string`, otherwise it respects the `ReactNode` rule the user puts on the tab
- UX padding and specification has been tweaked with @guscoveo 
This is the initial change needed for the upcoming UX updates.
- None - as the `description` prop is completely optional
https://user-images.githubusercontent.com/66333175/168903927-a06f544f-3552-4217-a1d9-0b70d263e132.mp4
Styling of all the tabs change automatically when a description is detected …
> feat(subnav): add a description in subnav

- build/publishNewVersion.mjs
When running `node build/publishNewVersion.mjs --dry --bump prerelease --tag next --branch next` locally,
output before
```
Last tag: v41.5.1-next.1
Bumping root to version 41.5.1-next.2
Would have called pnpmPublish with the following arguments:
pnpmPublish(v41.5.1-next.1, true, true)
```
output after
```
Last tag: v41.5.1-next.1
Bumping root to version 41.5.1-next.2
Would have called pnpmPublish with the following arguments:
pnpmPublish(v41.5.1-next.1, next, next)
```
None
> ci: fix the publish step for the next branch

- packages/react/src/components/loading/LoadingSpinner.tsx
- packages/react/src/components/loading/tests/LoadingSpinner.spec.tsx
- packages/react/src/components/searchBar/SearchBar.tsx
- packages/style/scss/components/loading.scss
- packages/website/src/pages/feedback/Loading.tsx
Before
After
Added the possibility of have loading spinners of different sizes
None
> fix(searchbar): make the loading spinner smaller in the search bar

- packages/react/src/components/limit/Limit.tsx
- packages/react/src/components/limit/tests/Limit.spec.tsx
Somehow when the limit value was zero, the limit label was removed. I'm not sure why that was the case, but I removed that behaviour.
Before
After
None
> fix(react): make sure a limit of 0 renders the limit label

- packages/react/src/components/badge/Badge.tsx
- packages/style/scss/components/badge.scss
- packages/website/src/examples/Badge/Badge.example.tsx
- packages/website/src/examples/Badge/BadgeSmall.example.tsx
There's was a sneaky breaking change with the revamp badges. By removing the default value for the type, it allows the existing badge using directly the css classes to keep their colors.
mod-information also make a come back because it's currently used in the admin.
none
> fix(badges): adding back information type + remove breaking change

- packages/react/src/components/dragAndDrop/DnDContainer.tsx
- packages/react/src/components/dropdownSearch/MultiSelectDropdownSearch/DraggableSelectedOption.tsx
- packages/react/src/components/multilineBox/hoc/MultilineBoxWithDnD.tsx
- packages/react/src/components/multilineBox/tests/MultilineBoxWithDnD.spec.tsx
- packages/react/src/components/select/MultiSelectConnected.tsx
- packages/react/src/components/select/tests/MultiSelectConnected.spec.tsx
Problem:
https://user-images.githubusercontent.com/35579930/170296843-6481ea0c-288b-41dd-96ff-ff2fbfd10edd.mp4
After this change, you should not be able to drag items across different instances of MultiLineBox and MultiSelectConnected anymore
None
> fix(react): prevent dragging stuff across different components

- packages/style/scss/controls/dropdown.scss
https://coveord.atlassian.net/browse/UITOOL-723
I noticed that the focus style on the button dropdown for the single select did not had the blue border so i'm adding it.
This is to keep consistency with other forms components
Before:
After:
None
> fix(dropdown btn): fix focus style for btn dropdown

- packages/style/scss/components/toast.scss
https://coveord.atlassian.net/browse/UITOOL-731
I noticed in the admin that when the title in the toast has a certain lenght, the space between the title and the X icon is existent 😆 
Adding a gap fix that issue 😄 
Before:
After:
None
> fix(toast): add gap in toast-title

- packages/react/src/components/button/Button.tsx
- packages/react/src/components/button/tests/Button.spec.tsx
- packages/style/scss/components/loading.scss
- packages/style/scss/elements/btn.scss
- packages/style/scss/guide.scss
- packages/style/scss/tools/loading.scss
- packages/website/src/examples/button/Button.example.tsx
- packages/website/src/examples/button/Disabled.example.tsx
- packages/website/src/examples/button/IconAndLink.example.tsx
- packages/website/src/examples/button/Loading.example.tsx
- packages/website/src/examples/button/Prepend.example.tsx
- packages/website/src/examples/button/Primary.example.tsx
- packages/website/src/examples/button/Small.example.tsx
- packages/website/src/pages/form/Button.tsx
Added `isLoading` props on buttons to show `LoadingSpinner` component.
NO
> feat(react, button): add new loading option

- .npmrc
PNPM now throw an error when there are missing peer dependencies. This modification will fix Renovate PRs
None
> build: fix exit code when installing with pnpm

- packages/style/scss/utility/flex.scss
Adds new CSS class that gives flex `align-items: baseline`.  I am using this in an upcoming feature and it could be added to Plasma.
None
> style: add CSS class for align-items: baseline

- packages/style/scss/components/tooltip.scss
✅ Closes: 8020
- Adjusted the positioning of arrow by adding their respective positions back to 50% - this will resolve the backbone component tooltips with the arrow being misaligned.
| --- | ----------- |
| ![CleanShot 2022-06-21 at 13 29 30](https://user-images.githubusercontent.com/66333175/174861468-a18501b7-47ac-4cef-8200-44566733b105.png) | ![CleanShot 2022-06-21 at 13 04 03](https://user-images.githubusercontent.com/66333175/174861377-06ac4de3-db7b-45de-86cb-6f4b39fad36c.png) 
You can test this by linking up Admin-UI and Plasma and go to the following panels reported in [ADUI-8020](https://coveord.atlassian.net/browse/ADUI-8020).
Tooltips in UA are affected by this change and will be fixed with this PR.
- There should be none
-   [ ] The proposed changes are …
> fix(tooltip): arrow adjustment on position

- .github/renovate.json
https://docs.renovatebot.com/configuration-options/#internalchecksfilter
> If you combine stabilityDays=3 and internalChecksFilter="strict" then Renovate will hold back from creating branches until 3 or more days have elapsed since the version was released.
None
> chore(deps): make renovate less eager to update packages

- packages/react/README.md
- packages/react/jest/utils.tsx
- packages/react/src/Defaults.ts
- packages/react/src/components/drop/DropPod.tsx
- packages/react/src/components/drop/tests/DropPod.spec.tsx
- packages/react/src/components/popover/Popover.tsx
- packages/react/src/components/popover/tests/Popover.spec.tsx
- packages/website/src/pages/_app.tsx
- packages/website/src/pages/_document.tsx
When using a dropdown inside a popover, it would toggle closed the whole popover when selecting a dropdown value.
To test in the demo:
1. copy the following code in a sandbox
2. try selecting a value in the dropdown inside the popover (the popover shouldn't close)
3. try removing the `hasDropdowns` prop and do step 2 (popover closes)
```tsx
import { Popover, SingleSelectConnected, Button } from '@coveord/plasma-react';
import { useState } from 'react';
export default () => {
const [isOpen, setOpen] = useState(false);
return (
<Popover
attachment="top left"
targetAttachment="bottom left"
isOpen={isOpen}
onToggle={setOpen}
hasDropdowns
>
<Button>Toggle</Button>
<div className='p3'>
<SingleSelectConnected
id="single-select-1"
items={[
{ value: 'one', displayValue: 'Option 1' },
{ value: …
```
> feat(react): allow using dropdowns inside popover

- packages/react/src/components/select/SingleSelectConnected.tsx
- packages/react/src/components/select/tests/SingleSelectConnected.spec.tsx
Small fix related to #2798, it was calling the method on mount
None
> fix(react, single select): call onSelectOptionCallback if there is a selected option

- packages/react/src/components/select/SingleSelectConnected.tsx
Follow up on the conversion of the SingleSelect to a FunctionComponent. Now that it's a function the Toggle is re-declared every time which might causes issues. The main change is the use of the useMemo, the rest is just a bit of cleanup
None
> fix(react, single select): memoize the button

- build/getLastTag.mjs
- build/publishNewVersion.mjs
- package.json
- pnpm-lock.yaml
https://coveord.atlassian.net/browse/UITOOL-829
This is an attempt to make sure we always publish all packages not published yet on NPM.
I'm simply removing the `--filter` option from the pnpm command.
Expected behavior --->
We'll see if it works 🤞 
None
> chore: 🤖 bump semantic-monorepo-tools

- packages/react/src/components/itemBox/ItemBox.tsx
expand the itembox to full width
✅ Required for: PLEX-77
Itembox to have `full-content-x`
This is required for the changes needed in PLEX-77 where we would like to add an SVG and badge to the org picker. With this change, it will allow us to create a div element and flex it according to the design.
There should be no changes observed in the Itembox
Before:
After:
none
> feat: 🎸 itembox apply full-content-x

- packages/react/src/components/info-token/InfoToken.tsx
- packages/react/src/components/info-token/tests/InfoToken.spec.tsx
Added the possibility to pass classes directly to the svg. So that the look of it can be overriden.
(Need to override color on svg)
:no_entry: 
> [MLX-170] fix(infotoken): allow passing classes to override svg properties

- packages/react/src/components/drop/DropPod.tsx
- packages/react/src/components/drop/tests/DropPod.spec.tsx
https://coveord.atlassian.net/browse/ADUI-8247
We have an issue in the admin where the Single select gets an error when trying to set the maxWidth value.
To patch this issue, i'm checking if the calculated value is a NaN and if so, I force a fallback value (I picked 850px but it could be bigger if needed ? 🙈 )
I'm prenneuse of better idea also 😅 
None
> fix: 🐛 adding a fallback when maxWidth is a NaN

- packages/style/scss/controls/inputs.scss
[UITOOL-875](https://coveord.atlassian.net/browse/UITOOL-875?atlOrigin=eyJpIjoiODNhNGY5MDYyOTkwNDQ3Yzk5YmMxZDBhNjUyNzA1NWQiLCJwIjoiaiJ9)
Removing the border radius causing issues in admin-ui - there should be no noticeable change in any of the inputs.
I linked this locally and briefly checked for the inputs and they seem to be O.K
> fix(style): inputs style remove border radius

- packages/react/package.json
I noticed a small typo in the exports configuration that certainly break tools that use that configuration.
None
> build(npm): fix typo in esm exports configuration

- packages/style/gulpfile.js
- packages/style/lib/js/collapse.js
- packages/style/lib/js/transition.js
- packages/style/package.json
- packages/style/scss/controls/collapsable.scss
- pnpm-lock.yaml
BREAKING CHANGE: 🧨 removing materialise-css as dependencies
Materialize-css is introducing a lot of vulnerability in Snyk scan and we don't anyway so I removed it from the project.
BREAKING CHANGE: 🧨 removing materialise-css as dependencies
> chore: 🤖 (dep, materialize-css) removing from project

- packages/react/src/components/limit/Limit.tsx
- packages/react/src/components/limit/tests/Limit.spec.tsx
- packages/style/scss/components/limit-box.scss
- packages/style/scss/variables.scss
Null or undefined limit and usage values should not be rounded out to 0 and the label should be hidden when that occurs
I also took the time to improve the dev setup 🤖 
None expected
> [plasma-react] handle null limits in Limits component

- package.json
- packages/react-icons/package.json
- packages/react/package.json
- packages/style/package.json
- packages/tokens/package.json
- packages/website/package.json
When next branch was merged in master, it didn't release major version 47. So I am specifying a breaking change in this commit to make it happen.
Svg component was removed, use Iconography instead
> feat: release major 47

- packages/style/scss/controls/inputs.scss
Removing the root level css rules on inputs, any custom style should be scoped down otherwise it leaks into components from other libraries
Components relying on those rules could look a little bit different (I didn't personally notice any difference), but should still be usable
> fix(style): remove root level style on inputs

- packages/website/build/getBasePath.js
Fixing the [build error](https://github.com/coveo/plasma/actions/runs/3329940221/jobs/5507790433#step:5:145) we see in the CD workflow for the master branch
```
@coveord/plasma-website:build: > Build error occurred
@coveord/plasma-website:build: Error: Specified basePath should not end with /, found "/feature/"
@coveord/plasma-website:build:     at assignDefaults (/home/runner/work/plasma/plasma/node_modules/.pnpm/next@12.1.5_dmi2t66wvavvdsdvw6dn5lzaaa/node_modules/next/dist/server/config.js:251:23)
@coveord/plasma-website:build:     at Object.loadConfig [as default] (/home/runner/work/plasma/plasma/node_modules/.pnpm/next@12.1.5_dmi2t66wvavvdsdvw6dn5lzaaa/node_modules/next/dist/server/config.js:94:16)
@coveord/plasma-website:build:     at async Span.traceAsyncFn …
```
> ci(cd): fallback on REF_NAME when defining the base path

- .github/workflows/cd.yml
Snyk now successfully scans and create sarif files, but fail to upload them because the github runner isn't allowed to push to security events and statuses, it needs write permissions to do so.
None
> ci(cd): add write permissions on security events

- package.json
- packages/mantine/jest.config.js
- packages/mantine/package.json
- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/mantine/src/components/code-editor/__mocks__/monaco-editor.ts
- packages/mantine/src/components/code-editor/__tests__/CodeEditor.spec.tsx
- packages/mantine/tsconfig.json
Lazy-load the monaco editor files. Also allow to load monaco files via CDN for those who need it, if your CSP allows it, it might be simpler than configuring the web workers properly.
None
> feat(mantine): lazy-load monaco-editor

- packages/mantine/src/components/modal-wizard/index.ts
- packages/mantine/src/index.ts
I noticed some type exports were missing in the new plasma-mantine package so I added them
- adjust type export for ColumnDef
- add type export for ModalWizard.Step props
None
> fix(mantine): add missing type exports

- .github/actions/publish/index.mjs
Replacing the random user plasma-bot by the actual [coveobot](https://github.com/coveobot).
Sometimes GitHub links "plasma-bot" with [this user](https://github.com/plasma-bot)
This is pretty random and could induce confusion, so using the coveobot makes a lot more sense
None
> ci(publish): use coveobot user as publish user

- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/components/collection/__tests__/Collection.spec.tsx
Use the allowAdd prop to tell the Collection whether the add button should be enabled
The Collection component will no longer disable its add button automatically if the newly added prop isn't provided
> feat(mantine): add "allowAdd" prop to Collection

- packages/mantine/src/components/collection/Colllection.styles.ts
UITOOL-923
Setting the Collection item alignement at baseline to avoid misalignment caused by validation errors.
Before:
After:
> style(mantine, collection):  align  item at baseline

- packages/website/package.json
- pnpm-lock.yaml
ADUI-8345
This is a fix for this snyk issue: 
Did some digging and turns out NextJs does not need next-fonts anymore to work properly so I just removed it 😄 
https://github.com/rohanray/next-fonts/issues/34
None
> chore: 🤖 remove next-fonts

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
UITOOL-956
A comment was raised in a pr that the Mantine table was not unselecting row if the user click outside the table. 
Now it does 😄 
No demo in Plasma website here but here's a video from me hacking a bit the Badge demo page 😆 
https://user-images.githubusercontent.com/63734941/199560856-46f68b13-ff93-4585-95fe-73596043b911.mp4
None
> feat(mantine, table):  reset row selection if user click outside the table

- .github/actions/snyk-pnpm/action.yml
We used to be able to merge even if medium vulnerabilities were found by snyk. I'm bringing this back.
doc: https://docs.snyk.io/snyk-cli/test-for-vulnerabilities/advanced-failing-of-builds-in-snyk-cli
None
> ci: 🎡 snyk scan fails only if high vulnerabilities if found

- packages/components-props-analyzer/bin/getPropsOfComponent.ts
- packages/components-props-analyzer/src/ComponentsList.ts
Use the props analyzer to generate props metadata for each of the components used on the website demo pages
None, not merging in master
> feat(props-analyzer): generate props metadata for each component

- packages/mantine/src/components/table/Table.tsx
UITOOL-1010
The Skeleton style is bleeding out in the table cells. I think it's because the skeleton is always render and only hidden if `loading` is false.
Before:
After:
None, Skeleton style works has before ☠️ 
> fix(table, Mantine):  removed rounded corners on selected text in table row

- packages/mantine/package.json
- packages/mantine/src/components/collection/__tests__/Collection.spec.tsx
- packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerInlineCalendar.spec.tsx
- packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerPopoverCalendar.spec.tsx
- packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerPresetSelect.spec.tsx
- packages/mantine/src/components/date-range-picker/__tests__/EditableDateRangePicker.spec.tsx
- packages/mantine/src/components/inline-confirm/__tests__/InlineConfirm.spec.tsx
- packages/mantine/src/components/modal-wizard/__tests__/ModalWizard.spec.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/mantine/src/components/table/__tests__/TableActions.spec.tsx
- packages/mantine/src/components/table/__tests__/TableDateRangePicker.spec.tsx
- packages/mantine/src/components/table/__tests__/TableFilter.spec.tsx
- packages/mantine/src/components/table/__tests__/TablePerPage.spec.tsx
- packages/mantine/src/components/table/__tests__/TablePredicate.spec.tsx
- pnpm-lock.yaml
Bumping userEvent to version 14.4.3 in plasma-mantine package.
Adjusted unit tests accordingly.
old: userEvent.click()
new: await user.click()
where: const user = userEvent.setup({delay: null});
Affecting unit tests
> chore: bump userEvent to V14.4.3 in plasma-mantine

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableContext.tsx
- packages/mantine/src/components/table/TablePagination.tsx
- packages/mantine/src/components/table/__tests__/TablePagination.spec.tsx
https://coveord.atlassian.net/browse/UITOOL-1011
There's was nothing implemented to scroll back up the table when changing pages. It now does 😄 
Demo:
https://user-images.githubusercontent.com/63734941/201192641-08548631-dc24-4f44-b73d-91cf3dc379c8.mp4
None
> feat(table pagination, Mantine):  scroll back up the table when changing pages

- packages/website/src/building-blocs/PageLayout.tsx
- packages/website/src/building-blocs/PropsTable.tsx
- packages/website/src/pages/_app.tsx
- packages/website/src/styles/props-table.scss
- Small renaming to remain consistent with the filename
- Removed unwanted empty `<ul>` when a prop has no params
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/35579930/201443983-fb9442ce-38c3-43da-9c2c-7ad28c66518e.png) | ![image](https://user-images.githubusercontent.com/35579930/201444015-2899cf45-b860-4721-aa7f-ff408771f114.png) |
> refactor(website): rename PropsDoc to PropsTable

- packages/components-props-analyzer/bin/index.ts
- packages/components-props-analyzer/src/ComponentsList.ts
This will get usefull when a mantine component has the same name as a plasma-react component
None
> feat(props-analyzer): add suffix option to avoid collisions

- package.json
- packages/components-props-analyzer/package.json
I noticed we were building the website and the component-props-analyzer twice when running `pnpm start`
none
> build(props-analyzer): avoid additional build on start

- packages/mantine/src/theme/Theme.tsx
UITOOL-1020
Currently, the checkbox label and description are all on the same line but they should not so i'm removing the custom style.
None
> fix(theme, Mantine):  remove labelWrapper style for checkbox

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/website/.eslintrc.js
- packages/website/build/demo-loader.js
- packages/website/next.config.js
- packages/website/src/SideNavigation.tsx
- packages/website/src/building-blocs/Demo.tsx
- packages/website/src/building-blocs/PageLayout.tsx
- packages/website/src/examples/code-editor/CodeEditor.demo.tsx
- packages/website/src/pages/mantine/CodeEditor.tsx
- packages/website/tsconfig.json
- packages/website/types/custom/index.d.ts
Added a demo page for the CodeEditor from plasma-mantine package. It uses the new demo-loader which is a static demo for now, but will eventually have a "Open in CodeSandbox" feature.
Removing the live sandbox allows the page to load instantly compared to the other pages, and also fixes the conflict with the monaco instance.
None
> Mantine code editor demo page

- packages/components-props-analyzer/nodemon.json
- packages/components-props-analyzer/package.json
- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/components/header/Header.tsx
- packages/website/src/building-blocs/PropsTable.tsx
Improved the props table styles and added missing jsdocs for header and collection components.
None
> Add missing JSDocs for mantine components

- packages/mantine/src/theme/PlasmaColors.ts
- packages/mantine/src/theme/Theme.tsx
- Add aliases (or synonyms) for some colors that are more semantic (the name describes a purpose instead of the visual look itself)
- Also corrected the default look of the badge in the theme
| before | after |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/35579930/203151919-2e5befc1-0587-440a-90dc-a5fc34fe8168.png) | ![image](https://user-images.githubusercontent.com/35579930/203152064-627921a7-07fe-4b83-9a9f-b494ab422fea.png) |
None
> Add semantic color aliases in the theme

- packages/website/src/pages/advanced/InfoToken.tsx
- packages/website/src/pages/advanced/ListBox.tsx
- packages/website/src/pages/feedback/Badge.tsx
- packages/website/src/pages/mantine/CodeEditor.tsx
- packages/website/src/pages/mantine/Collection.tsx
- packages/website/src/pages/mantine/Header.tsx
- packages/website/src/pages/navigation/Breadcrumbs.tsx
- packages/website/src/pages/navigation/SideNavigation.tsx
Removing relative imports of example files by using the existing path alias. Doing so will facilitate what comes next: moving pages around.
none
> refactor(website): use path aliases for all examples imports

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/website/build/demo-loader.js
- packages/website/src/building-blocs/Demo.tsx
- packages/website/src/building-blocs/PageHeader.tsx
- packages/website/src/building-blocs/PageLayout.tsx
- packages/website/src/building-blocs/getCodeSandboxLink.tsx
- packages/website/src/pages/form/CodeEditor.tsx
- packages/website/src/pages/form/Collection.tsx
- packages/website/src/pages/layout/Header.tsx
- packages/website/src/pages/layout/Table.tsx
- packages/website/src/pages/legacy/form/CodeEditor.tsx
- packages/website/types/custom/index.d.ts
Improved the look n feel of the new on-demand sandbox. Added some feature that will be necessary when converting all the pages to this new sandbox
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/35579930/204399646-77a7fa56-c79a-4ecc-ba74-7855f85d2df6.png) | ![image](https://user-images.githubusercontent.com/35579930/204399617-e266ffa0-e963-401f-92ae-8b1c83d09bc0.png) |
None
> Improve on demand sandbox & cleanup naming

- packages/react/jest/setup.ts
- packages/react/src/components/browserPreview/BrowserPreviewError.tsx
- packages/style/gulpfile.js
Right now, plasma-react cannot be used from within a code sandbox: [example](https://codesandbox.io/s/82y3hv?module=/src/Demo.tsx&file=/src/index.tsx)
The "previewError" svg from plasma-style is preventing plasma-react from being able to load in CodeSandbox, because of this bug https://github.com/facebook/create-react-app/issues/11770. CodeSandbox uses create-react-app which expects svgs to have attributes in camel case instead of standard xml markup. For example `xmlns:xlink="http://www.w3.org/1999/xlink"`  would need to be `xmlnsXlink="http://www.w3.org/1999/xlink"`. 
By not importing the svg file directly and using the svgString from the js object instead, it won't happen. But doing so requires the `xmlns` attributes to be set on the svg string.
1. Go in the BrowserPreview demo page
2. …
> fix(react): make plasma react usable from code sandbox

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
Added prop in Table to support doubleClick action on a Table Row.
We opted to add the prop in the table in case there is something wanted out of doubleclick that is not an action on the table.
None
> feat(table): added support for doubleclick on a row

- packages/mantine/src/components/table/Table.tsx
UITOOL-1013
I did a first fix in https://github.com/coveo/plasma/pull/2913 but turns out that now I need 40px instead of 24 :derp:
After:
Demo code (emulate a standard page layout):
None
> fix(table, Mantine):  adjust the first column padding to align with Header

- packages/mantine/src/index.ts
Explicitly exported interfaces and types need to be accompanied with the `type` keyword. Otherwise users of the package will get the following error 
cc: @paulgerold 
none
> fix(mantine): add type keyword to header props export

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/mantine/src/components/code-editor/__mocks__/@monaco-editor/react.tsx
- packages/mantine/src/components/code-editor/__tests__/CodeEditor.spec.tsx
- packages/mantine/src/components/code-editor/languages/xml.ts
- packages/website/src/examples/form/code-editor/CodeEditorXML.demo.tsx
Adding syntax highlighting and formatter for the xml language.
None
> feat(mantine): add xml language support to the CodeEditor

- packages/website/src/examples/form/code-editor/CodeEditorPython.demo.tsx
- packages/website/src/examples/form/code-editor/CodeEditorXML.demo.tsx
- packages/website/src/pages/form/CodeEditor.tsx
Add examples for the CodeEditor component with XML and Python languages
None
> feat(website): add CodeEditor examples for XML and python

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/theme/Theme.tsx
Standardize input wrapper (label, description) styles.
Before
After
> fix(mantine): standardize input wrapper styles

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/mantine/src/components/code-editor/__mocks__/@monaco-editor/react.tsx
- packages/mantine/src/components/code-editor/__tests__/CodeEditor.spec.tsx
https://coveord.atlassian.net/browse/UITOOL-1056
The useMonaco hook was using the CDN event when using the local version so I removed it.
None
> fix(CodeEditor, Mantine):  local monaco should not load via cdn

- packages/mantine/src/components/date-range-picker/DateRangePickerInlineCalendar.tsx
- packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerInlineCalendar.spec.tsx
https://coveord.atlassian.net/browse/UITOOL-1055
Before:
https://user-images.githubusercontent.com/63734941/208169332-2c61bc63-76ad-4e1b-96a3-f79511f94393.mp4
After:
https://user-images.githubusercontent.com/63734941/208169426-aa49cb43-86a5-4bd1-ad82-59ccad157938.mp4
None
> fix(RangePickerInlineCalendar, Mantine):  allow single day range

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableActions.tsx
- packages/mantine/src/components/table/TableCollapsibleColumn.tsx
- packages/mantine/src/components/table/Th.tsx
Make sure columns that are not sortable have the proper padding.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/35579930/208538978-9d132771-4d04-44a4-b895-53a1394641c2.png) | ![image](https://user-images.githubusercontent.com/35579930/208539032-ea80aa08-2068-4b81-ae0d-a32a65756479.png) |
Bonus: I converted the Collapsible toggle button to an ActionIcon, instead of a standard button, which reduces the minimum height of rows a bit allowing to have more rows displayed at the same time.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/35579930/208539409-dcc4082d-7b5f-4f36-9b3c-a90d7516731d.png) | ![image](https://user-images.githubusercontent.com/35579930/208539329-be931ab8-655f-44fa-a76e-967f91a61d3e.png) |
Bonus #2: …
> fix(mantine): give unsortable columns header some padding

- packages/style/package.json
- pnpm-lock.yaml
When building plasma with node 18, plasma-style fails on some error internal to webpack. By updating everything that is webpack related in that package it solves the issue.
> build(plasma-style): update webpack to support node 18

- packages/mantine/src/theme/Theme.tsx
Adjusting the modal sizes a bit. XS was so small it wasn't usable. MD was still in pourcentages, meaning on bigger screens it was possible to have an MD that is bigger than LG.
Here is what is looks like with the new sizes.
https://user-images.githubusercontent.com/35579930/209159052-0734ba36-5c54-4400-bca8-6f971e7c98e8.mov
Existing modals might change size a bit, but the new sizes should not cause any major problems
> fix(mantine): adjust modal sizes in the theme

- packages/mantine/src/components/modal/Modal.tsx
- packages/mantine/src/components/modal/__tests__/Modal.spec.tsx
https://coveord.atlassian.net/browse/UITOOL-1067
Added ReactNode as a type for modal title so it has more flexibility
e.g. from figma file 
> feat(Modal): +ReactNode as title prop type

- packages/mantine/jest.config.js
- packages/react-icons/bin/index.js
- packages/react-icons/mock/index.tsx
- packages/react-icons/package.json
- packages/react-icons/src/index.ts
- packages/react/jest.config.js
- packages/react/src/components/collapsible/tests/CollapsibleInfoBox.spec.tsx
- pnpm-lock.yaml
All icons are now rendered synchronously instead of async. A new mock is exposed to remove any lag sync icons could cause.
You should add the following moduleNameMapper entry to your jest config
```js
'^@coveord/plasma-react-icons$': '<rootDir>/node_modules/@coveord/plasma-react-icons/mock',
```
None
> feat(react-icons): remove loadable

- CODEOWNERS
We are deleting this github team, all of its members are in the admin-console team anyway
> ci(codeowners): remove ui-tooling team

- packages/react-icons/bin/index.js
- packages/react-icons/bin/template.js
- packages/react-icons/src/index.ts
- packages/react/src/components/collapsible/CollapsibleToggle.tsx
- packages/website/src/examples/foundations/Iconography/Iconography.demo.tsx
Changed the script that generates the icons to add the forwardRef. It's now possible to use multiple Mantine components like the Tooltip with the react-icons
The inferred interface of the icon changed but I don't think we need a breaking change for that
> feat(react-icons): add forwardRef on react icons

- packages/react-icons/package.json
The mock folder isn't exposed by the package.json, which makes it impossible to use it from dependent packages external to this monorepo. (related to https://github.com/coveo/plasma/pull/3005)
None
> fix(icons): expose mock folder

- packages/mantine/package.json
- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/components/collection/__tests__/Collection.spec.tsx
- packages/mantine/src/form/FormProvider.tsx
- packages/mantine/src/form/index.ts
- packages/mantine/src/form/useForm.ts
- packages/mantine/src/index.ts
Override of UseForm to front a `getInputProps` addapted to arrays
The controlled Collection component will not leverage the onChange prop anymore. Thus Collection components controlled manually with the `onChange` prop will break
[UITOOL-1030]: https://coveord.atlassian.net/browse/UITOOL-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(mantine form): override getinputprops and use in collection

- packages/style/scss/controls/dropdown.scss
- pnpm-lock.yaml
just changed the .scss. file of _dropdown.scss_ so we can make that quick fix for old dropdown (eventually this will be refactored using mantine and newer plasma components)
https://user-images.githubusercontent.com/52010042/214135377-0fade24a-c67e-4b64-b19f-d6cdac57f8cc.mov
> fix(dropdown): add a grey background on arrow selection options

- packages/mantine/src/theme/Theme.tsx
Adjusting the default size of the `ColorSwatch` to 8px
None
> fix(mantine): adjust color swatch default size

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/package.json
- packages/mantine/src/components/button/Button.tsx
- packages/mantine/src/components/button/ButtonWithDisabledTooltip.tsx
- packages/mantine/src/components/button/__tests__/ButtonWithDisabledTooltip.spec.tsx
- packages/mantine/src/components/button/index.ts
- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/components/date-range-picker/DateRangePickerInlineCalendar.tsx
- packages/mantine/src/components/index.ts
- packages/mantine/src/components/inline-confirm/InlineConfirmButton.tsx
- packages/mantine/src/components/inline-confirm/InlineConfirmPrompt.tsx
- packages/mantine/src/components/menu/Menu.tsx
- packages/mantine/src/components/menu/index.ts
- packages/mantine/src/components/modal-wizard/ModalWizard.tsx
- packages/mantine/src/components/table/TableDateRangePicker.tsx
- packages/mantine/src/components/table/TableHeader.tsx
- packages/mantine/src/components/table/__tests__/TableActions.spec.tsx
- packages/mantine/src/index.ts
- packages/mantine/src/utils/__tests__/overrideComponent.spec.tsx
- packages/mantine/src/utils/createPolymorphicComponent.ts
- packages/mantine/src/utils/index.ts
- packages/mantine/src/utils/overrideComponent.ts
- packages/website/src/SideNavigation.tsx
- packages/website/src/examples/form/button/Button.demo.tsx
- packages/website/src/examples/form/button/ButtonDisabled.demo.tsx
- packages/website/src/examples/form/button/ButtonSecondary.demo.tsx
- packages/website/src/pages/form/Button.tsx
- packages/website/src/pages/legacy/form/Button.tsx
- pnpm-lock.yaml
Implemented an easy way to add tooltips over disabled buttons. I basically took [this doc](https://mantine.dev/core/button/#disabled-button-with-tooltip) and generalized it into a [custom polymorphic component](https://mantine.dev/guides/polymorphic/#create-your-own-polymorphic-components). This way, we can just add the `disabledTooltip` prop to any button of the mantine ecosystem.
Examples
https://user-images.githubusercontent.com/35579930/215129583-b8f0bb1d-b18d-442c-aca5-e29f84c395eb.mov
https://user-images.githubusercontent.com/35579930/215128348-1c9ce008-cdc8-4c01-a85d-122080301b85.mov
I added a demo page for the Button component where you can test it out
As you can see in the diff, I created a new util that facilitates overriding components. Its pretty useful when you need to …
> feat(mantine): disabled button with tooltip

- packages/mantine/src/components/button/Button.tsx
- packages/mantine/src/components/button/ButtonWithDisabledTooltip.tsx
- packages/mantine/src/components/button/__tests__/ButtonWithDisabledTooltip.spec.tsx
- packages/mantine/src/components/inline-confirm/InlineConfirm.tsx
- packages/mantine/src/components/inline-confirm/InlineConfirmMenuItem.tsx
- packages/mantine/src/components/inline-confirm/__tests__/InlineConfirm.spec.tsx
- packages/mantine/src/components/menu/Menu.tsx
- packages/mantine/src/theme/Theme.tsx
I had an issue with the way the disabled tooltip mechanism was implemented when using it in conjunction with a menu item + the inline confirm button.
For example
```tsx
<Menu.Item
component={InlineConfirm.Button}
id={InlineConfirmId}
disabled={tooManyRules}
disabledTooltip={Locales.format('table.header.action.delete.disabled')}
>
{Locales.format('table.header.action.delete')}
</Menu.Item>
```
The `component={InlineConfirm.Button}` prop would overwrite the `component={MantineMenu.Item}` from the Menu.Item component which would render something like a button instead of a menu item.
I switched the ButtonWithDisabledTooltip implementation to just wrap the button with a div instead of adding all those data attributes. 
Anyways, long story short now it works and displays well.
-   [ ] The …
> fix(mantine): simplify disabled tooltip

- packages/mantine/src/components/button/Button.tsx
- packages/mantine/src/components/button/__tests__/Button.spec.tsx
When wrapping the Button component I forgot to expose the Button.Group component
None, it breaks currently when trying to render a Button.Group
> fix(mantine): expose Button.Group

- .github/renovate.json
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableContext.tsx
- packages/mantine/src/components/table/TablePagination.tsx
- packages/mantine/src/components/table/__tests__/TablePagination.spec.tsx
- packages/mantine/src/index.ts
- packages/website/package.json
- packages/website/src/examples/layout/Table/TableClientSide.demo.tsx
- packages/website/src/pages/layout/Table.tsx
- pnpm-lock.yaml
Add options prop to the Mantine table. This enables the developer to create client side filtering, pagination, sorting, etc.
None
> feat(mantine, table): allow passing options to the table

- packages/mantine/src/components/table/Th.tsx
- packages/mantine/src/components/table/__tests__/Th.spec.tsx
Change the icons used for table sorting
Before:
Unsorted
Sorted ascending
Sorted descending
After:
Unsorted
Sorted ascending
Sorted descending
> fix(mantine): adjust table sort icons

- packages/mantine/src/components/modal-wizard/ModalWizard.tsx
- packages/mantine/src/components/modal-wizard/ModalWizardStep.tsx
CTCORE-8959
This exports the `ModalWizardProps` interface and makes the `docLink` prop of the `ModalWizardStep` optional.
> fix(ModalWizard): some fixes to the ModalWizard

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/__tests__/TableActions.spec.tsx
https://coveord.atlassian.net/browse/UITOOL-1147
`enableRowSelection` option from tanStack table is now handled with the loading prop. Table row are not selectable anymore when the table rows are loading (Skeleton)
> fix(table): disable row selection when table is loading

- packages/mantine/src/__tests__/VitestSetup.ts
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableContext.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/website/src/building-blocs/Demo.tsx
- packages/website/src/examples/layout/Table/Table.demo.tsx
- packages/website/src/examples/layout/Table/TableEmptyState.demo.tsx
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
- packages/website/src/pages/layout/Table.tsx
When a table has no data and is unfiltered, show the `noDataChildren` but hide the header and footer. If the table is filtered, either by a regular filter, a predicate or a date range, show the `noDataChildren` with the header and footer.
Added a demo for it in the table section.
None
> fix(mantine): hide table on unfiltered empty state

- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/components/table/Table.tsx
As we're adding more features to the table component, its file is growing in size. Since mantine stores components styles in  separate files for all of its component in its codebase I figured it could not hurt to do it for our table too.
None
> refactor(mantine): extract table styles into its own file

- packages/style/package.json
- packages/style/svgWrapper.js
- pnpm-lock.yaml
There was a vulnerability detected in `fast-xml-parser`, which was used in plasma by `is-svg`. As `SVGWrapper` deprecated, I just remove the check "is-svg" to be able to remove the vulnerability. 
The removal of this check was approved by Germain, so yeah, trust me, it's ok.
> chore(fast-xml-parser): remove is-svg dependency to remove vulnerability

- packages/tokens/bin/fetch.ts
Fixing the design token extraction process. It was failing on a HTTP 413 error (content too large) when extracting the icons. I adjusted the existing chunking mechanism so that it doesn't break.
None
> ci(tokens): extract icons in chunks

- packages/mantine/package.json
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/mantine/src/components/table/index.ts
- packages/mantine/src/components/table/useRowSelection.ts
- packages/mantine/src/index.ts
- packages/website/src/examples/layout/Table/Table.demo.tsx
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
- pnpm-lock.yaml
Fix the Mantine table so that it supports having rows initially selected via the `initialState` prop.
**I added an example for initially selected rows on the website, be sure to check it out!**
I had to do some type hacking to the `rowSelection` state to make it work. Normally the tanstack table `rowSelection` state is of type `Record<string, boolean>`. My fix is to highjack that state so that it becomes `Record<string, TData>`. It works fine as long as TData is not `falsy` which never occurs in reality.
The type of `initialState.rowSelection` is changed from `Record<string, boolean>` to `Record<string, TData>` which is what we would expect anyway and fixes a lot of problems, so I am not planning to mark the commit as a breaking change.
-   [ ] The proposed changes are covered by unit …
> Allow Mantine table to have an initial row selection

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/mantine/src/components/table/useRowSelection.ts
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
Adding a prop on the table that allows to act whenever the row selection changes. The reason I am providing a new prop for this instead of just forcing people to reuse the onChange prop is that onChange only gets called when the table needs to refresh its data. Row selection has no effect on the data shown in the table, it just selects it.
None
> feat(mantine): add onRowSelectionChange prop to table

- packages/mantine/package.json
- packages/mantine/src/components/button/Button.tsx
- packages/mantine/src/components/button/__tests__/Button.spec.tsx
- packages/mantine/src/index.ts
- packages/website/src/examples/form/button/Button.demo.tsx
- packages/website/src/examples/form/button/ButtonSecondary.demo.tsx
- packages/website/src/examples/form/button/ButtonWithAsyncLoader.demo.tsx
- packages/website/src/pages/_app.tsx
- packages/website/src/pages/form/Button.tsx
- pnpm-lock.yaml
Override of the Mantine Button to make the addition of an async handler.
New button in the Demo page to show the async handler use case
switched the Alert to a notification. Because the promise is not fulfilled until we click `ok` to dismiss the alert and the loading of the button hanged in the demo, and that looked weird.
[simplescreenrecorder-2023-02-24_11.02.21.webm](https://user-images.githubusercontent.com/45688129/221226996-5c18f912-d22d-4285-af10-7d119fd37191.webm)
none that I can think of
> feat(mantine button): add async handler

- packages/style/gulpfile.js
- packages/style/scss/common/font.scss
- packages/style/scss/controls/checkboxes.scss
- packages/style/scss/controls/radios.scss
- packages/style/scss/controls/slide-toggle-double.scss
- packages/style/scss/controls/slider.scss
- packages/style/scss/sprites.scss
In #3044 I changed the imports to use absolute paths because I had issues with the relative path but it turns out that just removing a `../` fixes everything and inlines the assets in the generated file
None
> fix(style): inline svgs and fonts in generated stylesheet

- packages/mantine/src/components/button/Button.tsx
- packages/mantine/src/index.ts
Don't throw if the button doesn't have onClick prop
Export NotificationProps as a type
None
> Fix export NotificationProps as type and button without onClick

- packages/mantine/src/components/button/Button.tsx
- packages/mantine/src/components/button/ButtonWithDisabledTooltip.tsx
+fullWidth prop on disabledButtonWithTooltip so that the fullWidth can be applied (as of today, if you set a tooltip on a button and you use fullWidth prop, it is not applied. This pr fixes this
> fix(button): allowed fullwidth on button with tooltip button

- packages/mantine/src/components/modal-wizard/ModalWizard.tsx
- packages/mantine/src/components/modal-wizard/__tests__/ModalWizard.spec.tsx
- packages/website/src/examples/layout/ModalWizard/ModalWizard.demo.tsx
Display a border bottom on the modal wizard header when the progress bar is hidden.
https://user-images.githubusercontent.com/35579930/224437090-7ca97a53-446d-4458-9576-6f4f64b6f0cb.mov
None
> fix(mantine): modal wizard header border bottom

- packages/mantine/src/components/sticky-footer/StickyFooter.tsx
The sticky footer will not lose its border while sticking.
**Examples**
before: 
[simplescreenrecorder-2023-03-15_08.03.37.webm](https://user-images.githubusercontent.com/45688129/225305506-c83d298f-6d3a-4909-a105-b88b16eaf809.webm)
after
[simplescreenrecorder-2023-03-15_08.05.56.webm](https://user-images.githubusercontent.com/45688129/225305538-c718b5ee-b50f-459c-8e49-3179428ad61c.webm)
none
- I do not think I can properly test that even by scrolling
> fix(sticky footer): top border will not dissapear

- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/components/table/TableHeader.tsx
- packages/mantine/src/theme/Theme.tsx
FIX: https://coveord.atlassian.net/browse/UITOOL-1260
FIX: https://coveord.atlassian.net/browse/UITOOL-1232 and  https://coveord.atlassian.net/browse/UITOOL-1233
fixing layout issues by unsetting and diminishing some z-indexes
[simplescreenrecorder-2023-03-23_15.17.16.webm](https://user-images.githubusercontent.com/45688129/227326678-c2e90902-96d1-4347-8c0d-0092e2b2c1ac.webm)
Hiding stuff we want visible. 
But its way less risky to reduce z-indexes than to increase them.
> fix(z indexes): unset skeleton and segmented control

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
Add loading animation for `{noDataChildren}`
Let's assume this setup, and with a service that is slow to return data:
```typescript
<Table 
noDataChildren={
filtered ? <div>No results match your filter</div> : <div>There is no data in the backend</div>
}
>[...]</Table>
```
1- End user types something in the filter, no results match in the service, we display "No results match your filter".
2- User clears input, a new request is sent to the backend.
3- We want to ideally display to display a loading animation while the request is getting executed, and not "There is no data in the backend".
https://coveord.atlassian.net/browse/KIT-2358
> fix(mantine table): add loading state for no data children

- packages/mantine/src/components/header/__tests__/Header.spec.tsx
- packages/mantine/src/components/header/__tests__/__snapshots__/Header.spec.tsx.snap
- packages/mantine/src/components/prompt/Prompt.tsx
- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/theme/Theme.tsx
- packages/style/scss/components/navigation.scss
- packages/style/scss/redesign/variables.scss
- packages/style/scss/typekit.scss
- packages/style/scss/variables.scss
- pnpm-lock.yaml
Reverted this because it was causing too much trouble. We will keep default font-size at 16, while keeping the old typekit.scss file as it was
> revert(typekit): revert typekit.scss changes

- .github/actions/setup/action.yml
- .github/actions/snyk-pnpm/package-lock.json
- .github/actions/snyk-pnpm/package.json
- .github/actions/snyk-pnpm/src/generateNpmLockfile.ts
- .github/actions/snyk-pnpm/src/generatePackageJson.ts
- .github/actions/snyk-pnpm/src/processPnpmLockfile.ts
The CD is failing since the package lock was update to version 6. The snyk action required a few changes to work with this new version of the pnpm lockfile.
None
> ci(pnpm): add CI support for pnpm 8

- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/components/collection/CollectionItem.tsx
- packages/website/package.json
- packages/website/src/examples/form/collection/Collection.demo.tsx
- packages/website/src/examples/form/collection/CollectionWithReactHookForm.demo.tsx
- packages/website/src/pages/form/Collection.tsx
- pnpm-lock.yaml
> feat(mantine, collection): added getItemId props for ReactHookForm - CTCORE-9124

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/TableConsumer.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/website/src/examples/layout/Table/TableConsumer.demo.tsx
- packages/website/src/pages/layout/Table.tsx
Create a new `Table.Consumer` component. This component should be used to wrap "renderless" components that triggers `onChange` on the table in some way. For instance, a component that automatically refresh every X seconds, or a component that listen for changes in the URL, etc
None
> feat(mantine, table): create a consumer semantic component

- packages/mantine/src/components/copyToClipboard/CopyToClipboard.tsx
- packages/mantine/src/components/copyToClipboard/__tests__/CopyToClipboard.spec.tsx
- packages/mantine/src/theme/Theme.tsx
Add an `onCopy` callback prop to the CopyToClipboard component. We need this to facilitate analytics tracking in our project.
None
> feat(mantine): add onCopy callback to CopyToClipboard

- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableActions.tsx
- packages/mantine/src/components/table/TableDateRangePicker.tsx
- packages/mantine/src/components/table/TableFilter.tsx
- packages/mantine/src/components/table/TableHeader.tsx
- packages/mantine/src/components/table/TablePredicate.tsx
- Table.Header is now a Grid and placed inside the <thead> which makes the sticky positionning better
- Every component in the Table.Header is now wrapped inside of a Grid.Col
- The order of components in Table.Header is now predefined according to UX guidelines
NOTE: It's a bit easier to review without whitespace changes: https://github.com/coveo/plasma/pull/3152/files?w=1
Before:
https://user-images.githubusercontent.com/260007/232601526-d4aa24f1-2596-40e9-9793-1b46b129ad2d.mov
https://user-images.githubusercontent.com/260007/232601664-ff3ac530-40ef-42b1-a529-2d153ce4e140.mov
After:
https://user-images.githubusercontent.com/260007/232601570-e45a8bb3-fa07-4ed0-9733-7067c2ba6cb1.mov
https://user-images.githubusercontent.com/260007/232601693-fa7bd14a-6fee-4bc5-a4bd-786e841fee5e.mov
None
- …
> feat(mantine, table): update the style of the table header

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/__tests__/__snapshots__/Header.spec.tsx.snap
> fix(mantine, header): move the DocAnchor in the title to avoid wrapping issues

- .github/renovate.json
Currently we merge one or two Renovate PR per day because they have conflicts in the pnpm-lock and it only get resolved at night. To get through the list of dependencies to bump it would be better to let it run at any time
None
> chore(deps): run renovate more often

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableDateRangePicker.tsx
Previously the components shown in Table.Header were outside of the table, preventing style clashing. But since we moved the Table.Header inside the table this is not the case anymore.
Before:
After:
None
> fix(mantine, table): style of components shown in Table.Header

- packages/react-icons/mock/.swcrc
- packages/react-icons/package.json
`@coveord/plasma-react-icons/mock` used to be compiled to `commonjs`. When the transition to ESM package occured, the compiled version of the mock was thrown away, but it needs to remain compiled as `commonjs` otherwise jest cannot use it.
None
> fix(react-icons): bring back compiled mock

- packages/react-icons/.gitignore
- packages/react-icons/package.json
- packages/tokens/package.json
- pnpm-lock.yaml
Forgot two things:
- `@coveord/plasma-tokens` package needs `@swc/helpers` in its depencencies
- `@coveord/plasma-react-icons/mock` was not properly understood by jest just by using package.json exports field.
> fix(react-icons,tokens): add missing swc/helpers dependency

- packages/tokens/package.json
`@covoerd/plasma-tokens` package is missing some exports specifiers for scss, css, and icons entrypoints. I thought it was only necessary to specify javascript entries, but it turns out all entrypoints must be specified, even non .js stuff.
> fix(tokens): add missing exports specifiers for scss, css and icons

- packages/mantine/src/components/table/Th.tsx
Updated the style of the table header (th) elements of the Mantine table
normal:
hover:
normal:
hover:
None
> fix(mantine, table): update style of the th elements

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/components/prompt/Prompt.tsx
- packages/mantine/src/theme/Theme.tsx
- packages/website/src/SideNavigation.tsx
- packages/website/src/examples/layout/Prompt/Prompt.demo.tsx
- packages/website/src/pages/layout/Prompt.tsx
Changed the theme style from the Modal component so that it adds a horizontal line separator between the header and the body. Also, I've created a `prompt` variant for the Modal component, because we dont want prompt to have that separator.
> UI tool 8702 modal header separator line

- packages/mantine/src/components/date-range-picker/DateRangePickerInlineCalendar.tsx
This fix allows to invert the order of the buttons `Apply` and `Cancel` in the Date Picker in `Layout -> Table` of Plasma. The `Cancel` button needs to be on the left of the `Apply` button, as shown in the right side of the table below.
Before | After
-- | --
Link to ticket here : https://coveord.atlassian.net/jira/software/c/projects/UITOOL/boards/926?modal=detail&selectedIssue=UITOOL-8809 
> fix: order date range picker buttons

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/__tests__/Header.spec.tsx
- packages/mantine/src/components/header/__tests__/__snapshots__/Header.spec.tsx.snap
This fix allows the word-break styling to visualize better long field names when a user wants to edit a Field.
(Fixes third bullet point in : https://coveord.atlassian.net/browse/UITOOL-8758)
Located in `Content -> Fields`. Click on a long named Field and then click on "edit". You should see the window in the screenshots below.
**Before :** 
**After :** 
> fix: add word break for header title

- packages/mantine/src/theme/Theme.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.demo.tsx
> Deliverables: Based on our 2x grid and Mantine’s modal size presets, update the width values for the following:
> - xs = 432
> - sm = 664
> - md = 896
> - lg = 1120
> - xl = 88%
None
> feat(mantine): update modal sizes

- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/TableHeader.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/website/src/examples/layout/Table/TableDisabledRowSelection.demo.tsx
- packages/website/src/pages/layout/Table.tsx
* Added a `disableRowSelection` property to prevent row selection.
Essentially, enabling this property will **disable row selection** and **prevent clicks on the checkboxes** present on the table's rows. The purpose of this property is to be able to present the data in the table but to disallow users from modifying the rows that have been selected.
This property could be used for a table that's part of a form and the selected row are saved in it. When the form is disabled, we do not want users to be able to change the selected row in the table. In cases like these, we want to retrieve and save the information from the table, and not perform actions on its items. Hence, table and row actions are not relevant here.
None
-   [x] The …
> feat(mantine, table): add disableRowSelection property

- packages/mantine/src/components/table/Th.tsx
This fix resolves the second bullet point in this ticket : https://coveord.atlassian.net/browse/UITOOL-8758
(removes the excessive padding in the table header caused by the th that has a title with a word break)
A `whiteSpace: 'nowrap'` styling was added to the th of the table to make sure it doesn't break on multiple lines when the window size decreases.
before | after
-- | --
1. Navigate to `Layout -> Table`
2. Inspect this section of the table
3. `Edit as HTML` the concerned tag and add multiple words to the div to have text in the div like this : 
4. If you decrease the window size, the weird padding from before should not be there (it's easier to visualize when hovering on `Title`. 
-   [ ] The potential breaking changes are …
> fix: remove th padding due to word-break

- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/TableHeader.tsx
- packages/mantine/src/components/table/TableLayoutControl.tsx
- packages/mantine/src/components/table/TableLoading.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/mantine/src/components/table/index.ts
- packages/mantine/src/components/table/layouts/RowLayout.tsx
- packages/mantine/src/components/table/layouts/TableLayouts.tsx
- packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx
- packages/mantine/src/theme/Theme.tsx
- packages/website/src/pages/layout/Table.tsx
Enabling the `<Table>` component to offer multiple layouts to the user.
In this PR, I extracted the existing logic to render rows into a `RowLayout` and exposed a new `layouts` prop on the Table component. The default value of this prop is an array containing only the row layout, so this change is not breaking.
When providing more than one layout, a layout toggle appears and let the user switch between layouts.
https://github.com/coveo/plasma/assets/35579930/97506783-989e-4901-8c0d-9c45f1697f85
None
> feat(mantine): enable table to have multiple layouts

- packages/mantine/src/components/table/TableActions.tsx
- packages/mantine/src/components/table/TableDateRangePicker.tsx
- packages/mantine/src/components/table/TableFilter.tsx
- packages/mantine/src/components/table/TablePredicate.tsx
Followed https://mantine.dev/guides/custom-components/#add-styles-api-support to add support for custom styling on multiple elements that can be used in Table.Header 
None
> feat(mantine, table): add style API support

- packages/mantine/src/components/table/index.ts
These types should be exported to make it easier to build a custom table layout.
TableLayouts isn't exported directly anymore. It is accessible through Table.Layouts. Not marking the commit as breaking though since this was never intended and released very recently.
> fix(mantine): export table layout types

- packages/mantine/src/components/table/TablePredicate.tsx
- packages/mantine/src/components/table/__tests__/TablePredicate.spec.tsx
When using a Table.Predicate component within a Table, changing the predicate value would call the `onChange` prop twice. The fix of this PR is to make sure `onChange` prop gets called only once when selecting a new predicate value.
None
> fix(mantine): fix table predicate onChange

- .github/workflows/ci.yml
- turbo.json
We were `build`ing the app before running the tests which is unnecessary, because we already build during the demo deployment job. The `test` command builds the necessary dependencies for the test execution thanks to the `turbo` configuration. The `Test` check should be 2-3 minutes faster now, because building the website took a lot of time and we won't have to do that anymore.
| --- | --- |
| ![image](https://github.com/coveo/plasma/assets/35579930/6e78aea6-7ba7-4bf6-b8a9-faa65f571eb9) | ![image](https://github.com/coveo/plasma/assets/35579930/56646506-407f-438f-85b7-6dcef2ba7efd) |
None
-   [ ] …
> ci: accelerate CI by not building before tests

- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/TableFooter.tsx
- packages/mantine/src/components/table/TableHeader.tsx
- packages/mantine/src/components/table/TableLastUpdated.tsx
- packages/mantine/src/components/table/TablePagination.tsx
- packages/mantine/src/components/table/TablePerPage.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/mantine/src/components/table/__tests__/TableActions.spec.tsx
- packages/mantine/src/components/table/__tests__/TableLastUpdated.spec.tsx
- packages/mantine/src/components/table/layouts/RowLayout.tsx
- packages/website/src/examples/layout/Table/TableConsumer.demo.tsx
Updated the look of the table to match UX requirements. There are a few behaviour changes on row click:
- Display the actions
- If row is collapsible, row expand as user clicks anywhere on the row or on the cell containing the chevron
- If multiRowSelectionEnabled, checkbox is only ticked if the user clicks on the cell containing the checkbox or within the checkbox itself instead of anywhere on the row
I replaced the Table from Mantine with a `<Box component="table">` and a bit of style since we were fighting it and not really benefiting from the implementation
See behaviour change above
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted …
> feat(mantine, table): improve the style and UX

- packages/mantine/src/components/date-range-picker/DateRangePickerPresetSelect.tsx
Changed the height of the dropdown to make it crop a value in half if there is more than 5 values. Previously it was displaying exactly 5 values which confused some users
|-------|-------|
| <img width="661" alt="image" src="https://github.com/coveo/plasma/assets/260007/f0214622-bfd1-4aca-a432-e7a6c8630908"> | <img width="661" alt="image" src="https://github.com/coveo/plasma/assets/260007/f8a0cf3e-f47c-45d4-9fb1-4c95e247f54b"> |
None
> fix(mantine, date picker): change height of preset dropdown

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/mantine/src/components/table/useRowSelection.ts
Allow having elements outside the table that won't unselect rows when clicking on them.
There is no demo for it in the actual website, but I added a unit test for it and here's how it looks in a real use case.
Before
https://github.com/coveo/plasma/assets/35579930/2cad5e26-3a77-449b-ab90-8f3de4373625
After
https://github.com/coveo/plasma/assets/35579930/d4f48194-5079-4efb-9647-f47bcf60e089
None
> feat(mantine, table): improve click outside table row selection

- packages/mantine/src/components/code-editor/CodeEditor.tsx
When `onFocus` prop isn't specified on the `CodeEditor` component, it sets `undefined` as callback to the focus event, which leads to this error being printed in the console whenever you focus in the code editor. 
```console
errors.js:15 Uncaught Error: Cannot read properties of undefined (reading 'call')
TypeError: Cannot read properties of undefined (reading 'call')
at Listener.invoke (event.js:648:23)
at EventDeliveryQueue.deliver (event.js:829:34)
at Emitter.fire (event.js:794:33)
at BooleanEventEmitter.setValue (codeEditorWidget.js:1379:37)
at codeEditorWidget.js:1140:43
at Listener.invoke (event.js:648:23)
at PrivateEventDeliveryQueue.deliver (event.js:829:34)
at Emitter.fire (event.js:794:33)
at ViewModelEventDispatcher._emitOutgoingEvents (viewModelEventDispatcher.js:44:27)
at …
```
> fix(mantine): avoid CodeEditor errors onFocus

- packages/mantine/src/components/table/Th.tsx
text-align left in the table header
**Before the Fix**
**After the Fix**
none
> fix(table): header alignment

- packages/mantine/src/components/table/layouts/RowLayout.tsx
- packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx
Added data-testid attribute on table rows and cells. It creates a better developper experience because it's easier to access the table data with code
None
> feat(mantine, table): add data-testid attributes on rows and cells

- packages/react/src/components/dropdownSearch/DropdownSearchAutoInfiniteScroll.tsx
- packages/react/src/components/input/Input.tsx
- packages/react/src/components/multilineBox/MultilineBox.tsx
- packages/react/src/components/multilineInput/SplitMultilineInput.tsx
- packages/react/src/components/popover/Popover.tsx
While bumping to the most recent version of plasma-react I got a few type errors with some components. E.g.,:
```
error TS2786: 'Input' cannot be used as a JSX component.
Its type 'typeof Input' is not a valid JSX element type.
Type 'typeof Input' is not assignable to type 'new (props: any) => Component<any, any, any>'.
Types of construct signatures are incompatible.
Type 'new (props: IInputProps, state: IInputState) => Input' is not assignable to type 'new (props: any) => Component<any, any, any>'.
Target signature provides too few arguments. Expected 2 or more, but got 1.
```
I verified [React's doc](https://react.dev/reference/react/Component#constructor) and we don't have to add the state to the constructor arguments
None
-   [ ] …
> fix(react): type issue in component constructor

- packages/react/src/components/filterBox/FilterBoxSelectors.ts
This PR allows the org picker to be more tolerant with white spaces.
I closed [this PR](https://github.com/coveo/admin-ui/pull/7559) in `admin-ui` and opened this one in `plasma` to allow other `FilterBoxSelectors` to be more tolerant.
`trim()` is used to remove leading and trailing white spaces in the input.
Before | After
-- | --
> fix: trim whitespaces from filter box input

- packages/mantine/src/components/table/Th.tsx
- packages/mantine/src/components/table/layouts/RowLayout.tsx
**Problem** 
By using the `getSize` hook to get the size of the column and applying that size to the width css property, we create a confusing situation where setting `minSize` or `maxSize` property on a table column will not respect what we would expect using proper css.
**Solution**
Getting the default sizing or the custom sizing if used, and set those as plain CSS.
**Before the fix**
**After the fix**
**Disclaimer**
The solution does not change the default column layout of the table, no change will be seen unless custom width has been set on table column width. But if a custom width has been used, the new code will apply that styling to the CSS and this might change the table layout.
-   [x] The potential breaking changes are …
> fix(table): column width

- packages/mantine/src/components/table/TablePerPage.tsx
- packages/mantine/src/components/table/__tests__/TablePagination.spec.tsx
- packages/mantine/src/components/table/__tests__/TablePerPage.spec.tsx
When a table has no data, the pagination controls should not be rendered because they serve no purpose. This PR fixes that.
You can test it out in the demo by going in the "Table" section, if you scroll down to the empty state example, you should see no pagination controls.
Before
After
> fix(mantine): remove table pagination when there are no pages

- .github/renovate.json
All those renovate PRs are a bit annoying. I added the `allNonMajor` preset to group all the patches and minor together
https://docs.renovatebot.com/presets-group/#groupallnonmajor
None
> chore(renovate): update config to group minors and patches

- packages/react/package.json
- packages/style/package.json
- pnpm-lock.yaml
Renovate is trying to bump to V6, but while trying to find the component I should check I realized we don't use autosize anywhere.
None
> chore(style): remove unused autosize dependency

- packages/react/src/components/tooltip/Tooltip.tsx
- packages/style/scss/colors.scss
- packages/style/scss/components/banner.scss
- packages/style/scss/components/blankslate.scss
- packages/style/scss/components/card.scss
- packages/style/scss/components/facet.scss
- packages/style/scss/components/home-card.scss
- packages/style/scss/components/material-card.scss
- packages/style/scss/components/modal.scss
- packages/style/scss/components/popover.scss
- packages/style/scss/components/tooltip.scss
- packages/style/scss/controls/filtering/multi-filter-picker.scss
- packages/style/scss/controls/numeric-input.scss
- packages/style/scss/elements/btn.scss
- packages/style/scss/tables/table.scss
- packages/style/scss/utility/border.scss
- packages/style/scss/utility/shadow.scss
- packages/style/scss/variables.scss
Since #3471, the old plasma-react tooltips and many other components that relied on the `rgb` function were not displaying properly.
Before
After
> fix(plasma-style): fix rgb function misusage

- packages/style/gulpfile.js
- packages/style/package.json
- pnpm-lock.yaml
Last release of gulp-files-to-json was 8 years ago. I replaced it with a simple script to generate the dictionary. It generates the exact same `SvgName.d.ts`
None
> chore(deps): replace gulp-files-to-json with a script

- package.json
- pnpm-lock.yaml
Enforcing loader-utils 2.0.4
Fixes https://github.com/coveo/plasma/security/dependabot/32 and https://github.com/coveo/plasma/security/dependabot/31
None
> fix(vuln): enforce loader-utils 2.0.4

- packages/mantine/src/theme/Theme.tsx
[`InputDescription`](https://github.com/mantinedev/mantine/blob/cf0f85faec56615ea5fbd7813e83bac60dbaefb7/src/mantine-core/src/Input/InputDescription/InputDescription.styles.ts#L8) & [`InputError`](https://github.com/mantinedev/mantine/blob/cf0f85faec56615ea5fbd7813e83bac60dbaefb7/src/mantine-core/src/Input/InputError/InputError.styles.ts#L8) had line-height of `1.2` while everything else had `1.5`. This could cause misalignments. 
For example here:
One input (right) has an Anchor (line-height 1.5) within its description, the other one (left) does not.
I did a [quick search](https://github.com/search?q=repo%3Amantinedev%2Fmantine+lineHeight+path%3A%2F%5Esrc%5C%2Fmantine-core%5C%2Fsrc%5C%2F%2F&type=code) in the mantine/core package source code and these were the only 2 instances where I was …
> fix(mantine): make sure input components have uniform line-height

- packages/mantine/src/components/table/layouts/RowLayout.tsx
Long non breaked words are breaking the table layout. I added a rule in the built in row layout.
Tell me if you think this rule should be applied elsewhere instead.
I do not see any.
> fix(table): break long words

- packages/mantine/src/components/copyToClipboard/CopyToClipboard.tsx
- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/__tests__/__snapshots__/Header.spec.tsx.snap
- packages/mantine/src/components/table/TableFilter.tsx
- packages/mantine/src/components/table/__tests__/TableFilter.spec.tsx
- packages/website/src/building-blocs/LegacyWarningBanner.tsx
- packages/website/src/building-blocs/PageLayout.tsx
- packages/website/src/pages/_app.tsx
- packages/website/src/pages/foundations/Iconography.tsx
- packages/website/src/pages/index.tsx
- packages/website/src/pages/layout/Table.tsx
- packages/website/src/styles/iconography.scss
- packages/website/src/styles/page-layout.scss
Here's a little unplanned 🎁 
* Put gradient on top bar
* Center all pages' content using `@coveord/plasma-mantine` Containers
* Improve `Iconography` page:
*  use only `@coveord/plasma-mantine` components
*  collapse variants to see more icons at once
*  add code snippets with copy to clipboard for each variant
* Add 300 ms debounce on `TableFilter` input
* Add `autocomplete="off"` on `TableFilter` and `CopyToClipboard`
Before
After
> feat(website): misc improvements 🎁 

- packages/mantine/src/components/header/Header.styles.ts
- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/HeaderActions/HeaderActions.styles.ts
- packages/mantine/src/components/header/HeaderActions/HeaderActions.tsx
- packages/mantine/src/components/header/HeaderBreadcrumbs/HeaderBreadcrumbs.styles.ts
- packages/mantine/src/components/header/HeaderBreadcrumbs/HeaderBreadcrumbs.tsx
- packages/mantine/src/components/header/HeaderDocAnchor/HeaderDocAnchor.styles.ts
- packages/mantine/src/components/header/HeaderDocAnchor/HeaderDocAnchor.tsx
- packages/mantine/src/components/header/__tests__/Header.spec.tsx
- packages/mantine/src/components/header/__tests__/__snapshots__/Header.spec.tsx.snap
- packages/website/src/examples/layout/Header/HeaderModal.demo.tsx
- packages/website/src/pages/layout/Header.tsx
Followed [Mantine's guide on custom component](https://mantine.dev/guides/custom-components/) to make the Header themeable through the `theme` or `styles` attribute
None
> feat(mantine, header): make component theme-able

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/HeaderActions/HeaderActions.tsx
- packages/mantine/src/components/header/HeaderBreadcrumbs/HeaderBreadcrumbs.tsx
- packages/mantine/src/components/header/HeaderDocAnchor/HeaderDocAnchor.tsx
Added missing exports, some were previously exported (e.g.,  `HeaderDocAnchorProps `) and them not being exported is a breaking change
None
> fix(mantine, header): add missing exports

- packages/mantine/src/theme/Theme.tsx
- packages/website/src/pages/_app.tsx
A small bundle of minor adjustments to the `@coveord/plasma-mantine` theme.
* Hover color of `NavLink` is now `gray[1]` instead of `gray[0]` (for consistency with `Select`)
* `ScrollArea` now has `display: 'block'` instead of weird `display: 'table'`
* `Divider` default color is now `gray[3]` instead of `gray[4]`
* `Navbar` border color is now `gray[3]` instead of `gray[2]` (for consistency with `Divider`)
None
> fix(mantine): minor adjustments to the theme

- packages/mantine/src/components/table/TablePredicate.tsx
- packages/mantine/src/components/table/__tests__/TablePredicate.spec.tsx
https://coveord.atlassian.net/browse/ADUI-9179
When changing predicates, it sets the state to page: 0 the same way changing filter does.
> fix(table): +reset page on predicate change, +unit tests

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/components/action-icon/ActionIcon.tsx
- packages/mantine/src/components/action-icon/index.ts
- packages/mantine/src/components/index.ts
- packages/mantine/src/index.ts
- packages/website/src/SideNavigation.tsx
- packages/website/src/examples/form/action-icon/ActionIcon.demo.tsx
- packages/website/src/examples/form/action-icon/ActionIconDisabled.demo.tsx
- packages/website/src/examples/form/action-icon/ActionIconSecondary.demo.tsx
- packages/website/src/examples/form/action-icon/ActionIconWithAsyncLoader.demo.tsx
- packages/website/src/pages/form/ActionIcon.tsx
Doing the same trick we did on the Button component, but this time on the ActionIcon component. Meaning we're simplifying the combination of having tooltips over a disabled ActionIcon.
> feat(mantine): simplifying disabled tooltips on ActionIcon

- packages/mantine/src/components/sticky-footer/StickyFooter.tsx
When [making the StickyFooter customizable through the theme](https://github.com/coveo/plasma/pull/3547), I made a mistake by moving the root styles to the inner Group component. The current PR moves the styles back on the root element of the StickyFooter just like it was before. 
> fix(mantine): sticky footer doesn't stick anymore

- packages/mantine/src/components/code-editor/CodeEditor.tsx
While debugging a performance issue using the browser's performance profiler, I found out that the `CodeEditor` component from `@coveord/plasma-mantine` was having issues rendering very large chunks of text.
As we can see it in this screenshot, it would spend over 16 seconds in the `discoverBreaks` function. So I did a bit of research on monaco editor and found out about the `wrappingStrategy` option:
> wrappingStrategy: 'advanced' means that we delegate the wrap points computations to the browser. This works by us creating a dom node for each line of the editor, setting the contents of each dom node to the text on each line, and then setting a specific width. We then proceed to use browser APIs to detect the wrapping points. This is super slow (causes a forced browser layout). - …
> fix(mantine): performance issue in CodeEditor

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/website/src/examples/form/code-editor/CodeEditorError.demo.tsx
- packages/website/src/pages/form/CodeEditor.tsx
[CTCORE-9443](https://coveord.atlassian.net/browse/CTCORE-9404)
Improved the rendering of error in the CodeEditor component to be more visible.
Before: 
After:
Added an example in CodeEditor page as well
[Go to this link](https://plasma-website-eexd5b6cq-adui-core.vercel.app/form/CodeEditor) and verify that the red outline correctly shows on the last example whenever there's an error.
[CTCORE-9443]: https://coveord.atlassian.net/browse/CTCORE-9443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(mantine): improve error rendering of code editor : CTCORE-9443

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/components/browser-preview/BrowserPreview.styles.ts
- packages/mantine/src/components/browser-preview/BrowserPreview.tsx
- packages/mantine/src/components/browser-preview/__tests__/BrowserPreview.spec.tsx
- packages/mantine/src/components/browser-preview/index.ts
- packages/mantine/src/components/index.ts
- packages/mantine/src/hooks/useRowSelection.ts
- packages/mantine/src/index.ts
- packages/react/src/components/browserPreview/BrowserPreview.tsx
- packages/website/src/SideNavigation.tsx
- packages/website/src/building-blocs/Demo.tsx
- packages/website/src/examples/layout/BrowserPreview/BrowserPreview.demo.tsx
- packages/website/src/examples/layout/BrowserPreview/BrowserPreviewOverflow.demo.tsx
- packages/website/src/examples/layout/BrowserPreview/BrowserPreviewWithTitleAndDescription.demo.tsx
- packages/website/src/pages/layout/BrowserPreview.tsx
- packages/website/src/pages/legacy/layout/BrowserPreview.tsx
- packages/website/types/custom/index.d.ts
[SEARCHAPI-8834](https://coveord.atlassian.net/browse/SEARCHAPI-8834)
🆕 Adding a new `BrowserPreview` component using Mantine. 🆕 
🗝️ This component is based off the [current](https://plasma.coveo.com/legacy/layout/BrowserPreview) `BrowserPreview` component from the `plasma-react` package. 🗝️ 
See it in [Figma](https://www.figma.com/file/5g877KNr4rJOle1dpCBJJn/Preview?node-id=1%3A2&mode=dev).🎨 
Since all the demo components were rendered in a `ScrollArea`, I found it hard to showcase the height adjustments  and overflow behaviour of a component. So, I added a `maxHeight` prop which will render the demo component in a flex container with the specified max height.
🟢 No breaking changes. This PR adds a new component that is yet to be used anywhere. 🟢 
You see the new component in action …
> feat(mantine, browserpreview): add new Mantine BrowserPreview component

- packages/mantine/src/components/table/Table.styles.ts
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/layouts/RowLayout.tsx
i was trying to make use of the changes from https://github.com/coveo/plasma/pull/3535
at the moment, you can only do style overrides to the RowLayoutBody component, not to the header
you can see this here, where the theme's RowLayout classes only get applied to the body, so you can't theme any of the header's styles. The `thead`'s `tr` components should have the `headerColumns` class
shouldnt affect anything else
> feat(commerce-hub): make RowLayoutHeader respect Mantine theme MHUB-263

- packages/mantine/src/theme/Theme.tsx
Setting a default max width of 300px on the plasma-mantine Tooltip via the Theme object. 
> feat(mantine): set tooltip default max width of 300 px

- packages/mantine/src/components/prompt/Prompt.tsx
Allow the possibility to override classNames for the prompt component.
For this task : [MLX-644](https://coveord.atlassian.net/browse/MLX-644)
I have a problem displaying the prompt over a modal, I need to change the zindex of the prompt overlay
[MLX-644]: https://coveord.atlassian.net/browse/MLX-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(MLX): allow possibility to override classnames in prompt

- packages/mantine/src/components/prompt/Prompt.tsx
Allow the possibility to override classNames for the prompt component.
For this task : [MLX-644](https://coveord.atlassian.net/browse/MLX-644)
I have a problem displaying the prompt over a modal, I need to change the zindex of the prompt overlay
[MLX-644]: https://coveord.atlassian.net/browse/MLX-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(MLX): allow possibility to override classnames in prompt v2

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/website/src/examples/form/code-editor/CodeEditorGraphQL.demo.tsx
- packages/website/src/pages/form/CodeEditor.tsx
By using this nifty TypeScript trick `| (string & unknown)` in a string literal types we keep the autocomplete but allow custom values
None
> feat(mantine, code editor): allow dev to use more language

- .github/actions/cleanup-demo/cleanup-demo.sh
- .github/actions/deploy/action.yml
- .github/actions/deploy/deploy.sh
- .github/workflows/ci.yml
- .prettierignore
- packages/website/build/getBasePath.ts
Branch names containing a slash (`/`) in their names should now deploy a demo at a location that does not contain a slash.
For example the current branch is named `ADUI-9282/remove-slashes-in-branch-name`. But the demo is deployed at https://plasma.coveo.com/feature/ADUI-9282-remove-slashes-in-branch-name/. As you can see the `/` is getting replaced by a `-`.
> ci(website): remove slashes from demo branch name URLs

- packages/mantine/src/components/table/__tests__/TableFilter.spec.tsx
- packages/mantine/src/components/table/table-filter/TableFilter.tsx
There was a disconnect between the `Table` and the `Table.Filter` when clearing the filters. When calling `clearFilter` from the `useTable` hook, the global filter was clearer, but the textbox of the filter didn't.
More info in the jira ticket --> https://coveord.atlassian.net/browse/ADUI-9312
none
> Ad UI 9312 filter input in table component not clearing upon calling clear filter

- packages/mantine/src/components/table/__tests__/Th.spec.tsx
- packages/mantine/src/components/table/layouts/RowLayout.styles.ts
- packages/mantine/src/components/table/table-header/Th.styles.ts
- packages/mantine/src/components/table/table-header/Th.tsx
- packages/mantine/src/components/table/table-header/Th.types.ts
Allow customization of table column headers through the theme.
Using the new customization capabilities, I was able to produce a table looking like this 🎉 
I think it also makes sense for the plasma table to move the sort icon closer to the column header label:
Before
After
> feat(mantine): allow table column header customization

- packages/mantine/src/components/table/table-filter/TableFilter.tsx
Replaced "search" icon by the "filter" icon instead in the filter of the `Table` component.
|Before|After|
|--|--|
|<img width="823" alt="image" src="https://github.com/coveo/plasma/assets/105073504/e895dbe4-8d3b-4846-9c01-2bea79878207">|<img width="680" alt="image" src="https://github.com/coveo/plasma/assets/105073504/f89f1716-cc12-4635-ae68-1998a9bfd359">|
None
> feat(mantine): replace search icon with filter

- packages/components-props-analyzer/package.json
- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/mantine/src/components/code-editor/__tests__/CodeEditor.spec.tsx
- packages/react-icons/bin/index.js
- In the `CodeEditor`, now also display the error outline when there is an `error` coming from the form
- Fix some things along the way that were breaking when I tried to build the plasma repo on my Windows machine
> fix(WEB-6600): add error outline in CodeEditor when form is in error and fix windows build process

- .github/actions/setup/action.yml
same as https://github.com/coveo/admin-ui/pull/8833
I have explicitly specified the node-version in the action, since it's recommended from the documentation
```The node-version input is optional. If not supplied, the node version from PATH will be used. However, it is recommended to always specify Node.js version and don't rely on the system one.```
if green, good to go.
> chore(node): specified node-version in setup action

- packages/mantine/src/components/table/table-loading/TableLoading.tsx
- packages/react/README.md
- packages/react/jest/utils.tsx
- packages/react/src/components/limit/Limit.tsx
- packages/react/src/components/select/SelectSelector.ts
- packages/react/src/components/select/SingleSelectConnected.tsx
Removing this warning:
<pre>
SingleSelectConnected.tsx:69 Selector unknown returned a different result when called with the same parameters. This can lead to unnecessary rerenders.Selectors that return a new reference (such as an object or an array) should be memoized: https://redux.js.org/usage/deriving-data-selectors#optimizing-selectors-with-memoization {state: {…}, selected: {…}, selected2: {…}}     at SingleSelectConnected (http://localhost:3000/@fs/Users/gdostie/Developper/coveo/plasma/packages/react/dist/esm/components/select/SingleSelectConnected.js:21:37)    at WrappedComponent (http://localhost:3000/@fs/Users/gdostie/Developper/coveo/plasma/packages/react/dist/esm/components/select/hoc/SelectWithPredicate.js:35:30)    at ConnectFunction …
> fix(plasma-react,SingleSelect): memoize selectors

- packages/mantine/src/components/inline-confirm/InlineConfirmButton.tsx
- packages/mantine/src/components/inline-confirm/__tests__/InlineConfirm.spec.tsx
- Import button from plasma/mantine instead of mantine core. 
- Origin https://github.com/coveo/plasma/pull/3022/files#diff-76e149949bcb2228e7851d523510603b2ee856c7da95aaf1e5267069ce8a0eb7R1-R2
- Added test to cover the case
None
> fix(mantine): fix disabled tooltips for inline confim buttons

- packages/react/src/components/numericInput/NumericInputConnected.tsx
Adds the button types to the plus and minus numeric input buttons. This avoids premature default validations on the form when clicking on those buttons. Currently the default type of the button is submit and triggers validations on every button press. This behavior manifests itself by showing a `Please fill out this field` alert on every button press on forms where empty inputs are present in the form. Here's a [stack overflow post ](https://stackoverflow.com/a/28340579)describing the issue
> fix(wpc-154): add numeric input buttons type

- packages/react/src/components/filterBox/FilterBoxSelectors.ts
The `FilterBox` was trimming the text while users were typing a value.
🎬 Some examples within the ADUI:
https://github.com/coveo/plasma/assets/133259861/327f68a8-54d5-432a-a34d-417a4831a306
https://github.com/coveo/plasma/assets/133259861/cef859ae-aedb-4b03-9cc8-d7864f86c68e
🎬 I also confirmed the unwanted behaviour in the demo in Plasma:
https://github.com/coveo/plasma/assets/133259861/56894e32-3e58-4ac3-b574-24827cd69f47
The culprit seemed to be the `trim()` call that was introduced in this [PR](https://github.com/coveo/plasma/pull/3396). It was meant as a UX fix regarding the organization picker in the ADUI. Indeed, if you copy/paste some text with leading or trailing whitespaces, the filtering probably won't find what you're looking for since it takes into account the whitespaces. …
> fix(filterbox): do not trim end of string to avoid weird UX when typing

- packages/mantine/src/components/collection/Collection.module.css
- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/components/collection/CollectionContext.ts
- packages/mantine/src/components/collection/CollectionItem.tsx
- packages/mantine/src/index.ts
- packages/mantine/src/utils/createFactoryComponent.ts
- packages/mantine/src/utils/index.ts
this is a subtask of https://coveord.atlassian.net/browse/ADUI-9365 where a lot of components are using the plasma/mantine ```<Collection />``` component. When I did the migration from mantine 6 -> 7, I did not foresee that we would need to factorise this component so that devs could use it and access css selector, like so :
`<Collection styles={{root: {...}, item: {...}, otherSelector: {...}}}>{...}</Collection>`
With my migration, it was made so that the classes were directly used as an import, while now it's used with ```useStyles``` mantine hook.
With this new implementation, it is now possible to add style with styles prop and add custom style to ```'root' | 'item' | 'itemDragging' | 'dragHandle'``` selectors.
This should not break anything. In fact, it fixes a breaking behavior the …
> feat(collection): use getStyles, fixed collection

- packages/mantine/src/theme/Theme.tsx
Changing the default font style of the body tag. This way when you render text out of any mantine component, the same default font style is still applied.
Before
After
> fix(mantine): adjust default font styles

- packages/mantine/src/components/table/Table.types.ts
Changing the Table data prop type from `data: T[];` to `data: T[] | null;`.
The Table component already expects a `null` value when it is initially loading.
```tsx
if (!data) {
return (
<Center sx={{flexGrow: 1}}>
<Loader />
</Center>
);
}
```
https://github.com/coveo/plasma/blob/master/packages/mantine/src/components/table/Table.tsx#L141-L147
> fix(mantine): add null to table data prop type

- packages/mantine/src/components/action-icon/ActionIcon.tsx
- packages/mantine/src/components/button/Button.tsx
- packages/mantine/src/hooks/useClickWithLoading.ts
Made ActionIcon and Button theme-able via the factory
Extracted duplicated code between ActionIcon and Button to a shared hook
None?
> chore(mantine): button and action icon overridable via theme

- packages/mantine/src/components/header/HeaderDocAnchor/HeaderDocAnchor.tsx
Change type of `label` from `string` to `ReactNode` in `HeaderDocAnchor` to align with `Tooltip`
`string` type is allowed in `ReactNode` still, so nothing will break
** This is needed for https://github.com/coveo/admin-ui/pull/9769 **
> feat: change HeaderDocAnchor label type to align with mantine tooltip

- packages/style/scss/tables/pagination.scss
The disabled pagination  style of the plasma react table was not applied on the correct element classes. The effect is, when a user gets to the last page, the `next` is not grayed out. 
Duplicating the rules already applied on the `.change-page-link.disabled` to also apply on `.flat-select .flat-select-option.mod-link.disabled` fixes the situation.
TODO: I Will paste a proper destination in the demo to test the changes 
> Fix ad UI 9588 disabled style pagination plasma react table

- packages/mantine/src/components/table/Table.module.css
- packages/website/src/styles/main.scss
Somehow, Mantine 7 now sets a negative margin on the Grid component, which breaks the visuals of the table:
By setting this margin to `0`, it fixes the issue.
Before
After
> Fix mantine table header margin problem

- packages/mantine/src/theme/Theme.tsx
bumping the Zindex of the popover manually in the default props since the actual style coming from the module is not used. Modifying the style there or with the variables have no effect.
> Fix ad UI 9639 popover zindex

- packages/mantine/src/components/table/__tests__/TablePagination.spec.tsx
- packages/mantine/src/components/table/table-pagination/TablePagination.tsx
Added a bit of logic in the Mantine table to automatically changes the page when the total number of page is less than the current page. When the user deletes the last element of a page this fix will automatically go to the previous page
None
> fix(mantine, table): automatically update page when needed

- packages/mantine/src/components/table/Table.tsx
The table row layout style is like this:
```css
&[data-selected='true'] {
&[data-multi-selection='false'] { // <--- look here
@mixin light {
background-color: var(--mantine-color-gray-1);
}
@mixin dark {
background-color: rgba(var(--mantine-primary-color-7), 0.2);
}
}
&[data-multi-selection='true'] {
background-color: transparent;
}
}
```
So it means that table where multi row selection is disabled are expected to have the attribute `data-multi-selection="false"`. Since there was no default value of `false` for the multi row selection it would never happen unless specified manually to false.
Before
After
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README. …
> fix(mantine): table selected row highlight

- packages/style/scss/lib/reset.scss
This reverts commit 4db52652a2d0767daeaa5ed3701411d01217c4b5.
This change causes some issues with the old plasma-react table: the actions are not centered anymore.
Before the revert
After the revert
> Revert "fix(reset): line-height (#3648)"

- packages/mantine/src/components/prompt/Prompt.tsx
- packages/mantine/src/components/prompt/PromptFooter.tsx
- packages/mantine/src/styles/Modal.module.css
- packages/website/src/examples/layout/Modal/Modal.demo.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.demo.tsx
- packages/website/src/examples/layout/ModalWizard/ModalWizard.demo.tsx
- packages/website/src/pages/layout/ModalWizard.tsx
In my [previous PR](https://github.com/coveo/plasma/pull/3647) to fix the Mantine Modal after the update to version 7, I overlooked the padding top on the modal body.
In mantine 7 version a css rule was added to remove the padding top on the modal body. 
```css
.body {
padding: var(--mb-padding, var(--mantine-spacing-md));
padding-top: var(--mb-padding, var(--mantine-spacing-md));
&:where(:not(:only-child)) {
padding-top: 0; // this is annoying
}
}
```
https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/ModalBase/ModalBase.module.css
It makes sense for when the header does not have a border bottom, but all our modals do. So I added an override to put it back.
-   [ ] The potential breaking changes …
> fix(mantine): add back modal body padding top

- packages/mantine/src/components/button/Button.tsx
When `data-loading="false"` is applied to the button, the loading style still applies which hides the button text. This is because Mantine uses the selector `:where([data-loading])` and not `:where([data-loading='true'])`. So when the loading is false, the attribute must be set to undefined.
Before
After
> fix(mantine): button loading data attribute

- packages/mantine/src/index.ts
- packages/website/bin/index.ts
Pinning the mantine package version when cloning the examples page, otherwise we can end up having demo pages of components that don't exist.
> fix(website): pin mantine version when cloning examples

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/index.ts
Make the HeaderProps extend StylesAPIProps
> fix(mantine): header props type

- packages/mantine/src/components/button/Button.tsx
When using the polymorphic component of button and using it as a Link, the ```onClick``` prop was still triggered and a redirection to the ```to``` link prop specified occurred even though the button was disabled. We `preventDefault()` when ```data-disabled === true```. this should fix a lot (all) of redirection disabled button.
> fix(button): prevent default onclick for link button

- packages/mantine/src/styles/Combobox.module.css
Added a small margin under the Combobox.Search component
None
> fix(mantine, combobox): add small margin under Combobox.Search

- packages/mantine/src/components/code-editor/CodeEditor.module.css
Changed the z-index of the CodeEditor
Before:
After:
None
> fix(mantine, code editor): scrollbar z-index

- packages/mantine/src/components/table/Table.module.css
- packages/mantine/src/components/table/__tests__/TableDateRangePicker.spec.tsx
- packages/mantine/src/components/table/table-date-range-picker/TableDateRangePicker.tsx
https://coveord.atlassian.net/browse/ADUI-9905
Now:
I removed old test since these changes remove their usefulness. Adapting them would be to test implementation details already tested in mantine
> feat(table): visual update on datepicker

- packages/mantine/src/components/table/__tests__/TableDateRangePicker.spec.tsx
- packages/style/scss/lib/reset.scss
HTML tags like `<b>` or `<strong>` that inherently imply css style (`font-weight: bold` in this case) would not work anymore. This is due to the fact that Mantine version 6 would import [normalize.css](https://necolas.github.io/normalize.css/) and they stopped doing that in version 7. 
In this PR, I cherry picked some of the normalize.css that make sense for us and added them in the existing `reset.scss` file of the plasma-style package.
You can test it out in the demo, by editing the HTML somewhere to add a `<b>` tag around text. It should make it bold, while before on the branch `next` it would not. On `master` branch it does work.
-   [ ] …
> fix(style): add missing reset rules to reset.css

- packages/mantine/src/components/header/Header.module.css
- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/__tests__/Header.spec.tsx
- packages/mantine/src/components/header/__tests__/__snapshots__/Header.spec.tsx.snap
- packages/website/src/examples/layout/Header/HeaderContent.demo.tsx
- packages/website/src/examples/layout/Header/HeaderSecondary.demo.tsx
- packages/website/src/examples/layout/Modal/Modal.demo.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.demo.tsx
- packages/website/src/pages/layout/Header.tsx
https://coveord.atlassian.net/browse/ADUI-9094
This just adds another variant to the Header component. For now it is really dry, in fact the same as the modal variant, but now from within our code, we will use a relevant variant name + if we want to change the content variant visual, we could do so with module.css or other way, separating modal and content variants.
Also, nothing prevents the dev from putting any actions or breadcrumbs in that content variant, opening the possibility of creating a pretty intense header loop of stuff. (more an FYI than actual warning)
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the …
> feat(header): +content variant +example

- packages/mantine/src/styles/ScrollArea.module.css
- packages/mantine/src/theme/Theme.tsx
Some styles in the plasmantine theme were solving very specific problems that only the admin console app has. These styles have been moved inside the app's repository so it is safe to remove from the main theme.
> refactor(mantine): remove admin-ui specific styles from the theme

- packages/mantine/src/components/inline-confirm/InlineConfirm.tsx
- packages/mantine/src/components/inline-confirm/__tests__/InlineConfirm.spec.tsx
- packages/mantine/src/components/table/layouts/row-layout/RowLayoutHeader.tsx
- packages/website/src/examples/form/inline-confirm/InlineConfirmMenu.demo.tsx
InlineConfirm: Stop using forwardRef on InlineConfirm via Mantine factory, react warns about it
Table: Do not spread doubleClickAction on RowLayoutHeader, react warns about it
None
> Fix Mantine react warnings

- packages/mantine/src/components/table/Table.module.css
- packages/mantine/src/components/table/table-column/TableCollapsibleColumn.tsx
- packages/mantine/src/components/table/table-header/TableHeader.tsx
Fixing some alignment issues with the table header and collapsible column.
| --- | --- |
| <img width="529" alt="image" src="https://github.com/coveo/plasma/assets/35579930/529315cc-d1eb-426c-97fa-aeafb161b60e"> | <img width="531" alt="image" src="https://github.com/coveo/plasma/assets/35579930/61b11da5-027c-4d8f-9283-4443286d75e2"> |
> fix(mantine,table): table header alignment issues

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/styles/Alert.module.css
- packages/mantine/src/theme/Theme.tsx
- packages/website/src/Navigation.tsx
- packages/website/src/building-blocs/PageHeader.tsx
- packages/website/src/examples/feedback/alert/Alert.demo.tsx
- packages/website/src/examples/feedback/alert/AlertCritical.demo.tsx
- packages/website/src/examples/feedback/alert/AlertSuccess.demo.tsx
- packages/website/src/examples/feedback/alert/AlertTip.demo.tsx
- packages/website/src/examples/feedback/alert/AlertWarning.demo.tsx
- packages/website/src/pages/feedback/Alert.tsx
Made some adjustments in the theme for the Alert component
- Icon should be 16px (was 20px)
- Space between icon and text should be 16px (was 24px)
- Padding around the alert should be 16px (was 24px)
- Content text should have color gray-7 (was gray-9)
| Before | After | Figma |
| ![image](https://github.com/coveo/plasma/assets/35579930/f9d81ee6-2fbb-4e29-8393-55f1172bff94) | ![image](https://github.com/coveo/plasma/assets/35579930/81c52949-3a43-4ce7-9703-309e67eac39d) | ![image](https://github.com/coveo/plasma/assets/35579930/20628dff-59ce-418e-9ce6-b5ea039f65a1) |
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted …
> fix(mantine): adjust Alert visual look

- packages/mantine/src/components/sticky-footer/StickyFooter.module.css
- packages/mantine/src/components/sticky-footer/StickyFooter.tsx
- packages/website/src/examples/layout/Modal/Modal.demo.tsx
Currently, without going full blown modal compound components, there is no good way of having a border above the modal footer that stretches to the edges of the modal. This is because the footer is inside the modal body and that body has padding by default.
The solution I suggest is to add a new prop on the `StickyFooter` component called `removeModalPadding`. When true, this prop removes the modal's default padding so that the footer properly hugs the bottom of the modal. Making it easy for people to achieve the desired look without introducing any breaking change.
See first Modal example in the demo website
```
<StickyFooter borderTop removeModalPadding>
<Button variant="outline" onClick={() => setOpened(false)}>
Cancel
</Button>
<Button onClick={() => setOpened(false)}>Accept</Button> …
```
> feat(mantine): add variant modal-footer to StickyFooter

- packages/mantine/src/components/table/__tests__/TablePagination.spec.tsx
- packages/mantine/src/components/table/table-pagination/TablePagination.tsx
Modified the code that determines the total amount of pages in `TablePagination` to also take into account the case where `totalPages` could be `undefined` and not just `null`.
See [comment](https://github.com/coveo-platform/admin-ui/pull/10735#discussion_r1578149562) for more details.
None
> fix(mantine, table): modify condition to determine page total

- packages/style/scss/components/multiselect-input.scss
- packages/website/src/examples/legacy/form/MultiSelect/main.demo.tsx
[SEARCHAPI-10134](https://coveord.atlassian.net/browse/SEARCHAPI-10134)
Adjust how the margin is handled for the selected options in the legacy plasma-react `MultiSelect` component.
**Before**
margin was set on the last selected option and on the empty placeholder directly. This looked a bit weird when you had options side by side.
**After**
I put the margin directly on the parent container and tested the various use-cases.
Use can play with the demo [here](https://plasma.coveo.com/feature/SEARCHAPI-10134-multiselect-selected-margin/legacy/form/MultiSelect). 🧪 
None.
[SEARCHAPI-10134]: https://coveord.atlassian.net/browse/SEARCHAPI-10134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(plasma-react, multiselect): fix margin for selected options

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/mantine/src/components/table/table-column/TableSelectableColumn.tsx
- packages/website/src/TopBar.tsx
- packages/website/src/UnexpectedError.tsx
- packages/website/src/building-blocs/Demo.tsx
- packages/website/src/building-blocs/PageHeader.tsx
- packages/website/src/building-blocs/ResultList.tsx
- packages/website/src/examples/layout/BrowserPreview/BrowserPreview.demo.tsx
- packages/website/src/examples/layout/BrowserPreview/BrowserPreviewOverflow.demo.tsx
- packages/website/src/examples/layout/BrowserPreview/BrowserPreviewWithTitleAndDescription.demo.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.demo.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.module.css
- packages/website/src/styles/TopBar.module.css
- packages/website/src/styles/UnexpectedError.module.css
https://coveord.atlassian.net/browse/ADUI-9964
Since our last big migration from mantine 6 -> 7, we also instaure good practices to standardize code throughout our products and also reduce the maintenance of our code.
One of these good practices is to stop using **custom style** from `style` and `styles` props and use module.css instead. From there, I noticed that our own plasma website has not been updated to follow this good practice.
This PR aims to fix that so devs who are consulting our plasma website have examples that reflect how we want to write style in components.
FYI. I have done only /website (and few easy changeable ones from our mantine package), but I have not done the changes from the example we pull from the mantine repo. These examples are the result of a fetch from the …
> fix(website): remove custom style with props and module css

- .github/actions/publish/action.yml
- .github/actions/publish/index.mjs
- .github/workflows/cd.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- Modify the CD workflow to allow building the v53 branch.
- Added logic to prevent bumping a major on the branch
- Added special tag when publishing on NPM
- Branch protections were already added
None
> chore: setup CI/CD for v53 legacy branch

- .github/actions/publish/action.yml
NPM doesn't like it when we use a [semantic version for the tag](https://github.com/coveo/plasma/actions/runs/8896506218/job/24429273881) so I switched it to `legacy`
None
> chore: fix npm publish

- packages/mantine/src/components/table/Table.module.css
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
- packages/mantine/src/components/table/table-pagination/TablePagination.tsx
- packages/mantine/src/components/table/use-table.ts
- packages/website/src/examples/layout/Table/Table.demo.tsx
- packages/website/src/examples/layout/Table/TableClientSide.demo.tsx
- packages/website/src/examples/layout/Table/TableCollapsible.demo.tsx
- packages/website/src/examples/layout/Table/TableColumnsSelector.demo.tsx
- packages/website/src/examples/layout/Table/TableDateRangePicker.demo.tsx
- packages/website/src/examples/layout/Table/TableEmptyState.demo.tsx
- packages/website/src/examples/layout/Table/TableLayouts.demo.tsx
- packages/website/src/examples/layout/Table/TablePredicate.demo.tsx
- packages/website/src/examples/layout/Table/TableReactQuery.demo.tsx
- packages/website/src/pages/layout/Table.tsx
In this PR I made one addition to the use-table hook and several improvements to the table examples on the website.
The main fix is I added `isVacant` flag on the store object. This boolean indicates whether the table has rows when unfiltered. This is useful mainly in the case of server side tables to determine whether the table should show the empty state.
None
> feat(website): clarify table examples

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx
- packages/mantine/src/components/table/layouts/row-layout/RowLayoutBody.tsx
- packages/mantine/src/components/table/layouts/row-layout/RowLayoutHeader.tsx
Added a prop on the table called `getRowAttributes`. This prop is useful to provide some attributes on the `<tr>` tag that depend on the row data, for example if you need to disable one row.
None
> feat(mantine): add getRowAttributes prop on table

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableContext.tsx
- packages/mantine/src/components/table/__tests__/TableActions.spec.tsx
- packages/mantine/src/components/table/index.ts
- packages/mantine/src/components/table/table-actions/TableActionItem.tsx
- packages/mantine/src/components/table/table-actions/TableActions.tsx
- packages/mantine/src/components/table/table-actions/TableActionsList.tsx
- packages/mantine/src/components/table/table-actions/TableHeaderActions.tsx
- packages/mantine/src/components/table/table-actions/index.ts
- packages/mantine/src/components/table/table-column/TableActionsColumn.tsx
- packages/mantine/src/components/table/table-header/TableHeader.tsx
- packages/website/src/examples/layout/Table/Table.demo.tsx
- packages/website/src/examples/layout/Table/TableLayouts.demo.tsx
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
Rework the Table.Actions
- Developer need to move it outside of the `<TableHeader>` , it will be automatically added inside the header if the prop `showActions` is true.
- Created a new `Table.ActionsColumn` that can be used the same way as the `Table.CollapsibleColumn`, `Table.AccordionColumn` or `Table.SelectableColumn`. I wasn't able to find any UX mockup so take it with a grain of salt, but it's a good base.
- children must now return Table.ActionItem
- Updated the examples and fixed the tests
See above!
> refactor(mantine, table): decouple table actions from table header

- packages/mantine/src/components/table/table-actions/TableActions.tsx
- packages/mantine/src/components/table/table-actions/TableActionsList.tsx
- packages/website/src/examples/layout/Table/TableConfirmAction.demo.tsx
- packages/website/src/pages/layout/Table.tsx
Modified `Table.Actions` to allow usage of `InlineConfirm`. Since the target is always a button we can use `component={Table.ActionItem}` which then allow the `primary` props
Added demo for `InlineConfirm` inside of `Table.Actions`
Part of the table actions refactor
> feat(mantine, table): allow InlineConfirm actions in table

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx
- packages/mantine/src/components/table/layouts/row-layout/RowLayoutBody.tsx
- packages/mantine/src/components/table/table-header/Th.tsx
- packages/website/src/examples/layout/Table/TableLayouts.demo.tsx
Adjusting Table's `getRowAttributes` and `getExpandChildren` props so that they all match the same arguments signature. I chose the signature of the existing `getRowId` prop, which is the following:
```ts
getRowId?: (originalRow: TData, index: number, parent?: Row<TData>) => string;
```
Doing so has a few benefits:
- It gives more flexibility to the Table implementer. For instance since you have access to the row object (3rd param) you can gain access to tanstack table's row API. So you can do stuff like 
```tsx
<Table
getExpandChildren={(rowData, index, row) => row.getIsExpanded() 
? <ExpensiveContentOnlyFetchedWhenExpanded id={rowData.id} /> 
: <Loader />
}
/>
```
- It brings consistency to the table props `get*`
It can break custom layout implementations because the layout props now …
> feat(mantine): pass down row object to getRow* props

- packages/mantine/src/components/table/index.ts
- packages/mantine/src/components/table/table-actions/TableActions.tsx
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
The typing was too restrictive and prevented us from properly using Table.Actions
None
> chore: fix typing of TableActionsItem

- packages/mantine/src/components/table/table-actions/TableActionsList.tsx
- packages/mantine/src/components/table/table-date-range-picker/TableDateRangePicker.tsx
Two small fixes for the Table component:
- Remove TableActionsList unique keys warning
- Close date range picker popover when clicking outside of it
> fix(mantine): close date range picker on click outside

- helpers/eslint-config-plasma/index.js
- packages/mantine/src/components/table/Table.types.ts
Make sure autocomplete works in all IDE for the table actions group name
Before
After
> fix(mantine): table actions group type

- packages/mantine/src/components/inline-confirm/InlineConfirm.tsx
- packages/mantine/src/components/inline-confirm/InlineConfirmPrompt.tsx
- packages/mantine/src/components/inline-confirm/InlineConfirmTarget.tsx
- packages/mantine/src/components/inline-confirm/__tests__/InlineConfirm.spec.tsx
- packages/website/src/examples/form/inline-confirm/InlineConfirm.demo.tsx
- packages/website/src/examples/form/inline-confirm/InlineConfirmMenu.demo.tsx
- packages/website/src/examples/form/inline-confirm/InlineConfirmStyle.demo.tsx
- packages/website/src/examples/layout/Table/TableConfirmAction.demo.tsx
Allow wrapping of InlineConfirm.Prompt. To do so we need to add the `inlineConfirmId` (from `InlineConfirmComponentsProps`) on the immediate child of `InlineConfirm`
Changed prop `id` to `inlineConfirmId ` on InlineConfirm components
> fix(mantine, inline-confirm): allow prompt to be wrapped

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/__tests__/Table.spec.tsx
Adding the `data-loading={true}` attribute on the `<table>` element so that it is easier to wait for loading skeleton to be removed during tests, for example when changing page.
> fix(mantine): add data-loading attribute on table component

- packages/mantine/src/components/table/Table.module.css
- packages/mantine/src/components/table/table-actions/TableActionItem.tsx
- packages/mantine/src/components/table/table-actions/TableActionsList.tsx
- leftSection prop on Table.ActionItem is no longer required
- Empty action groups label and divider are hidden by default
- Action groups label and divider are now themeable
> fix(mantine): table action items leftSection prop is no longer required

- packages/mantine/src/components/table/Table.tsx
Fixed count not updating when using client-side pagination and the rows are filtered.
None
> fix(mantine, table): client side pagination rowCount

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/Table.types.ts
- packages/mantine/src/components/table/TableContext.tsx
- packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx
- packages/mantine/src/components/table/layouts/row-layout/RowLayoutBody.tsx
- packages/website/src/examples/layout/Table/Table.demo.tsx
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
Made some changes to the table row actions so that getRowActions does not get called once for every row on every render.
- `onRowDoubleClick` handler should now be passed down as prop within the `layoutProps`, instead of through the TableAction
- `TableAction` type no longer needs to be generic
> fix(mantine): perf fix related to double click action

- packages/mantine/src/components/table/layouts/row-layout/RowLayoutHeader.tsx
> fix(mantine): stop passing onRowDoubleClick handler to tr node

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/website/src/building-blocs/Demo.module.css
Making sure the CodeEditor `maxHeight` prop works as designed.
Before
After
> fix(mantine): make sure CodeEditor maxHeight prop works

- packages/style/scss/common/common.scss
- packages/style/scss/lib/reset.scss
Move reset styles into a [CSS layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) called `reset`.
Doing this ensures that reset styles coming from this package cannot override anything from other libraries even if the loading order of stylesheets in the DOM would otherwise have caused it to.
None
> fix(style): add reset stuff into a CSS layer

- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/__tests__/TableActions.spec.tsx
- packages/mantine/src/components/table/table-actions/TableHeaderActions.tsx
`table.state.rowSelection` is an object whose key is the row id and the value is the row data. Before this change, the row data in this object would remain the same even if the `data` prop changed. In this PR, I am adding an effect which keeps this `rowSelection` object in sync with the latest data.
> fix(mantine): make sure rowSelection row data stays fresh

- packages/website/build/start.js
- packages/website/package.json
- turbo.json
The new major version of turbo repo enforces a whitelist for environment variables that needs to be defined in the turbo.json config. You can read more about it here https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables, but essentially this was preventing the `GITHUB_*` and `CI` variables defined by the GitHub runners from reaching Vite.
To test the change, you can simply open the demo link and see that it works like it used to.
> ci: fix demo not building properly

- packages/mantine/src/components/table/Table.tsx
I need to remove the padding on the table for a feature, to avoid putting !important I have to modify this line
> feat: modification of the table in plasma to be able to modify the padding of the table

- packages/mantine/src/components/table/Table.tsx
While debugging an issue with the click outside handler I saw that the table re-rendered each time I clicked outside even if no rows where selected. In this PR I avoid calling the clear method if no rows are selected
None
> fix(mantine, table): avoid clearing rows when no rows are selected

- packages/mantine/src/components/prompt/Prompt.context.ts
- packages/mantine/src/components/prompt/Prompt.module.css
- packages/mantine/src/components/prompt/Prompt.tsx
- packages/mantine/src/components/prompt/PromptCancelButton.tsx
- packages/mantine/src/components/prompt/PromptConfirmButton.tsx
- packages/mantine/src/components/prompt/PromptFooter.tsx
- packages/mantine/src/components/prompt/__tests__/Prompt.spec.tsx
- packages/mantine/src/components/prompt/icons/critical.svg
- packages/mantine/src/components/prompt/icons/info.svg
- packages/mantine/src/components/prompt/icons/success.svg
- packages/mantine/src/components/prompt/icons/warning.svg
- packages/mantine/src/theme/Theme.tsx
- packages/mantine/src/types/svg/index.d.ts
- packages/website/src/examples/layout/Prompt/PromptCritical.demo.tsx
- packages/website/src/examples/layout/Prompt/PromptSuccess.demo.tsx
- packages/website/src/examples/layout/Prompt/PromptWarning.demo.tsx
- packages/website/src/pages/layout/Prompt.tsx
Updated the look of the prompt component
| Before | After | Mockup |
| <img width="687" alt="image" src="https://github.com/coveo/plasma/assets/260007/8a6e1213-381d-48a7-b2f4-9e158c17e017"> | <img width="685" alt="image" src="https://github.com/coveo/plasma/assets/260007/315e32a8-d3d0-400d-a43d-9d3544ea0041"> | <img width="720" alt="image" src="https://github.com/coveo/plasma/assets/260007/bd06a499-7d0e-4e13-be01-269d8757e028"> |
The prompt now uses the compound components (Modal.Root, Modal.Header, etc) from Mantine's Modal instead of using Modal
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the …
> feat(mantine, prompt): update look of prompt component

- .github/actions/setup/action.yml
The pnpm-setup action is broken. We cannot update to latest version. Leverage corepack instead
None
> chore: replace pnpm/action-setup

- packages/components-props-analyzer/tsconfig.build.json
- packages/components-props-analyzer/tsconfig.json
- packages/mantine/tsconfig.build.json
- packages/mantine/tsconfig.json
- packages/react-icons/tsconfig.build.json
- packages/react-icons/tsconfig.json
- packages/tokens/tsconfig.build.json
- packages/tokens/tsconfig.json
- packages/tsconfig-base.json
- scripts/build.js
With the new TypeScript 5.5 we can leverage the ${configDir} variable in tsconfig. This simplifies our tsconfig quite a lot and allowed me to even delete the tsconfig.build.json
ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#the-configdir-template-variable-for-configuration-files
None
> chore: simplify tsconfig files

- packages/mantine/src/styles/Tabs.module.css
- packages/mantine/src/theme/Theme.tsx
Fixed the look of the Tabs component.
- Increased line height
- Used css variables to override border width and color
- Changed the default padding of Tab
| --- | --- |
| <img width="373" alt="image" src="https://github.com/user-attachments/assets/4e9e7a35-3a36-446c-af99-3c067711a06e"> | <img width="303" alt="image" src="https://github.com/user-attachments/assets/32687e46-d9fc-4272-87c9-9ed8d8eadfb6"> |
| <img width="240" alt="image" src="https://github.com/user-attachments/assets/42472db9-ac84-47f3-bdc1-b01822db3e3d"> | <img width="212" alt="image" src="https://github.com/user-attachments/assets/31208c2a-651a-4d8d-bf32-7de29cf16af1"> |
None
-   [ ] …
> fix(mantine, tabs): apply changes to style

- packages/mantine/src/components/prompt/Prompt.tsx
Center the prompt component by default.
No
> fix(mantine, prompt): center the prompt component by default

- eslint.config.mjs
- packages/components-props-analyzer/bin/getPropsOfComponent.ts
- packages/components-props-analyzer/package.json
- packages/components-props-analyzer/tsconfig.build.json
- packages/mantine/package.json
- packages/mantine/tsconfig.build.json
- packages/react-icons/package.json
- packages/react-icons/tsconfig.build.json
- packages/tokens/package.json
- packages/tokens/tsconfig.build.json
- packages/tsconfig-base.json
- packages/website/package.json
- scripts/build.js
I saw that renovate PRs [were failling](https://github.com/coveo/plasma/actions/runs/10345730745/job/28633183570) due to an ESLint error. I made sure our tsconfig included all relevant files and added a tsconfig.build.json to exclude files when we build
None
> chore: fix eslint configuration

- packages/mantine/src/styles/Skeleton.module.css
This fixes the issue with buttons, indicator, etc being visible when wrapped by a Skeleton 
https://mantine.dev/styles/css-variables/#z-index-variables
The z-index changed but it shouldn't break anything ™️ 
> fix(mantine, skeleton): increase z-index

- packages/mantine/src/components/date-range-picker/DateRangePickerInlineCalendar.tsx
- packages/mantine/src/components/date-range-picker/DateRangePickerPopoverCalendar.tsx
Applied requested changes to the date picker. It now scroll month by month even if it shows two months
https://github.com/user-attachments/assets/d53b5d85-518a-4ccb-b167-8d16f5202ac0
None
> fix(mantine, date picker): scroll one month instead of two

- packages/mantine/src/components/table/layouts/row-layout/RowLayout.tsx
Fixed warning that was thrown when using the RowLayout in a table.  
```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
```
None
> fix(mantine, table): react warning for unused ref on RowLayout

- packages/mantine/src/components/table/table-pagination/TablePagination.tsx
Updated the pagination boundaries to match UX's suggestion.
None
> fix(mantine, table): change the pagination boundaries

- .github/renovate.json5
Currently renovate creates a separate PR from the minor/patch one for ui-kit (headless, atomic) and tanstack (query, table, etc) packages even if the bump is a patch or a minor which creates a lot of noise. I updated the config to only group the major of those packages
None
> chore(renovate): only split major versions

- packages/mantine/src/styles/Radio.module.css
- packages/mantine/src/theme/Theme.tsx
As per designers demand, we are changing the Radio label color from default gray-9 to gray-7.
Before
After
> fix(mantine): change Radio label color to gray-7

- packages/mantine/src/styles/Badge.module.css
- packages/mantine/src/theme/Theme.tsx
- packages/website/src/pages/foundations/Colors.tsx
- packages/website/src/pages/index.tsx
Designs we receive sometimes require spacing of 4px, which is smaller than xs (8px). Having a `xxs` size variant avoids resorting to a custom css module with custom css rules for those cases.
This PR adds the `xxs` sapcing to the Plasma theme.
> feat(mantine): add xxs spacing size to plasma theme

- packages/react/src/components/modalWizard/ModalWizard.tsx
- packages/react/src/components/modalWizard/tests/ModalWizard.spec.tsx
- packages/website/src/examples/legacy/layout/ModalWizard/ModalWizardWithProvidedFinishButton.demo.tsx
- packages/website/src/pages/legacy/layout/ModalWizard.tsx
* Added a `renderFinishButton` prop to the modal wizard component to allow users to configure the primary button action on the last step;
* Added a test;
* Added a demo for the usage of this new prop.
None. The added prop is optional.
> feat(react, modal-wizard): add renderFinishButton prop

- packages/mantine/src/components/table/index.ts
This [PR](https://github.com/coveo/plasma/pull/3885) did not export `TablePredicateProps` using type-only so it throws an error when running the admin
> fix(table): type only import for table predicate props

- packages/mantine/src/components/table/__tests__/TablePredicate.spec.tsx
- packages/mantine/src/components/table/table-predicate/TablePredicate.tsx
BREAKING CHANGE: the Table.Predicate label prop is now required.
We are making the Table.Predicate prop `label` required so that users always know what they are filtering on. We have seen implementations where the implementer forgot to add a label and it was unclear for the user.
> fix(mantine): make Table.Predicate label prop required

- packages/mantine/src/components/read-only/ReadOnlyInputStyles.ts
- packages/mantine/src/theme/Theme.tsx
The required asterisk of Select components had a shade too light when not in read only.
|| Before | After |
|---| --- | --- |
| Normal | ![image](https://github.com/user-attachments/assets/5053c5ce-c215-4644-af7d-d7c7a88135fc) | ![image](https://github.com/user-attachments/assets/2fd3c0b2-c769-46c2-be5f-d7a97248c87c) |
| Read only | ![image](https://github.com/user-attachments/assets/0ded319e-b944-419a-9def-f5a8628926c6) | ![image](https://github.com/user-attachments/assets/050f6869-958b-4d26-beec-cdddd7f3040e) |
> fix(mantine): select asterisk color is too light

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/components/ellipsis-text/EllipsisText.module.css
- packages/mantine/src/components/ellipsis-text/EllipsisText.tsx
- packages/mantine/src/components/ellipsis-text/index.ts
- packages/mantine/src/components/index.ts
- packages/mantine/src/styles/Tooltip.module.css
- packages/mantine/src/theme/Theme.tsx
- packages/website/src/Navigation.tsx
- packages/website/src/examples/layout/EllipsisText/EllipsisText.demo.tsx
- packages/website/src/pages/layout/EllipsisText.tsx
Created the `EllipsisText` component that allows to truncate content and show a tooltip with the full length of the content if it overflows the max width.
> feat(mantine,website): create the EllipsisText component

- packages/mantine/src/styles/List.module.css
If we want to use the ordered type on the List component, then `list-style-type` is set to `disc` by default instead of `decimal`.
I've simply defined a root class for each HTML tag (ul and ol)
```
<List type="ordered">
<List.Item>Clone or download repository from GitHub</List.Item>
<List.Item>Install dependencies with yarn</List.Item>
<List.Item>To start development server run npm start command</List.Item>
<List.Item>Run tests to make sure your changes do not break the build</List.Item>
<List.Item>Submit a pull request once you are done</List.Item>
</List>
```
https://mantine.dev/core/list/
By the way, this `<List type=“ordered”>` is only used in the documentation website, so the impact is to delete the documentation website theme update.
-   [ ] The proposed changes are covered by unit …
> fix: improve List component style

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/components/child-form/ChildForm.module.css
- packages/mantine/src/components/child-form/ChildForm.tsx
- packages/mantine/src/components/child-form/__tests__/ChildForm.spec.tsx
- packages/mantine/src/components/child-form/index.ts
- packages/mantine/src/components/index.ts
- packages/website/src/Navigation.tsx
- packages/website/src/examples/form/child-form/ChildForm.demo.tsx
- packages/website/src/examples/form/child-form/ChildFormWithForm.demo.tsx
- packages/website/src/examples/form/child-form/ChildFormWithTitleAndDescription.demo.tsx
- packages/website/src/pages/form/ChildForm.tsx
Added a new `ChildForm` component. This pattern for forms is used at a couple of places in the Admin-UI but each place has its own implementation with different styling. 
On our side, we have a need for it for two features we are currently working on, so I thought it would be a good time to add it.
I validated with UX to make sure the styling was up to their liking. 
[Figma](https://www.figma.com/design/NRBnfgMxgVs7h6qwP6ADBV/Elevation-%26-Focus-FX---PDS?node-id=804-297&node-type=frame&m=dev).🎨 
[Demo](https://plasma.coveo.com/feature/SEARCHAPI-11252-child-form/form/ChildForm). 🧪 
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to …
> feat(mantine): ChildForm component

- packages/mantine/src/components/ellipsis-text/EllipsisText.module.css
- packages/mantine/src/components/ellipsis-text/EllipsisText.tsx
When using the EllipsisText component inside other components like buttons or nav links, I realized that its style was sometimes creating unwanted overrides.
This PR makes the component more adaptable to its parent style:
- Changing the Text node to be a `span` instead of a `p`
- Adding `inherit` prop on the text node, so that it can take its parent text styles
- Ensuring `width` and `display` can easily be overridden via the styles API
None, the component should look exactly as it did before
> fix(mantine): make EllipsisText style more adaptable

- packages/mantine/src/components/prompt/Prompt.tsx
- packages/mantine/src/components/prompt/PromptConfirmButton.tsx
This feature will unblock this task
https://coveord.atlassian.net/browse/ADUI-10365
This PR adds the ButtonDisabledTooltip to the Prompt.Confirm button so that we can use the button component with the functionality of the tooltips
> feat(prompt): +disabledwithtooltip on confirm button

- packages/mantine/src/components/table/Table.module.css
- packages/mantine/src/components/table/table-actions/TableActionsList.tsx
When a table has secondary actions that render nothing, the "More" menu would still show up.
The current PR solves that problem, by hiding the menu target if the menu dropdown does not render any menu item. For this to work, the menu dropdown has to always be rendered so that the CSS can properly query the DOM nodes of its content
> fix(mantine): hide table more menu if no actions are visible

- packages/components-props-analyzer/src/ComponentsList.ts
- packages/mantine/src/components/date-range-picker/DateRangePickerPopoverCalendar.tsx
- packages/website/src/Navigation.tsx
- packages/website/src/building-blocs/PageHeader.tsx
- packages/website/src/examples/date-range/inline/DateRangePickerInlineCalendar.demo.tsx
- packages/website/src/examples/date-range/popover/DateRangePickerPopoverCalendar.demo.tsx
- packages/website/src/pages/date-range/DateRangePickerInlineCalendar.tsx
- packages/website/src/pages/date-range/DateRangePickerPopoverCalendar.tsx
Fixed issue with `DateRangePickerPopoverCalendar` popover opening in the top left
Added demo for `DateRangePickerPopoverCalendar` and `DateRangePickerInlineCalendar`
None
> fix(mantine, date-range): popover opens close to dropdown

- packages/mantine/src/components/table/Table.module.css
For most implementations, this fix will be transparent. It mostly impacts tables that are displayed within a flex container. In this situation, the table will take the full with of that flex container instead of minimally fitting the content of the table.
Example
If we imagine the following component:
```tsx
<Box display="flex">
<Table {...} />
</Box>
```
Before
After
> fix(mantine): make table root have 100% width

- packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx
- packages/mantine/src/components/table/table-column/TableSelectableColumn.tsx
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
Prevent table double click action from being triggered when the user double clicks on a row selection checkbox. 
> fix(table): prevent double click action on row selection checkboxes

- packages/mantine/src/components/table/__tests__/TableColumnsSelector.spec.tsx
- packages/mantine/src/components/table/__tests__/TableDateRangePicker.spec.tsx
- packages/mantine/src/components/table/__tests__/TableFilter.spec.tsx
- packages/mantine/src/components/table/__tests__/TablePagination.spec.tsx
- packages/mantine/src/components/table/__tests__/TablePerPage.spec.tsx
- packages/mantine/src/components/table/__tests__/TablePredicate.spec.tsx
- packages/mantine/src/components/table/__tests__/Th.spec.tsx
- packages/mantine/src/components/table/__tests__/use-url-synced-state.unit.spec.ts
- packages/mantine/src/components/table/use-table.ts
- packages/mantine/src/components/table/use-url-synced-state.ts
- packages/website/src/examples/layout/Table/TableClientSide.demo.tsx
- packages/website/src/examples/layout/Table/TablePredicate.demo.tsx
Add `syncWithUrl` option to `useTable` hook. When true, the table will sync its state with the url using search parameters.
> feat(mantine): add syncWithUrl option to table hook

- packages/mantine/src/components/date-range-picker/DateRangePickerInlineCalendar.tsx
- packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerInlineCalendar.spec.tsx
**TL;DR**: change the time part of the end value of the Date (range) picker to be "end-of-day" (`23:59:59.999`) instead of "start-of-day" (`00:00:00.000`).
The change in itself isn't that involved, but explaining why I think it is necessary and why I chose this particular solution does require some background. What follows is the long explanation, so grab your favorite beverage and settle in.
When you encode a range, you have to decide whether the upper bound is **inclusive** or **exclusive**. Which one you prefer and/or use ultimately comes down to personal preference. Things go bad when you mix up the two concepts though, as you are very likely to run into an off-by-one error. (More specifically, it can lead to ["fencepost errors"](https://en.wikipedia.org/wiki/Off-by-one_error#Fencepost …
> fix(table-date-picker): date range picker end date at end of day

- packages/mantine/src/components/table/__tests__/use-url-synced-state.unit.spec.ts
- packages/mantine/src/components/table/index.ts
- packages/mantine/src/components/table/use-table.ts
- packages/mantine/src/components/table/use-url-synced-state.ts
[ADUI-10457](https://coveord.atlassian.net/browse/ADUI-10457)
> ⚠️ The scope of these changes is a bit more than strictly required for the mentioned defect fix, since this fix was done as part of an effort to use `useUrlSyncedState` from Admin-UI.
The short summary:
- Export `useUrlSyncedState`, so it can be used from Admin-UI too.
_(It appears to be the best way forward for Data Platform Foundation to fix another state + search parameters related issue)._
- Support the "hash router", that puts the page path inside the hash (`#`) section of the URL.
Officially the 'search' part comes before the 'hash', but for page hashes there should be a "fake" search inside the hash path too. This makes sense when you realize that the whole reason for using the HashRouter is making sure you don't send …
> feat(mantine): export useUrlSyncedState and support hash router [ADUI-10457]

- packages/mantine/src/components/table/table-predicate/TablePredicate.tsx
Before
https://github.com/user-attachments/assets/807a9d32-786a-4517-b263-3e7eedcdc048
After
https://github.com/user-attachments/assets/9b09ad86-7c9e-4bd6-ae79-0fed140dc952
> fix(mantine,table): make table predicate scroll more visible

- packages/mantine/src/components/table/__tests__/use-url-synced-state.unit.spec.ts
- packages/mantine/src/components/table/index.ts
- packages/mantine/src/components/table/use-table.ts
- packages/mantine/src/components/table/use-url-synced-state.ts
> ⚠️ While this PR adds a feature, it also fixes bad behavior I introduced in #3992. Details are in the description below, but in short: I added use of `useMemo`, but it was completely useless, as I put the serializer in the dependencies. If you put the serializer in-line (like `useTable` did), it'll be invalidated **on every render**. The whole approach I took was flawed, so it has been rewritten.
I wrote another long PR description do explain all the details and decisions, so here's a summary:
Use Case for the features: Particularly useful for `from` and `to` (dateRange) states in the table. Ensures consistent URL parameters for sharing links, even if the initial state changes over time.
- Added an "alwaysEmit" flag to the `useUrlSyncedState` hook (serialization), ensuring non-empty …
> feat(useUrlSyncedState): allow always emitting values

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/website/src/examples/form/code-editor/CodeEditorPython.demo.tsx
Allow setting a custom `tabSize` in the `CodeEditor` component.
Previously, it was hardcoded to `2` but let's say for example you use the editor to write Python code and want to follow the `PEP8` guidelines, you need to set `4`.
Demo [here](https://plasma.coveo.com/feature/SEARCHAPI-11667-code-editor-tabs/form/CodeEditor). 🧪 
📖 This prop is supported by the `Monaco Editor` and documented [here](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IStandaloneEditorConstructionOptions.html#tabSize).
⚠️ Note: According to the Monaco Editor's documentation on `tabSize`:
> This setting is overridden based on the file contents when detectIndentation is on. 
So this means that if you set a `tabSize` of 4, but the content of the editor is using 2 spaces, it will enforce a `tabSize` …
> feat(code-editor): support custom tabSize

- packages/mantine/src/components/code-editor/CodeEditor.tsx
Currently, the `CodeEditor` uses the default formatting provided by the Monaco Editor. For `json` language, the editor inherently relies on `vscode-json-languageservice`, which does a best-effort formatting of the text regardless whether the JSON is valid or not.
However, in the scenario where the JSON is invalid, we've observed UI issues caused by the formatting, where the mouse pointer is relocated to the end of the text:
https://github.com/user-attachments/assets/d5766c42-2259-4f30-af3c-32519328475f
Thus we want to disable the best-effort formatting. This is done by overriding the default formatter with a simple `JSON.stringify(JSON.parse(model.getValue()), null, tabSize)`, which will fail in invalid scenarios and thus does nothing.
None since change is behavioral.
-   [ ] The proposed …
> fix(CodeEditor): format text only on valid input

- packages/mantine/src/components/code-editor/CodeEditor.tsx
Since the code formatting now has a timeout, we no longer have guarantee that the editor is still mounted by the time the formatting code is executed. We thus need to make sure that the code doesn't break on undefined or null values.
> fix(CodeEditor): do not format if editor closed

- packages/style/scss/components/multiselect-input.scss
[SEARCHAPI-9091
](https://coveord.atlassian.net/browse/SEARCHAPI-9091)
There was a display issue in the legacy Plasma-React multi-select. When in you added a long custom value, it would sometime hide the clear button.
📷 Before
📷 After
Demo [link](https://plasma.coveo.com/feature/SEARCHAPI-9091-fix-multiselect-truncate/legacy/form/MultiSelect). 🧪 
None.
> fix(multi-select): truncate long custom values

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/HeaderRight/HeaderRight.tsx
- packages/mantine/src/components/header/__tests__/Header.spec.tsx
- packages/website/src/examples/layout/Header/Header.demo.tsx
- packages/website/src/examples/layout/Header/HeaderSecondary.demo.tsx
We need to achieve something like :point_down: in the Coveo Knowledge Hub
I think I could achieve this throught the `Header.Action` compound, since its location is proper and it can take any react node.
But it wouldn't feel right and make the implementation code confusing.
Renamed `Header.Actions` to Header.Right in order to reflect that the compound component can render more than just actions.
Header.Actions can still be used in order to keep retro compatibility. But its future usage will be discouraged in favor of the renamed version.
None of the actually implemented header should be impacted.
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is …
> feat(header): refactor of the Header.Actions compound to become Header.Right

- packages/mantine/src/components/header/Header.module.css
- packages/mantine/src/styles/Breadcrumbs.module.css
- packages/mantine/src/styles/Checkbox.module.css
- packages/mantine/src/styles/CheckboxIndicator.module.css
- packages/mantine/src/styles/Input.module.css
- packages/mantine/src/styles/Pagination.module.css
- packages/mantine/src/styles/Radio.module.css
- packages/mantine/src/theme/Theme.tsx
- packages/mantine/src/theme/__tests__/plasmaCSSVariablesResolver.spec.ts
- packages/mantine/src/theme/plasmaCSSVariablesResolver.ts
- packages/website/src/examples/layout/Header/Header.demo.tsx
Adjusted breadcrumbs style to match Figma
Renamed a custom variable I created to `--coveo-...` instead of `--mantine-...` to make it clear it's us that define it
None
> Breadscrumbs styles

- packages/mantine/src/components/prompt/Prompt.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.demo.tsx
- packages/website/src/examples/layout/Prompt/Prompt.demo.tsx
- packages/website/src/examples/layout/Prompt/PromptCritical.demo.tsx
- packages/website/src/examples/layout/Prompt/PromptSuccess.demo.tsx
- packages/website/src/examples/layout/Prompt/PromptWarning.demo.tsx
Updated the prompt to display the title in a `<Header variant="secondary">` if the title is a string
Updated the Modal example to omit the Modal.Title since it renders a `H2` and we put a complex component inside it
None
> Fix Prompt title and Modal demo

- packages/mantine/src/components/code-editor/CodeEditor.tsx
- packages/mantine/src/components/code-editor/__tests__/CodeEditor.spec.tsx
We had an issue where the switch tabs and code editor doesn't play well together when doing `ctrl-z`, since we change the content of the editor based on the  selected tab. Doing an "undo(ctrl-z)" after switching tab would set the content to the content of the previous tab. We added the `clearUndoStack` method to be able to clear the stack when switching tabs and prevent this behaviour
Here's an example of an issue we have.
Here I pressed `ctrl-z` after switching tab and it sets the value to the old tab content.
- Added a new optional `editorRef` prop to the `CodeEditor` component, allowing external access to the editor instance. Specifically, the `editorRef` exposes a `clearUndoStack` method that, when called, resets the editor's content to its current value, effectively clearing the undo …
> feat(codeEditor): front the editor instance

- packages/mantine/src/theme/Theme.tsx
Remove the margin-top on Inputs if they don't have a description or label
Before
After
The difference is minor (4px)
None
> fix(mantine, input): only add margin top if there's a title or description

- packages/mantine/src/components/copyToClipboard/CopyToClipboard.tsx
Making improvements to the CopyToClipboard component:
- add access to the click event from the `onCopy` prop
- extend ActionIcon props
- allow overriding tooltip texts
- update icons using the new iconography
> feat(mantine): improve CopyToClipboard component

- packages/mantine/src/components/loader/CircleLoader.module.css
- packages/mantine/src/components/loader/CircleLoader.tsx
- packages/mantine/src/theme/Theme.tsx
| Before | After | Figma |
| <img width="51" alt="image" src="https://github.com/user-attachments/assets/e6cf32ba-7b29-44d5-8864-19e3e62a7fe9" /> | <img width="50" alt="image" src="https://github.com/user-attachments/assets/14ed0fe6-6e66-497f-89b5-0dbac1c1355f" /> | <img width="50" alt="image" src="https://github.com/user-attachments/assets/e7dccac9-6202-4269-95f8-85d3e6c71bce" /> |
Demo: https://plasma.coveo.com/feature/feat-ADUI-10692-loader-style/mantine/Loader
None
> feat(mantine, loader): custom loader to match figma

- packages/mantine/src/styles/Pagination.module.css
https://coveord.atlassian.net/browse/ADUI-10590
Added root variables override for active bg-color and active-color with respect to UX recommendations.
[figma](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Pretine-7-for-Coveo?node-id=8613-333163&m=dev&focus-id=10073-410423)
Even though UX requested changes for Hover & disabled, we want to make adjustments only through css variables and mantine does not provide any for these two use case. So as a first iteration, we will keep it like this, as close to mantine as possible.
> feat(pagination): +active-bg +active-color

- packages/mantine/src/styles/Radio.module.css
- packages/mantine/src/theme/plasmaCSSVariablesResolver.ts
This removes some previous custom style that would remove the builtin visual behavior of the error radio button to reflect mantine better. The ux request cannot be fulfilled completely because of lack of css variable accessible from mantine to cover their demands.
[discussion](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd?node-id=9038-234373&m=dev#1244897930)
> Ad UI 10593 apply style radio

- packages/mantine/src/components/collection/Collection.tsx
- packages/mantine/src/components/collection/CollectionItem.tsx
- packages/mantine/src/components/collection/__tests__/Collection.spec.tsx
Added data-testid attribute to remove buttons that has the matching CollectionItem item ids. This way we can differentiate between remove buttons of the same collection.
[Jira Link](https://coveord.atlassian.net/browse/ADUI-10483?atlOrigin=eyJpIjoiMWEzNTUxOTY4ZThkNGYyODgzZDJjMjBiNWNiMTdlZWEiLCJwIjoiaiJ9)
> feat(collection): add-data-testid-param-to-collection

- packages/mantine/src/components/table/Table.module.css
- packages/mantine/src/components/table/table-header/TableHeader.tsx
- packages/mantine/src/styles/Tabs.module.css
- packages/website/src/examples/layout/Table/Table.demo.tsx
- packages/website/src/examples/layout/Table/TableClientSide.demo.tsx
- packages/website/src/examples/layout/Table/TableColumnsSelector.demo.tsx
- packages/website/src/examples/layout/Table/TableConfirmAction.demo.tsx
- packages/website/src/examples/layout/Table/TableDateRangePicker.demo.tsx
- packages/website/src/examples/layout/Table/TableDisabledRowSelection.demo.tsx
- packages/website/src/examples/layout/Table/TableLayouts.demo.tsx
- packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx
- packages/website/src/examples/layout/Table/TablePredicate.demo.tsx
- packages/website/src/examples/layout/Table/TableReactQuery.demo.tsx
Updated the style of the Tab component to match latest UX design
Before 
After
Gallery is hovered, Settings disabled, Account is default and Chat is selected
Figma:
I also added a new optional `borderTop` prop on the Table (with a default of true). And updated the demo to remove the double border. We'll be able to do the same thing when one tab first child is a Table with an Header
None
> feat(mantine, tabs): update the style

- packages/mantine/src/components/header/Header.module.css
- packages/mantine/src/components/table/Table.module.css
- packages/mantine/src/styles/Alert.module.css
- packages/mantine/src/styles/Badge.module.css
- packages/mantine/src/styles/Button.module.css
- packages/mantine/src/styles/InputWrapper.module.css
- packages/mantine/src/styles/Modal.module.css
- packages/mantine/src/styles/NavLink.module.css
- packages/mantine/src/styles/SegmentedControl.module.css
- packages/mantine/src/styles/Stepper.module.css
- packages/mantine/src/styles/Table.module.css
- packages/mantine/src/styles/Tabs.module.css
- packages/mantine/src/styles/Text.module.css
- packages/mantine/src/styles/global.css
- packages/mantine/src/theme/plasmaCSSVariablesResolver.ts
- packages/website/src/styles/main.css
Adding 3 new CSS variables to streamline font-weights. The Gibson font is picky with weights, it gets way too bold, too quickly.
Here are the new variables:
- `--coveo-fw-bold`
- `--coveo-fw-normal`
- `--coveo-fw-light`  
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> feat(variables): create CSS variables for font-weight

- packages/mantine/src/components/code-editor/CodeEditor.tsx
Disabling monaco-editor's `stickyScroll` feature to prevent the big empty space issue:
https://github.com/user-attachments/assets/91861356-3cd7-4ec4-9423-c5bfe52d06fd
To test this in the demo, you can go in the CodeEditor demo page and paste a big json object with a lot of nested properties in the JSON code editor example. You will see that the "stickyScroll" behaviour is no longer there.
> fix(mantine): disable CodeEditor stickyScroll

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/modal/Modal.module.css
- packages/mantine/src/components/modal/Modal.tsx
- packages/mantine/src/components/modal/ModalFooter.module.css
- packages/mantine/src/components/modal/ModalFooter.tsx
- packages/mantine/src/components/modal/__tests__/Modal.spec.tsx
- packages/mantine/src/components/modal/__tests__/ModalFooter.spec.tsx
- packages/mantine/src/components/prompt/Prompt.module.css
- packages/mantine/src/components/prompt/Prompt.tsx
- packages/mantine/src/components/sticky-footer/StickyFooter.module.css
- packages/mantine/src/styles/Modal.module.css
- packages/website/src/examples/layout/Modal/Modal.demo.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.demo.tsx
- packages/website/src/examples/layout/Modal/ModalWithTabs.module.css
- packages/website/src/pages/layout/Modal.tsx
Changing the Modal component so that it fits the new mockups, but also simplifying its usage. It should be no longer necessary (but still possible) to resort to using the Modal compound components.
|Before|After|
|---|---|
|<img width="931" alt="image" src="https://github.com/user-attachments/assets/01fe7681-b495-41dc-85a6-8e0f049258a7" />|<img width="924" alt="image" src="https://github.com/user-attachments/assets/1205e2e3-ac54-40c4-9988-e35a3aa8ceee" />|
|<img width="934" alt="image" src="https://github.com/user-attachments/assets/ac614d46-b404-486e-93e9-9387f6c06493" />|<img width="928" alt="image" src="https://github.com/user-attachments/assets/df35b291-549c-41e7-8e64-38f62957b79d" />|
|<img width="696" alt="image" src="https://github.com/user-attachments/assets/8264f389-cf3b-4ef5-8645 …
> feat(mantine): simplify modal usage

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/header/__tests__/Header.spec.tsx
Making sure the Header with variant secondary remains a `h3`.
|Before|After|
|---|---|
|<img width="346" height="290" alt="image" src="https://github.com/user-attachments/assets/95e5a116-7a1a-439a-be8e-0818032acc1b" />|<img width="344" height="286" alt="image" src="https://github.com/user-attachments/assets/bd7ee955-36ab-48d3-b27d-6d7cff6e231a" />|
> fix(mantine,header): header secondary order

- packages/mantine/src/styles/Select.module.css
- packages/mantine/src/theme/Theme.tsx
This PR does not change much from the previous [PR](https://github.com/coveo/plasma/pull/4062) that applied style to Select component appart 
- removing the arrow from the popover
- popover shadow
- modifying option padding
- option border-radius
[JIRA](https://coveord.atlassian.net/browse/ADUI-10883)
[Figma](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Opal-Components--Pretine-source-library-?node-id=8613-333163&p=f&m=dev)
> Ad UI 10883 select style changes

- packages/mantine/src/styles/NavLink.module.css
Adjusting the NavLink styles so that the rules specificity doesn't increase to a point where it surpasses what we have in the admin-ui.
Before
After
Reasoning:
> fix(mantine,navlink): reduce style specificity

- packages/mantine/src/styles/RadioCard.module.css
- packages/mantine/src/theme/Theme.tsx
[JIRA](https://coveord.atlassian.net/browse/ADUI-10704)
[FIGMA](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Opal-Components--Pretine-source-library-?node-id=10029-56434&t=mI7ocwIoeGdyDPDt-0)
On hover:
Before:
After:
Mockups:
This change can only be seen by modifing the RadioCard demo in the Radio section of Mantine components. You need to remove the hover color in the Radio.demo.card.module.css file and you should see the new color appear on hover.
> Ad UI 10704 apply style changes to radio card

- packages/mantine/src/styles/InputWrapper.module.css
- packages/mantine/src/styles/Pill.module.css
Most of the MultiSelect visual changes were already made from a previous PR. 
[FIGMA](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Opal-Components--Pretine-source-library-?node-id=10364-11750&m=dev)
[JIRA](https://coveord.atlassian.net/browse/ADUI-10892)
I have changed to the correct text color for the `Pill` component and I put back the 4px gap between label and description of the inputWrapper
| | Before | After |
|----------|----------|----------|
| Pill    | <img width="71" height="42" alt="image" src="https://github.com/user-attachments/assets/e0ab4b01-f88e-4348-aa35-f97f01f199a6" />     | <img width="58" height="42" alt="image" src="https://github.com/user-attachments/assets/aa9235e5-806c-4831-8ff9-435657cc2a28" />     |
| InputWrapper | <img width="401" height="138" …
> feat(multiselect): change pill text color, revert gap inputwrapper

- packages/mantine/src/components/browser-preview/BrowserPreview.module.css
- packages/mantine/src/components/browser-preview/BrowserPreview.tsx
- packages/mantine/src/components/browser-preview/__tests__/BrowserPreview.spec.tsx
- packages/mantine/src/components/info-token/InfoToken.tsx
Update the style of the BrowserPreview component
|Before|After|Mockup|
|---|---|---|
|<img width="591" height="749" alt="image" src="https://github.com/user-attachments/assets/d37727d8-097b-4aef-8304-b32ba3075ebb" />|<img width="593" height="749" alt="image" src="https://github.com/user-attachments/assets/17b8265c-d47a-4623-bf58-3d64855e4591" />|<img width="574" height="685" alt="image" src="https://github.com/user-attachments/assets/0e1de6f8-a1bd-4274-8e02-dc7c1420567d" />|
> feat(mantine,browserpreview): update style

- packages/mantine/src/styles/Card.module.css
- packages/mantine/src/styles/Paper.module.css
- packages/mantine/src/theme/Theme.tsx
- packages/website/src/examples/layout/Table/TableLayouts.demo.tsx
Added a "hover" variant on [Mantine's Card component](https://mantine.dev/core/card/) and a "selected" state. This way it allows us to cover all required use cases.
Example with the table card layout
https://github.com/user-attachments/assets/325258a0-e943-4119-aee3-a0e3767569e8
Mockups
> feat(mantine,card): create card variant hover and selected state

- packages/mantine/src/styles/ActionIcon.module.css
- packages/mantine/src/theme/Theme.tsx
Changed the default ActionIcon size to 36px
> feat(actionicon): change default size to 36px

- packages/mantine/src/components/prompt/Prompt.tsx
Removed the double padding between the content of the `Prompt` and the footer by removing the padding top on the `Prompt.Footer`.
| Before | After | 
| --- | --- |
| <img width="675" height="287" alt="image" src="https://github.com/user-attachments/assets/a418d917-6c63-42b1-ae5d-01b48fc8491f" /> | <img width="673" height="257" alt="image" src="https://github.com/user-attachments/assets/1bd44f48-ff57-42f4-97c9-7b18ca5d0384" /> |
None
> fix(Mantine, Prompt): padding between body and footer

- packages/mantine/src/components/header/Header.tsx
- packages/mantine/src/components/prompt/Prompt.tsx
- packages/mantine/src/components/prompt/PromptCancelButton.tsx
- packages/mantine/src/components/prompt/PromptConfirmButton.tsx
- packages/mantine/src/components/table/Table.tsx
- packages/mantine/src/components/table/TableContext.tsx
- packages/mantine/src/components/table/index.ts
- packages/mantine/src/components/table/table-pagination/TablePagination.tsx
- packages/mantine/src/components/table/table-per-page/TablePerPage.tsx
- packages/tokens/src/index.ts
This pull request updates import statements to consistently use explicit `.js` file extensions that were forgotten in the last PR (#4145). No changes to logic or functionality were made—only import paths were updated for compatibility.
> fix: remaining imports without explicit file extension

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- package.json
- scripts/turboLogin.mjs
- turbo.json
This pull request introduces improvements to Turborepo remote caching and streamlines the setup for local development and CI/CD workflows. The main changes include adding a script for Turborepo authentication using AWS SSM, updating workflow files to use the `TURBO_TOKEN` secret, and configuring remote caching in Turborepo. These updates help ensure that remote caching is enabled for faster builds and that authentication is handled securely and automatically.
<details>
<summary>More details</summary>
**Turborepo Remote Caching Setup:**
* Added a new script `scripts/turboLogin.mjs` that automates fetching the Turborepo token from AWS SSM and configures it locally, improving developer experience and security.
* Updated `turbo.json` to enable remote caching with the correct team slug and API …
> ci: enable turbo remote caching

- packages/react-icons/turbo.json
Added an override for turbo cache in react-icons, since it produce the mock/index.js artefact
None
> fix(react-icons): missing element in cache prevent package publish
