gulpfile.js
karma.entry.ts
package.json
src/components/ChosenSelect.tsx
src/components/Popover.tsx
src/components/Svg.tsx
src/components/Tooltip.tsx
src/utils/ReduxUtils.ts
tsconfig.json
tsconfig.test.json
webpack.config.prod.js

* Bundle react-tether definition file in react-vapor.d.ts
- Remove chosen-js and tether from peerDependencies
+ Add react-redux and redux to peerDependencies (and stop bundling them)
* Minor random improvements

Peer dependencies rework!

---

package.json
webpack.config.prod.js

I did my fix based on that: https://github.com/webpack/webpack/issues/1275#issuecomment-245470919

! Fix web pack externals definition

---

src/components/facets/FacetMoreRows.tsx
src/components/facets/tests/FacetMoreRows.spec.tsx
src/components/filterBox/FilterBox.tsx
src/components/filterBox/tests/FilterBox.spec.tsx

Focus on filter input when opening facet more rows and when clearing the filter input

Filter box focus

---

docs/Index.tsx
src/Index.ts
src/components/tables/TableEmptyRow.tsx
src/components/tables/examples/TableEmptyRowExamples.tsx
src/components/tables/tests/TableEmptyRow.spec.tsx

+ Added a table empty row component

---

src/components/navigation/Navigation.tsx
src/components/navigation/perPage/NavigationPerPage.tsx
src/components/navigation/perPage/NavigationPerPageConnected.tsx
src/components/navigation/perPage/tests/NavigationPerPage.spec.tsx
src/components/navigation/tests/NavigationConnected.spec.tsx

**EDIT: this PR is also adding a 'adjust page selected' behavior on perPageSelect change. Tests related to this behavior are also added.** 
After you approved the change I will release a new version of react-vapor on npm and change the version in jsadmin-activity-browser.
Should I change the version of the package in jsadmin-v2 as well once you will have approved this change?

! fix conditional of PerPageSelect options

---

package.json
webpack.config.js
webpack.config.prod.js

Added import-loader to force jQuery instance
Removed ProvidePlugin

Fix Chosen jQuery

---

src/components/actions/ActionBar.tsx
src/components/actions/filters/ItemFilter.tsx
src/components/actions/filters/examples/ItemFilterConnectedExamples.tsx
src/components/actions/filters/tests/ItemFilter.spec.tsx

Added a prop to be able to crop the item filter on the right or on the left

---

docs/members-example/views/MemberEditView.tsx
src/components/popover/Popover.spec.tsx
src/components/popover/Popover.tsx

Add possibility for the popover to behave as a modal

---

package.json

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Adds types field to .d.ts

---

src/components/actions/filters/tests/ItemFilterActions.spec.ts
src/components/calendar/tests/Calendar.spec.tsx
src/components/calendar/tests/CalendarDay.spec.tsx
src/components/datePicker/tests/DatePickerActions.spec.ts
src/components/facets/tests/FacetConnected.spec.tsx
src/components/facets/tests/FacetMoreRows.spec.tsx
src/components/filterBox/tests/FilterBox.spec.tsx
src/components/lastUpdated/tests/LastUpdatedConnected.spec.tsx
src/components/optionPicker/tests/OptionPickerActions.spec.ts
src/components/optionsCycle/tests/OptionsActions.spec.ts
src/components/tab/tests/TabConnected.spec.tsx

Fixes broken tests since jasmine update

---

src/components/datePicker/DatePickerReducers.ts
src/components/datePicker/tests/DatePickerReducers.spec.ts

You can ignore most of the test file, the only changes were formatting changes.

Fallback on previously applied date if the new date is invalid

---

src/components/modal/examples/ModalExamples.tsx

Not compiling on linux if the casing is wrong.

fix casing of the react import

---

src/components/popover/Popover.spec.tsx
src/components/popover/Popover.tsx

Added "style" in the list of allowed props

Fix missing popover prop

---

docs/Index.tsx
src/components/blankSlate/BlankSlate.tsx
src/components/chosen/examples/ChosenSelectExamples.tsx

add files to regroup all chosen select examples
add example witht 2000 options

remove example for chosen single select in index.tsx

---

src/components/blankSlate/BlankSlate.tsx
src/components/blankSlate/examples/BlankSlateExample.tsx
src/components/blankSlate/tests/BlankSlate.spec.tsx

Added a test, and an example for that. Now we can optionally add an icon in the top of the blankslate

Add icon to blankslate

---

package.json

chore(package): update redux to version 3.7.2

---

package.json

chore(package): update @types/webpack to version 3.0.4

---

package.json

chore(package): update @types/react-redux to version 4.4.46

---

package.json

chore(package): update @types/react to version 15.0.38

---

src/components/dropdownSearch/DropdownSearch.tsx

very small change just to be able to have a preview of the full display value on hover of an option or selected option, see attached images

add title for options to see full display value on hover

---

docs/Index.tsx
src/components/calendar/Calendar.tsx
src/components/calendar/CalendarConnected.tsx
src/components/calendar/tests/CalendarConnected.spec.tsx
src/components/datePicker/DatePickerBox.tsx
src/components/datePicker/DatePickerDropdown.tsx
src/components/datePicker/DatesSelection.tsx
src/components/datePicker/DatesSelectionConnected.tsx
src/components/datePicker/examples/DatePickerDropdownConnectedSingleDateExamples.tsx
src/components/datePicker/examples/DatePickerExamplesCommon.ts
src/components/datePicker/tests/DatesSelection.spec.tsx
src/components/datePicker/tests/DatesSelectionConnected.spec.tsx
src/components/dropdownSearch/DropdownSearch.tsx

demo: https://drive.google.com/file/d/0B75i_S1A9mU2MlpoMWY0ektLS2M/view

Make date picker single date great

---

src/components/datePicker/DatePickerDropdown.tsx
src/components/optionPicker/Option.tsx

old behavior https://drive.google.com/file/d/0B75i_S1A9mU2RF9PRFZVQmx4WkU/view
the current fix prevents that

Fix quick option buttons to have no default behavior (default is submit when inside a form)

---

src/Index.ts

Export selectSubNavigationAction

---

package.json

remove pre-push

---

src/components/filterBox/FilterBox.tsx
src/components/filterBox/examples/FilterBoxExamples.tsx
src/components/filterBox/tests/FilterBox.spec.tsx

add with title feature
allow the possibility to add an input max width

allow the possibility to add an input max width

---

src/components/actions/ActionBar.tsx
src/components/actions/examples/ActionBarExamples.tsx
src/components/actions/filters/ItemFilter.tsx
src/components/actions/filters/examples/ItemFilterConnectedExamples.tsx
src/components/actions/filters/tests/ItemFilter.spec.tsx
src/components/actions/tests/ActionBar.spec.tsx

add feature to toggle default classes for action bar
add possibility to add a tooltip on item in item filter
add examples
add unit tests

add feature to toggle default classes for action bar and a tooltip on item filter

---

src/components/toast/Toast.tsx
src/components/toast/examples/ToastExamples.tsx
src/components/toast/tests/Toast.spec.tsx

Added option to make toast undismissible

---

karma.entry.ts
src/components/dropdown/Dropdown.tsx
src/components/dropdown/tests/Dropdown.spec.tsx
src/components/facets/FacetMoreRows.tsx
src/components/facets/tests/FacetMoreRows.spec.tsx
src/components/popover/Popover.spec.tsx
src/components/popover/Popover.tsx

Some components use listeners on the global click event, do a check to
see if they are open before doing anything else
Before:
After:

Fix Performance Issues

---

src/components/tables/Table.tsx
src/components/tables/examples/TableExamples.tsx
src/components/tables/table-children/TableChildBody.tsx
src/components/tables/tests/TableTestCommon.tsx

```
interface IData {
id: string;
[attribute: string]: any;
}
```
```
interface ITableRowData {
[id: string]: IData;
}
```

use IData instead of ITableRowData where appropriate

---

docs/Index.tsx
src/Index.ts
src/components/splitlayout/SplitLayout.spec.tsx
src/components/splitlayout/SplitLayout.tsx
src/components/splitlayout/examples/SplitLayoutExamples.tsx
src/components/stepProgressBar/examples/StepProgressBarExamples.tsx

live demo https://coveo.github.io/react-vapor/split-layout/ OR see screenshot below

add split layout

---

src/components/stepProgressBar/examples/StepProgressBarExamples.tsx
src/components/tables/TableHeadingRow.tsx
src/components/tables/table-children/TableChildBody.tsx
src/components/tables/tests/TableChildBodyTest.tsx
src/components/tables/tests/TableHeadingRow.spec.tsx

Calls actions with property `callOnDoubleClick: true` on table row double click.

Table row double click

---

.travis.yml
package.json
src/components/datePicker/tests/DatePickerDropdown.spec.tsx
src/components/tables/tests/TableChildActionBar.spec.tsx
webpack.config.js
webpack.config.prod.js
webpack.config.test.js

attempt at fixing build failing because of an older version of tslint (not sure it will work)

fix master build

---

src/components/tables/Table.tsx
src/components/tables/table-children/TableChildBody.tsx

move undefined getActions at the table level

---

src/animations/SlideY.spec.tsx
src/animations/SlideY.tsx
src/components/tables/examples/TableRowExamples.tsx

Fix SlideY when content is dynamic

---

src/components/modal/Modal.tsx
src/components/modal/ModalComposite.tsx
src/components/modal/tests/Modal.spec.tsx

Mostly used to clear inputs when closing.

Added a callback when closing the modal

---

src/components/headers/HeaderWrapper.tsx

The classes don't do anything yet. I don't know if the fix I'll make should go in v2 or vapor, but we'll need to fix the Breadcrumb Header which currently do not ellipsise long header properly in the admin.

add class to allow for targetted style fix

---

src/components/facets/FacetRow.tsx
src/components/facets/tests/FacetConnected.spec.tsx
src/components/facets/tests/FacetRow.spec.tsx

Revert changes from https://github.com/coveo/react-vapor/pull/490 which were breaking in some places

Put checkboxes in facet the way they where

---

docs/Index.tsx
package.json
src/components/badge/Badge.tsx
src/components/badge/examples/BadgeExamples.tsx
src/components/badge/tests/Badge.spec.tsx

Feature badge component

---

docs/Index.tsx
package.json
src/components/cornerRibbon/CornerRibbon.tsx
src/components/cornerRibbon/examples/CornerRibbonExamples.tsx
src/components/cornerRibbon/examples/CornerRibbonExamplesCommon.ts
src/components/cornerRibbon/tests/CornerRibbon.spec.tsx

Implemented CornerRibbon component.
Demo: https://coveo.github.io/react-vapor/feature-corner-ribbon-component/

Feature corner ribbon component

---

src/components/actions/ActionBar.tsx
src/components/actions/examples/ActionBarExamples.tsx
src/components/actions/tests/ActionBar.spec.tsx
src/components/badge/tests/Badge.spec.tsx
src/components/cornerRibbon/tests/CornerRibbon.spec.tsx

much better without spaces for review https://github.com/coveo/react-vapor/pull/535/files?w=1

add the props to have the small actions in the ActionBar component

---

.tsconfig.lint.temp.json
src/components/collapsibleContainer/CollapsibleContainer.tsx
src/components/labeledValue/LabeledValue.spec.tsx
src/components/labeledValue/LabeledValue.tsx

the info icon is not looking very good on the labeled values right now, i'll see what i can do in vapor for this

replace help icon with info icon where appropriate

---

src/components/input/Input.tsx
src/components/input/tests/Input.spec.tsx

One liner, prevents value to disappear when entering decimals

Add step="any" when input type is number

---

src/components/input/Input.tsx
src/components/input/tests/Input.spec.tsx

front autofocus props

---

src/components/tables/table-children/TableChildActionBar.tsx
src/components/tables/tests/TableChildActionBar.spec.tsx

Let's you assign another default value for a table predicates other than ALL.
Let me know if you want me to add an example 😄

Table predicates custom default

---

src/components/dropdownSearch/DropdownSearchActions.tsx
src/components/dropdownSearch/DropdownSearchConnected.tsx
src/components/dropdownSearch/DropdownSearchReducers.tsx

need this for a use case in ML

pass active option to active action

---

src/components/dropdownSearch/MultiSelectDropdownSearch/MultiSelectInput.tsx
src/components/svg/examples/SvgExamples.tsx

Part 2 of fixes:
* Change select option for filter icon
* Remove filter icon when selected options are present

! Fix multiselect dropdown style

---

package.json
src/components/modal/ModalBackdrop.tsx
src/components/modal/tests/ModalBackdrop.spec.tsx

Previous technique was not working in all browsers, now should work at large.

! Fix modal escape behavior

---

src/components/dropdownSearch/MultiSelectDropdownSearch/MultiSelectInput.tsx
src/components/modal/ModalBackdrop.tsx
src/components/modal/ModalHeader.tsx
src/components/modal/ModalHeaderConnected.tsx
src/components/modal/tests/ModalBackdrop.spec.tsx
src/components/modal/tests/ModalHeader.spec.tsx
src/components/modal/tests/ModalHeaderConnected.spec.tsx
src/components/modalPrompt/tests/ModalPrompt.spec.tsx

Using the good key help 🤦‍♂️ 
@sroy3  we still have a problem though... if we have multiple modals opened, they _all_ close when pressing X. Pressing escape works correctly though. I'm not sure how to fix this one...
EDIT: I have a tentative fix in there, feel free to review properly.

* Fix modal for real

---

src/components/datePicker/DatesSelection.tsx
src/components/datePicker/examples/DatePickerDropdownConnectedExamples.tsx
src/components/datePicker/examples/DatePickerExamplesCommon.ts
src/components/datePicker/tests/DatesSelection.spec.tsx

Changed how classes are added in the date picker selectors
Added examples

Fix Date Picker Spacing

---

src/components/select/MultiSelectConnected.tsx
src/components/select/SelectConnected.tsx
src/components/select/SingleSelectConnected.tsx
src/components/select/examples/MultiSelectExamples.tsx
src/components/select/examples/SingleSelectExamples.tsx
src/components/select/tests/MultiSelectConnected.spec.tsx
src/components/select/tests/SingleSelectConnected.spec.tsx

Added possibility to put placeholders on SingleSelect and MultiSelect
Updated examples
Added UTs

Fix Placeholder on Selects

---

src/components/dropdown/Dropdown.tsx
src/components/dropdown/tests/Dropdown.spec.tsx
src/components/sideNavigation/SideNavigation.tsx
src/components/sideNavigation/SideNavigationLoadingItem.tsx
src/components/svg/LinkSvg.tsx
src/utils/FalsyValuesUtils.spec.tsx

Added the optional `className` prop to `<Dropdown />` component.

Add additional className on dropdown component

---

CODEOWNERS
docs/Index.tsx
src/components/modal/ModalComposite.tsx

This prop exists on `ModalComposite`'s underlying `Modal` component, but it wasn't propagated making it unusable.
Also removed JF from the code owners so he doesn't get flooded with reviews while he's not here.

Fix ModalComposite closeTimeout prop

---

docs/Index.tsx
src/components/tables/TableHeadingRow.tsx
src/components/tables/examples/TableRowConnectedExamples.tsx
src/components/tables/examples/TableRowExamples.tsx
src/components/tables/tests/TableHeadingRow.spec.tsx
src/utils/EventUtils.spec.tsx
src/utils/EventUtils.ts
src/utils/FalsyValuesUtils.ts

Fix table collapsible row expand

---

docs/Index.tsx
src/components/dropdownSearch/DropdownSearch.tsx
src/components/dropdownSearch/examples/DropdownSearchExamples.tsx

The origin of the problem was hard to find in this messy component so I first thought it would be a good idea to duplicate and simplify the component. I got to something really clean when I figured out where the problem originated. Since creating a new component is less desirable (also there were some behaviours that weren't copied and I would have had to had tests), I fixed what was wrong with the component.

Fix keyboard nav on infinite scroll dropdown search

---

src/components/tables/Table.tsx
src/components/tables/examples/TableExamples.tsx
src/components/tables/table-children/TableChildBody.tsx

Add a props to remove the on hover on table rows

---

src/utils/DateUtils.spec.tsx
src/utils/DateUtils.ts

Change formatting according to UX's preferences.

* Change date picker formatting

---

docs/Index.tsx
src/ReactVapor.ts
src/ReactVaporReducers.ts
src/components/menu/MenuActions.ts
src/components/menu/MenuConnected.tsx
src/components/menu/MenuReducers.ts
src/components/menu/examples/MenuExamples.tsx
src/components/menu/tests/MenuConnected.spec.tsx
src/components/menu/tests/MenuReducers.spec.ts
src/utils/TestUtils.ts

add actions for the menu connected
add reducers for the menu connected
add uts
Add examples for the Menu connected

add the new menu connected component

---

src/components/collapsible/CollapsibleInfoBox.tsx

Applied UX review on CollapsibleInfoBox

! Fix collapsible info box toggle icon offset right

---

src/components/select/MultiSelectConnected.tsx
src/components/select/examples/MultiSelectExamples.tsx
src/components/select/tests/MultiSelectConnected.spec.tsx

Added examples
Added disabled attribute
Added tests

Disable the MultiSelect options if there's no option left

---

src/components/diffViewer/DiffViewer.tsx
src/components/diffViewer/tests/DiffViewer.spec.tsx

Diff blankslate

---

src/components/tables/Table.tsx
src/components/tables/examples/TableExamples.tsx
src/components/tables/table-children/TableChildBody.tsx
src/components/tables/tests/TableChildBody.spec.tsx
src/utils/EventUtils.ts
src/utils/TestUtils.ts

add utils for uts
add uts for the additionalClasses on cell
add props for onClick on cell click with a condition

Add onClick and additional classes on cell for the table

---

src/components/tables/table-children/TableChildBlankSlate.tsx

no hover on empty row or blankslate row in tables

---

src/components/tables/TableConnected.tsx
src/components/tables/TableReducers.ts
src/components/tables/tests/TableReducers.spec.ts

remove deleted table data entry in selected ids for getActions not to crash after a selected row and its data are deleted

remove deleted table data entry in selected ids for getActions not to throw

---

docs/Index.tsx
src/components/statusCard/StatusCard.tsx
src/components/statusCard/examples/StatusCardExamples.tsx
src/components/statusCard/styles/StatusCard.scss
src/components/statusCard/styles/StatusCard.scss.d.ts
src/components/statusCard/tests/StatusCard.spec.tsx

https://github.com/coveo/vapor/pull/580 needed for a successful build.

Status card

---

docs/Index.tsx
src/ReactVapor.ts
src/ReactVaporReducers.ts
src/components/radio/RadioSelect.tsx
src/components/radio/RadioSelectActions.ts
src/components/radio/RadioSelectConnected.tsx
src/components/radio/RadioSelectReducers.ts
src/components/radio/examples/RadioExamples.tsx
src/components/radio/examples/RadioSelectConnectedExample.tsx
src/components/radio/examples/RadioSelectExample.tsx
src/components/radio/tests/RadioSelect.spec.tsx
src/components/radio/tests/RadioSelectConnected.spec.tsx
src/components/radio/tests/RadioSelectReducers.spec.tsx
src/utils/TestUtils.ts

https://coveo.github.io/react-vapor/radioselect-connected/  
look for the `Radio` section last example 
the disabled option is still selectable, on it to fix it

RadioSelectConnected

---

create-live-demo.js

this will avoid to post the demo link at each build

Live demo posting upgrade

---

src/components/input/Input.tsx
src/components/input/tests/Input.spec.tsx
src/components/radio/RadioSelect.tsx
src/components/radio/examples/RadioSelectConnectedExample.tsx

Radio option disabled tooltip

---

create-live-demo.js
src/components/input/Input.tsx
src/components/input/tests/Input.spec.tsx
src/components/radio/RadioSelect.tsx
src/components/radio/examples/RadioSelectConnectedExample.tsx
src/components/radio/tests/RadioSelect.spec.tsx

need this for my current feature

add onChangeCallback for RadioSelect component

---

src/components/input/Input.tsx

thanks to @sroy3 for finding the issue

add keys to input children

---

docs/Index.tsx
src/ReactVapor.ts
src/ReactVaporReducers.ts
src/components/popover/Popover.tsx
src/components/popover/PopoverActions.ts
src/components/popover/PopoverConnected.tsx
src/components/popover/PopoverReducers.ts
src/components/popover/examples/PopoverConnectedExamples.tsx
src/components/popover/tests/PopoverConnected.spec.tsx
src/components/popover/tests/PopoverReducers.spec.ts
src/utils/TestUtils.ts

popover connected

---

src/components/datePicker/DatePickerDropdown.tsx
src/components/dropdownSearch/DropdownSearch.tsx
src/components/select/MultiSelectConnected.tsx
src/components/select/SingleSelectConnected.tsx

MultiSelect
DatePickerDropdown
DropdownSearch

Add class on dropdown when no values are selected

---

src/components/button/Button.tsx
src/components/button/examples/ButtonExamples.tsx

add children for the Button

---

src/components/filterBox/FilterBox.tsx
src/components/filterBox/examples/FilterBoxExamples.tsx

Add example for the filterBox with an button

add children for the FilterBox

---

src/components/listBox/ListBox.tsx
src/components/listBox/ListBoxActions.ts
src/components/listBox/ListBoxConnected.tsx
src/components/listBox/ListBoxReducers.ts
src/components/listBox/examples/ListBoxExamples.tsx
src/components/listBox/tests/ListBoxReducers.spec.ts
src/utils/ReduxUtils.ts
src/utils/TestUtils.ts

Add an action to update items in the store
Add items in the store for the listBox

Update listbox list action

---

docs/Reducers.ts
src/components/listBox/ListBox.tsx
src/components/listBox/ListBoxActions.ts
src/components/listBox/ListBoxConnected.tsx
src/components/listBox/ListBoxReducers.ts
src/components/listBox/examples/ListBoxExampleActions.ts
src/components/listBox/examples/ListBoxExampleConnected.tsx
src/components/listBox/examples/ListBoxExampleReducer.ts
src/components/listBox/examples/ListBoxExamples.tsx
src/components/listBox/tests/ListBoxReducers.spec.ts
src/components/select/SelectConnected.tsx
src/components/select/tests/SingleSelectConnected.spec.tsx

Revert change on listBox to remove items in the store
Add example with a component to wrap the listBox with a custom list in the store.
Add a button to update the current list in the store to show a listbox with a dynamic item list

ListBoxExample

---

CODEOWNERS

I'm going to spend some time here for a project.
Might as well help out! 😄

Add a codeowner

---

src/ReactVapor.ts
src/ReactVaporReducers.ts
src/components/filterBox/tests/FilterBox.spec.tsx
src/components/listBox/examples/ListBoxExampleConnected.tsx
src/components/select/SelectWithFilter.tsx
src/reusableState/customList/StringListActions.ts
src/reusableState/customList/StringListReducers.ts
src/reusableState/customList/tests/StringListReducers.spec.ts

A simple string list we can use with other component connected

Add string list reusable

---

src/components/select/tests/SelectSelector.spec.ts
src/reusableState/customList/tests/StringListReducers.spec.ts

Add missing uts for Utils in StringListReducers

add uts for SelectSelector

---

src/components/select/tests/MultiSelectWithFilter.spec.tsx
src/components/select/tests/SingleSelectWithFilter.spec.tsx

Add a specific UT for the case of a MultiSelect with the SelectWithFilter

Add UTs for the SelectWithFilter

---

docs/Index.tsx
docs/index.html

Auto-reload will stay on the current component
The active component will be in the url to share more easily

Better Demo Page

---

src/components/modal/ModalHeader.tsx
src/components/modal/examples/ModalCompositeConnectedExamples.tsx
src/components/modal/tests/ModalHeader.spec.tsx
src/components/title/Title.tsx
src/components/title/tests/Title.spec.tsx
webpack.config.js

Fix modal header truncate

---

src/components/select/MultiSelectConnected.tsx
src/components/select/SelectSelector.ts
src/components/select/SelectWithFilter.tsx
src/components/select/SingleSelectConnected.tsx
src/components/select/tests/SelectSelector.spec.ts

Small Refact for the SelectSelector

Add interface for createSelector in SelectSelector

---

src/components/select/MultiSelectConnected.tsx
src/components/select/examples/MultiSelectExamples.tsx

Add example with items only selectable

Remove duplicate selected with customValue

---

src/components/select/MultiSelectConnected.tsx
src/components/select/SelectWithFilter.tsx
src/components/select/examples/MultiSelectExamples.tsx
src/components/select/tests/MultiSelectConnected.spec.tsx
src/components/select/tests/MultiSelectWithFilter.spec.tsx

Add example with list of only selectable without customValue
Add option to set disabled or not the button on noselected
Add items when no items in the list

Add example with list of only selectable

---

src/components/lastUpdated/LastUpdated.tsx
src/components/tables/Table.tsx
src/components/tables/table-children/TableChildLastUpdated.tsx

Add an attribute to pull at left the last update element in table footer

+ Add pull last update to left attribute [ADUI-3358]

---

src/components/select/SelectWithFilter.tsx
src/components/select/examples/MultiSelectExamples.tsx

Add the defaultCustomValues for SelectWithFilter

---

src/components/select/MultiSelectConnected.tsx
src/components/select/SelectConnected.tsx
src/components/select/SingleSelectConnected.tsx
src/components/select/examples/MultiSelectExamples.tsx

Add style to customize select

---

src/components/select/SelectWithFilter.tsx

disabled noItems box to remove style on hover and select
remove code to have an item in the array

Remove selectable no items box

---

src/components/select/SelectWithFilter.tsx
src/components/select/tests/MultiSelectWithFilter.spec.tsx

Add text when all values are selected

---

src/components/select/MultiSelectConnected.tsx
src/components/select/SelectSelector.ts
src/components/select/tests/SelectSelector.spec.ts

Add selector to get all values from the multiSelect with customValue

---

src/components/navigation/pagination/NavigationPaginationReducers.ts
src/components/table-hoc/TableHOC.tsx
src/components/table-hoc/TableHOCUtils.ts
src/components/table-hoc/TableWithPagination.tsx
src/components/table-hoc/TableWithPredicate.tsx
src/components/table-hoc/examples/TableHOCExamples.tsx
src/components/table-hoc/examples/TableHOCServerExampleReducer.ts
src/components/table-hoc/examples/TableHOCServerExamples.tsx
src/components/table-hoc/styles/TableWithPredicates.scss
src/components/table-hoc/styles/TableWithPredicates.scss.d.ts

Feature Table HOC with Predicates & Loading

---

src/ReactVapor.ts
src/ReactVaporReducers.ts
src/components/actions/ActionBarReducers.ts
src/components/table-hoc/TableHOC.tsx
src/components/table-hoc/TableRowConnected.tsx
src/components/table-hoc/TableWithActions.tsx
src/components/table-hoc/TableWithSort.tsx
src/components/table-hoc/actions/TableRowActions.ts
src/components/table-hoc/reducers/TableRowReducers.ts

See https://github.com/coveo/react-vapor/pull/908/files#diff-465068f1d1e6ba675d6cf11134870c53R73 for example

Feature Table HOC with Actions

---

src/components/table-hoc/TableWithPredicate.tsx
src/components/table-hoc/tests/TableWithPredicate.spec.tsx

Removed useless selector since I already had the selected value

Added Uts for the TableWithPredicate

---

src/components/table-hoc/TableRowConnected.tsx
src/components/table-hoc/tests/TableRowConnected.spec.tsx
src/components/table-hoc/tests/TableRowReducers.spec.ts

Added UTs for the component
Added UTs for the reducers

Added UTs for the TableRowConnected

---

docs/Index.tsx
src/components/filterBox/FilterBoxSelectors.ts
src/components/filterBox/tests/FilterBoxSelectors.spec.ts
src/components/navigation/NavigationSelectors.ts
src/components/select/SelectSelector.ts
src/components/select/SelectWithFilter.tsx
src/components/select/tests/SelectSelector.spec.ts
src/components/table-hoc/TableSelectors.ts
src/components/table-hoc/TableWithBlankslate.tsx
src/components/table-hoc/TableWithFilter.tsx
src/components/table-hoc/TableWithPagination.tsx
src/components/table-hoc/TableWithSort.tsx
src/components/table-hoc/tests/TableWithBlankslate.spec.tsx
src/components/tables/Table.tsx
src/utils/FilterUtils.ts

Moved filters selector in their own files, used them in the select selectors and in the table
Added Table selectors
Fixed file casing

Added selectors for Table

---

src/components/actionable-item/ActionableItem.tsx
src/components/actionable-item/styles/ActionableItem.scss
src/components/actionable-item/styles/ActionableItem.scss.d.ts

slight modification to the actionable item for it to be the same height as SingleSelect and Button  
also the dots were black and need to be blue

Actionable item height

---

src/components/stickyFooter/StickyFooter.scss

the footer was not hidden when the wrapped component was not dirty
https://coveo.github.io/react-vapor/fix-with-edit/#ComponentWithEditing

fix withEdit hoc hidden sticky footer when not dirty

---

src/components/subNavigation/SubNavigation.tsx
src/components/subNavigation/SubNavigationConnected.tsx
src/components/subNavigation/tests/SubNavigation.spec.tsx

I needed to pass a custom className on the SubNavigation.

Make sub navigation more generic

---

src/components/table-hoc/TableRowConnected.tsx
src/components/table-hoc/tests/TableRowConnected.spec.tsx

https://github.com/facebook/react/issues/7685

fix: TableRowConnected children count

---

src/components/subNavigation/SubNavigation.tsx
src/components/subNavigation/examples/SubNavigationConnectedExamples.tsx

improvement: allow subnavigation items to be react nodes

---

docs/Index.tsx
src/components/infoBox/InfoBox.scss
src/components/infoBox/InfoBox.scss.d.ts
src/components/infoBox/InfoBox.tsx
src/components/infoBox/InfoBoxFooter.tsx
src/components/infoBox/InfoBoxLink.tsx
src/components/infoBox/examples/InfoBoxExamples.tsx
src/components/infoBox/tests/InfoBox.spec.tsx
src/components/infoBox/tests/InfoBoxFooter.spec.tsx
src/components/infoBox/tests/InfoBoxLink.spec.tsx

Feature InfoBox Component

---

docs/Index.tsx

navigate via the url and the section should change accordingly

change section on hashchange in docs

---

src/components/select/SingleSelectConnected.tsx
src/components/select/styles/SingleSelect.scss
src/components/select/styles/SingleSelect.scss.d.ts

https://coveo.github.io/react-vapor/singleselect-fixed-width/#SingleSelect

single select fixed width to prevent dropdown width to change when changing value

---

src/components/slider/Slider.tsx
src/components/slider/examples/SliderExamples.tsx

Allow more props for the tooltip
Fix missing style
Add example

Fix Slider Style

---

src/components/input/Input.tsx
src/components/input/InputSelectors.ts
src/components/input/tests/InputSelectors.spec.ts

Add uts
Remove useless duplicate for IInputState

Add input value selector

---

src/components/actionable-item/ActionableItem.tsx
src/components/modal/examples/ModalExamples.tsx
src/components/popover/Popover.tsx

adjust popover to be shown properly in modals

---

src/components/autocomplete/AutocompleteConnected.tsx
src/components/menu/MenuConnected.tsx
src/components/select/SelectConnected.tsx

just `document.contains` causes an error

Use document.body.contains which works in IE11

---

src/components/modal/examples/ModalCompositeConnectedExamples.tsx

I was looking for a prompt which was connected to redux and could not find any example of it, so I built one using the ModalCompositeConnected component.

Add example of a redux connected prompt

---

src/components/modal/ModalBackdropConnected.tsx

there was some compile errors in common

fix modalbackdrop type

---

src/components/select/SelectConnected.tsx
src/components/select/styles/SelectConnected.scss
src/components/select/styles/SelectConnected.scss.d.ts

Select Dropdown should open on top when placed after the middle of the screen

---

src/components/table-hoc/TableRowNumberColumn.tsx

Fix table row number when the row wraps

---

docs/Index.tsx
docs/index.html
gulpfile.js
karma.entry.ts
src/Defaults.spec.ts
src/Defaults.ts
src/components/modal/ModalComposite.tsx

Needed a way to set global variables outside the scope of the lib. I implemented the `defaults` class. Let me know what you think about it.

Implement a way to handle global defaults

---

src/components/actionable-item/ActionableItem.tsx
src/components/actionable-item/tests/ActionableItem.spec.tsx

Add prop to ActionableItem
Add UT
Improve UTs for the ActionableItem

Add container class on ActionableItem

---

src/components/multilineBox/tests/MultilineBox.spec.tsx
src/components/multilineBox/tests/MultilineBoxSelector.spec.tsx

Add uts for the multiline box selector

Add uts for MultilineBox

---

src/components/autocomplete/AutocompleteConnected.tsx
src/components/listBox/ListBox.tsx
src/components/select/SelectWithFilter.tsx
src/components/select/tests/SingleSelectWithFilter.spec.tsx

Fix Select with Filter Highlight

---

src/components/banner/Banner.tsx
src/components/banner/BannerContainer.tsx
src/components/banner/examples/BannerExamples.tsx
src/components/banner/styles/Banner.scss
src/components/banner/tests/BannerContainer.spec.tsx

Added BannerContainer for when you need something simple
Added example
Fixed style issue

Feature More Banner Flexibility

---

src/components/optionsCycle/OptionsCycle.tsx
src/components/optionsCycle/OptionsCycleConnected.tsx
src/components/optionsCycle/OptionsCycleSelectors.ts
src/components/optionsCycle/examples/OptionsCycleConnectedExamples.tsx
src/components/optionsCycle/tests/OptionsCycleConnected.spec.tsx

Added example
Added selector to get the option cycle value
Refactored and added unit tests

Added possibility to disable wrap around for Options Cycle

---

src/components/facets/Facet.tsx
src/components/facets/tests/Facet.spec.tsx

Fix facets missing row

---

src/components/tab/TabContent.tsx
src/components/tab/TabNavigation.tsx
src/components/tab/examples/TabConnectedExample.tsx

Fix tab navigation props order

---

.travis.yml
create-live-demo.sh

Added deploy step to deploy master on surge

Try to fix the demo branches

---

src/components/modal/ModalComposite.tsx
src/components/modal/tests/ModalComposite.spec.tsx

Workaround for https://github.com/reactjs/react-modal/issues/745

Workaround issue react-modal/issues/745

---

karma.entry.ts
src/components/modal/Modal.tsx
src/components/modal/ModalComposite.tsx
src/components/modal/ModalHeaderConnected.tsx
src/components/modal/examples/ModalCompositeConnectedExamples.tsx
src/components/modal/tests/Modal.spec.tsx
src/components/modal/tests/ModalComposite.spec.tsx

Also did a correction to the workaround for https://github.com/reactjs/react-modal/issues/745

Fix Modal & ModalComposite header close

---

src/components/actionable-item/ActionableItem.tsx
src/components/actionable-item/examples/ActionableItemExamples.tsx
src/components/actionable-item/styles/ActionableItem.scss
src/components/actionable-item/styles/ActionableItem.scss.d.ts
src/components/actionable-item/tests/ActionableItem.spec.tsx

Added example with scroll
Removed now useless style
Fixed unit tests

Replace Popover in ActionableItem with Drop

---

src/components/textarea/TestAreaSelectors.ts
src/components/textarea/examples/TextAreaExamples.tsx
src/components/textarea/tests/TextAreaSelectors.spec.ts

- Implemented a textarea value selector
- Added a textarea example that follows the style given in vapor (see demo)

TextArea selectors

---

src/components/table-hoc/TableRowConnected.tsx
src/components/table-hoc/examples/TableHOCExamples.tsx
src/components/table-hoc/tests/TableRowConnected.spec.tsx

Add callback on collapsible rows in table

---

src/components/chart/ChartTooltip.tsx
src/components/chart/ChartTooltipContent.tsx
src/components/chart/examples/ChartExamples.tsx
src/components/chart/styles/ChartTooltipContent.scss
src/components/chart/styles/ChartTooltipContent.scss.d.ts
src/components/drop/DropPod.tsx

Feature Chart Tooltip

---

src/components/drop/Drop.tsx
src/components/drop/DropPod.tsx
src/components/drop/examples/DropExamples.tsx
src/components/drop/tests/Drop.spec.tsx
src/components/select/tests/SingleSelectConnected.spec.tsx

Update interface
update logic with hasSameWidth to avoid an error with Edge

Add validation before DOMRect to avoid an error in Edge

---

src/components/checkbox/examples/CheckboxExamples.tsx

The link will be active once https://github.com/coveo/vapor/pull/667 is merged

Added documentation link to checkboxes

---

README.md

Demo: https://github.com/coveo/react-vapor/blob/6ff66e264f2ef946c43adaa0e5af4373eff4b23b/README.md

Refresh/update the readme [ADUI-4108]

---

src/components/childForm/ChildForm.tsx
src/components/childForm/examples/SimpleChildFormExample.tsx
src/components/multilineBox/examples/MultilineBoxExamples.tsx

Improvement child form

---

docs/Index.tsx
src/components/color/examples/ColorExamples.tsx

This refactoring of the colors demo page include multiple improvements :
- Both hex values and color names are searchables (and you can copy them)
- Colors are categorized (impending Vapor PR)

Refactor colors demo

---

src/components/sideNavigation/SideNavigationHeader.tsx
src/components/sideNavigation/SideNavigationMenuSection.tsx

It aims to make it easier to read and reduce information overload.

Transparency on icons in left nav

---

src/utils/InputUtils.spec.ts
src/utils/InputUtils.ts

What I want
What I have
- Added a `decodeHtml` util that safely decodes html entities.
None

Added decode html util

---

.travis.yml
create-live-demo.js
packages/vapor/README.md
packages/vapor/_config.yml
packages/vapor/docs/_includes/head.html

http://vapor.surge.sh was broken because it tried to load the file inside the vapor sub-folder, I need to create a PR to see if it works in the demo build
- Change the vapor server configuration to run on the root instead
Might break the demo, I'll validate before merging

Fix Vapor Deployment on Master

---

packages/react-vapor/src/components/actions/ActionBar.tsx

- remove a class with no sens to be there.
- Text do not wrap correctly
- make sure the action bar continue to wrap
- a little change in the space between each *small* action, do not affect normal size action.

remove unnecessary class on action

---

packages/react-vapor/src/components/table-hoc/actions/TableRowActions.ts
packages/react-vapor/src/components/table-hoc/examples/TableHOCExamples.tsx
packages/react-vapor/src/components/table-hoc/examples/TableHOCServerExampleReducer.ts
packages/react-vapor/src/components/table-hoc/reducers/TableRowReducers.ts
packages/react-vapor/src/components/table-hoc/tests/TableRowReducers.spec.ts

add action to deselectAll
add example with a table with actions
add example with a table with multi select row and a button to trigger the deselect
add uts
- New actions to deselect all rows
- nothing

Add an action to deselect rows

---

packages/react-vapor/tsconfig.build.json

Scoped tsconfig.build.json to only the source files
Nonce

Scope build tsconfig properly

---

packages/vapor-demo/components/messages/MessageTooltip.js
packages/vapor-demo/components/utility/Shadow.js
packages/vapor-demo/layouts/Navigation.js
packages/vapor-demo/pages/utility.js
packages/vapor/scss/guide.scss
packages/vapor/scss/utility/shadow.scss

Implemented some css `shadow-x` helper classes. @Charles-ErickBG feel free to checkout on this branch and edit `packages/vapor/scss/utility/shadow.scss` as needed.
None

Implement shadow example in vapor demo

---

packages/vapor/package.json

move dependencies in peer and dev dependencies to remove vunerability

---

packages/react-vapor/src/components/select/SelectConnected.tsx

I did some changes to the keyboard event logic a month ago, they don't really bring value and broke the item selection. In this PR, I simply reverted the changes to the old version.
None

correction to selectConnected keyboard event logic

---

packages/react-vapor/src/components/table-hoc/TableSelectors.ts
packages/react-vapor/src/components/table-hoc/TableWithSort.tsx
packages/react-vapor/src/components/table-hoc/examples/TableHOCServerExamples.tsx

Remove double render on sort with server hoc table

---

packages/react-vapor/src/components/table-hoc/TableWithSort.tsx
packages/react-vapor/src/components/table-hoc/tests/TableWithSort.spec.tsx

Update table with sort

---

packages/react-vapor/src/utils/ReduxUtils.ts

Since we're moving to connect, deprecate ReduxConnect

---

packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx
packages/react-vapor/src/components/table-hoc/tests/TableRowConnected.spec.tsx
packages/vapor/webpack.config.js

- Add deselectAll to TableRowConnected when unmount

Add deselectAll to TableRowConnected when unmount

---

README.md
packages/react-vapor/README.md
packages/vapor/README.md

Update all the README files to reflect the changes done on merging the demos together.
None.

Update READMEs about demo related information

---

packages/react-vapor/docs/src/styles/Menu.tsx
packages/react-vapor/docs/src/styles/messages/MessagePopover.tsx
packages/vapor/scss/components/popover-rich-documentation.scss
packages/vapor/scss/guide.scss

- Example in the popover section in Vapor
- Inner Rich Popover styles in Vapor
None
None

Rich Documentation Popover Example and Styles

---

packages/react-vapor/src/components/table-hoc/TableHOCUtils.ts
packages/react-vapor/src/components/table-hoc/tests/TableHOCUtils.spec.ts

Fix broken predicates and update unit tests.

Fix broken predicates

---

packages/react-vapor/src/components/table-hoc/TableHeaderWithSort.tsx

There was an id attribute in the TableHeaderWithSort component, but it was never used. I've added it to help QA FT

+id in tableHeaderWithSort

---

.travis.yml
packages/react-vapor/webpack.config.js

None, but I don't know if the configuration will work. I'll do another PR to change the README if it does or revert if it doesn't

Try to deploy in S3 instead of deploying in surge

---

packages/react-vapor/src/components/radio/examples/RadioExamples.tsx
packages/react-vapor/src/components/radio/examples/RadioSelectExample.tsx
packages/react-vapor/src/components/radio/examples/SingleRadioWithDescriptionExample.tsx
packages/vapor/scss/controls/radios.scss

Add radio description to some radio examples
no
-   [ x] The proposed changes are covered by unit tests
-   [ x] The potential breaking changes are clearly identified
-   [ x] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

Add radio description examples

---

packages/react-vapor/src/components/select/SelectConnected.tsx

Add dropOption for the select component

---

packages/react-vapor/src/components/radio/examples/RadioExamples.1.use.md
packages/react-vapor/src/components/radio/examples/RadioExamples.tsx

Added description in the DEVELOP tab
Added the USE tab for Radio Button
Links to two other sections 
Link to the All form guidelines to be updated later on when this section is created
*Finger crossed* hopefully none

Added the USE tab for Radio Button, and description in the DEVELOP tab

---

packages/react-vapor/docs/src/components/index.tsx

We never need to fetch the full list of components once loaded
None

Fix Demo Always Reload the all the Components

---

packages/react-vapor/src/components/radio/examples/RadioExamples.1.use.md
packages/react-vapor/src/components/radio/examples/RadioExamples.tsx

I was added too late to review this PR https://github.com/coveo/react-vapor/pull/1272/files. After discussion, we decided I could simply make a PR for my review. So here it is :)
N/A

apply doc review

---

packages/react-vapor/src/components/tooltip/examples/TooltipExamples.1.use.md
packages/react-vapor/src/components/tooltip/examples/TooltipExamples.tsx

+ Documentation
+ Page description
None
None

Tooltips - USE tab documentation + Page description

---

packages/vapor/scss/components/breadcrumbs.scss
packages/vapor/scss/typography/headings.scss

Did what the title says.
Added some variables in the mean time.

Removed margin-top on h1 in page header

---

packages/vapor/scss/components/blankslate.scss

Fix Blankslate Spacing

---

packages/react-vapor/src/components/checkbox/examples/CheckboxExamples.1.use.md
packages/react-vapor/src/components/checkbox/examples/CheckboxExamples.tsx

USE tab + description + removed duplicate h1 in DEVELOP tab

---

packages/react-vapor/src/components/childForm/examples/ChildFormExamples.1.use.md
packages/react-vapor/src/components/childForm/examples/ChildFormExamples.tsx

Childform documentation

---

packages/react-vapor/src/components/numericInput/examples/NumericInputExamples.1.use.md
packages/react-vapor/src/components/numericInput/examples/NumericInputExamples.tsx

numeric input documentation and description

---

packages/react-vapor/src/components/numericInput/examples/NumericInputExamples.tsx

I forgot to push my commit 🤦‍♂ 

removed double exports

---

packages/react-vapor/src/components/input/examples/InputExamples.1.use.md
packages/react-vapor/src/components/input/examples/InputExamples.tsx

text input documentation

---

packages/vapor/scss/components/tab.scss

Removed extra margin-top

---

packages/react-vapor/src/components/filterBox/FilterBoxConnected.tsx
packages/react-vapor/src/components/input/InputConnected.tsx
packages/react-vapor/src/components/input/InputSelectors.ts
packages/react-vapor/src/components/radio/RadioSelectConnected.tsx
packages/react-vapor/src/components/radio/RadioSelectSelectors.ts
packages/react-vapor/src/components/radio/tests/RadioSelectSelectors.spec.ts

then again trying to do just right by using the components selectors
none

Fix adui 4535 connect react vapor input to selector

---

packages/react-vapor/src/components/select/examples/MultiSelectExamples.1.use.md
packages/react-vapor/src/components/select/examples/MultiSelectExamples.tsx

multi-select documentation

---

packages/react-vapor/src/components/numericInput/NumericInputConnected.tsx
packages/react-vapor/src/components/numericInput/examples/NumericInputExamples.tsx
packages/vapor/scss/controls/numeric-input.scss
packages/vapor/scss/guide.scss
packages/vapor/scss/variables.scss

Add mod classes for numeric input

---

packages/react-vapor/src/components/numericInput/NumericInputConnected.tsx
packages/react-vapor/src/components/numericInput/tests/NumericInputConnected.spec.tsx

I have added the up and down arrow to increment or decrement NumericInput

Feature adui 4849 up down arrow key change value numericinput

---

packages/react-vapor/src/components/datePicker/examples/DatePickerDropdownConnectedExamples.1.use.md
packages/react-vapor/src/components/datePicker/examples/DatePickerDropdownConnectedExamples.tsx

date picker documentation

---

packages/react-vapor/src/components/table-hoc/TableWithUrlState.tsx
packages/react-vapor/src/utils/UrlUtils.spec.ts
packages/react-vapor/src/utils/UrlUtils.ts

- Added `toQueryString` and `toObject` url utils.
- Add export for the `TableWithUrlStateParameters`
None.

UrlUtils improvements

---

packages/react-vapor/webpack.config.prod.js

Update list of libraries that must be transpilled

---

packages/react-vapor/src/components/breadcrumbs/Breadcrumb.tsx
packages/react-vapor/src/components/breadcrumbs/BreadcrumbLink.tsx
packages/react-vapor/src/components/breadcrumbs/tests/Breadcrumb.spec.tsx
packages/react-vapor/src/components/breadcrumbs/tests/BreadcrumbLink.spec.tsx
packages/react-vapor/src/components/headers/examples/HeaderExamples.tsx

Update uts and remove old mount

Update breadcrumb to include a section without link

---

packages/react-vapor/src/components/numericInput/NumericInputActions.ts
packages/react-vapor/src/components/numericInput/NumericInputConnected.tsx
packages/react-vapor/src/components/numericInput/NumericInputReducers.ts
packages/react-vapor/src/components/numericInput/tests/NumericInputReducers.spec.ts

https://coveord.atlassian.net/browse/CT-5963
Added validation for the initial value that is set by the "mount" function for the NumericInputConnected component.

Added initial value validation on mount for NumericInputConnected

---

.travis.yml
invalidate-cloudfront.js

- Fixed the invalidate-cloudfront script
- Added some temporary commands to cleanup our s3 bucket
None

Fix invalidate script and cleanup bucket

---

.travis.yml

Previous attempt failed with
Moved the AWS credentials inside global environment variables so that our script can pick-up on them

Invalidate cloudfront take 4

---

packages/react-vapor/src/components/loading/components/PaginationLoading.tsx
packages/react-vapor/src/components/loading/examples/LoadingExamples.tsx
packages/react-vapor/src/components/navigation/NavigationConnected.tsx
packages/vapor/scss/components/content-placeholder.scss
packages/vapor/scss/variables.scss

New pagination loading
Full table result

Add pagination loading

---

packages/vapor/scss/utility/flex.scss

Create a reusable class to include `flex flex-row flex-auto flex-center space-between`.
No

fix(flex): create reusable class

---

packages/react-vapor/src/components/chart/ChartContainer.tsx
packages/react-vapor/src/components/chart/ChartTooltip.tsx
packages/react-vapor/src/components/drop/DropPod.tsx

Quickly fixed the `cannot apply method of undefined` errors that were throwing in the demo.
I did not took the time to really understand the components or the methods that were used, but I could check deeper if it worth the time.
plus adding some unit tests if need be.
**Edit:** After more research. It was the tooltip rendering that was at fault when not finding the parent component.
I did not change the implementation. Only avoided any undefined in the workflow.

fix(charts): quick fix to avoid undefined throwing

---

.travis.yml

Demo won't update for now, I'll change the url

Change AWS Credentials and S3 Bucket

---

packages/react-vapor/src/components/blankSlate/examples/BlankSlateExample.tsx

I removed a duplicated example in the BlackSlate section and fixed some capitalization
Pretty sure there's none

Removed duplicate example in blankslate

---

packages/react-vapor/src/components/select/SingleSelectConnected.tsx

Related to this one: http://bitbucket.org/coveord/jsadmin-machine-learning/pull-requests/231

Do not open drop-down when deselecting an option

---

packages/react-vapor/src/components/drop/DropPod.tsx
packages/react-vapor/src/components/select/SingleSelectConnected.tsx

Remove the condition to hide the dropPod if the width is too long

---

packages/react-vapor/src/components/actionable-item/ActionableItem.tsx

+dataId attribute in IActionableItemProps interface

+dataId as an ActionableItemPropd interface attribute

---

packages/react-vapor/package.json

Forgot to change the types path in the package.json
None

Fix declaration path in package.json

---

packages/react-vapor/src/components/index.ts
packages/react-vapor/src/components/modal/index.ts

Forgot to export some component :bear: 

Added missing exports of forms and modal loading

---

packages/react-vapor/src/components/checkbox/CheckboxActions.ts
packages/react-vapor/src/components/filterBox/FilterBoxActions.ts
packages/react-vapor/src/components/modal/ModalActions.tsx
packages/react-vapor/src/components/tables/TableActions.ts
packages/react-vapor/src/components/tables/TableConnected.tsx

add new objects

---

packages/react-vapor/gulpfile.js

add in gulp file the task to remove .awcache on reconstruct

---

packages/react-vapor/src/components/tables/TableDataModifier.ts

export TableDataModifier

---

packages/react-vapor/src/components/dropdownSearch/DropdownSearchActions.tsx
packages/react-vapor/src/components/listBox/ListBoxActions.ts
packages/react-vapor/src/components/searchBar/SearchBarActions.tsx
packages/react-vapor/src/components/textarea/TextAreaActions.ts

add DropdownSearchReduxActions

---

packages/vapor/scss/utility/layout.scss

add z-index utils for simple layout fix

---

packages/react-vapor/package.json
packages/vapor/package.json

updated the node-sass version
a minor version update should not be breaking

feat(package.json): updated the node-sass version

---

packages/react-vapor/src/components/stickyFooter/StickyFooter.scss

fix(stickyfooter): add z-index

---

.travis.yml
create-live-demo.sh
lerna.json
package.json

Setup conventionnal commits configuration to automatically bump and publish the proper versions when merging pull requests on master.
I don't know how it will react with the existing commits.

ci(lerna): setup conventionnal commits

---

.travis.yml
README.md
packages/react-vapor/README.md
packages/vapor/README.md
publish.sh

- Moved the lerna publish step into a custom deploy script
- Updated READMEs to better reflect the conventional commit setup
None

Adui 4684/publish with custom script

---

.travis.yml
packages/react-vapor/package.json
packages/vapor/package.json
publish.sh

We were building and testing everything 2 times for nothing

Adui 4684/remove version script

---

.travis.yml
publish.sh

lerna wasn't able to push tags to the repo

ci(travis): fix lerna authentication for publish

---

.travis.yml
publish.sh

I swear this is the last PR for conventionnal commits :bear: 
The previous build on master published on npm properly, but did not create a release on github

ci(lerna): add the "--create-release" option when publishing

---

packages/vapor/scss/dependencies.scss

`../` is not always valid since the package might be in a installed in a different folder
None

fix(style): style import should be relative

---

packages/react-vapor/src/components/table-hoc/TableWithFilter.tsx

fix(table): imports deduplication
None

fix(table): missing type caused d.ts for tableWithFilter to be missing

---

packages/react-vapor/src/components/actions/examples/ActionBarExamples.tsx
packages/react-vapor/src/components/actions/tests/ActionBar.spec.tsx
packages/react-vapor/src/components/actions/tests/ActionsDropdown.spec.tsx
packages/react-vapor/src/components/actions/tests/SecondaryActions.spec.tsx
packages/react-vapor/src/components/dropdown/tests/Dropdown.spec.tsx
packages/react-vapor/src/components/table-hoc/tests/TableHOC.spec.tsx

Add uts for ActionBar
Add uts for ActionsDropdown
Add uts for Secondary Actions
Add uts for Dropdown
Add uts for TableHOC

fix(add uts): Add UTs for table action in mode disabled

---

packages/react-vapor/src/components/actions/ActionBar.tsx
packages/react-vapor/src/components/actions/ActionsDropdown.tsx
packages/react-vapor/src/components/actions/SecondaryActions.tsx
packages/react-vapor/src/components/actions/examples/ActionBarConnectedExamples.tsx
packages/react-vapor/src/components/actions/examples/ActionBarExamples.tsx
packages/react-vapor/src/components/actions/tests/ActionBar.spec.tsx
packages/react-vapor/src/components/actions/tests/ActionsDropdown.spec.tsx
packages/react-vapor/src/components/actions/tests/SecondaryActions.spec.tsx
packages/react-vapor/src/components/dropdown/Dropdown.tsx
packages/react-vapor/src/components/dropdown/tests/Dropdown.spec.tsx
packages/react-vapor/src/components/table-hoc/TableHOC.tsx
packages/react-vapor/src/components/table-hoc/tests/TableHOC.spec.tsx

Add disabled for table action bar

---

packages/react-vapor/src/components/subNavigation/index.ts

fix(subnavigation): add selector export to index

---

packages/react-vapor/src/components/table-hoc/TableWithNewPagination.tsx

add back the children for the table pagination

fix(table-loading): table pagination

---

packages/vapor/README.md

Update vapor readme

---

packages/react-vapor/src/utils/PropsToOmitUtils.ts

fix(propstoomitutils.ts): added changeDirtyState as props to omit

---

packages/react-vapor/docs/src/styles/Menu.tsx

Table components are in the component section

refactor(menu.tsx): remove the table section in style from react-vapor

---

packages/vapor/scss/tables/table.scss

Moved from CommonStyle.scss
No

Add blacklistCard style

---

packages/vapor/scss/dependencies.scss

add missing style for the rc-slider

fix(rc-slider): fix style rc-slider

---

.travis.yml
README.md
package.json

chore(build): change the way travis install dependencies
None

chore(build): change the way dependencies are installed

---

packages/react-vapor/src/components/numericInput/numeric-input.scss

This adds weight to the rule and override the values of the button
None

fix(numeric input): scope the classes inside coveo-styleguide

---

packages/demo/src/demo-styling/base/_base.scss
packages/vapor/scss/components/navigation.scss

Remove overflow visible on menu
None

fix(navigation): items are now wrapping when they are too large

---

lerna.json
package.json
packages/react-vapor/package.json
packages/react-vapor/src/components/datePicker/tests/SetToNowButton.spec.tsx
packages/react-vapor/src/components/facets/tests/FacetMoreToggle.spec.tsx
packages/react-vapor/src/components/filterBox/tests/FilterBox.spec.tsx
packages/react-vapor/src/components/lastUpdated/tests/LastUpdated.spec.tsx
packages/react-vapor/src/components/tables/TableConnected.tsx
packages/react-vapor/src/components/tables/TableDataModifier.ts
packages/react-vapor/src/components/tables/table-children/TableChildActionBar.tsx

build(react-vapor): add tslint in the dev dependencies

---

packages/vapor/scss/tables/table.scss
packages/vapor/scss/variables.scss

feat(variables): add big panel header height and mod card list paddings

---

packages/react-vapor/src/components/input/Input.tsx

fix(input intefaces): required props was autoFocus. not autofocus

---

packages/demo/src/components/examples/InputExamples.tsx
packages/react-vapor/src/components/index.ts
packages/react-vapor/src/components/multiValueInputs/MultiValuesInput.tsx
packages/react-vapor/src/components/multiValueInputs/MultiValuesInputSelectors.ts
packages/react-vapor/src/components/multiValueInputs/index.ts
packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx
packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInputSelectors.spec.ts
packages/react-vapor/src/components/multilineInput/MultilineInput.tsx

Add new multi-values input to replace non-connected one
None

feat(input): add multi values input to replace multiline input

---

packages/demo/src/components/examples/BadgeExamples.tsx
packages/vapor/scss/components/badge.scss
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/variables.scss

+border-radius, +text-transform: uppercase, *font-size, *height

style(badge.scss): added/modify style for badge component

---

lerna.json
package.json
packages/demo/package.json
packages/react-vapor/package.json
packages/react-vapor/tsconfig.lib.json
packages/react-vapor/webpack.config.js

fix(convert-es5-lib): convert lib in es5

---

packages/react-vapor/package.json

add missing library in es6 to translate in es5

fix(es6-lib): es6 library

---

README.md
packages/demo/package.json
packages/react-vapor/README.md

Change url in the readme/package.json
The old url is dead

chore: change url endpoint

---

packages/demo/src/components/examples/TableHOCExampleUtils.tsx
packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx
packages/react-vapor/src/components/table-hoc/tests/TableRowConnected.spec.tsx

set collapsible invisible if the content is null
add invisible class
add uts

feat(invisible-collapsible): invisible collapsible

---

packages/demo/src/components/examples/LoadingExamples.tsx
packages/react-vapor/src/components/loading/components/TableLoading.tsx
packages/react-vapor/src/components/loading/components/tests/TableLoading.spec.tsx
packages/react-vapor/src/components/table-hoc/TableHOC.tsx
packages/vapor/scss/tables/table-loading.scss

added a  isCard prop in table loading so we can render loading cards in the same logic as loading table. One addition, is CardSubRow, which is the number of rows inside the card.

feat(tableloading): added table of loading cards

---

packages/vapor/scss/tables/table.scss

set style on tr and td instead of only td

fix(table-tr-style): style tr style

---

packages/vapor/scss/components/member.scss
packages/vapor/scss/components/menu.scss

changed the size of the provider logo and change the background of the member and help dropdown on
hover and open

style(menu member.scss): changed style for member and menu admin header

---

packages/demo/src/components/examples/ButtonExamples.tsx
packages/react-vapor/src/components/button/Button.tsx
packages/react-vapor/src/components/menu/MenuConnected.tsx

feat(menu): add menu exemple

---

packages/demo/src/components/examples/SliderExamples.tsx
packages/react-vapor/src/components/slider/MiddleSlider.tsx
packages/react-vapor/src/components/slider/SliderUtils.ts
packages/react-vapor/src/components/slider/tests/MiddleSlider.spec.tsx

fix(middleslider): adapted the step to the range of the slider

---

packages/react-vapor/src/components/slider/tests/MiddleSlider.spec.tsx

update value in uts for MiddleSlider

fix(uts): fix-uts

---

packages/react-vapor/src/components/splitlayout/SplitLayout.spec.tsx
packages/react-vapor/src/components/splitlayout/SplitLayout.tsx
packages/vapor/scss/utility/layout.scss

add class to remove the border in the center for a split layout

fix(split-layout): remove border

---

packages/demo/src/components/examples/SectionExamples.tsx
packages/react-vapor/src/components/section/Section.tsx
packages/react-vapor/src/components/section/tests/Section.spec.tsx

convert title string to reactNode
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to

feat(section): update section title

---

packages/vapor/scss/tables/table.scss

Brought in the CSS changes demonstrated in Admin UI [ADUI-3484](https://coveord.atlassian.net/browse/ADUI-3484) to make the table rows align vertically when at smaller sizes
None
-   [x ] The proposed changes are covered by unit tests
-   [x ] The potential breaking changes are clearly identified
-   [ x] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

improvement(tables): vertically aligned table rows

---

packages/react-vapor/src/utils/ReduxTestUtilities.ts
packages/react-vapor/src/utils/index.ts
packages/react-vapor/src/utils/tests/ReduxTestUtilities.spec.ts

add function to get the state with the right type
add function to get a full state to test the table composite state

feat(test-utilities): table and state

---

packages/demo/src/components/examples/ToastConnectedExamples.tsx
packages/react-vapor/src/components/toast/ToastActions.ts

update addToast interface with children

fix(toast): interface

---

packages/demo/src/components/examples/SliderExamples.tsx
packages/react-vapor/src/components/slider/MiddleSlider.tsx
packages/react-vapor/src/components/slider/SliderHandle.tsx

Add props to add custom props on tooltip used for the slider
Add props to customize the tooltips for the slider
none

fix(slider): custom tooltip props

---

packages/demo/src/components/examples/SliderExamples.tsx
packages/react-vapor/src/components/slider/MiddleSlider.tsx
packages/react-vapor/src/components/slider/tests/MiddleSlider.spec.tsx

Add function to customize happen value

fix(slider): custom append value

---

packages/demo/src/components/examples/SubNavigationExamples.tsx
packages/react-vapor/src/components/subNavigation/SubNavigation.tsx
packages/react-vapor/src/components/subNavigation/tests/SubNavigation.spec.tsx
packages/vapor/scss/components/sub-navigation.scss

added a simple disabled state prop on subnavigationitem

improvement(subnavigation): added a disabled state prop

---

packages/react-vapor/src/components/collapsible/CollapsibleSelectors.ts
packages/react-vapor/src/components/collapsible/index.ts
packages/react-vapor/src/components/collapsible/tests/CollapsibleSelectors.spec.ts
packages/react-vapor/src/components/textarea/TextAreaSelectors.ts
packages/react-vapor/src/components/textarea/tests/TextAreaSelectors.spec.ts

Add selectors to TextArea and Collapsible

---

packages/react-vapor/src/components/filterBox/tests/FilterBoxSelectors.spec.ts
packages/react-vapor/src/components/listBox/tests/ListBox.spec.tsx
packages/react-vapor/src/components/select/MultiSelectConnected.tsx
packages/react-vapor/src/components/select/SelectConnected.tsx
packages/react-vapor/src/components/select/SelectSelector.ts
packages/react-vapor/src/components/select/SingleSelectConnected.tsx
packages/react-vapor/src/components/select/hoc/SelectComponents.tsx
packages/react-vapor/src/components/select/hoc/SelectWithFilter.tsx
packages/react-vapor/src/components/select/hoc/SelectWithInfiniteScroll.tsx
packages/react-vapor/src/components/select/hoc/SelectWithPredicate.tsx
packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithFilter.spec.tsx
packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithPredicate.spec.tsx
packages/react-vapor/src/components/select/hoc/tests/SingleSelectWithFilter.spec.tsx
packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx
packages/react-vapor/src/components/select/tests/SelectSelector.spec.ts
packages/react-vapor/src/components/select/tests/SingleSelectConnected.spec.tsx
packages/react-vapor/src/utils/TypesUtils.ts
packages/react-vapor/src/utils/index.ts

- Cleaned up the types of multiple selects components and HOCs
Some missused selects might break

fix(selects): cleanup the selects type declarations

---

packages/react-vapor/src/components/calendar/Calendar.tsx
packages/react-vapor/src/components/calendar/tests/Calendar.spec.tsx
packages/react-vapor/src/components/datePicker/DatePickerBox.tsx
packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx
packages/react-vapor/src/components/datePicker/tests/DatePickerBox.spec.tsx
packages/vapor/scss/components/calendar.scss
packages/vapor/scss/variables.scss

Add props to set the height fix to avoid resize when the month change
add uts
add prop to set the height fix for the calendar box
no

feat(calendar): height fix

---

packages/react-vapor/src/components/select/hoc/SelectWithPredicate.tsx

build: fix a bad import

---

packages/react-vapor/src/components/tooltip/Tooltip.tsx

fix(tooltip): import * as React from react

---

packages/react-vapor/package.json
packages/react-vapor/rollup.config.js
packages/react-vapor/webpack.config.js

The demo local server wasn't reloading on change anymore since the rollup build merge. It is slower than before the rollup thing but at least it works now. We will investigate how to improve rebuild speeds later.

chore(demo): make the demo local server reload on change

---

packages/demo/src/demo-styling/main.scss
packages/demo/src/styles/icons/IconsList.tsx
packages/vapor/gulpfile.js

When we click on the icon of Icons List, it should redirect to the svg file in github, ex: https://github.com/coveo/react-vapor/blob/master/packages/vapor/resources/icons/svg/access-private.svg
nope

feat(iconslist): add link to icons

---

packages/react-vapor/src/utils/RandomUtils.spec.ts
packages/react-vapor/src/utils/RandomUtils.ts

Random utils are usefull to render random length loading placeholders.
- `Random.pick`: picks an element from the array at random
- `Random.bool`: choose between `true` or `false` at random

feat(randomutils): implement random utils

---

packages/demo/src/components/examples/ListBoxExamples.tsx
packages/demo/src/components/examples/SingleSelectExamples.tsx
packages/demo/src/components/examples/TextAreaExamples.tsx
packages/react-vapor/src/components/listBox/ListBox.tsx
packages/react-vapor/src/components/listBox/tests/ListBox.spec.tsx
packages/react-vapor/src/components/loading/components/ItemBoxLoading.tsx
packages/react-vapor/src/components/loading/components/tests/ItemBoxLoading.spec.tsx

feat(single-select-loading): implement a selectWithLoading HOC

---

packages/react-vapor/src/components/statusCard/StatusCard.tsx

A simple prop to add classes to the component container
none

feat(status card): added classname prop to the component

---

packages/vapor/scss/forms/block-form.scss

fix(labeledinput): remove margin top on first child

---

packages/react-vapor/src/components/labeledValue/LabeledValue.tsx

changed the information prop type to accept a ReactNode
none

feat(labeled value): accept react node to insert html elements

---

packages/react-vapor/src/components/slider/index.ts

Deleted this one by error when refactoring the slider files.
None, breaking without this fix.

fix(sliders): add SliderActions to the Entry

---

packages/react-vapor/src/components/searchBar/SearchBarSelector.ts
packages/react-vapor/src/components/searchBar/index.ts
packages/react-vapor/src/components/searchBar/tests/SearchBar.spec.tsx
packages/react-vapor/src/components/searchBar/tests/SearchBarConnected.spec.tsx
packages/react-vapor/src/components/searchBar/tests/SearchBarPropsScenarios.spec.ts
packages/react-vapor/src/components/searchBar/tests/SearchBarReducers.spec.tsx
packages/react-vapor/src/components/searchBar/tests/SearchBarSelector.spec.ts
packages/react-vapor/src/components/select/hoc/tests/SingleSelectWithFilter.spec.tsx

- Add search bar selector
- Move all test files to the `tests` folder
None

feat(searchbar): add selector

---

packages/react-vapor/src/components/tab/TabPaneConnected.tsx
packages/react-vapor/src/components/tab/TabSelectors.ts
packages/react-vapor/src/components/tab/tests/TabSelectors.spec.tsx

added a selector for tabconnected + unit tests

feat(tab component): +tab selector for tabconnected component + UTs

---

packages/react-vapor/src/components/tab/index.ts

fix(index.ts): added tabselectors in index.ts so i can use it in admin

---

packages/react-vapor/src/components/tab/TabSelectors.ts
packages/react-vapor/src/components/tab/tests/TabSelectors.spec.tsx

feat(tabselector.ts): added a selector for selected tab

---

packages/react-vapor/src/components/subNavigation/SubNavigation.tsx
packages/react-vapor/src/components/subNavigation/tests/SubNavigation.spec.tsx

fix(sub-nav): make sure only one item is seleted at once

---

packages/react-vapor/src/components/tab/TabSelectors.ts
packages/react-vapor/src/components/tab/tests/TabSelectors.spec.tsx

fix(tabselector): fix the selector

---

packages/react-vapor/src/components/actions/tests/SecondaryActions.spec.tsx
packages/react-vapor/src/components/facets/tests/FacetRow.spec.tsx
packages/react-vapor/src/components/lastUpdated/tests/LastUpdated.spec.tsx
packages/react-vapor/src/components/listBox/tests/ListBox.spec.tsx
packages/react-vapor/src/components/refresh/tests/RefreshCallback.spec.tsx
packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithPredicate.spec.tsx
packages/react-vapor/src/components/slider/tests/Slider.spec.tsx
packages/react-vapor/src/components/textarea/tests/TextArea.spec.tsx
packages/react-vapor/src/components/tooltip/tests/Tooltip.spec.tsx
packages/react-vapor/webpack.config.js
packages/react-vapor/webpack.config.test.js

fix(build): eslint

---

packages/react-vapor/src/components/limit/Limit.tsx

As part of https://coveord.atlassian.net/browse/ADUI-5749 and the larger https://coveord.atlassian.net/browse/ADUI-5819
In order to have the same look I need to apply classes to the outer container of the Limit component
none

improvement: added classes prop to Limit component

---

README.md

This will fix the issue in the admin UI temporarily (the commit will bump a major)

fix: typo in the README.md

---

packages/react-vapor/src/components/checkbox/tests/GroupableCheckboxConnected.spec.tsx
packages/react-vapor/src/components/checkbox/tests/GroupableCheckboxReducers.spec.ts
packages/react-vapor/src/components/datePicker/tests/DatePicker.spec.tsx
packages/react-vapor/src/components/datePicker/tests/DatePickerActions.spec.ts
packages/react-vapor/src/components/select/tests/SelectSelector.spec.ts
packages/react-vapor/src/components/tab/tests/TabConnected.spec.tsx
packages/react-vapor/src/components/tab/tests/TabReducers.spec.tsx
packages/react-vapor/src/components/tab/tests/TabSelectors.spec.tsx

While I was removing the circular dependencies I missed the compilation failures in the UTs. Here are the required fixes 
None

fix: type errors in unit tests

---

packages/demo/src/components/examples/FacetConnectedExamples.tsx
packages/react-vapor/src/components/slider/Slider.tsx
packages/react-vapor/src/components/subNavigation/SubNavigation.tsx
packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueMultiSelectValidationHOC.tsx

fix(use-effect): update use effect

---

packages/react-vapor/src/components/tab/TabSelectors.ts
packages/react-vapor/src/components/tab/tests/TabSelectors.spec.tsx

getTab selector get you the tab with the provided id

feat(tabselectors.ts): +getTab selector + uts

---

Jenkinsfile.groovy
build/add-comment.js

build: add missing token to tag version

---

packages/react-vapor/src/components/checkbox/CheckboxActions.ts
packages/react-vapor/src/components/checkbox/CheckboxConnected.ts
packages/react-vapor/src/components/checkbox/CheckboxReducers.ts
packages/react-vapor/src/components/checkbox/CheckboxSelectors.ts
packages/react-vapor/src/components/checkbox/tests/CheckboxReducers.spec.ts

+disable action for checkboxConnected

Update checkboxes payload

---

packages/react-vapor/src/components/actionable-item/ActionableItem.tsx

fix(actionableitem): omit containerclassname prop to fix the warning

---

Jenkinsfile.groovy

The previous code was only stopping the current stage (the first stage) of the build. Now it will skip all the remaining stages and give the build a success status.
None

ci(jenkins): fix the skip when its a version bump script

---

packages/vapor/resources/icons/svg/info-reversed.svg

feat(svg): add reversed info icon

---

package-lock.json
packages/demo/package-lock.json
packages/demo/src/components/examples/modalWindowExamples.tsx
packages/react-vapor/src/components/modal/UnsavedChangeModalProvider.tsx
packages/react-vapor/src/components/modalPrompt/ModalPrompt.tsx
packages/react-vapor/src/hoc/withPreventNavigation/PreventNavigationPrompt.tsx
packages/vapor/scss/components/modal.scss

now, there is Sucess, warning, critical and info prompt (as well as the mod- class in scss) class as
requested by @oliviertaillon  (future pr to change from confirmation to warning and warning to critical in
the admin)

feat(modal): changed modal type color

---

package-lock.json
packages/demo/package-lock.json
packages/demo/package.json

updating package-lock for demo of react-vapor.

feat(demo package-lock): update package-lock to newest release

---

packages/react-vapor/src/components/input/tests/Input.spec.tsx
packages/react-vapor/src/components/multiValueInputs/tests/MultiValuesInput.spec.tsx
packages/react-vapor/src/components/multilineBox/tests/MultilineBoxWithRemoveButton.spec.tsx

add uts for input, multilineBoxWithRemoveButton and multiValuesInput

fix(uts): multiValue disabled

---

packages/vapor/resources/icons/svg/unchecked.svg

feat(svg): add unchecked icon

---

packages/react-vapor/src/components/table-hoc/TableWithBlankSlate.tsx
packages/react-vapor/src/components/table-hoc/tests/TableWithBlankslate.spec.tsx

Added 2 new props to the HOC `TableWithBlankSlate`:
- `renderBlankslate?: React.ReactNode`
- `renderBlankslateOnly?: boolean`
```tsx
const TableWithBlankSlate = _.compose(tableWithBlankSlate())(TableHOC);
const MyTable = () => (
<TableWithBlankSlate
// other table props
renderBlankslate={<div>This is 🔥</div>}
renderBlankslateOnly
/>
);
```
```tsx
const MyTable = () => (
<TableWithBlankSlate
// other table props
renderBlankslate={<div>This is 🔥</div>}
/>
);
```
```tsx
const MyTable = () => (
<TableWithBlankSlate
// other table props
/>
);
```
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the proposed changes (if …

improvement(table): render custom blankslate from tableWithBlankslate

---

packages/demo/src/components/examples/RadioExamples.tsx
packages/react-vapor/src/components/radio/RadioSelect.tsx
packages/react-vapor/src/components/radio/RadioSelectConnected.tsx
packages/react-vapor/src/components/radio/tests/RadioSelect.spec.tsx

dont call the onChange to modify the state if the component is disabled

fix(disabled): radio select

---

packages/react-vapor/src/components/collapsible/CollapsibleConnected.tsx
packages/react-vapor/src/components/collapsible/tests/CollapsibleConnected.spec.tsx

This prop is needed for customizing the expanded step in Trial Dashboard.
None

feat(collapsibleconnected): add onclick prop

---

packages/react-vapor/src/components/table-hoc/TableRowConnected.tsx
packages/vapor/scss/tables/table.scss

fix(tablerow): adjust collapsible row height to match non-collapsible

---

packages/demo/src/components/examples/LogoCardExamples.tsx
packages/react-vapor/src/components/logoCard/LogoCard.tsx
packages/react-vapor/src/components/logoCard/tests/LogoCard.spec.tsx

added tooltip prop as a title with tooltipPlacement as its location. UT has been added also
-   [x ] The proposed changes are covered by unit tests

improvement(logocard.tsx): +tooltip on logoCard

---

Jenkinsfile.groovy

build: fix missing credential in build

---

packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/colors.scss

fix(variables): name

---

packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/fonts.scss

We will need to replace text-transform: uppercase with none in the admin-ui for rebranding style.
None

feat(button): create css variable for text-transform

---

packages/vapor/scss/variables.scss

fix(fonts): revert css variables

---

packages/vapor/scss/redesign/fonts.scss

Added `#{VARIABLE}` to font-size values used for CSS variables.
None

fix(fonts): convert css variables

---

packages/react-vapor/src/components/sideNavigation/SideNavigationMenuSection.tsx
packages/vapor/scss/components/navigation-loading.scss
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/variables.scss

fix(navigation): align menu items

---

.deployment.config.json

Add some steps in the deployment process to deploy on https://static.cloud.coveo.com/styleguide/{VERSION}

build: deploy styleguide on cdn

---

packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx
packages/react-vapor/src/components/dropdownSearch/DropdownSearch.tsx
packages/react-vapor/src/components/select/MultiSelectConnected.tsx
packages/react-vapor/src/components/select/SelectConnected.tsx
packages/react-vapor/src/components/select/SingleSelectConnected.tsx
packages/vapor/scss/components/menu.scss
packages/vapor/scss/controls/chosen.scss
packages/vapor/scss/controls/dropdown.scss
packages/vapor/scss/icons/svgs.scss

remove mixin with Svg for SingleSelect and Menu
keep mixin to handle the deprecated component chosen
[Screen Recording 2020-12-10 at 11.09.41 AM.zip](https://github.com/coveo/react-vapor/files/5674257/Screen.Recording.2020-12-10.at.11.09.41.AM.zip)

fix(mixin): single select

---

packages/react-vapor/src/components/sideNavigation/SideNavigationMenuSection.tsx
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/guide.scss
packages/vapor/scss/redesign/variables.scss

add color variables for navigation component

feat(navigation): add variables

---

packages/vapor/scss/components/header.scss
packages/vapor/scss/redesign/variables.scss

feat(header): variables

---

packages/vapor/scss/elements/color-dot.scss
packages/vapor/scss/redesign/variables.scss

Created CSS variables for status-green and status-red color dots.
None

feat(variables): status green and red

---

packages/demo/src/components/examples/ButtonExamples.tsx
packages/react-vapor/src/components/button/Button.tsx
packages/react-vapor/src/components/button/tests/Button.spec.tsx
packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/variables.scss

feat(button): variables

---

packages/vapor/scss/controls/splash.scss
packages/vapor/scss/redesign/variables.scss

Background gradient color

---

packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/variables.scss

fix(buttons): variables

---

packages/demo/src/components/examples/ExamplesUtils.ts
packages/react-vapor/src/components/title/Title.tsx
packages/vapor/scss/components/tab.scss
packages/vapor/scss/elements/links.scss
packages/vapor/scss/icons/icons.scss
packages/vapor/scss/redesign/colors.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/typography/headings.scss

Created CSS variables for basic header, breadcrumb and tab.
None

feat(table): create css variables for header and tab

---

packages/react-vapor/src/components/datePicker/DatePickerDropdown.tsx
packages/react-vapor/src/components/dropdownSearch/DropdownSearch.tsx
packages/react-vapor/src/components/select/MultiSelectConnected.tsx
packages/react-vapor/src/components/select/SingleSelectConnected.tsx
packages/vapor/scss/components/menu.scss
packages/vapor/scss/controls/dropdown.scss
packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/variables.scss

Fix dropdown toggle

---

packages/vapor/scss/controls/flat-select.scss
packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/tables/big-table.scss
packages/vapor/scss/typography/headings.scss

fix(header): typo in font-size variable

---

packages/vapor/scss/components/badge.scss
packages/vapor/scss/components/blankslate.scss
packages/vapor/scss/components/breadcrumbs.scss
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/controls/flat-select.scss
packages/vapor/scss/elements/color-dot.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss

Created more CSS variables for table components, status colors and navigation scrollbar.
None

feat(table): create css variables

---

packages/vapor/scss/components/modal.scss
packages/vapor/scss/components/sync-feedback.scss
packages/vapor/scss/components/toast.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/tables/big-table.scss

Created CSS variable for big table first row text color, and override colors of modal headers and toasts
None

feat(css): add more variables

---

packages/react-vapor/src/components/select/SingleSelectConnected.tsx
packages/vapor/scss/components/list-box.scss
packages/vapor/scss/controls/dropdown.scss
packages/vapor/scss/elements/btn-append-prepend.scss
packages/vapor/scss/redesign/variables.scss

add variables css for dropdown menu, single select and dropdown search
add list-box variable

feat(dropdown): variables

---

packages/react-vapor/src/components/banner/styles/Banner.scss
packages/react-vapor/src/components/filterBox/FilterBox.tsx
packages/react-vapor/src/components/statusCard/styles/StatusCard.scss
packages/vapor/scss/common/common.scss
packages/vapor/scss/components/badge.scss
packages/vapor/scss/components/calendar.scss
packages/vapor/scss/components/facet.scss
packages/vapor/scss/components/home-card.scss
packages/vapor/scss/components/labeled-value.scss
packages/vapor/scss/components/menu.scss
packages/vapor/scss/components/navigation-loading.scss
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/controls/collapsable.scss
packages/vapor/scss/controls/dropdown.scss
packages/vapor/scss/controls/filter-box.scss
packages/vapor/scss/controls/filtering/filters-values.scss
packages/vapor/scss/controls/flat-select.scss
packages/vapor/scss/controls/inputs.scss
packages/vapor/scss/elements/btn.scss
packages/vapor/scss/elements/color-dot.scss
packages/vapor/scss/elements/links.scss
packages/vapor/scss/lib/_mixins.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/tables/pagination.scss
packages/vapor/scss/typography/elements.scss
packages/vapor/scss/typography/font-size.scss
packages/vapor/scss/typography/headings.scss

- Used default font-size variable
- Added CSS variables to refactor temporary demo styles in admin
None

feat(rebranding): use default font-size variable and cleanup

---

packages/react-vapor/src/components/collapsible/CollapsibleHeaderIcon.tsx
packages/react-vapor/src/components/collapsible/tests/CollapsibleHeaderIcon.spec.tsx
packages/react-vapor/src/components/facets/Facet.tsx
packages/react-vapor/src/components/modal/ModalHeader.tsx
packages/vapor/scss/components/breadcrumbs.scss
packages/vapor/scss/components/facet.scss
packages/vapor/scss/components/labeled-value.scss
packages/vapor/scss/components/list-box.scss
packages/vapor/scss/components/member.scss
packages/vapor/scss/components/navigation-loading.scss
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/controls/checkboxes.scss
packages/vapor/scss/controls/slider.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/typography/font-size.scss
packages/vapor/scss/variables.scss

Added new CSS variables and several fixes for rebranding style.
None

refactor(rebranding): css variables adjustments

---

packages/vapor/scss/components/facet.scss
packages/vapor/scss/components/labeled-value.scss
packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/variables.scss

Several small fixes of CSS variables
None

fix(rebranding): css variables

---

packages/react-vapor/src/components/calendar/Calendar.tsx
packages/react-vapor/src/components/calendar/CalendarDay.tsx
packages/react-vapor/src/components/datePicker/DatePicker.tsx
packages/react-vapor/src/components/datePicker/DatesSelection.tsx
packages/react-vapor/src/components/datePicker/tests/DatePicker.spec.tsx
packages/react-vapor/src/components/dropdownSearch/DropdownSearchAutoInfiniteScroll.tsx
packages/react-vapor/src/components/facets/FacetMoreRows.tsx

I removed all the UNSAFE_* react lifecycle methods except those in the old `Table` component because they were complex to remove and this component is deprecated.
None

Remove all unsafe lifecycle methods

---

packages/vapor/scss/components/logo-card.scss

Direction from UI to improve the way disabled sources are being shown. Part of the trial
improvements. [JIRA ADUI-6370](https://coveord.atlassian.net/browse/ADUI-6370)
Before:
After:

style(logo-card.scss): removing grey scaling and opacity

---

packages/vapor/scss/common/palette-map.scss
packages/vapor/scss/common/palette.scss
packages/vapor/scss/redesign/colors.scss
packages/vapor/scss/utility/colors.scss

Replace the white variable with light

fix(white): utils white

---

Jenkinsfile.groovy

removed the now useless skip stage from the jenkins pipeline
none since the jenkins webhook has be adjusted

feat(jenkins pipeline): remove skip stage

---

packages/vapor/scss/controls/radios.scss

The selected radio button were orange. Now they are blue!
None

fix: change color of selected radio button

---

Jenkinsfile.groovy
lerna.json

Modified the Jenkinsfile to also run on the `next` branch. It will be usefull to bundle a lot of changes together
None

build(next): deploy "next" branch with a custom tag

---

packages/react-vapor/src/components/banner/styles/Banner.scss
packages/vapor/scss/redesign/colors.scss
packages/vapor/scss/redesign/variables.scss

adjust style with rebranding for banner
- background color
- text-color 

Banner style

---

packages/react-vapor/src/components/drop/DropPod.tsx
packages/react-vapor/src/components/drop/tests/DropPod.spec.tsx

reverted the breaking change made in the drop pod. 
none, recovering initial working code.

fix(drop pod): revert portal removal

---

Jenkinsfile.groovy

I tought `--preid` was enough, I was wrong
Doc
https://www.npmjs.com/package/@lerna/publish?activeTab=readme#--dist-tag-tag

build(next): added specific tag to avoid using latest

---

packages/vapor/scss/variables.scss

changed step-progress-bar color for rebranding

refactor(variables.scss): changed step-progress-bar color for rebranding

---

packages/demo/src/styles/Menu.tsx
packages/demo/src/styles/cards/Card.tsx
packages/demo/src/styles/cards/index.tsx
packages/react-vapor/src/components/logoCard/LogoCard.tsx
packages/vapor/scss/components/card.scss
packages/vapor/scss/components/logo-card.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/variables.scss

In order to update the logo card component to its new look and feel, I created a `card` css class
that gives a light shadow and rounded corners to its holder.
- New `card` class, you can check it out in at `#/styles/cards/card`.
- Updated look for the `LogoCard` component.
Removed some scss variables related to the logo card.

improvement(logo-card): refresh the looks of the logo-card component

---

package-lock.json
packages/demo/package-lock.json
packages/react-vapor/package-lock.json
packages/react-vapor/package.json
packages/react-vapor/rollup.config.js

added terser plugin to rollup to create a minified build
none, justs add another file to the bundle with minified code.
-   [x ] The potential breaking changes are clearly identified

Feature ad UI 5371 terser plugin

---

packages/demo/src/components/examples/BadgeExamples.tsx
packages/vapor/scss/components/badge.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/variables.scss

create the new style for the badge

feat(badge): redesign

---

packages/demo/src/demo-styling/main.scss
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/redesign/variables.scss

fix(vapor): demo

---

package-lock.json
packages/react-vapor/package-lock.json
packages/react-vapor/package.json
packages/react-vapor/rollup.config.js

using a plugin to handle the external dependencies global variables.
none, it fixes a problem

fix(external globals): using a plugin

---

packages/vapor/scss/components/tooltip.scss

-state-error class from tooltip.scss

refactor(tooltip.scss): -state-error class from tooltip.scss

---

packages/react-vapor/rollup.config.js

For some reason when excluding the externals in the esm build everything breaks including the demo
None

build: make esm build include the externals

---

packages/react-vapor/rollup.config.js

added the globals to the rollup setup event if the plugin is supposed to do so.
none. it fixes the admin tests.

fix(rollup build): adding regular globals

---

Jenkinsfile.groovy

post steps were added to Build, Test & Deploy in S3 in case something fails, so that a comment can
be added to the pr saying so.

ci(jeninsfile.groovy): +function to post comment on github pr

---

packages/react-vapor/src/components/drop/DropPod.tsx
packages/react-vapor/src/components/drop/tests/DropPod.spec.tsx

The fix is actually working, it simply need some tweaking in the admin to make sure the focus don't shift under the body
Requires coveo/admin-ui#1748 to be merged first

fix(drop): revert the revert of the fix for drop

---

packages/vapor/scss/forms/form-child.scss

[ADUI-6597](https://coveord.atlassian.net/browse/ADUI-6597)
Change the color of child form to make it visible.
None

fix(child-form): background and border colors

---

packages/react-vapor/src/components/listBox/ListBox.tsx

I revert some code that was probably not meant to be committed while we moved from Karma to Jest
None, it fixes all the dropdown

fix(dropdown): keyboard navigation

---

packages/demo/src/components/examples/ModalWizardExamples.tsx
packages/react-vapor/src/components/modalWizard/ModalWizardWithValidations.tsx
packages/react-vapor/src/components/modalWizard/index.ts
packages/react-vapor/src/components/modalWizard/tests/ModalWizardWithValidations.spec.tsx

Implemented a variant of the ModalWizard with built-in validations done from validationIds.
None

improvement(modalwizard): add ModalWizardWithValidations

---

package-lock.json
packages/demo/package.json
packages/demo/webpack.config.js
packages/react-vapor/package.json

Add a plugin to copy jquery and chosen in the dist folder. Add a plugin to automatically add the script tags for jquery and chosen
None, it fixes the demo page

fix(chosen): load chosen in the demo

---

packages/react-vapor/src/components/numericInput/NumericInputConnected.tsx
packages/react-vapor/src/components/numericInput/numeric-input.scss
packages/vapor/scss/controls/numeric-input.scss

fixed too dark +-sign colors and :focus background-color

style(numericinput.tsx): fixed color problem since rebranding

---

packages/react-vapor/src/components/facets/FacetRow.tsx
packages/vapor/scss/components/facet.scss
packages/vapor/scss/guide.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/variables.scss

Fixed some style issues of the FacetConnected component in the next branch:
- Fixed icon colors when hovering or not
- Removed unwanted checkbox next to the exclude icon
- Fixed alignment of the facet row
Before:
After:
None

fix(facet): style issues in the next branch

---

package-lock.json
packages/demo/package-lock.json
packages/demo/package.json
packages/demo/src/components/examples/DiffViewerExamples.tsx
packages/react-vapor/package.json
packages/react-vapor/src/components/diffViewer/DiffViewer.tsx
packages/react-vapor/src/components/diffViewer/tests/DiffViewer.spec.tsx

changed the lib of the DiffViewer from diff2html to react diff viewer
~~BREAKING CHANGE: the props (and the interface) to use the diffViewer arent the same~~
Mapping the old props to the new one and deprecating them prevents breaking changes.
Go checkout the DiffViewer in the Demo to see the new lib at work

feat(diffviewer): change lib

---

packages/react-vapor/src/components/actionable-item/styles/ActionableItem.scss
packages/vapor/scss/components/header.scss
packages/vapor/scss/components/home-card.scss
packages/vapor/scss/components/menu.scss
packages/vapor/scss/components/navigation.scss
packages/vapor/scss/components/tab.scss
packages/vapor/scss/components/tooltip.scss
packages/vapor/scss/controls/dropdown.scss
packages/vapor/scss/controls/filter-box.scss
packages/vapor/scss/controls/flat-select.scss
packages/vapor/scss/controls/multiline-field.scss
packages/vapor/scss/controls/splash.scss
packages/vapor/scss/elements/btn.scss
packages/vapor/scss/redesign/colors.scss
packages/vapor/scss/redesign/fonts.scss
packages/vapor/scss/redesign/variables.scss
packages/vapor/scss/tables/table-actions.scss
packages/vapor/scss/variables.scss

We created lots of CSS variables to override the style for the light reskin project, and now we want to remove them and apply the new style everywhere. 
There should not have any visual change in this PR, here are components that have been refactored:
- Header
- Navigation
- Gradient
- Button
- Home card
- Filter box
- Tooltip
- Tab
The others will be done in another PR.
None

refactor(next): cleanup of css variables - part 1

---

packages/react-vapor/src/components/validation/hoc/WithDirtyInputHOC.tsx
packages/react-vapor/src/components/validation/hoc/tests/WithDirtyInputHOC.spec.tsx

An issue was found regarding `withDirtyInputHOC` where a component would stop detecting user changes after clearing the `isDirty` flag. The root cause is that `withDirtyInputHOC` kept the last `isDirty` value in a local state and was not aware of the dispatched clear action. So, when user makes new changes to the input, the component thinks it is still dirty and does not dispatch the set dirty action.
In this PR, `withDirtyInputHOC` relies on the store to retrieve the last `isDirty` value instead of the local state. This way it stays synchronized.
None
-   [ ] The potential breaking changes are clearly identified. Does not apply
-   [ ] [README.md](https://github.com/coveo/react-vapor/blob/master/README.md) is adjusted to reflect the …

fix(SFINT-3779): detect changes after clearing dirty flag

---

lerna.json

Set `"allowBranch": ["master", "release-*"]` in lerna, like what we do in admin-ui.
None

build(lerna): add release-* to allow branch

---

CHANGELOG.md
lerna.json
packages/demo/CHANGELOG.md
packages/demo/package-lock.json
packages/demo/package.json
packages/react-vapor/CHANGELOG.md
packages/react-vapor/package-lock.json
packages/react-vapor/package.json

There is an error on Jenkins about the tag.
And the `release-9.34` branch is based on **v9.34.3**
None

build(lerna): change version to 9.34.3

---

packages/react-vapor/src/components/labeledValue/LabeledValue.tsx
packages/react-vapor/src/components/menu/MenuConnected.tsx
packages/vapor/scss/controls/checkboxes.scss
packages/vapor/scss/controls/chosen.scss
packages/vapor/scss/controls/dropdown.scss
packages/vapor/scss/controls/flat-select.scss
packages/vapor/scss/controls/input-field.scss
packages/vapor/scss/controls/slider.scss
packages/vapor/scss/forms/form-validation.scss
packages/vapor/scss/tables/table.scss

This PR contains several minor adjustments on style for the rebranding fix, such as:
- Icon alignments
- Reusable padding-left for checkbox option description
- Label colors, disabled colors, font-weight
- Selected value color in the deprecated dropdown component
- Icon color of the JSON editor error message
- Row style status colors
None

fix(rebranding): minor adjustments on style

---

package-lock.json
packages/react-vapor/package.json
packages/vapor/package.json

https://coveord.atlassian.net/browse/ADUI-6756
Bumping minimist to fix Snyk issue
no

ADUI-6756/snyk bump minimist to 1.2.3

---

packages/react-vapor/package.json

fix(react-vapor): fix "main" and "module" paths in package.json

---

packages/demo/src/components/examples/DatePickerExamples.tsx

the example was missing the code to go with it so I moved it around
Added countdown code under example
None

feat(datepicker): added code example for countdown

---

Jenkinsfile.groovy

https://github.com/coveo/jsadmin_pipeline/pull/25
Update the script to add the comment to github
Look at this PR and check if the comment is here

build(github-comment): update script to add github comment

---

Jenkinsfile.groovy
packages/demo/src/components/ComponentPage.tsx
packages/demo/src/components/examples/CodeEditorExamples.tsx
packages/demo/src/components/examples/ModalWizardExamples.tsx
packages/demo/src/components/examples/modalWindowExamples.tsx
packages/react-vapor/src/components/actions/ActionBar.tsx
packages/react-vapor/src/components/actions/TriggerActionConnected.tsx
packages/react-vapor/src/components/color-picker/ColorPicker.spec.tsx
packages/react-vapor/src/components/color-picker/ColorPicker.tsx
packages/react-vapor/src/components/editor/CodeEditor.tsx
packages/react-vapor/src/components/refresh/tests/RefreshCallback.spec.tsx
packages/react-vapor/src/components/table-hoc/TableWithPagination.tsx
packages/react-vapor/src/components/table-hoc/TableWithPrepend.tsx
packages/react-vapor/src/components/table-hoc/tests/TableWithEmptyState.spec.tsx
packages/react-vapor/src/components/validation/hoc/WithDirtyCheckboxHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithDirtyInputHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithDirtyMultiSelectHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithDirtySaveButtonHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithDirtySingleSelectHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithDirtyStickyFooter.tsx
packages/react-vapor/src/components/validation/hoc/WithInitialValuesMultiSelectHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithNonEmptySingleSelectHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueInputValidationHOC.tsx
packages/react-vapor/src/components/validation/hoc/WithNonEmptyValueMultiSelectValidationHOC.tsx
packages/react-vapor/src/components/validation/hoc/tests/WithDirtySingleSelectHOC.spec.tsx
packages/react-vapor/src/components/validation/hoc/tests/WithNonEmptySingleSelectHOC.spec.tsx
packages/react-vapor/tsconfig.build.json
pnpm-lock.yaml

Fix build and unit tests
I've changed/fixed a couple of interfaces and classes

build(pnpm): fix build and unit tests

---

packages/demo/src/components/examples/BadgeExamples.tsx
packages/vapor/scss/components/badge.scss
packages/vapor/scss/redesign/colors.scss

[Mockup here](https://www.figma.com/file/JbXRfSOwdEuq3VJGpUyyiJ/Coveo-Brand-Library?node-id=1066%3A152)
[Jira here](https://coveord.atlassian.net/browse/ADUI-6814)
Une pierre 2 coups for the badge colors.
UX was ready with the new colors for the badge so I've made all the changes while I was in there.
The new border color will make the badge visible in the selected source row in the source table :tada: 
Before ---> 
After --->
None

fix(badges): new border colors to make the badge stand out

---

packages/vapor/scss/colors.scss
packages/vapor/scss/redesign/colors.scss

Added all the new colors declarations and removed the duplicate variable declarations.
None, some colors will slightly change, but its barely noticable.

feat(vapor): add new colors and remove duplicate variables declaration

---

packages/demo/src/components/examples/CollapsibleExamples.tsx
packages/demo/src/components/examples/LinkSvgExamples.tsx
packages/demo/src/demo-styling/main.scss
packages/react-vapor/src/components/collapsible/CollapsibleContainerConnected.tsx
packages/react-vapor/src/components/collapsible/CollapsibleHeaderIcon.tsx
packages/react-vapor/src/components/collapsible/tests/CollapsibleContainerConnected.spec.tsx
packages/react-vapor/src/components/collapsible/tests/CollapsibleHeaderIcon.spec.tsx
packages/react-vapor/src/components/select/hoc/tests/MultiSelectWithPredicate.spec.tsx
packages/react-vapor/src/components/select/hoc/tests/SelectWithInfiniteScroll.spec.tsx
packages/react-vapor/src/components/select/tests/MultiSelectConnected.spec.tsx
packages/react-vapor/src/components/svg/LinkSvg.tsx
packages/react-vapor/src/components/svg/Svg.tsx

Before
https://user-images.githubusercontent.com/35579930/116117314-14d2f780-a68a-11eb-920c-ff1d6371bd25.mp4
After
https://user-images.githubusercontent.com/35579930/116117551-5b285680-a68a-11eb-8040-d555238a8ea1.mp4
Style of the LinkSvg slightly changed.

fix(collapsible): make collapsible header icon tooltip appear

---

packages/e2eTesting/integration/Collapsible.spec.ts

Validate Collapsible from https://vapor.cloud.coveo.com/#/components/Collapsible

Validate Collapsible

---

packages/vapor/scss/colors.scss
packages/vapor/scss/components/card.scss
packages/vapor/scss/controls/radios.scss
packages/vapor/scss/guide.scss
packages/vapor/scss/utility/shadow.scss
packages/vapor/scss/utility/transitions.scss

- Added the css variables for the 3 elevation shadows on light background.
- Also added a variable for the default transition
None

feat(vapor): added the variables for the shadows on light background

---

Jenkinsfile.groovy

I saw that in the admin we don't have those `--no-push` and it works well.
None

chore: fix tag and release not being created

---

packages/react-vapor/src/components/modalWizard/ModalWizard.tsx
packages/react-vapor/src/components/modalWizard/tests/ModalWizard.spec.tsx

Added the possibility to execute custom code when clicking cancel
none

feat(modal wizard): oncancel

---

packages/demo/src/components/examples/LinkSvgExamples.tsx
packages/demo/src/styles/Menu.tsx
packages/demo/src/styles/typography/Links.tsx
packages/demo/src/styles/typography/index.tsx
packages/react-vapor/src/components/svg/LinkSvg.tsx
packages/vapor/scss/elements/links.scss
packages/vapor/scss/helpers.scss
packages/vapor/scss/icons/icons.scss
packages/vapor/scss/lib/reset.scss
packages/vapor/scss/redesign/variables.scss

Links style have changed in the designs. Since their inception is not finished by the design team, here is a early refresh of the links styles to allow me to continue with the IconCard.
None

feat(links): improve links style

---

pnpm-lock.yaml

Master build if failing because of this.
none

chore(pnpm): update lockfile

---

packages/react-vapor/src/components/editor/index.ts

just added the selector to the index file to export it properly
none

fix(code editor): selectors to export

---

packages/react-vapor/src/components/iconCard/IconCard.tsx
packages/vapor/scss/components/icon-card.scss

Apply some minor visual corrections to the `IconCard` component's padding and font styles as demanded by the design team.
none

fix(iconcard): apply some minor visual corrections to the iconcard

---

packages/vapor/scss/colors.scss
packages/vapor/scss/utility/shadow.scss

Added css variables for these:
None

feat(shadow): add new css variables for shadows

---

packages/demo/src/styles/cards/Home.tsx
packages/demo/src/styles/cards/Material.tsx
packages/demo/src/styles/cards/Wizard.tsx
packages/vapor/scss/components/header.scss

https://coveord.atlassian.net/browse/ADUI-7121
Fixed demo for Home, Wizard and Material.
none

Adui-7121/fix stuff new typekit

---

packages/demo/src/components/examples/BrowserPreviewExamples.tsx
packages/demo/src/components/examples/ColorBarExamples.tsx
packages/demo/src/components/examples/ListBoxExamples.tsx
packages/react-vapor/src/components/blankSlate/BlankSlate.tsx
packages/react-vapor/src/components/blankSlate/tests/BlankSlate.spec.tsx
packages/react-vapor/src/components/statusCard/StatusCard.tsx

https://coveord.atlassian.net/browse/ADUI-7101
none

Adui-7101/fix: fix titles sizes

---

packages/demo/src/components/examples/DatePickerExamples.tsx
packages/react-vapor/src/components/calendar/Calendar.tsx
packages/react-vapor/src/components/datePicker/DatePickerBox.tsx

https://coveord.atlassian.net/browse/ADUI-7095
none

fix: fix date picker style for new typekit

---

packages/demo/src/styles/general-guidelines.tsx
packages/demo/src/styles/typography/Lists.tsx
packages/demo/src/styles/typography/Utilities.tsx

https://coveord.atlassian.net/browse/ADUI-7120
I fixed the style for the Guidelines, List and utilities demo to adapt to the new typekit!
I also tried to improve them a bit, tell me what you think :eyes: 
Should not break anything I have not touch any components.

Adui-7120/fix utilities list general demo

---

packages/demo/src/components/examples/CollapsibleExamples.tsx
packages/react-vapor/src/components/collapsible/CollapsibleConnected.tsx
packages/react-vapor/src/components/collapsible/CollapsibleInfoBox.tsx
packages/react-vapor/src/components/collapsible/tests/CollapsibleInfoBox.spec.tsx

Improved typography, layout, content and examples
[ADUI-7097](https://coveord.atlassian.net/browse/ADUI-7097)
- Fix new Typekit problems
- Improved examples and content
- Refactored CollapsibleInfoBox to functional component
None

style(collapsible): refactored collapsible components and examples

---

packages/react-vapor/src/components/slider/Slider.tsx

when fixing a vulnerability, the sliders interface was changed and it was breaking in the admin. I
used the interface we used before (which extends the current one) and changed it a bit to make sure
the typing is good.

fix(slider.tsx): changed interface for slider

---

packages/react-vapor/.eslintrc.js
packages/react-vapor/src/TestUtils.tsx

See associated jsdocs for description of the change.
None

test(utils): add expectToThrow util

---

packages/demo/src/components/examples/BannerExamples.tsx
packages/demo/src/components/examples/ChartExamples.tsx
packages/demo/src/components/examples/OptionsCycleExamples.tsx
packages/demo/src/components/examples/SeparatorExamples.tsx
packages/demo/src/components/examples/SliderExamples.tsx
packages/demo/src/components/examples/TabConnectedExample.tsx
packages/demo/src/components/examples/TableHOCExamples.tsx
packages/demo/src/components/examples/TableHOCLoadingExamples.tsx
packages/demo/src/components/examples/ToastConnectedExamples.tsx
packages/demo/src/styles/general-guidelines.tsx

https://coveord.atlassian.net/browse/ADUI-7098
Fixed a few nitpick of mine
none

Adui-7098/nitpick fixes new typekit

---

packages/react-vapor/src/components/tab/Tab.tsx
packages/react-vapor/src/components/tab/TabNavigation.tsx
packages/react-vapor/src/components/tab/TabPane.tsx
packages/react-vapor/src/components/tab/tests/Tab.spec.tsx
packages/vapor/scss/components/tab.scss

Our tabs now fully respect the [ARIA norm](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role) with keyboard navigation and all.
None expected.

feat(tabs): improve accessibility of tabs

---

Jenkinsfile.groovy

Needs to be merged after https://github.com/coveo/jsadmin_pipeline/pull/30
None

UI tool 60/use pipeline master version

---

.deployment.config.json
Jenkinsfile.groovy

Snyk will now run on a package-lock generated from the pnpm-lock.
None

ci(snyk): make snyk scan work

---

Jenkinsfile.groovy

Forgot to update the function definition.

ci(jenkins): fix pnpm lock conversion

---

packages/demo/src/components/examples/LimitExamples.tsx
packages/react-vapor/src/components/limit/Limit.tsx
packages/react-vapor/src/components/limit/tests/Limit.spec.tsx
packages/vapor/scss/components/limit-box.scss

+onClick method, +UTs, *style-color

feat(limit): +onClick method on history icon

---

packages/react-vapor/src/components/limit/Limit.tsx

not suppose to be decisive of limit label value

fix(limits): removed conditional limitlabel

---

packages/react-vapor/src/components/actions/ActionsDropdown.tsx
packages/react-vapor/src/components/actions/LinkAction.tsx
packages/react-vapor/src/components/actions/TriggerActionConnected.tsx
packages/react-vapor/src/components/dropdown/Dropdown.tsx
packages/react-vapor/src/components/table-hoc/tests/TableWithActions.spec.tsx
packages/react-vapor/src/utils/InputUtils.ts

Make the table actions more accessible
* Add possibility to trigger the event with space and enter
* Add a tabIndex to make it possible to focus on the actions
None

feat(table): make the table actions more accessible

---

packages/react-vapor/src/components/checkbox/Checkbox.tsx
packages/react-vapor/src/components/checkbox/CheckboxContext.ts
packages/react-vapor/src/components/checkbox/tests/Checkbox.spec.tsx
packages/react-vapor/src/components/input/Label.tsx
packages/vapor/scss/controls/checkboxes.scss

Improve accessibility of the checkbox component
Update the focus and hover colour at the same time
Add some unit tests with RTL

feat: improve accessibility of the checkbox component

---

packages/e2eTesting/CHANGELOG.md
packages/react-vapor/src/components/table-hoc/actions/TableHOCRowActions.ts
packages/react-vapor/src/components/table-hoc/reducers/TableRowReducers.ts
packages/react-vapor/src/components/table-hoc/tests/TableRowReducers.spec.ts

Add new action for `TableHOCRowActions`, `closeAllCollapsible`, for closed all collapsible row

feat(table-hoc): add action close all collapsible row

---

packages/vapor/scss/controls/text-input.scss

https://coveord.atlassian.net/browse/UITOOL-133
None

fix: changed the width for min-width at 320px

---

packages/vapor/scss/components/toast.scss

fix(toast): add word-break to toast-title

---

packages/react-vapor/src/components/inlinePrompt/InlinePrompt.tsx
packages/react-vapor/src/components/inlinePrompt/tests/InlinePrompt.spec.tsx

Removed the icon from the <InlinePrompt /> component that's used in the action bar
None

feat(inlineprompt): removed icon from inline prompt

---

packages/vapor/scss/components/selected-option.scss
packages/vapor/scss/variables.scss

https://coveord.atlassian.net/browse/UITOOL-186
When exploring, the difference didn't look as extreme to me as it did in the screenshot in the ticket, but I made an adjustment of 1px to the line-height anyway
None

style(multiselect): reduced the min-height by 1px

---

packages/vapor/scss/components/list-box.scss

style change to the listbox scrollbar
Customer eye bleeding before a too obvious scrollbar
Designers will review this before merging.

fix(list box): scrollbar visibility

---

packages/vapor/scss/components/lightbox-search.scss

Style adjustments to the lightbox search
your eyes

feat(lightbox search): style update

---

packages/demo/src/components/examples/RadioExamples.tsx
packages/vapor/resources/icons/svg/content/disabled-radiocheck.svg
packages/vapor/resources/icons/svg/content/radiocheck.svg
packages/vapor/scss/controls/radios.scss
packages/vapor/scss/typography/utility.scss
packages/vapor/scss/variables.scss

Applied early designs of the radio button to fix alignment at the same time

fix(radio): refresh style of radio buttons

---

packages/react-vapor/src/components/table-hoc/TableHeaderWithSort.tsx

https://coveord.atlassian.net/browse/UITOOL-205
Removed title attribute. It didn't any any value and caused UI issues with the tooltip

fix(remove title from th): title is unnecessary and causes UI issue

---

packages/react-vapor/src/components/title/Title.tsx

fix(title component): changed mr1 for m1

---

Jenkinsfile.groovy
packages/react-vapor/package.json
packages/react-vapor/rollup.config.js
packages/react-vapor/src/Version.ts
pnpm-lock.yaml

- Remove `lerna version` command from the prepare stage, `lerna publish` internally does the same thing during the publish stage
- Extract the novelty check (new commits on master = abort) outside the publish stage
- Remove duplicate version bump commits (kept the one with the version in it)
- Extract snyk outside the deployment pipeline stage
- Extract veracode outside the deployment pipeline stage
Release process might break, will take care of fixing it if that happens.

Refactor & clarify Jenkinsfile

---

.github/renovate.json

Basic renovate configuration
I would suggest changing the schedule to something outside of working hours once we're happy and we know it works
None, doesn't impact the code

feat(deps): add renovate bot configuration

---

Jenkinsfile.groovy

Small changes to the way we print the build success message in Slack. It will allow us to build branches instead of PR and will make the renovate bot happier
None

chore(ci): use the commit hash instead of the change_id

---

Jenkinsfile.groovy

There was a rotation of credentials, and it seems the new token cannot publish anymore. I switched to the same credentials we use in admin-ui
None

ci: fix the git credentials

---

packages/tokens/.env.example
packages/tokens/.gitignore
packages/tokens/README.md
packages/tokens/bin/.eslintrc.js
packages/tokens/bin/fetch.ts
packages/tokens/bin/lib/mappings.ts
packages/tokens/bin/tsconfig.json
packages/tokens/package.json
pnpm-lock.yaml

Created the [`tokens`](https://github.com/coveo/react-vapor/tree/UITOOL-236/implement-tokens-fetch-logic/packages/tokens#readme) package.
Implemented the logic to fetch the tokens from our tokens library.
None

feat(tokens): initialize tokens package + implement fetch tokens logic

---

packages/tokens/README.md
packages/tokens/bin/build.ts
packages/tokens/package.json
packages/tokens/tsconfig.json
pnpm-lock.yaml

Implement the `tokens:build` command. The build and different output formats cannot be implemented yet because we have not settled what we want to extract first with the UX team.
none

[tokens] Implement build command logic

---

.github/renovate.json

- Set a schedule to run outside of work hours to reduce noise
- Change the type back to pr because the branch is not compatible with branch restrictions
None

ci(renovate): update config

---

packages/demo/package.json
packages/react-vapor/package.json
pnpm-lock.yaml

Updated demo's coveo-styleguide to match that of react-vapor

fix(package): update coveo styleguide

---

Jenkinsfile.groovy
lerna.json
packages/demo/package.json
packages/e2eTesting/package.json
packages/react-vapor/package.json
packages/tokens/package.json
packages/vapor/package.json
pnpm-lock.yaml

Reverting back to not using `--no-git-tag-version` as it prevents from creating releases (again undocumented behavior 😞 ).
Instead I am manually deleting the git tag it creates to recreate it after the commit is amended.
None

UI tool 292/use lerna tag behavior

---

.github/renovate.json
CODEOWNERS

[UITOOL-295](https://coveord.atlassian.net/browse/UITOOL-295)
Remove the Codeowners assignation from package.json and pnpm-lock.yaml
Disable renovate rebasing outside of schedule
Nothing to test
Renovate PRs

chore(renovate): reduce noise

---

packages/react-vapor/src/components/textarea/TextArea.tsx
packages/react-vapor/src/components/textarea/tests/TextArea.spec.tsx
packages/vapor/scss/typography/utility.scss

[UITOOL-291](https://coveord.atlassian.net/browse/UITOOL-291)
None

fix(textarea): render disabled textarea as paragraph

---

.deployment.config.json
Jenkinsfile.groovy
README.md
build/deploy-demo.sh
packages/demo/package.json
packages/react-vapor/README.md

The demo will now be deployed in the RD environment.
The demo will now be hosted at `vapor.coveo.com`

ci: deploy demo in RD bucket

---

packages/demo/src/demo-building-blocs/nav-items.ts

Created a hardcoded structure for the side nav from Figma https://www.figma.com/file/ZCYszsYyyPpLnlUF7Zc81u/Plasma-Website?node-id=920%3A37595

refactor(sidenav): hardcoded the sidenav structure

---

packages/demo/src/demo-styling/home.scss
packages/demo/src/plasma/Home.tsx

https://coveord.atlassian.net/browse/UITOOL-207
This is the layout for the Home page (overview page) for Plasma!
I've put placeholders to demo the style for the future TileComponent.
The TileComponent is currently in review here ---> https://github.com/coveo/react-vapor/pull/2312 
None

UITOOL-207/layout for overview page

---

packages/demo/src/plasma/Home.tsx

https://coveord.atlassian.net/browse/UITOOL-345
Set the links for the tiles in the Home page
None

feat(homepage): set href to tiles to redirect to component page

---

packages/react-vapor/src/components/modalWizard/ModalWizard.tsx
packages/react-vapor/src/components/svg/SvgNames.ts
packages/vapor/resources/icons/svg/minus-16px.svg
packages/vapor/resources/icons/svg/minus-32px.svg

- Added some minus icons to go with the `plus` icons.
- I need both so let's go! 🎉 

feat(icons): added minus icons

---

packages/vapor/scss/components/lightbox-search.scss

css change to respect Coveo design
none

fix(lightbox): respect new coveo styling on hover

---

Jenkinsfile.groovy
package.json
packages/react-vapor/jest.config.js
packages/react-vapor/package.json

https://coveord.atlassian.net/browse/UITOOL-350
First pr to improve build time for Jest + set the workers for local run and Jenkins run :eyes: 
none

perf(jest): change config of Jest to make uts run faster

---

packages/demo/src/demo-building-blocs/VaporComponent.tsx

fix(demo): remove extraneous padding of the usage tab

---

packages/tokens/package.json

Following IT ticket the npm user now has the privilege to publish the package so let's make it public
None

build(tokens): make package public

---

packages/vapor/scss/tables/table.scss

Make disabled table rows appeared greyed out.
Before
After
None

fix(table): make disabled table rows appear greyed out

---

packages/demo/src/plasma/routes/foundations/pages/typekit/UtilitiesExamples.tsx
packages/vapor/scss/typekit.scss

- Added typekit styling class `.code` which displays text in code format following the same style as our public documentation. 

feat(typekit): added code class

---

packages/demo/package.json
packages/demo/src/Index.tsx
packages/demo/src/Store.ts
packages/demo/src/demo-building-blocs/Sandbox.tsx
packages/demo/src/demo-building-blocs/useTypescriptServer.ts
packages/demo/src/demo-styling/sandbox.scss
packages/demo/tsconfig.json
packages/demo/webpack.config.js
pnpm-lock.yaml

Required code to have a Sandbox component that accept any code and render the results
https://user-images.githubusercontent.com/260007/146600870-0fdc64e3-65c5-4889-8011-e1a73b68f2c8.mov
None

feat(code-editor): Dynamic code editor in the demo

---

packages/demo/src/demo-building-blocs/ExampleLayout.tsx
packages/demo/src/demo-building-blocs/GuidelinesTab.tsx
packages/demo/src/demo-building-blocs/Sandbox.tsx
packages/demo/src/demo-building-blocs/VaporComponent.tsx
packages/demo/src/demo-styling/example-layout.scss
packages/demo/src/demo-styling/sandbox.scss
packages/demo/src/plasma/routes/input/index.tsx
packages/demo/src/plasma/routes/input/pages/ButtonV2.tsx

Create the new page for the plasma components
Move the guidelines in a separate component
None

feat(demo): create new page layout for plasma components

---

packages/website/src/building-blocs/PropsDoc.tsx
packages/website/src/building-blocs/Sandbox.tsx
packages/website/src/styles/sandbox.scss

https://user-images.githubusercontent.com/35579930/150016885-2bf026e0-6706-4724-aed4-b77f66b99a54.mp4
None

feat(website): make sandboxes fit their content

---

packages/react/package.json

Add start command for PlasmaReact

feat(react): add start command

---

packages/website/src/index.html

rename "Vapor Design System" to "Plasma Design System"

refactor(website): change page title

---

Jenkinsfile.groovy
README.md
build/deploy-demo.sh
packages/react/README.md
packages/style/README.md
packages/style/package.json
packages/website/package.json

The website is now available at plasma.coveo.com
None

refactor(website): change website url to plasma.coveo.com

---

packages/website/src/SideNavigation.tsx
packages/website/src/pages/Home.tsx

Links to the external coveo brand website
none

feat(website): add coveo brand links

---

packages/website/src/pages/Home.tsx
packages/website/src/styles/home.scss

Adjust the size for the title to be smaller
before:
After:
none

fix(homepage): fix style for page title

---

packages/react/src/components/optionPicker/Option.tsx
packages/react/src/components/optionPicker/tests/Option.spec.tsx
packages/react/src/components/optionPicker/tests/OptionPicker.spec.tsx
packages/style/scss/components/calendar.scss
packages/website/src/pages/form/DatePickerExamples.tsx
packages/website/src/utils/DatePickerExamplesCommon.ts

Added a simple disable prop to a use case of a custom datepicker in UA

feat(optionpicker): +disable prop on option interface

---

packages/website/src/index.html
packages/website/webpack.config.js

Remove the need to specify the path to the css file since we use HtmlWebpackPlugin
None

fix(loading): add a chunk for the loading logo

---

packages/website/src/search/engine/Engine.ts

Search from prod org. Access token only has access to execute queries and push analytics data
None

refactor(website): make search use our prod org

---

packages/website/docs/TextInput.md
packages/website/src/building-blocs/Guidelines.tsx
packages/website/src/pages/Home.tsx
packages/website/src/pages/form/TextInputExamples.tsx

Revised all texts to match current state of the text inputs.
It's a first draft and more guidelines will be added later on if needed.
The best practices appears in quotes format as an attempt to style them within a grey box, not sure if how it would like in the real website though...
The description of the component (which should appear on the tile and in the header of its page) is commented in this file so that you guys have access.
I wasn't able to dismiss the hyperlink on the email, so please help. 
Please make sure that the information here is compliant with the current behavior. If not, indicate how. 
If there is no specific code that prevents a user to apply such guidelines, we can keep it there.
This I don't know ⬇️ 
-   [ ] …

Revised TextInput.md

---

packages/website/docs/MultiSelect.md
packages/website/src/pages/Home.tsx
packages/website/src/pages/form/MultiSelectExamples.tsx

Revised multi-select guidelines for MVP
I'm doing so layout test below, please disregard that section.
Please make sure that the information here is compliant with the current behavior. If not, indicate how.
If there is no specific code that prevents a user to apply such guidelines, we can keep it there.
This I don't know ⬇️

Revised MultiSelect.md

---

packages/website/src/pages/SearchResultPage.tsx

- Add query in the search results page title
- Add number of results
None

refactor(website): improve search results page

---

packages/react/package.json
packages/react/src/Entry.ts
packages/react/src/Version.ts

Remove the version variable containing the current version number
The version variable will cease to exist, go look in the package.json to know what is your current version

feat(version): remove version

---

TokensExtraction.groovy

This job doesn't do much for now but its just to see if jenkins can authenticate properly. When this PR is merged I will able to play around with it to make it work.
none

feat(tokens): create a jenkins job for tokens extraction

---

packages/website/src/FeatureFlags.tsx
packages/website/src/search/StandaloneSearchBar.tsx

https://coveord.atlassian.net/browse/UITOOL-437
none

feat(featureflag): put FF on query suggestions + remove from search bar

---

packages/website/src/SideNavigation.tsx
packages/website/src/building-blocs/PlasmaComponent.tsx
packages/website/src/building-blocs/Tile.tsx
packages/website/src/search/StandaloneSearchBar.tsx
packages/website/src/styles/main.scss
packages/website/src/styles/plasmaSearchBar.scss

https://coveord.atlassian.net/browse/UITOOL-444
Check for:
- Side nav items
- Component page titles
- Thumbnail title
- Query suggestions
none

refactor(css): component title are now in sentence-case

---

packages/website/src/OneDemoToRuleThemAll.tsx
packages/website/src/styles/home.scss
packages/website/src/styles/main.scss
packages/website/src/styles/plasmaSearchBar.scss

feat(website): tweak the css a bit to have a responsive search bar
feat(website): animate the logo background
None, only impacting the website

Some small CSS changes

---

packages/website/src/pages/form/ButtonExamples.tsx

The example showcased a pattern we don't want people to reproduce for copy to clipboard behaviour
Before
After
None

fix(button): remove bad copy to clipboard example

---

packages/style/index.d.ts

fix(plasma-style): render function parameters are all optional

---

packages/website/src/pages/layout/IconCardExamples.tsx

Small typo in Icon Card Example section

chore(iconcard): example section typo

---

packages/website/src/pages/layout/TableHOCExamples.tsx

We tried to spread a function and that is not possible with SWC
None

fix(website, tableHOC): cannot spread a function

---

packages/website/docs/Button.md

Guidelines fresh out of the UX oven ready for review!
Refined all guidelines. 
None
This I don't know 👇 

Revised button guidelines for Plasma

---

packages/website/docs/ToastConnected.md

fixed or removed outdated related components links (popover was removed)
changed the table titles styling
fixed a few text.

Remove outdate guidelines for Toast

---

packages/website/src/pages/SearchResultPage.tsx

A little hack to make the search work again
None

fix(website): use Next pipeline for the search

---

packages/website/src/pages/Home.tsx
packages/website/src/pages/feedback/BadgeExamples.tsx
packages/website/src/pages/feedback/ColorDotExamples.tsx
packages/website/src/pages/feedback/LastUpdatedExamples.tsx
packages/website/src/pages/feedback/LoadingExamples.tsx
packages/website/src/pages/feedback/ProgressBarExamples.tsx
packages/website/src/pages/feedback/ToastExamples.tsx
packages/website/src/pages/feedback/TooltipExamples.tsx
packages/website/src/pages/form/FilepickerExamples.tsx
packages/website/src/pages/form/FilterBoxExamples.tsx
packages/website/src/pages/form/FlatSelectExamples.tsx
packages/website/src/pages/form/JSONEditorExamples.tsx
packages/website/src/pages/form/MultiSelectExamples.tsx
packages/website/src/pages/form/MultilineBoxExamples.tsx
packages/website/src/pages/form/NumericInputExamples.tsx
packages/website/src/pages/form/RadioButtonExamples.tsx
packages/website/src/pages/form/SearchBarExamples.tsx
packages/website/src/pages/form/SingleSelectExamples.tsx
packages/website/src/pages/form/SliderExamples.tsx
packages/website/src/pages/form/TextAreaExamples.tsx
packages/website/src/pages/form/TextInputExamples.tsx
packages/website/src/pages/layout/CollapsibleExamples.tsx
packages/website/src/pages/layout/InfoBoxExamples.tsx
packages/website/src/pages/layout/LimitExamples.tsx
packages/website/src/pages/navigation/BreadcrumbsExamples.tsx
packages/website/src/pages/navigation/SideNavigationExamples.tsx
packages/website/src/pages/navigation/SubNavigationExamples.tsx
packages/website/src/pages/navigation/TabsExamples.tsx

https://coveord.atlassian.net/browse/UITOOL-425
Second half of the descriptions for the components! 
none

feat(descriptions): adding descriptions for components part 2

---

Jenkinsfile.groovy

Code coverage is not useful for us + it's now failing so :scissors: 
none

ci: remove code coverage step

---

.deployment.config.json
packages/website/next.config.js

Fix issue that happen when we deploy on master
None

fix(website): deploy of nextjs on master

---

package.json
packages/react/package.json

https://coveord.atlassian.net/browse/UITOOL-408
The same is being done in the admin-ui project. PR incomming.
This new command let you run only the tests impacted by any of your changes. 
None

test(test:changed): new script to only run impacted uts from root

---

TokensExtraction.groovy

Implemented the "Open pull request" stage in the TokenExtraction jenkins job. We can see that it worked here: https://github.com/coveo/plasma/pull/2467
This PR: https://github.com/coveo/jsadmin_pipeline/pull/37 has to be merged first for it to fully work.
None

feat(tokens): create a github PR from jenkins job

---

packages/website/build/getBasePath.js
packages/website/next-sitemap.js
packages/website/next.config.js

Applied the same change that I did to fix master on the sitemap. Extracted the logic in a function to re-use it
None

fix(website): changed the sitemap base url on master

---

packages/website/docs/Slider.md

###Proposed Changes
revised all guidelines
###Potential Breaking Changes
N\A
###Acceptance Criteria
This I don't know 👇

MVP guidelines for Slider

---

.deployment.config.json
Jenkinsfile.groovy
packages/website/docs/Button.md
packages/website/docs/Slider.md
packages/website/tsconfig.json

https://coveord.atlassian.net/browse/UITOOL-471
Initial setup for Snyk-Code + removing the veracode steps
Should be none

ci(snyk-code): initial setup

---

.deployment.config.json

ci(snyk-code): config need to be an array

---

packages/website/docs/CodeEditor.md

New guidelines
Once this version is approved and proof-read, I will based the JSON editor guidelines on it.
New guidelines
None

MVP guidelines for CodeEditor

---

packages/website/docs/NumericInput.md

revised all guidelines
N\A
This I don't know 👇 

MVP guidelines for Numerical Input

---

packages/website/package.json
pnpm-lock.yaml

open-cli is cross-os compatible (open does not working on Linux)
Should be none  - pull the branch and run pnpm start, see if the website start properly :smile: 

build(open-cli): using open-cli for start script

---

Jenkinsfile.groovy
build/publishNewVersion.mjs
package.json
pnpm-lock.yaml

Added a bit of logs to help debug issues with the publish step
None?

build(publish): add debugging information in publish script

---

packages/react/src/components/actionable-item/ActionableItem.tsx
packages/react/src/components/actionable-item/tests/ActionableItem.spec.tsx
packages/website/src/pages/_app.tsx
packages/website/src/pages/_document.tsx
packages/website/src/pages/form/ActionableItem.tsx
packages/website/src/pages/foundations/Iconography.tsx

Switch out Svg for plasma-react-icons in ActionableItem component
Before
After
None

feat(react): remove Svg from ActionableItem

---

Jenkinsfile.groovy

When looking at the logs of the last publish it seems like it failed on the push and stoped processing steps after that
None

build(publish): make sure we track the remote branch

---

packages/react-icons/.swcrc
packages/react-icons/package.json
packages/react-icons/tsconfig.json
pnpm-lock.yaml

Added SWC to plasma-react-icons package to distribute the package both to cjs and esm
none

feat(react-icons): add module field to package.json

---

packages/react/src/components/datePicker/SetToNowButton.tsx
packages/react/src/components/datePicker/tests/SetToNowButton.spec.tsx
packages/style/scss/components/calendar.scss

fix(react): fix the date picker SetToNow button

---

packages/website/src/building-blocs/PageLayout.tsx
packages/website/src/pages/foundations/Links.tsx

refactor(website): update the links demo page

---

packages/react/src/components/badge/Badge.tsx
packages/website/src/pages/feedback/Badge.tsx

https://coveord.atlassian.net/browse/UITOOL-567
none

feat(demo): revamp badge page

---

packages/website/src/SideNavigation.tsx
packages/website/src/pages/foundations/Typekit.tsx

https://coveord.atlassian.net/browse/UITOOL-586
none

feat: add link to external design priciples

---

packages/website/src/pages/foundations/Typekit.tsx
packages/website/src/pages/layout/BorderedLine.tsx

https://coveord.atlassian.net/browse/UITOOL-526
none

feat(demo): update bordered line page

---

packages/react/src/components/iconCard/IconCard.tsx
packages/react/src/components/svg/Svg.tsx
packages/react/src/components/svg/SvgChild.tsx
packages/website/src/pages/layout/IconCard.tsx

refactor(website): revamp the icon card demo page

---

packages/react/src/components/browserPreview/BrowserPreview.tsx
packages/website/src/pages/form/TextInput.tsx
packages/website/src/pages/foundations/Typekit.tsx
packages/website/src/pages/layout/BrowserPreview.tsx

https://coveord.atlassian.net/browse/UITOOL-527
none

feat(demo): update browser preview page

---

packages/react/src/components/iconBadge/IconBadge.tsx
packages/website/src/pages/feedback/IconBadge.tsx
packages/website/src/pages/foundations/Typekit.tsx

https://coveord.atlassian.net/browse/UITOOL-570
none

feat(demo): update icon badge page

---

packages/website/docs/Iconography.md

Added basic guidelines as provided by Shannon in iconography
None

docs(iconography): add basic guidelines

---

packages/react/src/components/modalWizard/ModalWizard.tsx
packages/website/src/pages/layout/ModalWizard.tsx

Update the ModalWizard page to the new layout 
None

refactor(website): update ModalWizard demo page

---

packages/website/src/pages/layout/InfoBox.tsx

refactor(website): update the InfoBox component demo page

---

packages/react/src/components/checkbox/Checkbox.tsx
packages/website/src/pages/form/Checkbox.tsx

refactor(website): update the checkbox component demo page

---

packages/react/src/components/numericInput/NumericInputConnected.tsx
packages/style/scss/controls/numeric-input.scss
packages/style/scss/variables.scss
packages/website/src/pages/form/NumericInput.tsx

refactor(website): update numeric input page

---

packages/react/src/components/splitlayout/SplitLayout.tsx
packages/website/src/pages/layout/SplitLayout.tsx

refactor(website): update split layout demo page

---

packages/react/src/components/actionable-item/ActionableItem.tsx
packages/website/src/pages/form/ActionableItem.tsx

Update the demo for the Actionable Item
Added JsDoc for props
None

refactor(website, actionable item): update the page layout

---

packages/react/src/components/editor/CodeEditor.tsx
packages/react/src/components/editor/JSONEditor.tsx
packages/website/src/pages/form/CodeEditor.tsx

refactor(website): update the code editor demo page

---

packages/react/src/components/facets/Facet.tsx
packages/react/src/utils/ReduxUtils.ts
packages/website/src/pages/form/Facet.tsx

Updated the layout of the Facet demo page
Added JsDoc on the Facet component
None

refactor(website, facet): change layout for demo

---

packages/react/src/components/filepicker/Filepicker.tsx
packages/website/src/pages/form/Filepicker.tsx

Update the layout of the file picker demo page
None

refactor(website, file picker): update the demo layout

---

packages/react/package.json
packages/react/src/components/diffViewer/DiffViewer.tsx
packages/website/package.json
packages/website/src/building-blocs/useTypescriptServer.ts
packages/website/src/pages/form/DiffViewer.tsx
pnpm-lock.yaml

Same as #2568 I'm not sure what went wrong on my rebase
None

refactor(website, diffviewer): update example page layout

---

packages/react/src/components/radio/RadioSelect.tsx
packages/react/src/components/radio/RadioSelectConnected.tsx
packages/website/src/examples/RadioButton/main.example.tsx
packages/website/src/examples/RadioButton/radioCard.example.tsx
packages/website/src/pages/form/RadioButton.tsx

Update RadioButton demo page

---

packages/react/src/components/calendar/Calendar.tsx
packages/react/src/components/calendar/Countdown.tsx
packages/react/src/components/datePicker/DatePicker.tsx
packages/react/src/components/datePicker/DatePickerBox.tsx
packages/react/src/components/datePicker/DatePickerDropdown.tsx
packages/react/src/components/datePicker/DatePickerDropdownConnected.tsx
packages/react/src/components/datePicker/DatesSelection.tsx
packages/react/src/components/table-hoc/TableWithDatePicker.tsx
packages/website/src/SideNavigation.tsx
packages/website/src/building-blocs/Sandbox.tsx
packages/website/src/pages/form/Countdown.tsx
packages/website/src/pages/form/DatePicker.tsx
packages/website/src/pages/index.tsx

UI tool 549/date picker

---

packages/react/src/components/filterBox/FilterBox.tsx
packages/react/src/components/filterBox/FilterBoxConnected.tsx
packages/website/src/pages/form/FilterBox.tsx

Updated the layout of the Filter Box demo page
Added JsDoc on the Filter Box component
None

refactor(website, filter box): change layout for demo

---

packages/react/src/components/slider/Slider.tsx
packages/website/package.json
packages/website/src/building-blocs/useTypescriptServer.ts
packages/website/src/examples/Slider/Slider.example.tsx
packages/website/src/examples/Slider/SliderAppend.example.tsx
packages/website/src/examples/Slider/SliderAsymetric.example.tsx
packages/website/src/examples/Slider/SliderOnChange.example.tsx
packages/website/src/pages/form/Slider.tsx
pnpm-lock.yaml

Added JsDoc on Slider props
Updated Slider demo layout
None

refactor(website, slider): update demo layout

---

packages/react/src/components/colorBar/ColorBar.tsx
packages/website/src/examples/ColorBar/ColorBar.example.tsx
packages/website/src/examples/ColorBar/ColorBarOverflow.example.tsx
packages/website/src/examples/ColorBar/ColorBarPartial.example.tsx
packages/website/src/pages/feedback/ColorBar.tsx

Added JsDoc on ColorBar props
Updated ColorBar demo layout
None

refactor(website, color bar): update demo layout

---

packages/react/src/components/lastUpdated/LastUpdated.tsx
packages/react/src/components/lastUpdated/LastUpdatedConnected.tsx
packages/website/src/examples/LastUpdated/LastUpdated.example.tsx
packages/website/src/examples/LastUpdated/LastUpdatedSpecifiedTime.example.tsx
packages/website/src/pages/feedback/LastUpdated.tsx

Added JsDoc on LastUpdated props
Updated LastUpdated demo layout
None

refactor(website, last updated): update demo layout

---

packages/website/src/pages/advanced/OptionsCycle.tsx

See page in advanced section of the website

refactor(website): update OptionsCycle demo page

---

packages/website/src/pages/advanced/PartialStringMatch.tsx

See page in advanced section of the website

refactor(website): update partial string match demo page

---

packages/website/src/examples/ListBox/loading.example.tsx
packages/website/src/examples/ListBox/main.example.tsx
packages/website/src/pages/advanced/ListBox.tsx

See page in advanced section of the website

refactor(website): update ListBox demo page

---

packages/react/src/components/info-token/InfoToken.tsx
packages/website/src/examples/InfoToken/critical.example.tsx
packages/website/src/examples/InfoToken/info.example.tsx
packages/website/src/examples/InfoToken/main.example.tsx
packages/website/src/examples/InfoToken/question.example.tsx
packages/website/src/examples/InfoToken/success.example.tsx
packages/website/src/examples/InfoToken/tip.example.tsx
packages/website/src/examples/InfoToken/warning.example.tsx
packages/website/src/pages/advanced/InfoToken.tsx

refactor(website): update InfoToken demo page

---

packages/react/src/components/stepProgressBar/StepProgressBar.tsx
packages/website/src/pages/feedback/StepProgressBar.tsx

refactor(website): update StepProgressBar demo page

---

packages/react/src/components/loading/Loading.tsx
packages/website/src/examples/Header/loading.example.tsx
packages/website/src/examples/Header/main.example.tsx
packages/website/src/pages/feedback/Loading.tsx
packages/website/src/pages/layout/PageHeader.tsx

refactor(website): update loading demo page

---

packages/react/src/animations/SlideY.tsx
packages/website/src/examples/SlideY/main.example.tsx
packages/website/src/pages/advanced/SlideY.tsx

See page in advanced section of the website

refactor(website): update slide Y demo page

---

packages/react/src/components/editor/JSONEditor.tsx
packages/react/src/components/editor/JSONEditorConnected.tsx
packages/react/src/components/editor/tests/JSONEditor.spec.tsx
packages/react/src/components/editor/tests/JSONEditorConnected.spec.tsx
packages/website/.eslintrc.js
packages/website/src/examples/JSONEditor/InError.example.tsx
packages/website/src/examples/JSONEditor/JSONEditor.example.tsx
packages/website/src/examples/JSONEditor/ReadOnly.example.tsx
packages/website/src/examples/JSONEditor/ValueState.example.tsx
packages/website/src/pages/form/JSONEditor.tsx

Update the demo page of the JSON Editor
None

refactor(website, json editor): update the demo page

---

packages/react/src/components/actions/SecondaryActions.tsx
packages/react/src/components/actions/tests/SecondaryActions.spec.tsx
packages/react/src/components/editor/tests/CodeEditor.spec.tsx
packages/style/scss/controls/dropdown.scss

https://coveord.atlassian.net/browse/UITOOL-431
I removed the focus style on the more button
none

fix(actions): removed focus style on more button

---

Jenkinsfile.groovy
package.json
pnpm-lock.yaml

Let's add a bit of debug to see what we run and why it breaks!
None

docs: add debug information on publish

---

package.json
pnpm-lock.yaml

Bump dependency
It now returns the process and should help debug the issue with releases
None

chore(deps): bump semantic-monorepo-tools

---

packages/react/src/components/drop/DropPod.tsx
packages/react/src/components/drop/tests/DropPod.spec.tsx

Evolved version of what I proposed here https://github.com/coveo/plasma/pull/2603#discussion_r837757681
None?

fix(react, drop): use last position

---

packages/website/docs/MultilineBox.md

Was reviewed by UX and Danny
New guidelines
None I hope

MVP guidelines for Multiline box

---

packages/website/docs/Button.md

Added more details about the order of button
Added the "Order of button" section and move the previous guidelines in that section and added more details.
non

Button Guidelines - Ordering

---

packages/react/src/components/iconCard/IconCard.tsx
packages/react/src/components/iconCard/tests/IconCard.spec.tsx
packages/style/scss/components/icon-card.scss

IconCard title update:
- changing h6 -> h5
- fontweight to be 500
Both changes confirmed with @guscoveo 

style(icon-card): title styling change

---

packages/react-icons/bin/template.js
packages/react/src/components/actionable-item/tests/ActionableItem.spec.tsx
packages/react/src/components/actions/Action.tsx
packages/react/src/components/actions/TriggerActionConnected.tsx
packages/react/src/components/actions/tests/Action.spec.tsx
packages/react/src/components/badge/tests/Badge.spec.tsx
packages/react/src/components/browserPreview/tests/BrowserPreview.spec.tsx
packages/react/src/components/collapsible/tests/CollapsibleContainerConnected.spec.tsx
packages/react/src/components/collapsible/tests/CollapsibleInfoBox.spec.tsx
packages/react/src/components/collapsible/tests/CollapsibleToggle.spec.tsx
packages/react/src/components/info-token/tests/InfoToken.spec.tsx
packages/react/src/components/inlinePrompt/InlinePrompt.tsx
packages/react/src/components/textInput/tests/TextInput.spec.tsx
packages/react/src/components/toast/tests/Toast.spec.tsx
packages/website/src/examples/ActionBar/ActionBar.example.tsx
packages/website/src/examples/Table/withAction.example.tsx

https://coveord.atlassian.net/browse/UITOOL-496
Removed old svgs and they are replace with Icons
None 🤔  well theres is but we will tag them once when we merge next into master no? xD

UITOOL-496/remove svg from action bar

---

packages/react/src/components/datePicker/DatePickerDropdown.tsx
packages/react/src/components/dropdownSearch/DropdownSearch.tsx
packages/react/src/components/select/MultiSelectConnected.tsx
packages/react/src/components/select/SingleSelectConnected.tsx
packages/style/scss/controls/dropdown.scss
packages/website/src/building-blocs/PageLayout.tsx
packages/website/src/building-blocs/Sandbox.tsx
packages/website/src/pages/_app.tsx

Before
After
Before
After
Before
After

Use new icons for dropdown toggle arrows

---

packages/react/src/components/datePicker/SetToNowButton.tsx
packages/react/src/components/datePicker/tests/SetToNowButton.spec.tsx
packages/react/src/components/optionsCycle/OptionsCycle.tsx
packages/style/scss/components/calendar.scss

refactor(react): use new icons in date picker

---

packages/website/src/Store.ts
packages/website/src/building-blocs/PropsDoc.tsx
packages/website/src/building-blocs/Sandbox.tsx
packages/website/src/building-blocs/useTypescriptServer.ts
packages/website/src/pages/_app.tsx

Create the Typescript system and environment only once and re-use it in all pages
Stop modifying the map of file, instead write the file in the environment
Remove the useTypescriptServer from the Sandbox, it wasn't useful
https://user-images.githubusercontent.com/260007/167716604-172d9600-7383-4c50-8940-16561a7ad55c.mov
None, only affects the website

fix(website): performance issue with props table

---

TokensExtraction.groovy

Update scripts so that the token extraction job can work with pnpm7
None

ci(tokens): update scripts to work with pnpm 7

---

packages/website/src/Store.ts
packages/website/src/building-blocs/Sandbox.tsx

https://coveord.atlassian.net/browse/UITOOL-682
Fix the render for the server side table demo
None, it's only the website that was broken 

fix(tableserverside): fix store creation for sandbox

---

packages/react/src/components/calendar/tests/CalendarConnected.spec.tsx
packages/react/src/components/datePicker/DatePickerReducers.ts
packages/website/src/Store.ts

Auto focusing on the start date after the end date has been selected improves the usability of the component.
https://user-images.githubusercontent.com/35579930/167891275-dfa65619-47e3-45ab-81dc-21fce221bd06.mov

Date range picker behaviour improvements

---

packages/react/package.json
packages/react/src/components/loading/LoadingCircle.tsx
packages/react/src/components/loading/LoadingSpinner.tsx
packages/react/src/components/loading/index.ts
packages/react/src/components/searchBar/SearchBar.tsx
packages/react/src/components/searchBar/tests/SearchBar.spec.tsx
packages/react/src/components/toast/Toast.tsx
packages/react/src/components/toast/tests/Toast.spec.tsx
packages/style/scss/components/loading.scss
packages/style/scss/components/search-bar.scss
packages/style/scss/components/toast.scss
packages/style/scss/variables.scss
pnpm-lock.yaml

https://coveord.atlassian.net/browse/UITOOL-677
The new loading spinner is super nice and maybe we want to be able to use it somewhere else easily 👀  🌻  
I'm not sure about the name though 🙈 
https://user-images.githubusercontent.com/63734941/168388701-192fb98b-6302-4d1d-bd14-efc909af56bc.mov
https://user-images.githubusercontent.com/63734941/168389083-3213563c-cd8f-47b1-b901-bbbbff6a8c30.mov
None

UITOOL-677/extract new spinner

---

packages/react/src/components/limit/Limit.tsx
packages/react/src/components/limit/tests/Limit.spec.tsx
packages/website/src/pages/layout/Limit.tsx

feat(limit): add thousands separators for big numbers

---

packages/react/src/components/textInput/TextInput.tsx
packages/style/scss/controls/text-input.scss

https://coveord.atlassian.net/browse/UITOOL-693
After discussion with UX, we agreed to downsize a bit the TextInput to have the same height as the other form components (buttons, flat selects, filter box, single select, etc). This improve consistency between them and it's looking better when they a put together in a form 😄 
Before:
After:
None

refactor(mvp, text input): adjustment to better fit other form component

---

packages/react/src/components/modal/ConfirmationModalProvider.tsx

Coveo UX designers decided that primary buttons should be to ones on the right.
none

fix(unsaved change modal): button layout

---

packages/website/src/pages/feedback/Loading.tsx

Adding a demo so dev can see it and choose to use it in their components if needed 👀 
Go in the LoadingSpinner page to see it 😛 
None, plasma website only

docs(loadingspinner): added demo for the new loading spinner

---

Jenkinsfile.groovy
TokensExtraction.groovy

Pnpm released new versions which make the latest pnpm version work with our setup. We dont need to
pin the 7.0.0 version anymore
None

ci(pnpm): unpin pnpm version

---

packages/react/src/components/actionable-item/ActionableItem.tsx
packages/react/src/components/actionable-item/tests/ActionableItem.spec.tsx
packages/react/src/components/drop/Drop.tsx
packages/style/scss/components/actionable-item.scss
packages/website/src/pages/form/ActionableItem.tsx

The ActionableItem component looks a little weird, so I fixed that. Refactored its implementation
and redid all its tests while at it.
Before
After
I removed the extend of HTMLAttributes of HTMLDivElement so if additional div props were passed down to the component, it might break. (Verified in the admin and it isn't the case)

fix(react): make ActionableItem display better

---

packages/react/src/components/itemBox/ItemBox.tsx
packages/react/src/components/listBox/ListBox.tsx
packages/react/src/components/listBox/tests/ListBox.spec.tsx
packages/react/src/components/loading/components/ItemBoxLoading.tsx
packages/style/scss/components/list-box.scss
packages/style/scss/lib/_mixins.scss
packages/style/scss/variables.scss
packages/website/src/examples/ListBox/empty.example.tsx
packages/website/src/examples/ListBox/main.example.tsx
packages/website/src/examples/ListBox/withFooter.example.tsx
packages/website/src/pages/advanced/ListBox.tsx

https://coveord.atlassian.net/browse/UITOOL-700
The List Box component have it's new look!
Before:
After:
Empty state
With a footer
None

UITOOL-700/mvp listbox

---

packages/react/src/components/datePicker/DatePickerDropdown.tsx
packages/react/src/components/datePicker/tests/DatePickerDropdown.spec.tsx
packages/react/src/components/datePicker/tests/DatePickerDropdownConnected.spec.tsx

https://coveord.atlassian.net/browse/UITOOL-714
Before:
After:
None

fix(datepicker): fix button order + style

---

CHANGELOG.md
packages/react/src/components/datePicker/DatePickerDropdown.tsx
packages/react/src/components/datePicker/tests/DatePickerDropdown.spec.tsx
packages/react/src/components/datePicker/tests/DatePickerDropdownConnected.spec.tsx
packages/react/src/components/filterBox/FilterBox.tsx
packages/react/src/components/filterBox/tests/FilterBox.spec.tsx
packages/react/src/components/itemBox/ItemBox.tsx
packages/react/src/components/listBox/ListBox.tsx
packages/react/src/components/listBox/tests/ListBox.spec.tsx
packages/react/src/components/loading/components/ItemBoxLoading.tsx
packages/react/src/components/select/SelectConnected.tsx
packages/style/scss/components/list-box.scss
packages/style/scss/components/navigation.scss
packages/style/scss/controls/dropdown.scss
packages/style/scss/controls/filter-box.scss
packages/style/scss/controls/flat-select.scss
packages/style/scss/elements/btn.scss
packages/style/scss/helpers.scss
packages/style/scss/lib/_mixins.scss
packages/style/scss/variables.scss
packages/website/src/examples/ListBox/empty.example.tsx
packages/website/src/examples/ListBox/main.example.tsx
packages/website/src/examples/ListBox/withFooter.example.tsx
packages/website/src/pages/advanced/ListBox.tsx
packages/website/src/pages/form/FilterBox.tsx

Merge master into Next to get the latest changes for MVP components
None

Rebase master for single select

---

packages/react/src/components/itemBox/ItemBox.tsx
packages/react/src/components/listBox/ListBox.tsx
packages/react/src/components/listBox/tests/ListBox.spec.tsx
packages/style/scss/components/list-box.scss
packages/style/scss/lib/_mixins.scss
packages/style/scss/variables.scss
packages/website/src/examples/ListBox/main.example.tsx
packages/website/src/examples/ListBox/withFooter.example.tsx

https://coveord.atlassian.net/browse/UITOOL-720
Little oopsie on my part when I MVPied the ListBox: the footer need to always be visible at the bottom of the list but it was not 🙈 
Before:
https://user-images.githubusercontent.com/63734941/170720236-bda71312-6417-43b6-8044-e96fd8c5bfd4.mov
divider:
After:
Divider style: 
None

fix(listbox): footer is now external to the list

---

packages/react/src/components/editor/tests/CodeEditor.spec.tsx

https://coveord.atlassian.net/browse/UITOOL-719
Changing a bit the way the tests were handling the wait, hopefully it will be more stable 🙏 
I'll try a few runs on Jenkins to make sure it's ok 🏃‍♀️ 
None

test(fix, codeeditor): make uts more stable

---

packages/react/src/components/listBox/ListBox.tsx
packages/react/src/components/listBox/tests/ListBox.spec.tsx
packages/style/scss/components/list-box.scss

https://coveord.atlassian.net/browse/UITOOL-733
Fixing my boubou 🙈 
This issue breaks the orgPicker in the admin 😨 
Before:
https://user-images.githubusercontent.com/63734941/171678702-ba17a333-f194-4d68-8d74-352179c5d281.mov
After:
https://user-images.githubusercontent.com/63734941/171678865-d08b8308-4085-4029-9f6a-e25654468ffd.mov
Should be none

fix(list-box, infinite scroll): fix infinite scroll for single select

---

packages/react/src/components/datePicker/tests/DatePickerDropdownConnected.spec.tsx

Added a unit test to make sure #2785 is covered. Thanks @mikedidomizio for the code
None

test(react, date picker): add a unit test mocking the date

---

packages/react/src/components/checkbox/Checkbox.tsx
packages/react/src/components/input/Input.tsx
packages/react/src/utils/PropsToOmitUtils.ts

Converted the checkbox from a ClassComponent to a FunctionComponent
None, the tests are all passing

refactor(react, checkbox): convert to function component

---

packages/react/src/components/actions/Action.tsx
packages/react/src/components/button/Button.tsx
packages/website/src/examples/button/WithTooltip.example.tsx
packages/website/src/pages/form/Button.tsx

https://coveord.atlassian.net/browse/UITOOL-635
After: 
None

refactor: 💡 tooltip placement is now an enum for buttons

---

packages/react/package.json
packages/website/package.json
pnpm-lock.yaml

UITOOL-284
graft moment update in version 42.9
None, vulnerability fix

chore(deps): update dependency moment to v2.29.4 [security]

---

packages/react/src/components/modalWizard/ModalWizard.tsx

https://coveord.atlassian.net/browse/UITOOL-667
Before:
After:
None

feat: 🎸 make steps in modalWizard full-height

---

packages/react/src/components/select/SingleSelectConnected.tsx

https://coveord.atlassian.net/browse/UITOOL-802
In preparation of our POC for React Hook Form, we need to make our components compatible.
This is for the SingleSelect 🔥 
Should be none

refactor(singleSelect): convert to functional component

---

packages/react/src/components/editor/CodeEditor.tsx
packages/react/src/components/loadable/Loadable.tsx
packages/react/src/components/loadable/tests/Loadable.spec.tsx

Create a Loadable to lazy load component
Use the Loadable in CodeMirror
None

feat(react, loadable): create loadable to lazy load component

---

packages/react/src/components/index.ts
packages/react/src/components/loadable/index.ts

A loadable component was created but it was never exported
None

fix(loadable): export the component

---

.deployment.config.json

https://coveord.atlassian.net/browse/UITOOL-861
🙈 
None

chore: 🤖 apply new schema to deployment config for snyk

---

packages/style/gulpfile.js
packages/style/package.json
packages/style/scss/dependencies.scss
pnpm-lock.yaml

Attempt at removing this legacy artifact of the past, it is no longer used.

chore(style): remove depedency on coveo-slider

---

.husky/commit-msg
.husky/pre-commit
packages/react/src/components/tooltip/Tooltip.tsx

- Fix intellisense being too slow
- Remove pnpm dlx from husky hooks
None

Performance improvements of the dev setup

---

packages/website/src/pages/index.tsx

UITOOL-926
Just adding the tile in the home page 👀 
None, demo only

feat: 🎸 adding link to colors in home page for demo

---

.eslintrc.js
.github/actions/lint/action.yml
.github/actions/lint/lintChangedFiles.mjs
.github/actions/setup/action.yml
.github/workflows/ci.yml
.husky/pre-commit
package.json
packages/react/package.json
packages/style/package.json
packages/tokens/package.json
packages/website/package.json

- Created a github action workflow called "CI" which will run on opened PRs
- Run ESLint from this workflow
- Removing ESLint from the pre-commit phase
None, ci stuff only

Improve linting process

---

.github/actions/build/action.yml
.github/actions/setup/action.yml
.github/actions/test/action.yml
.gitignore
Jenkinsfile.groovy
package.json
packages/react/package.json
pnpm-lock.yaml
turbo.json

Replacing ultra-runner by turborepo.
None

Replace ultra runner by turborepo

---

packages/react/src/components/limit/Limit.tsx
packages/react/src/components/limit/tests/Limit.spec.tsx

Change the icon ( I think the new one was added recently ) since it was a placeholder

fix(limit): chart pie was renamed so i changed the icon

---

.github/actions/snyk-pnpm/action.yml
packages/website/build/getBasePath.js

This time the CD workflow is failing on snyk not actually outputting any sarif file
https://github.com/coveo/plasma/actions/runs/3330137324/jobs/5508961655#step:7:94
None

Fix CD workflow

---

.github/actions/setup/action.yml

https://github.com/coveo/plasma/actions/runs/3338096897/jobs/5525303870#step:9:118

ci(setup): setup git user

---

.github/actions/publish/publishNewVersion.mjs
.github/actions/setup/action.yml
.github/workflows/cd.yml
package.json
pnpm-lock.yaml

Publish new versions using a github ssh deploy key. Doing so should allow to bypass the master branch protection rule and fix the [error we have in the CD](https://github.com/coveo/plasma/actions/runs/3339812089/jobs/5529201766#step:9:697).
None

ci(cd): setup deploy key

---

.github/actions/cleanup-demo/action.yml
.github/actions/cleanup-demo/cleanup-demo.sh
.github/workflows/demo-cleaner.yml

Added a workflow to cleanup the demo files of closed pull requests
None

ci: delete old demo files

---

packages/mantine/package.json
packages/mantine/src/index.ts
pnpm-lock.yaml

Added the carousel package to plasma-mantine package for ML feature 

feat(carousel): +carousel component for ML feature

---

packages/mantine/src/components/date-range-picker/EditableDateRangePicker.tsx
packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerInlineCalendar.spec.tsx
packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerPopoverCalendar.spec.tsx
packages/mantine/src/components/date-range-picker/__tests__/EditableDateRangePicker.spec.tsx
packages/mantine/src/components/table/TableDateRangePicker.tsx
packages/mantine/src/components/table/Th.tsx

Fixed style of Th of the table component
Fixed the table date formatting with dayjs
These were changes meant to be pushed before the mantine files changed location.

feat: made adjustments to table component dates and style of th

---

packages/mantine/package.json
packages/mantine/src/index.ts
pnpm-lock.yaml

modifies coveo/plasma#2895 dependencies

"feat(carousel): *carousel dependencies"

---

packages/mantine/src/components/collection/Collection.tsx
packages/mantine/src/components/collection/__tests__/Collection.spec.tsx

Added a new onRemoveItem prop on the Collection component
None

feat(mantine, collection): call callback function when an item is removed

---

packages/components-props-analyzer/src/ComponentsList.ts
packages/mantine/package.json
packages/mantine/src/components/header/Header.tsx
packages/website/src/SideNavigation.tsx
packages/website/src/building-blocs/PageHeader.tsx
packages/website/src/building-blocs/typesLoader.ts
packages/website/src/examples/Header/Header.mantine.example.tsx
packages/website/src/pages/mantine/Header.tsx

Adding a demo page for the mantine header component
None

feat(website): add a demo page for the manine header component

---

packages/style/scss/controls/radios.scss

https://coveord.atlassian.net/browse/ADUI-7804
Reduce the animation from 8px to 4px

feat(radio-card): lower the translation on hover

---

packages/components-props-analyzer/src/ComponentsList.ts
packages/website/src/SideNavigation.tsx
packages/website/src/building-blocs/typesLoader.ts
packages/website/src/examples/collection/Collection.example.tsx
packages/website/src/pages/mantine/Collection.tsx

feat(website): add demo page for the Mantine Collection component

---

packages/mantine/src/theme/Theme.tsx

| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/35579930/202776672-6ba9e59b-3254-489b-a44d-13f91d7c958a.png) | ![image](https://user-images.githubusercontent.com/35579930/202776537-cfd65942-2298-46e6-a149-ed9d7af446f3.png) |
None

feat(mantine): adjust popover default shadow

---

packages/components-props-analyzer/package.json
packages/mantine/package.json
packages/react-icons/package.json
packages/react/package.json
packages/react/src/components/toast/Toast.tsx
packages/react/src/utils/JSXUtils.tsx
packages/tokens/package.json
packages/website/package.json
pnpm-lock.yaml

chore(deps): update mantine and typescript

---

packages/mantine/src/components/table/Table.tsx
packages/website/src/examples/layout/Table/Table.demo.tsx

Made the demo page for the Mantine Table more complete.
It now features:
- pagination
- collapsible rows
- date picker
- sorting columns
- API data instead of lorem ipsum
Also re-wrote the description of the table to include missing features.
None

Feat UI tool1024 add demo page tableMantineImprovement example

---

packages/react/src/components/collapsible/CollapsibleHeaderIcon.tsx
packages/style/package.json
packages/style/svgWrapper.js
packages/website/package.json
packages/website/src/building-blocs/GithubButton.tsx
packages/website/src/building-blocs/ResultList.tsx
pnpm-lock.yaml

UITOOL-1054
Fixing those security issues:
The other one are in .js files generated from old bootstrap that i'm not touching with a ten foot pole no sir 🙃 
None

fix: 🐛 fix security vulnerabilities

---

package.json

Cleanup the turborepo cache folders when running reconstruct
None

build: clean turbo cache on reconstruct

---

packages/react-icons/.gitignore
packages/react-icons/mock/.swcrc
packages/react-icons/mock/index.tsx
packages/react-icons/package.json

Improve the icons mock by adding more props and a forward ref. Also convert it to `commonjs`
None

fix(react-icons): improve mock and convert to js

---

packages/mantine/src/components/collection/Collection.tsx

Remove header extra margin bottom
Handle withAsterisk prop on Input.Label
None

fix(mantine): small adjustments in Collection component

---

packages/mantine/src/components/table/Table.tsx
packages/mantine/src/components/table/TableCollapsibleColumn.tsx
packages/mantine/src/components/table/__tests__/Table.spec.tsx
packages/website/src/examples/layout/Table/Table.demo.tsx

Created a new generic column for the table. It can be used in place of the Table.CollapsibleColumn to have an accordion behaviour instead
None

feat(mantine, table): create new accordion column

---

packages/mantine/src/components/table/TableFilter.tsx
packages/mantine/src/components/table/__tests__/TableFilter.spec.tsx

Add a cross icon at the right of the table filter to clear its value when its not empty.
https://user-images.githubusercontent.com/35579930/218854353-a26a350a-9764-49ab-b7ee-bf102ecb0e54.mov
None

feat(mantine): add table filter clear button

---

packages/mantine/package.json
packages/mantine/src/components/table/Table.tsx
packages/mantine/src/components/table/__tests__/TableDateRangePicker.spec.tsx
packages/mantine/src/components/table/__tests__/TableFilter.spec.tsx
packages/mantine/src/components/table/__tests__/TablePerPage.spec.tsx
packages/mantine/src/components/table/__tests__/TablePredicate.spec.tsx
pnpm-lock.yaml

https://coveord.atlassian.net/browse/UITOOL-1121
+debounce on the triggerChange method so the table does not trigger a change on every change on the filter, sort, pagination, perpage and forms (datepicker / predicate) of the mantine table

fix(table): +debounce on triggerChange method

---

packages/website/.eslintignore
packages/website/.eslintrc.js
packages/website/src/examples/layout/Table/Table.demo.tsx
packages/website/src/examples/layout/Table/TableClientSide.demo.tsx
packages/website/src/examples/layout/Table/TableMultiSelection.demo.tsx

The table demos had a few issues that we should avoid demoing. Otherwise people are going to repeat those bad patterns.
None

refactor(website): cleanup table demos

---

packages/mantine/src/theme/Theme.tsx
packages/website/src/examples/layout/Modal/Modal.demo.tsx

fix(modal): reverse to pixel in theme modal content custom size

---

packages/style/scss/components/navigation.scss
packages/style/scss/redesign/variables.scss
packages/style/scss/typekit.scss
packages/style/scss/variables.scss

https://coveord.atlassian.net/browse/UITOOL-1442
Align the default font-size to 16px = 1rem to help with the mantine v6 bump that converts px to rem with the 16:1 ratio

UI tool 1442 font size changes

---

packages/mantine/src/theme/Theme.tsx

A little adjustment to the checkbox label style to respect Coveo brand
This is made while working on the Facet component in the Coveo Admin UI
none

feat(checkbox label): style

---

packages/mantine/package.json

+ Add the link to the repository in package.json
Fixes license detection by Dependabot and friends.

Add the link to the repository in package.json

---

packages/mantine/src/theme/Theme.tsx

Update the look of the Stepper component in the theme
Before:
After:
Figma:
None, only the theme changed

feat(mantine, stepper): update style of component

---

packages/mantine/src/theme/Theme.tsx
packages/website/src/examples/layout/Modal/ModalWithTabs.demo.tsx

This is the second part of this jira https://coveord.atlassian.net/browse/UITOOL-8702 addressing the tabs rendered inside a modal. 
Basically, it adjusts the border's style with respect to the request from the JIRA

UI tool 8702 tab border fix

---

packages/mantine/src/theme/Theme.tsx

Update the Theme so the Select component looks closer to what is shown in the figma mockups
| mockups | before | after |
| ![image](https://github.com/coveo/plasma/assets/35579930/2e6eff37-8269-4038-87e2-c2e49866b8d3) | ![image](https://github.com/coveo/plasma/assets/35579930/ddc7c53c-ae07-495e-bbca-bf282dad72c7) | ![image](https://github.com/coveo/plasma/assets/35579930/d04a8684-a2f5-4b72-9a01-690d12ac70ad) |

feat(mantine): update style of the Select component

---

packages/mantine/src/components/table/Table.tsx
packages/mantine/src/components/table/Table.types.ts
packages/mantine/src/components/table/TableLastUpdated.tsx
packages/mantine/src/components/table/__tests__/TableLastUpdated.spec.tsx
packages/website/src/examples/layout/Table/TableConsumer.demo.tsx

Create a new component that displays the last time the table updated. It hints the user when the table automatically refreshes
None, new component

feat(mantine, table): create a new LastUpdated component

---

packages/mantine/src/components/table/TablePagination.tsx
packages/mantine/src/components/table/TablePerPage.tsx
packages/mantine/src/components/table/__tests__/TablePagination.spec.tsx
packages/mantine/src/components/table/__tests__/TablePerPage.spec.tsx

Addition of a callback function in the TablePagination Component
This callback will receive the current pageSize and the pageIndex that was just selected
[Uploading simplescreenrecorder-2023-07-25_15.56.03.webm…]()
none

feat(tablepagination): call back on page change

---

packages/style/package.json
pnpm-lock.yaml

This dependency has a vulnerability and we don't even use it
None

chore(deps): remove unused dependency

---

packages/mantine/src/theme/Theme.tsx
packages/website/src/SideNavigation.tsx
packages/website/src/building-blocs/ResultList.tsx
packages/website/src/pages/_app.tsx
packages/website/src/pages/index.tsx
packages/website/src/pages/legacy/index.tsx
packages/website/src/styles/main.scss

Refactoring the website's side navigation so that it uses Mantine's NavBar and NavLink.
None

refactor(website): use mantine nav components

---

packages/mantine/src/components/table/layouts/RowLayout.tsx

`overflow-wrap: 'anywhere'` is the rule that works. :see_no_evil: 
none

fix(table): word wrap

---

packages/mantine/src/components/table/TablePredicate.tsx

[MLX-531]
Add class for changing the style of the select input;
For example, will be useful if someone needs a bigger Select when the data names are longer than the default.
no

[MLX-531] Add ability to style Select input

---

packages/mantine/src/components/sticky-footer/StickyFooter.tsx
packages/website/src/pages/layout/StickyFooter.tsx

Problem:
https://github.com/coveo/plasma/assets/35579930/c1f83f6b-7313-46ca-b9f4-a5aa6c96bc86
After:
https://github.com/coveo/plasma/assets/35579930/423a42ba-2b0e-4d08-a1d4-0b699125607f

fix(mantine): fix SegmentedControl overlapping StickyFooter

---

packages/mantine/src/components/sticky-footer/StickyFooter.tsx

Allowing the `StickyFooter` component to be customizable through the theme.

feat(mantine): make StickyFooter more flexible

---

packages/mantine/src/components/inline-confirm/InlineConfirmPrompt.tsx
packages/mantine/src/components/table/table-actions/TableActions.styles.ts

https://coveord.atlassian.net/browse/ADUI-9268
wrapped the inline prompt string properly inside its container.
[simplescreenrecorder-2023-10-10_17.24.51.webm](https://github.com/coveo/plasma/assets/45688129/df8c0847-2447-4ab4-bf13-399696014b2f)
none

fix(table inline prompt): overflow

---

package.json
packages/components-props-analyzer/package.json
packages/mantine/package.json
packages/react-icons/package.json
packages/react/package.json
packages/tokens/package.json
packages/website/package.json
pnpm-lock.yaml

Updating the `@coveo/atomic-react` version to fix the search box crashing. See [related issue](https://github.com/coveo/ui-kit/issues/3310)
Before
After

fix(website): update @coveo/atomic-react

---

packages/mantine/src/components/browser-preview/__tests__/BrowserPreview.spec.tsx
packages/mantine/src/components/button/Button.tsx
packages/mantine/src/components/button/__tests__/Button.spec.tsx
packages/mantine/src/components/date-range-picker/__tests__/DateRangePickerPresetSelect.spec.tsx
packages/mantine/src/components/table/__tests__/Table.spec.tsx
packages/mantine/src/components/table/__tests__/TablePredicate.spec.tsx
packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx

This is a separate PR that fixes the failing tests coming from the mantine bump to v7
If green : woohoo

fix(plasma): fixed the test with mantine v7 bump

---

packages/mantine/package.json
packages/website/.gitignore

Update peer dependencies to include @mantine/notifications

chore(plasma mantine): update peer dependencies

---

packages/mantine/src/components/table/layouts/row-layout/RowLayout.module.css

Fix for the svg style of the table top row
Before
AFTER

fix(mantine table): header row svg

---

packages/mantine/src/styles/NavLink.module.css
packages/mantine/src/theme/Theme.tsx

| `master` | `next` | this branch |
| <img width="250" alt="image" src="https://github.com/coveo/plasma/assets/35579930/384b21b0-17ae-4d51-a52d-f1f445d95c49"> | <img width="249" alt="image" src="https://github.com/coveo/plasma/assets/35579930/de8242aa-b7b7-475f-b0c0-d67b8a42d80d"> |<img width="251" alt="image" src="https://github.com/coveo/plasma/assets/35579930/66680256-2ff1-43d4-a374-b825556f1f44"> |

fix(mantine): adjust NavLink styles

---

packages/mantine/src/components/table/table-filter/TableFilter.tsx

Changing the style of the right clearInput button of the table filter. 

fix(table filter): clear button subtle

---

packages/style/scss/lib/reset.scss

The default line height everywhere in the Coveo-Admin should be 1.5 rem

fix(reset): line-height

---

packages/mantine/src/theme/Theme.tsx

Added `aria-label='close'` on closeButton component so that we have accessibility to leverage in unit test (as of now, we have nothing other than going with `querySelector('.matine-class-name')` which is not ideal)

feat(close-button): +aria-label for unit tests purpose

---

packages/mantine/src/styles/Input.module.css
packages/mantine/src/styles/InputWrapper.module.css
packages/mantine/src/theme/Theme.tsx

fix(mantine): adjust Input styles

---

packages/mantine/src/styles/Button.module.css
packages/mantine/src/theme/Theme.tsx

Before
https://github.com/coveo/plasma/assets/35579930/47478a3a-d174-45ab-a4d5-6f211e1f2943
After
https://github.com/coveo/plasma/assets/35579930/26efd61d-8bed-4e54-a5f8-1d64fc2ba0fd

fix(mantine): subtle button hover background color

---

packages/mantine/src/styles/Stepper.module.css

making sure the active stepper step has the correct border color.

fix(stepper): border color

---

packages/react-icons/package.json
packages/website/vite.config.ts

There was an approval with automerge and once I fixed the build, it merged automatically, but I still had some stuff to remove and add back.
https://github.com/coveo/plasma/pull/3525

fix(plasma): fix the build and remove dead code

---

packages/mantine/src/components/table/Table.tsx

Forgot to push this change in #3725 
None

chore(mantine, table): apply missing review

---

packages/style/scss/components/corner-ribbon.scss
packages/style/scss/components/icon-card.scss
packages/style/scss/components/navigation.scss
packages/style/scss/typekit.scss
packages/style/scss/variables.scss

Same as #3759 but for plasma-style in V53
None

chore: remove custom letter spacing in deprecated packages

---

.github/actions/publish/index.mjs

I tried to publish a new version and it failed https://github.com/coveo/plasma/actions/runs/9668056564/job/26671315279#step:7:206
While debugging locally I saw that the convention object changed.
None

chore(publish): fix version bump

---

packages/mantine/src/components/table/Table.module.css
packages/mantine/src/components/table/Table.tsx

Oops, in this [PR](https://github.com/coveo/plasma/pull/3783) I made a change and when I tested it worked but it didn't use the right code, the `pb="sm"` adds an inline style, I moved it to the module file to be able to overwrite it

feat: modification of the table in plasma to be able to modify the padding of the table (v2)

---

.github/workflows/scorecards.yml
README.md

J:DEF-160
[](https://github.com/ossf/scorecard?tab=readme-ov-file#what-is-scorecard)
None.

chore(CI): Add a scorecard badge

---

.stylelintignore
.stylelintrc
package.json
packages/mantine/src/components/code-editor/CodeEditor.module.css
packages/mantine/src/components/collection/Collection.module.css
packages/mantine/src/components/header/Header.module.css
packages/mantine/src/components/sticky-footer/StickyFooter.module.css
packages/mantine/src/components/table/Table.module.css
packages/mantine/src/components/table/layouts/row-layout/RowLayout.module.css
packages/mantine/src/styles/Alert.module.css
packages/mantine/src/styles/Checkbox.module.css
packages/mantine/src/styles/Combobox.module.css
packages/mantine/src/styles/Modal.module.css
packages/mantine/src/styles/NavLink.module.css
packages/mantine/src/styles/Notification.module.css
packages/mantine/src/styles/Pagination.module.css
packages/mantine/src/styles/Select.module.css
packages/mantine/src/styles/Skeleton.module.css
packages/mantine/src/styles/Stepper.module.css
packages/mantine/src/styles/Tabs.module.css
packages/tokens/css/Colors.css
packages/tokens/scss/Colors.scss
packages/website/src/building-blocs/Demo.module.css
packages/website/src/styles/CodeHighlight.theme.module.css
packages/website/src/styles/TopBar.module.css
packages/website/src/styles/_syntax-highlighting.css
packages/website/src/styles/home.css
packages/website/src/styles/loading-screen.css
packages/website/src/styles/reset.css
pnpm-lock.yaml

Add `.css` to the files linted on commit. Also run `stylelint --fix` on all css modules.

ci: add lint css modules

---

eslint.config.mjs

The last few renovate build failed with errors about those files. I added them to the defaultProject which fixed the issue
None

chore: fix eslint config

---

packages/mantine/src/components/ellipsis-text/EllipsisText.tsx

fix(mantine): make EllipsisText tooltipProps prop optional

---

packages/mantine/src/styles/Checkbox.module.css

fix(checkbox): readOnly checkbox style

---

packages/mantine/src/components/modal/Modal.tsx

Small fix on `Modal.tsx` imports.
Thanks to @FelixBlaisThon for coming back to the code and noticing the issue.
N/A

fix(modal): optimize import

---

packages/mantine/src/components/table/__tests__/use-url-synced-state.unit.spec.ts
packages/mantine/src/components/table/use-url-synced-state.ts

I've added a feature to the `useUrlSyncedState` hook for the table, that some parameters will always be added to the URL. In short, the idea behind this is to do this for `from` and `to`, since the default/initial values for those fields are often relative to now. By always serializing, sharing and opening the URL leads to seeing the same range, even if days later. (For more details, see #3996).
I **thought** I did two things:
- Manually test this in Admin-UI.
- Add proper unit test coverage.
For the manual test part, I think my hacked "local link" set-up wasn't working as well as I thought it did, and I probably tested with some weird mixed old-version and new-version states. For the unit test coverage, I honestly don't know why I completely missed that. The only excuse I have is that …

fix(table): correct useUrlSyncedState serialization logic

---

packages/mantine/package.json
pnpm-lock.yaml

Added cross-env to the script, to make `TZ=UTC vitest` work on Windows.

fix(script): make script cross-env

---

packages/components-props-analyzer/src/ComponentsList.ts
packages/mantine/package.json
packages/mantine/src/__tests__/VitestSetup.ts
packages/mantine/src/components/alert/Alert.tsx
packages/mantine/src/components/index.ts
packages/mantine/src/components/info-token/InfoToken.module.css
packages/mantine/src/components/info-token/InfoToken.tsx
packages/mantine/src/components/info-token/index.ts
packages/mantine/src/styles/Alert.module.css
packages/mantine/src/theme/Theme.tsx
packages/mantine/src/theme/__tests__/plasmaCSSVariablesResolver.spec.ts
packages/mantine/src/theme/plasmaCSSVariablesResolver.ts
packages/website/src/Navigation.tsx
packages/website/src/examples/feedback/alert/Alert.demo.tsx
packages/website/src/examples/feedback/alert/AlertAdvice.demo.tsx
packages/website/src/examples/feedback/alert/AlertCritical.demo.tsx
packages/website/src/examples/feedback/alert/AlertInformation.demo.tsx
packages/website/src/examples/feedback/info-token/InfoToken.demo.tsx
packages/website/src/pages/feedback/Alert.tsx
packages/website/src/pages/feedback/InfoToken.tsx
pnpm-lock.yaml

Created the new InfoToken component
Adjusted the style of the Alert component to match what we have in Figma
None

new InfoToken component & adjusted Alert style

---

packages/mantine/src/styles/Input.module.css
packages/mantine/src/styles/InputWrapper.module.css
packages/mantine/src/styles/ReadOnlyInput.module.css
packages/mantine/src/theme/Theme.tsx
packages/mantine/src/theme/__tests__/plasmaCSSVariablesResolver.spec.ts
packages/mantine/src/theme/plasmaCSSVariablesResolver.ts

Update the style of the Input and Input.Wrapper
None

chore(mantine, input): update the style of the input and input wrapper

---

packages/mantine/src/theme/Theme.tsx

Updated the look of the Modal Overlay.
Changed the colour, opacity and added a blur
| --- | --- |
| ![image](https://github.com/user-attachments/assets/58fcc645-f1e0-4735-b95b-8cb5018fe013) | ![image](https://github.com/user-attachments/assets/5d0fa7c2-ee3e-41b9-b8f0-f363c0dc9cb3) |
None

feat(mantine, modal): update overlay style

---

packages/mantine/src/components/action-icon/ActionIcon.tsx
packages/mantine/src/components/code-editor/search/Search.tsx
packages/mantine/src/components/collection/Collection.tsx
packages/mantine/src/components/collection/CollectionItem.tsx
packages/mantine/src/components/copyToClipboard/CopyToClipboard.tsx
packages/mantine/src/components/table/__tests__/TableFilter.spec.tsx
packages/mantine/src/components/table/layouts/__tests__/RowLayout.spec.tsx
packages/mantine/src/components/table/table-actions/TableActionsList.tsx
packages/mantine/src/components/table/table-column/TableCollapsibleColumn.tsx
packages/mantine/src/components/table/table-filter/TableFilter.tsx
packages/mantine/src/styles/ActionIcon.module.css
packages/mantine/src/theme/Theme.tsx
packages/mantine/src/theme/__tests__/plasmaCSSVariablesResolver.spec.ts
packages/mantine/src/theme/plasmaCSSVariablesResolver.ts
packages/website/src/TopBar.tsx
packages/website/src/building-blocs/Demo.tsx
packages/website/src/examples/form/action-icon/ActionIcon.demo.tsx
packages/website/src/examples/form/action-icon/ActionIconDisabled.demo.tsx
packages/website/src/examples/form/action-icon/ActionIconSecondary.demo.tsx
packages/website/src/examples/form/action-icon/ActionIconWithAsyncLoader.demo.tsx
packages/website/src/pages/form/ActionIcon.tsx

Applied the new look on ActionIcon
Created semantic components, used same name as Button
Updated usage of ActionIcon to use the semantic version
None

ActionIcon styles

---

packages/mantine/src/styles/Badge.module.css
packages/mantine/src/theme/Theme.tsx

Update the font-size and text-transform css attributes of the Badge component
None

fix(mantine, badge): font-size and text-transform

---

packages/style/scss/colors.scss
packages/style/scss/components/calendar.scss
packages/style/scss/components/list-box.scss
packages/style/scss/components/loading.scss
packages/style/scss/components/navigation.scss
packages/style/scss/components/sub-navigation.scss
packages/style/scss/components/tab.scss
packages/style/scss/components/tooltip.scss
packages/style/scss/controls/checkboxes.scss
packages/style/scss/controls/datepicker.scss
packages/style/scss/controls/dropdown.scss
packages/style/scss/controls/filter-box.scss
packages/style/scss/controls/flat-select.scss
packages/style/scss/controls/input-field.scss
packages/style/scss/controls/multiline-field.scss
packages/style/scss/controls/numeric-input.scss
packages/style/scss/controls/radios.scss
packages/style/scss/controls/slider.scss
packages/style/scss/controls/text-input.scss
packages/style/scss/elements/btn-append-prepend.scss
packages/style/scss/elements/btn.scss
packages/style/scss/elements/links.scss
packages/style/scss/forms/block-form.scss
packages/style/scss/helpers.scss
packages/style/scss/placeholders.scss
packages/style/scss/tables/pagination.scss
packages/style/scss/tables/table.scss
packages/style/scss/typography/elements.scss
packages/style/scss/variables.scss
packages/website/src/styles/tile.css

Updated the CSS of plasma-style to change the primary color from blue to teal.
The color changed. It's possible to overide the variables to go back to the old values:
```css
.some-rule {
--primary-color-60: var(--digital-blue-60);
}
```

feat(style): change primary color

---

packages/mantine/__mocks__/@monaco-editor/react.tsx
packages/mantine/src/components/code-editor/CodeEditor.module.css
packages/mantine/src/components/code-editor/CodeEditor.tsx
packages/website/src/examples/form/code-editor/CodeEditorDisabled.demo.tsx
packages/website/src/pages/form/CodeEditor.tsx
packages/website/vite.config.ts

|before|after|
|---|---|
|<img width="632" alt="image" src="https://github.com/user-attachments/assets/7304a5b3-9479-463c-bcd5-5a42b6ac6292" />|<img width="634" alt="image" src="https://github.com/user-attachments/assets/bd73459f-793b-4655-be11-e030cc56ec68" />|
|<img width="634" alt="image" src="https://github.com/user-attachments/assets/1251bb93-252d-4ed5-b3ef-d03427668c22" />|<img width="632" alt="image" src="https://github.com/user-attachments/assets/fe0c7b18-7a62-4b9c-83c8-0ce753f514cc" />|
|<img width="633" alt="image" src="https://github.com/user-attachments/assets/9788ec2a-9598-4b0f-aad5-c451b6a536c8" />|<img width="633" alt="image" src="https://github.com/user-attachments/assets/86aef4fa-0566-4558-9f71-92316f71027a" />|
-   [ …

feat(mantine): update CodeEditor look

---

packages/mantine/src/components/checkbox/CheckboxIcon.tsx
packages/mantine/src/components/checkbox/index.ts
packages/mantine/src/components/index.ts
packages/mantine/src/components/loader/index.ts
packages/mantine/src/styles/Checkbox.module.css
packages/mantine/src/styles/CheckboxIndicator.module.css
packages/mantine/src/theme/Theme.tsx
packages/mantine/src/theme/plasmaCSSVariablesResolver.ts

|Before|After|
|---|---|
|<img width="308" alt="image" src="https://github.com/user-attachments/assets/5c355421-e0fb-49f9-827d-94e8dad80b88" />|<img width="316" alt="image" src="https://github.com/user-attachments/assets/043ad768-3091-4251-bbc2-811efaabfdb8" />|

feat(mantine): update style of checkbox

---

packages/mantine/src/components/read-only/ReadOnlyInputStyles.ts
packages/mantine/src/styles/Input.module.css
packages/mantine/src/styles/ReadOnlyInput.module.css
packages/mantine/src/styles/Select.module.css
packages/mantine/src/theme/Theme.tsx
packages/mantine/src/theme/plasmaCSSVariablesResolver.ts

https://coveord.atlassian.net/browse/ADUI-10596
https://coveord.atlassian.net/browse/ADUI-10694
This PR aims at applying the style changes from UX to the mantine `Select` and `MultiSelect` components. These changes are exclusively visual ones.
#Options:
https://github.com/user-attachments/assets/d8b6415e-05e2-4da8-822b-d521daae33cc
https://github.com/user-attachments/assets/ab5bd053-9f9c-4e48-952c-622b150c51a5
| Before  | After |
|----------|----------|
| ![image](https://github.com/user-attachments/assets/50d44070-f425-48a0-a86e-ae4b9e0f3a8b) | Data 2   |
| ![image](https://github.com/user-attachments/assets/5e1a6aaf-eef2-4a5a-8747-64ef99855fc9)    | Data 3   |
| | Before | Platform theme | MHub theme | KHub theme |
|----------|----------|----------|----------|----------|
| default    | …

Ad UI 10596 apply style changes select

---

.gitignore
packages/mantine/src/styles/Slider.module.css
packages/mantine/src/theme/Theme.tsx

Updated the look of the slider component to new mockup changes.
Before:
After:
With markers:
Before:
After:
Disabled:
Before:
After:
Mockups:
Disabled:

feat(mantine): update slider look

---

packages/mantine/src/styles/Pill.module.css
packages/mantine/src/theme/Theme.tsx

Minor change to the background color of the pill
Before:
After:
Mockup:

Ad UI 10878 apply changes to pill

---

packages/mantine/src/styles/NavLink.module.css

Ad UI 10702 apply style changes to nav link

---

packages/mantine/src/styles/Pagination.module.css

Applied some of the changes requested by UX. 
[JIRA](https://coveord.atlassian.net/browse/ADUI-10874)
[Figma](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Opal-Components--Pretine-source-library-?node-id=10073-410423&m=dev)
I had to add **custom** changes to reflect the changes requested

feat(pagination): +style change for pagination

---

packages/website/src/examples/layout/StickyFooter/StickyFooter.demo.tsx

Updated the demo using the secondary cancel button, no changes required for the footer itself. The padding and the gap is already the same (24px, 32px) and 16px respectively.
Before:
After:
Mockup:

feat(mantine): apply changes to Footer

---

packages/mantine/src/components/header/HeaderDocAnchor/HeaderDocAnchor.tsx
packages/mantine/src/components/info-token/InfoToken.tsx
packages/website/src/examples/layout/Header/Header.demo.tsx

feat(mantine,header): update doc anchor icon

---

packages/components-props-analyzer/src/ComponentsList.ts
packages/mantine/src/components/badge/Badge.tsx
packages/mantine/src/index.ts
packages/mantine/src/styles/Badge.module.css
packages/website/src/examples/feedback/badge/Badge.demo.tsx

feat: implement semantic badges components
Before
After
Mockups

feat: implement semantic badges components

---

packages/mantine/src/styles/Tabs.module.css

feat(mantine,tabs): apply style changes

---

packages/mantine/src/components/child-form/ChildForm.module.css
packages/mantine/src/components/child-form/ChildForm.tsx

[JIRA](https://coveord.atlassian.net/browse/ADUI-10897)
Adjust styling to ChildForm component with Pretine
[Mockup](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Opal-Components--Pretine-source-library-?node-id=17201-42830&m=dev)
Before:
After: 

feat(childform): adjust background and border thickness of childform

---

packages/mantine/src/components/button/Button.tsx
packages/mantine/src/components/code-editor/search/Search.tsx
packages/mantine/src/components/copyToClipboard/CopyToClipboard.tsx
packages/mantine/src/components/table/table-column/TableCollapsibleColumn.tsx
packages/mantine/src/components/table/table-filter/TableFilter.tsx
packages/mantine/src/theme/Theme.tsx
packages/mantine/src/theme/__tests__/plasmaCSSVariablesResolver.spec.ts
packages/mantine/src/theme/plasmaCSSVariablesResolver.ts
packages/mantine/src/theme/plasmaVariantColorResolver.ts
packages/website/src/building-blocs/Demo.tsx
packages/website/src/examples/form/action-icon/ActionIcon.demo.tsx
packages/website/src/examples/form/action-icon/ActionIconDisabled.demo.tsx
packages/website/src/examples/form/action-icon/ActionIconWithAsyncLoader.demo.tsx

Updating the Button and ActionIcon components with the latest style updates.
|Before|After|
|---|---|
|<img width="180" height="102" alt="image" src="https://github.com/user-attachments/assets/2a9a4229-7625-4eb4-9cf7-fc7d14537d93" />|<img width="224" height="132" alt="image" src="https://github.com/user-attachments/assets/40c296fa-724f-4956-a13f-8334144aaa18" />|
|<img width="402" height="138" alt="image" src="https://github.com/user-attachments/assets/da1eb8bd-fc1d-4afe-8099-7ae82494aa8e" />|<img width="373" height="119" alt="image" src="https://github.com/user-attachments/assets/64a5abdb-6b7b-4429-9566-baf27089ff31" />|
Also, I did some modifications to the variant resolver so that the different between light and light-hover matches what UX want.
-   [ ] The proposed changes are covered …

feat(mantine,button): update Button & ActionIcon style

---

packages/mantine/src/styles/Accordion.module.css
packages/mantine/src/theme/Theme.tsx
packages/website/package.json
packages/website/src/building-blocs/Demo.tsx
pnpm-lock.yaml

Updated the basic accordion styles to fit the designs and created a new variant called `nested` to follow what UX wants. I also added an error boundary to demos on the plasma website.
`variant="default"`
https://github.com/user-attachments/assets/2143a505-0db8-4bba-86f0-98a823da1659
`variant="separated"`
https://github.com/user-attachments/assets/b31d7534-db2e-48aa-a7bb-939f56db6484
`variant="nested"`
https://github.com/user-attachments/assets/cc8af580-d991-4898-ba50-e1137b2658dc
Mockups

feat(mantine,accordion): update accordion style

---

packages/mantine/src/styles/Popover.module.css
packages/mantine/src/theme/Theme.tsx

[FIGMA](https://www.figma.com/design/lFjxQoLHYzdLObC0g4HdWd/Opal-Components--Pretine-source-library-?node-id=12710-32536&m=dev)
[JIRA](https://coveord.atlassian.net/browse/ADUI-10893)
This PR adds necessary style for the pretine update. It basically adds shadow, border-radius, position and padding
|----------|----------|
| <img width="243" height="142" alt="image" src="https://github.com/user-attachments/assets/c0b59f92-3c68-475b-8750-e1b43e6ad6c0" />  | <img width="227" height="129" alt="image" src="https://github.com/user-attachments/assets/5b792e5f-ca56-4cc9-a9ab-0ccf758b3c2e" />  |
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README. …

feat(popover): +shadow,+padding,+radius,+position of popover

---

packages/mantine/src/styles/Notifications.module.css
packages/mantine/src/theme/Theme.tsx
packages/mantine/src/theme/plasmaCSSVariablesResolver.ts
packages/website/src/examples/form/button/Button.demo.tsx

Applied the custom style for this.
Beware that it goes against Mantine's logic and might create some unwanted style/colors in the future.
I still had some unanswered questions on the mockup.  will wait a bit if I get feedback on it!
Before:
After

Ad UI 10705 apply change to toast

---

packages/mantine/src/components/header/HeaderBreadcrumbs/HeaderBreadcrumbAnchor.tsx
packages/mantine/src/components/header/HeaderBreadcrumbs/HeaderBreadcrumbText.tsx
packages/mantine/src/components/header/HeaderBreadcrumbs/HeaderBreadcrumbs.tsx
packages/mantine/src/components/header/HeaderDocAnchor/HeaderDocAnchor.tsx
packages/mantine/src/components/header/HeaderRight/HeaderRight.tsx
packages/mantine/src/components/table/__tests__/Table.spec.tsx
packages/mantine/src/components/table/layouts/row-layout/RowLayout.tsx
packages/mantine/src/components/table/layouts/row-layout/RowLayoutBody.tsx
packages/mantine/src/components/table/layouts/row-layout/RowLayoutHeader.tsx
packages/mantine/src/components/table/table-actions/TableActionsList.tsx

Forgot more imports again, I swear these are the last ones

fix: last remaining imports without explicit file extension

---

CHANGELOG.md
packages/components-props-analyzer/package.json
packages/mantine/package.json
packages/react-icons/package.json
packages/tokens/package.json
packages/website/package.json

This reverts commit f9551c86eedcb29d160dbb9184a0aa5e05b2e66d.
This reverts commit df37610254c68847a6aa42e7b3b33d6ad431da99.
Those changes were pushed in the repo, but the publish on NPM failed. Now there's a mismatch between the repo and NPM so I'm reverting the changes
None

chore(release): revert failed releases
